### ISSUE TITLE
Custom URL is not being used correctly

### ISSUE THREAD

**Issue by bjwyse** [vvoovv/blender-geo#101]
If I use the custom URL for Google Maps tiles as per https://answers.splunk.com/answers/186394/how-to-specify-google-maps-url-for-map-tiles-in-sp.html then the URL is not being formed correctly.

![custom_url](https://user-images.githubusercontent.com/511510/44557102-e6602a00-a734-11e8-8fa2-86507fc96589.png)

![error](https://user-images.githubusercontent.com/511510/44557104-eb24de00-a734-11e8-87d0-353093a77936.png)

**Comment by vvoovv** [comment]
Thank you for reporting! I confirm the problem. I am going to fix it as soon as possible.

**Comment by vvoovv** [comment]
I've fixed the problem. An overlay defined by that kind URL template is now downloaded as well.
I'll provide the addon with the fix on Friday (at the end of the day) or on Satturday.

**Comment by vvoovv** [comment]
Please use the download link in your purchase confirmation e-mail to get the version with the fix. Please follow the [installation instructions](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#installation). I'd appreciate your feedback.

**Comment by bjwyse** [comment]
It's working now. Thanks!
