### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by dburton90** [vvoovv/blender-geo#102]
Hi I can't import any map from server, neither from file. It throws this error:
I am using Blender 2.79 and python 3.7
Any suggestion?

![deepinscreenshot_select-area_20180828225329](https://user-images.githubusercontent.com/4021087/44750801-b5a63900-ab16-11e8-9f74-79b63f1120b2.png)

**Comment by vvoovv** [comment]
Try to restart Blender.

If it doesn't help, send me to the e-mail prokitektura+support@gmail.com:
* version of the addon
* the Blender file, saved after unsuccessful import

**Comment by Just5D** [comment]
I can't import any map from server, neither from file. It throws this error: "A valid directory fro data in the addon preferences isn't set"
I am using Blender 2.79 and python 3.6

**Comment by Just5D** [comment]
problem solved！ thx

**Comment by vvoovv** [comment]
> problem solved！ thx

Great!
Please refer to the addon documentation:
https://github.com/vvoovv/blender-osm/wiki/Documentation#installation

**Comment by upperdecker954** [comment]
im getting the same error as dburton90

**Comment by vvoovv** [comment]
@upperdecker954 
What are your operating system, Blender and Python (used by Blender) versions?

**Comment by dburton90** [comment]
My problem was python3.7. I changed to version python3.6.6 and it works now. I still can't render 3d with textures, but I don't need this.

**Comment by vvoovv** [comment]
@dburton90 
We could solve the problem with the missing textures quite quickly. If you are interested in having the textures, please send me some screenshots and other information describing the problem. The e-mail address is prokitektura+support@gmail.com

**Comment by geo23tud** [comment]
My is not working sir pls tel me how is work and how to instal. Please Make 1 video how to instal the add thx

**Comment by vvoovv** [comment]
@geo23tud 
There is the detailed [documentation](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#installation).

Please provide more details about your problem. Screenshots illustrating your problem would be helpful. Please send them to prokitektura+support@gmail.com

**Comment by dngulin** [comment]
Same problem with Blender 2.79 + Python 3.7 + blender-osm 1.0.10 (Premium) on Linux.

**Comment by vvoovv** [comment]
@dngulin
Please use the latest stable version of Blender from https://www.blender.org/download/

If you are curious and know the Python a bit, here is the cause of the problem. 

The following Python code behaves differently in Python 3.5.3 (stable Blender 2.79b) and Python 3.7.0 (Blender 2.8 and daily builds).
``` python
class C:
    a = (1,)
    b = (1,)
C.a is C.b

```
<pre>
# in Python 3.5.3:
>>> C.a is C.b
False
</pre>

<pre>
# in Python 3.7.0
>>> C.a is C.b
True
</pre>

I'll fix it in the the next release.

**Comment by franzimil** [comment]
When i want to unable the blender-osm  addon this error appears 


![error](https://user-images.githubusercontent.com/45962036/50140029-ba4c5400-02a3-11e9-9415-d07564551c20.jpg)

**Comment by vvoovv** [comment]
@franzimil 
The problem isn't related to the blender-osm addon.

Please try the solution from [here](https://blender.stackexchange.com/a/106056/14200).
Please let me know if it worked for you.

**Comment by Uvindu** [comment]
Hi @vvoovv ,

I am using Blender 2.79(Blensor - https://www.blensor.org), not the latest version since I need to generate some scans. This is with python 3.6 and tried to install blender OSM add-on (https://prochitecture.gumroad.com/l/blender-osm)  but it gives following error. 
My operating system is Mac OS
<img width="1454" alt="Screenshot 2565-07-06 at 1 28 14 PM" src="https://user-images.githubusercontent.com/25794688/177530203-bd8ae97e-1b75-4d33-8b55-678dc9d147b2.png">
I highly appreciate your help.
Thanks

**Comment by vvoovv** [comment]
Hi @Uvindu 

Sorry, we can't support custom Blender builds. Please use the official Blender build from https://www.blender.org/download/

However you could try the last release of the Blender-OSM addon that worked on Blender 2.79:
https://github.com/vvoovv/blender-osm/releases/tag/v2.4.21
