### ISSUE TITLE
How can I link building in blender to the website.

### ISSUE THREAD

**Issue by CharliePM** [vvoovv/blender-geo#103]
I am working on a college project that I have to build a prototype, my prototype need to work like click on a building and it will link you to some website.

Now I finished import the city and render the buildings already, and I have no idea how to start next step. Could someone guide me please, do I have to save my blender into some other kind of file and continue my work on other software?

**Comment by vvoovv** [comment]
[blend4web](https://www.blend4web.com) could be a way to go.
