### ISSUE TITLE
Support glTF Export - Premium Version

### ISSUE THREAD

**Issue by JeremyBYU** [vvoovv/blender-geo#104]
Hi,
So I purchased the premium version and have really enjoyed how the buildings look. However, I would like to export the created meshes and textures to the Unreal Engine.  Previously I have been doing this with FBX export and it worked fine, because there were no building textures but just basic material color. However, now the materials are PBR based, use the node editor, and have textures.  FBX does not handle this use case and all the materials have to basically be recreated in unreal engine.  Boo.

So I have been looking into if there are any other export options and [glTF](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md) by the Khronos group seems to be one.  It can successfully export PBR materials, even with glossiness and roughness etc.  I have done some experimentation with a simple cube with textures and roughness and the export/import into Unreal worked correctly.  

I have looked into the `materials.blend` file provided by the premium version and have started learning how the materials are created.  I have tried to port over some of the materials to KhronosGroup NodeGroup but have been unsuccessful in some areas. Heres a link to an issue in gltf issue [tracker](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/305).  The basic problems I see are these:

1.  Can't find a way to mix the vertex color with the texture.  The Texture Image has to go **directly** into the Khronos Group custom node group for shading.
2. Can't find a way to do the facade mixing as well.

**Comment by vvoovv** [comment]
@JeremyBYU Thank you for purchasing the premium version!
Yes, the Blender materials supplied with the addon were designed for the Cycles rendering engine and can't be exported to the popular 3D formats (.dae, .fbx, .3ds, .obj). That's also stated in the product description and documentation.
Only blend4web supports export of the Cycles material to its own 3D application for the webbrowser.

I am going to implement the assignment of simple materials which can be exported to external 3D formats. There is a demand for that feature. However it will take time since it will also require to change how the mesh is generated.

**Comment by JeremyBYU** [comment]
Okay, thanks for looking into it!

**Comment by rohapa** [comment]
@vvoovv Recent buyer of your wonderful plugin. Noting that you had mentioned that it can't be exported to other programs. Is there anyway to get the materials exported to C4D?
I can get the models and everything else, but I wish I had read more into the product description before purchasing. Haha. I will take any suggestion at all to get the textures into C4D.

**Comment by vvoovv** [comment]
@rohapa 
Thank you very much for purchasing the blender-osm addon!

There are numerous request to implement export to the popular 3D formats. I am doing my best to implement it as soon as possible. Please stay on board :)

**Comment by jgwinner** [comment]
Hi! Thought I'd jump on and express a desire for the same feature. (Critical in our case).

gLTF would be great. It's a PITA from blender due to the need to mess with the nodes. Do the textures all use the same shared nodes? I could convert that by hand then.

        == John ==

**Comment by vvoovv** [comment]
@jgwinner, @rohapa, @JeremyBYU 

A "work in progress" version that supports the export of textures is available for testing for the customers of the premium addon. Please send a request to prokitektura@gmail.com and I'll send you the related links and instructions.

By the way the sources code is hosted on Github: https://github.com/vvoovv/blender-osm/tree/dev

**Comment by vvoovv** [comment]
Forgot to mention.

Export of textured buildings is available for some months in the experimental mode. Please read [here](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#export-of-the-imported-scene) for the details.

**Comment by JeremyBYU** [comment]
I just wanted to chime in and say that it worked perfectly on first use. I exported to GLTF and it worked great. Thanks!
