### ISSUE TITLE
image overlay: wrong orientation/import?

### ISSUE THREAD

**Issue by severin-lemaignan** [vvoovv/blender-geo#106]
Using blender-osm premium (with default settings), I'm attempting to import an image overlay, but the overlay does not match the imported buildings (I've tried both with Mapbox satelite imagery and OSM tiles).

For instance, using the OSM tiles, this is the result: it seems that the overlay is repeated 3 times (and only the 'middle' section does match the building:

![untitled](https://user-images.githubusercontent.com/385379/47803660-e24f1a80-dd2a-11e8-98eb-d5e59c74ce4b.png)

(exact same issue with the satellite imagery: the same section of overlay is repeated 3 times, and only the middle section is aligned with buildings).

Looking at the UV editor, it seems that the imagery tiles are imported with the wrong orientation:
![untitled](https://user-images.githubusercontent.com/385379/47804080-cef07f00-dd2b-11e8-8db1-d3bc6af3402e.png)

**Comment by severin-lemaignan** [comment]
Follow-up: the problem does not arise for small areas. In the examples above, the imported zone was rather large (coordinates are -2.55758,51.49464,-2.46909,51.50714 -> ~15 km x 4 km).

**Comment by vvoovv** [comment]
Thank you for reporting the problem and providing coordinates of the area that caused the problem.
I'll try to reproduce the problem.

**Comment by vvoovv** [comment]
I am unable to reproduce your problem. Everything is imported correctly:
![image](https://user-images.githubusercontent.com/613295/47817688-5f988080-dd67-11e8-8ed8-c53e2ea7bcab.png)
![image](https://user-images.githubusercontent.com/613295/47817582-16483100-dd67-11e8-8a9f-58e232aaa4b2.png)

**Comment by vvoovv** [comment]
Please ensure that you use the latest stable Blender release from https://www.blender.org/download/
Unstable and experimental Blender builds produce strange errors.

I'd suggest even to reinstall Blender after downloading it from https://www.blender.org/download/

**Comment by severin-lemaignan** [comment]
Thanks @vvoovv  for your quick response. I should have mentioned that I am using Blender 2.79b (ie, the latest stable release), as packaged in Ubuntu 18.04.

I've retried the whole process using a Blender 2.79b downloaded from the Blender website, and it works fine... weird. Anyway, problem solved, thanks!
