### ISSUE TITLE
Compatibility with Blender 2.80

### ISSUE THREAD

**Issue by der-On** [vvoovv/blender-geo#107]
It would be nice to have a version that is compatible to Blender 2.80.

It should be possible to make one codebase that can deal with 2.79 and 2.80 at the same time.

**Comment by vvoovv** [comment]
Support of Blender 2.80 will be provided after the release of betha version of Blender 2.80

**Comment by der-On** [comment]
@vvoovv Thank you.

**Comment by vvoovv** [comment]
Opened #113 for porting the addon to the Blender 2.8
