### ISSUE TITLE
Unable to install  | MacOS | Blender 2.78c, 2.79

### ISSUE THREAD

**Issue by buzzdev** [vvoovv/blender-geo#110]
Just purchased premium plugin, but despite install success message, the plugin is not listed:
Modules Installed from '/Users/xxx/Downloads/blender-osm.zip' into '/Users/xxx/Library/Application Support/Blender/2.78/scripts/addons' ()

OS: macOS 10.13.6 High Sierra

<img width="1046" alt="screen shot 2018-11-14 at 19 50 55" src="https://user-images.githubusercontent.com/6644151/48505239-d8f3a100-e846-11e8-9428-26eabc84faf0.png">

**Comment by vvoovv** [comment]
Hello,

Thank you very much for purchasing the blender-osm addon!

Sometimes a browser creates an additional zip archive for downloaded content. So one has a zip archive located inside another zip archive. Could it be your case?

The correct structure should be
blender-osm.zip ->
blender-osm (a directory) ->
directories app, assets, building and so on

**Comment by buzzdev** [comment]
Hi,
yes, that was exactly the case.
I just didn't unpack the downloaded zip, because it was specifically mentioned in install manual.

So unpacking the dowloaded zip from github actually extracted another zip, which was the correct one for installation.

If not already there, it might be a good idea to mention that in the install manual.

Thank you
