### ISSUE TITLE
create a skirt for the terrain

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/blender-geo#114]
Example of the skirt: https://www.youtube.com/watch?v=ctyyYj8KcL4

**Comment by buzzdev** [comment]
Good idea. I was doing this manually by combination of boolean modifiers, which by large terrains is time consuming.

**Comment by CivilVisions** [comment]
I agree that this would be a nice option to have.

**Comment by vvoovv** [comment]
Finally the feature is implemented. It's available starting from the version 2.7.10 of the Blosm addon.

![image](https://github.com/user-attachments/assets/8845e948-0b6c-4ad8-a30c-fac25adac5b7)
