### ISSUE TITLE
Installation Error in 2.79b

### ISSUE THREAD

**Issue by CivilVisions** [vvoovv/blender-geo#118]
I downloaded the latest Blender OSM Premium from Gumroad yesterday and tried installing it this morning in Blender 2.79b. During install it errors out with the attached console message. 

It looks as though the `/Renderer/__init__.py` is loading 2.8x modules (line 22) without checking for the correct Blender version first.

Despite the installation error, it appears that the add-on operates correctly.

Cheers!

![blender osm premium - install error in b2 79b](https://user-images.githubusercontent.com/46461674/51250692-300c1400-1965-11e9-8fa4-53753392673c.png)

**Comment by vvoovv** [comment]
Please try restarting Blender.
Please inform if that helped.

**Comment by vvoovv** [comment]
Restarting Blender solved the problem.
