### ISSUE TITLE
Just can import terrain image, overlay, building in 2.79b new version of osm.

### ISSUE THREAD

**Issue by andrewdx3** [vvoovv/blender-geo#119]
The import of the street version 2D and 3D report error, or import notting:
some eror is 
![image](https://user-images.githubusercontent.com/33329350/51262781-548edd00-19b3-11e9-8841-e8c6aa1fe6e4.png)
i try some combinatio mix to import street but notting...
![image](https://user-images.githubusercontent.com/33329350/51262920-96b81e80-19b3-11e9-8266-2ce55592c1b3.png)
I try to make terrain first but same error. Previus version of osm work, i unistall to instll this version but this version not working nice

**Comment by andrewdx3** [comment]
Ok i find problem , the error appears when i put directory of setup script. If no put the directory in "Box" directory , just import all but without Texture...

**Comment by vvoovv** [comment]
Hi @Andreax81,
Thank you for reporting the problem.

_premium_default.py_ is the setup script for the _3D realistic_ mode, but you tried in the _2D_ mode. 
However, you don't need to set the setup script in the _3D realistic_ mode to _premium_default.py_, because _premium_default.py_ is executed by default in the _3D realistic_ mode.

Please refer to the documentation how to use the addon:
https://github.com/vvoovv/blender-osm/wiki/Premium-Version#openstreetmap-import-from-the-server

If you have any problem with the addon, please let me know.

**Comment by andrewdx3** [comment]
Yes i make all you tell.
Not work ,  only way is :
Import terrain 3D, import image overlay
swithc off "py" preset
import street , water, etc.
switch on "py" preset
Import 3D realistic.
Now have all i whant. But i think is a big bug this...

Inviato da Outlook<http://aka.ms/weboutlook>

________________________________
Da: Vladimir Elistratov <notifications@github.com>
Inviato: mercoledì 16 gennaio 2019 20:27
A: vvoovv/blender-osm
Cc: Andreax81; Mention
Oggetto: Re: [vvoovv/blender-osm] Just can import terrain image, overlay, building in 2.79b new version of osm. (#119)


Hi @Andreax81<https://github.com/Andreax81>,
Thank you for reporting the problem.

premium_default.py is the setup script for the 3D realistic mode, but you tried in the 2D mode.
However, you don't need to set the setup script in the 3D realistic mode to premium_default.py, because premium_default.py is executed by default in the 3D realistic mode.

Please refer to the documentation how to use the addon:
https://github.com/vvoovv/blender-osm/wiki/Premium-Version#openstreetmap-import-from-the-server

If you have any problem with the addon, please let me know.

**Comment by vvoovv** [comment]
Setup script is an advanced setting. You don't need it normally.

Please try to follow the documentation:
https://github.com/vvoovv/blender-osm/wiki/Premium-Version#openstreetmap-import-from-the-server
