### ISSUE TITLE
Interesting data: AHN

### ISSUE THREAD

**Issue by gtoonstra** [vvoovv/blender-geo#12]
The Netherlands has published a very dense elevation map of the entire country in an "open data" program (since 2014). It contains filtered data to describe the terrain without buildings, cars and vegetation and has a precision of 20cm in a grid of 0.5m. The maps are downloadable.

There's another point cloud called "filtered", which is raw data covering all the points that are not considered part of the terrain. So that point cloud covers laser reflections from trees, buildings, cars and bridges.

The two can be used to derive building heights for all buildings in NL established in 2014, even derive the roof type, flat roof constructions like terraces, etc. Since the data is considered open, it may even be allowed to back-update openstreetmap, so that each building has very accurate height information. The "levels" data item remains important, because it can be used to derive the average height per floor and other rendering purposes.

More info and data download: http://nationaalgeoregister.nl/geonetwork/srv/eng/search#|9ca6f842-9482-4f5a-ad87-5307723cfe16

**Comment by vvoovv** [comment]
Unfortunately, it's only for Netherlands
