### ISSUE TITLE
Premium plugin is destructive to original OSM files

### ISSUE THREAD

**Issue by Andrew-Matheny** [vvoovv/blender-geo#120]
I'm building a region-wide model using OSM files simply because it allows easy workflows between pulling/editing/tracing building footprints in JOSM and interoperability with a GIS.

However, it appears that the plugin modifies an imported OSM source file in a way that is destructive to building geometries, especially with complex and/or angular building footprints. See this example for **Before:**
![Before](https://user-images.githubusercontent.com/28968059/56238390-0772e380-6054-11e9-930f-56d5dd2fe3af.JPG) and **After**
![After](https://user-images.githubusercontent.com/28968059/56238411-13f73c00-6054-11e9-9c2f-f7f02d976493.JPG)

I'm only importing copies of the source files as a workaround, but it'd be great if the plugin doesn't modify the source it's importing.

Edit: The issue is not unique to buildings that are in multipolygon relations, but happens with regular building ways as well.

**Comment by vvoovv** [comment]
@Andrew-Matheny 
I'd like to assure you that the blender-osm addon doesn't modify an OSM source file in any way!

Was it import from the server or from a local OSM file?

**Comment by Andrew-Matheny** [comment]
From a local OSM file

**Comment by vvoovv** [comment]
Please check the edit time of the local OSM file before and after import. The blender-osm addon doesn't modify the OSM file. It only uses it in the read-only mode.

**Comment by Andrew-Matheny** [comment]
Hm, now I'm not able to replicate the issue. I'll keep and eye on it and let you know if it reoccurs.

**Comment by vvoovv** [comment]
Anyway, thank you for reporting
