### ISSUE TITLE
Blender 2.80 Addon Not Working

### ISSUE THREAD

**Issue by Dooshbagg** [vvoovv/blender-geo#121]
I tried to install the openstreetmaps addon to Blender 2.80, io_import_scene_osm.py, and when I enable it in Blender I get an error message from Blender saying I need to upgrade to version 2.8x.  There is no version 2.8x.  2.80 is a Beta version.  There are no newer releases of it yet.  Any ideas?  Any help would be appreciated.
Here's a link to the addon I downloaded.  I've seen it work for others.
https://drive.google.com/file/d/0B19GBkMpIGvuYmxkUUlCSEVkdHc/view

**Comment by vvoovv** [comment]
@Dooshbagg 
Thank you for the interest in the blender-osm addon!

You downloaded quite old and experimental version. I can't provide support for it. I'd suggest to try it in Blender 2.79.

I'd recommend you to purchase the paid addon:
* [the base version](https://gumroad.com/l/blender-osm)
* [the premium version](https://gumroad.com/l/blosm)
