### ISSUE TITLE
"mono-pitched" roof shape should be "skillion"

### ISSUE THREAD

**Issue by Andrew-Matheny** [vvoovv/blender-geo#123]
Just a small note on the documentation in the Wiki and elsewhere, the "mono-pitched" roof shape is actually tagged as "skillion" in OSM and is rendered as such by the plugin. 

If a building is tagged as "mono-pitched", the plugin will just import the building with a flat roof.

**Comment by vvoovv** [comment]
The word _mono-pitched_ is probably easier to understand than _skillion_.

**Comment by Andrew-Matheny** [comment]
Right, just wanted to make sure it wasn't an oversight 👍
