### ISSUE TITLE
Cannot pack edited image from disk, only as internal PNG

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/blender-geo#124]
See https://github.com/vvoovv/blender-osm/issues/122#issuecomment-495786566 reported by @woodengun

**Comment by vvoovv** [comment]
@woodengun
Could you post a screenshot of the Blender splash screen? I'd like to see the date of your version of Blender 2.80. The date is shown on the splash screen.

**Comment by woodengun** [comment]
Sure Thing! Sorry for the delayed response. Heres both the splash screen and the python error:
![Screen Shot 2019-05-26 at 7 53 07 AM copy](https://user-images.githubusercontent.com/18755554/58374116-47e74a80-7f8c-11e9-9d6e-330dfbe0553a.jpg)
![Screen Shot 2019-05-26 at 7 55 54 AM copy](https://user-images.githubusercontent.com/18755554/58374117-49b10e00-7f8c-11e9-97b1-a1bb4a88da70.jpg)

**Comment by vvoovv** [comment]
Thank you for the feedback!
Your version of Blender 2.80 is from the beginning of March. Could you please try the blender-osm addon with the latest version of Blender 2.80?

**Comment by woodengun** [comment]
That did it!
Thanks! I should have checked that first. Thanks again for a great plugin! This rocks

**Comment by vvoovv** [comment]
You are welcome!
