### ISSUE TITLE
Mesh combined

### ISSUE THREAD

**Issue by danksky** [vvoovv/blender-geo#125]
When importing .osm files, the main layer combines the buildings and terrain as one mesh. Is it possible to import the OSM file so that buildings are discrete and uniquely identifiable?

**Comment by vvoovv** [comment]
Hi Daniel,

Could you please post a screenshot with the Blender outliner window to illustrate what you exactly mean?

**Comment by danksky** [comment]
This is embarrassing. I opened this issue in on **blender-osm** instead of **BlenderGIS**.
