### ISSUE TITLE
import 3D realistic with errors:

### ISSUE THREAD

**Issue by RezoChiang** [vvoovv/blender-geo#126]
![image](https://user-images.githubusercontent.com/26949018/58805840-737eca80-8647-11e9-8c0d-7cc4df0605c3.png)

**Comment by vvoovv** [comment]
Thank you for your report!

Could you please post a screenshot of the Blender splash screen? The splash screen can be activated through the main menu Help -> Splash Screen. We'd like to see information about the version of your Blender release.

We suspect your Blender build is not the official one. Please ensure that you are using the official stable Blender release from https://www.blender.org/download/

**Comment by RezoChiang** [comment]
![image](https://user-images.githubusercontent.com/26949018/58809496-9cef2480-864e-11e9-9d26-8ba30ad06f99.png)

Manjaro Aur

**Comment by vvoovv** [comment]
Yes, that's a custom build. Please use the official one from https://www.blender.org/download/

**Comment by RezoChiang** [comment]
It's ok now  when I switched 2.8b, Thanks.
