### ISSUE TITLE
mimic lit windows

### ISSUE THREAD

**Issue by RayLee2333** [vvoovv/blender-geo#127]
How to find mimic lit windows in premium and make it glow

**Comment by vvoovv** [comment]
Hi @RayLee2333 
It's described in the following section of the documentation:
https://github.com/vvoovv/blender-osm/wiki/Premium-Version#openstreetmap-import-from-the-server

To assign materials for a late evening setting to the imported buildings, set a value of the field _Percentage of lit windows_ (s)  between 1 and 100. As its name implies, it defines approximately, how many windows of the imported buildings will be lit. The value of 30 percent normally gives nice looking scene. It's also possible to change the percentage of lit windows after the import of buildings and see the effect immediately. Keep the value of the field set to zero to assign the materials without light emission (i.e. for a day setting). Note, that if the percentage of lit windows was set to zero before the import, any change of the field won't produce any effect after the import.

**Comment by RayLee2333** [comment]
thanks
