### ISSUE TITLE
"Delete materials..." error

### ISSUE THREAD

**Issue by muratagawa** [vvoovv/blender-geo#128]
When I have tried the tutorial "[Using custom textures · vvoovv/blender-osm Wiki](https://github.com/vvoovv/blender-osm/wiki/Using-custom-textures)", I got the error in this step:

> Press the button Delete materials...  to delete existing Blender materials for residential buildings in the currently opened Blender file.

When I press the button, the error message was shown:

```
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\util\blender_extra\material.py", line 462, in execute
    bpy.data.materials.remove(material, True)
TypeError: BlendDataMaterials.remove(): required parameter "do_unlink" to be a keyword argument!

location: <unknown location>:-1
```

Here is the screenshot.

![osm_error](https://user-images.githubusercontent.com/21990514/59080026-93510f80-8921-11e9-8c29-1c6324ebb30e.png)

How do I fix it?

I'm using Blender 2.8 beta 2.80.60 (2019-05-07 build) and 2.80.74 (2019-06-01 build), but the both cause the same error.

**Comment by vvoovv** [comment]
Thank you for reporting the problem!
 I'll check it with the latest version of Blender 2.80 Beta. I'll will back to you as soon as possible.

**Comment by muratagawa** [comment]
Thanks you for your response. I will wait.
I want to use my customized textures for a cartoon illustration.

**Comment by vvoovv** [comment]
We reproduced the error in the latest release of Blender 2.80 Beta. The Blender developers still made some changes to the Python API.

We'll fix the problem very soon.

**Comment by vvoovv** [comment]
The problem has been fixed. Please use the link in your purchase confirmation e-mail to download the latest version of the blender-osm addon.

Please delete the previous version of the blender-osm addon and restart Blender before installing the latest one.

**Comment by vvoovv** [comment]
Please let me know if it works for you.

**Comment by muratagawa** [comment]
It's working now. I appreciate your support.
