### ISSUE TITLE
[Feature Request] Toggle Lights On/Off by toolbar

### ISSUE THREAD

**Issue by muratagawa** [vvoovv/blender-geo#129]
This is not an issue, just a feature request.

Blender OSM Premium Add-on is my life saver. However, the add-on lacks the ability to turn the window lights on/off. So I implemented some modification to the materials and wrote Python script.

----

In detail:

1. Added _Math (Multiply)_ node before _Emission_ node in all `*_emission` materials

![osm_enhance_1](https://user-images.githubusercontent.com/21990514/59153392-40976500-8a93-11e9-8451-c3bbc4ff2729.png)

![osm_enhance_2](https://user-images.githubusercontent.com/21990514/59153356-58bab480-8a92-11e9-868f-a91ccc8cc70e.png)

2. Added Python script which does `make_local()` and changes the value of  _Multiply_ nodes

```python
import bpy

for mat in bpy.data.materials:
    mat.make_local()

for mat in bpy.data.materials:
    if hasattr(mat.node_tree, 'nodes') and 'Window_Glow' in mat.node_tree.nodes:
        # Change the value to turn the lights on
        mat.node_tree.nodes['Window_Glow'].inputs[1].default_value = 0.0

        #  mat.node_tree.nodes['Window_Glow'].inputs[1].default_value = 10.0
```

Here is how it works:

![osm_enhance](https://user-images.githubusercontent.com/21990514/59153437-548f9680-8a94-11e9-819d-56180f68499b.gif)

(MP4 Movie: https://twitter.com/muratagawa/status/1137496517483196416)

----

If this feature is implemented to `osm` tool panel, it will be nicer.

**Comment by vvoovv** [comment]
Thank you for the feature request!

Window lights can be turned off by setting the value of the field _Percentage of lit windows_ to zero.

**Comment by muratagawa** [comment]
Oh, I didn't noticed the parameter is dynamic :frowning:
Thanks for your advice.
