### ISSUE TITLE
Texturing on self-build buildings?

### ISSUE THREAD

**Issue by muratagawa** [vvoovv/blender-geo#130]
Excuse me for asking a series of questions.

Is there a way to apply OSM's 3D realistic textures to my own building?

I want to add my own building in the city created by the add-on, but I don't know how to paste the texture in the same way. I found OSM is using 3 UV Maps but I couldn't create those manually.

![osm_custom_building](https://user-images.githubusercontent.com/21990514/59165761-eadabf80-8b5b-11e9-933f-add8b9237bb3.png)

If there is a way, please tell me.

**Comment by vvoovv** [comment]
It's required to set all UV maps and a layer for the vertex color.
It isn't easy to set them manually. A Python script is needed for that task.

**Comment by muratagawa** [comment]
I see... It is difficult to do it manually.
I will look for another way. Thank you.
