### ISSUE TITLE
OSM wont enable in Blender

### ISSUE THREAD

**Issue by szasha** [vvoovv/blender-geo#131]
I'm able to download the OSM zip file, which I bought. I'm using Blender ver. 2.80, and followed instructions. The addon seemed to download, but everytime I try to enable it there's an error.

**Comment by vvoovv** [comment]
Hi @szasha ,

Thank you very much for purchasing the blender-osm addon!

Please send a screenshot with the error. You can post it also to the e-mail prokitektura@gmail.com

**Comment by szasha** [comment]
![Image 1](https://user-images.githubusercontent.com/54554087/63719485-95bb6980-c87f-11e9-94d3-fe700dfa27a2.png)

**Comment by vvoovv** [comment]
Please try to delete the file _C:\Users\GP73 LEOPARD 8RE\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\random.py_ and then try to enable the addon again.

I suspect the file was placed there by mistake.

**Comment by szasha** [comment]
It works now, thank you.
