### ISSUE TITLE
Problems with import of trees for 3d realistic

### ISSUE THREAD

**Issue by Silvasalta** [vvoovv/blender-geo#132]
Hello, if I try to import forest and trees in the 3d realistic mode I get the following message:
![error](https://user-images.githubusercontent.com/54995212/64444081-a2d42600-d0d3-11e9-9d10-0f2809926b41.jpg)
and the result is quite funny.
![error2](https://user-images.githubusercontent.com/54995212/64444222-edee3900-d0d3-11e9-9557-38590ebd493f.jpg)

I'm using Blender 2.8, but started with 2.79. Do I have to change some settings?
Thanks in advance

**Comment by vvoovv** [comment]
Hi,
I imported your area of interest and it worked for without any problem.
Which version of Blender do you use? Please ensure that it's the latest stable one from https://www.blender.org/download/

**Comment by Silvasalta** [comment]
Hello,
I'm using the official Version of Blender 2.8, which I downloaded in August. But I reinstalled it and now it seems to work. Thanks
