### ISSUE TITLE
Grey overlay. 

### ISSUE THREAD

**Issue by Zappfe** [vvoovv/blender-geo#135]
Hi. 

I'm quite new to blender so this might just be an rocky mistake. But when I download the overlays into blender using your app, they just turn out grey. No image at all. Am I doing something wrong? 

TH.

**Comment by vvoovv** [comment]
Which overlay is that?
Please also inform the coordinates for the area with the grey overlay.
That information is needed to reproduce the problem.

**Comment by Zappfe** [comment]
Sorted it out. Just my total lack of knowledge about blender. 

Thanks for the fast reply

**Comment by vvoovv** [comment]
Please let me know if you have any further questions.
