### ISSUE TITLE
Support importing parks

### ISSUE THREAD

**Issue by liszi** [vvoovv/blender-geo#137]
In urban areas, parks are the most common vegetation types. It would be a very nice feature to be able to import parks too, like forests and other vegetation.
Parks could be included into _Import other vegetation_ or it could have it's own import option, like _Import parks_.

**Comment by vvoovv** [comment]
Park in OSM isn't a vegetation. It can contain ponds, trees, grass, paved areas, flowers, buildings.

To import parks please use a custom setup script. [Here](https://github.com/vvoovv/blender-osm/blob/setup_scripts/base_landuse.py) is an example of the custom setup script. It imports landuse s: residential, industrial and other. Take look at the code limited by
`# custom setup begins`
and
`# custom setup ends`
The condition for parks would be
`lambda tags, e: tags.get("leisure") == "park",`

**Comment by liszi** [comment]
vvoovv, thanks for the clarification about parks. 
Custom setup seems to be very useful, didn't know about this, thanks. I'll use this.
