### ISSUE TITLE
Can't see or render textures on output.

### ISSUE THREAD

**Issue by marcolomeo99** [vvoovv/blender-geo#139]
- System: Windows 10
- Blender version: 2.81
- Blender-osm version: 2.3.17

I've managed to import the map successfully from file, and the add-on outputs the 3d object.
I've made sure the normals are correct, then, upon assigning all faces to a single material, and removed the rest, I create a texture slot, load an image to it, switch to shading editor, add the texture to the material node.

But nothing shows in the viewport or in renders (Eevee and Cycles).

If I unwrap the buildings, I *might* get the texture visible in the viewport, but still not in the renders. But also, the UV editor might loose the information on the unwrapping whenever I try to resize it. (which is a minor problem).

I've tried to separate the buildings by loose object, and since they were not manifold, made them so, but with no success.

I added a cube to the scene for testing the issue, and simply assigning to it the created material, the texture was shown correctly on it in renders and viewport:

![Image of renderview](https://i.imgur.com/YulE8gr.jpg)

(btw, beside this problem I'm playing with this add-on since a couple of days and I LOVE it, thank you very much!)

**Comment by vvoovv** [comment]
Hi @marcolomeo99 
Thank you very much for purchasing the blender-osm addon!

The textures are assigned only in the basic version of the blender-osm addon.

**Comment by marcolomeo99** [comment]
hello @vvoovv a clarification please: **does that means that in the basic version I cannot create my own textures?** (I don't care for the realistic ones that the premium version extrapolates by the open source maps data)
Or is there something I'm doing wrong?

If the premium version is needed to have **any** kind of texture, is there a way I can change my purchase to that version, by paying the difference?

**Comment by marcolomeo99** [comment]
solved! By some reason there is a render-disabled uvmap generated by the program; by activating that, everything works!

Thanks a lot! :)

**Comment by vvoovv** [comment]
@marcolomeo99 
UV maps are created in the base version but not assigned.
To purchase the premium version with a discount please contact me via [e-mail](mailto:prokitektura+support@gmail.com).

**Comment by Fataturca** [comment]
> solved! By some reason there is a render-disabled uvmap generated by the program; by activating that, everything works!
> 
> Thanks a lot! :)

Hy! What means " there is a render-disabled uvmap generated by the program; by activating that, everything works" where i need to go? please

**Comment by marcolomeo99** [comment]
> Hy! What means " there is a render-disabled uvmap generated by the program; by activating that, everything works" where i need to go? please

I meant in the N-panel, in the UV section, you choose the UVmap generated by the program, to use with your own materials
