### ISSUE TITLE
Add-On requires upgrade to 2.8x

### ISSUE THREAD

**Issue by MMorpheus1** [vvoovv/blender-geo#140]
I completely reinstalled Blender, now Version 2.80. I wanted to integrate the (purchased) base version of the Add-on again and redownloaded it as well from the gumroad website. Blender says "upgrade to 2.8x required", see picture.
<img width="772" alt="Bildschirmfoto 2020-01-03 um 19 28 20" src="https://user-images.githubusercontent.com/27648257/71741877-49e98400-2e60-11ea-8346-04da3ae17873.png">

Am I missing something?

**Comment by vvoovv** [comment]
Please download the latest version of the blender-osm addon using the link in your purchase confirmation e-mail. The latest version is 2.3.17

I can resend you the purchase confirmation message. Please contact me via e-mail prokitektura+support@gmail.com for that.

**Comment by MMorpheus1** [comment]
I thought i did that, because i directly downloaded it from an E-mail send by gumroad. But it actually wasn't the confirmation message itself and apparently led to an old version. After searching my mails again and downloading it from the actual purchase confirmation messeage, it works.
Thanks!
