### ISSUE TITLE
osm did not show up as an option in import

### ISSUE THREAD

**Issue by ViscountMaxwell** [vvoovv/blender-geo#141]
I had this add-on installed and enabled properly, but it did not show up in import
blender version: 2.81a

**Comment by vvoovv** [comment]
Hi @ViscountMaxwell 
The blender-osm addon panel is located on the right side of the Blender's 3D Viewport. Please refer to the documentation how to use the addon:
* [the base version](https://github.com/vvoovv/blender-osm/wiki/Documentation#openstreetmap-import-from-the-server)
* [the premium version](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#installation)
