### ISSUE TITLE
osm import image overlay

### ISSUE THREAD

**Issue by blenderhippy** [vvoovv/blender-geo#142]
blender 2.82 official.  i get an error when trying to import the i
![Untitled-2](https://user-images.githubusercontent.com/47124989/74596982-ac679f80-501c-11ea-82d8-fcbf2e20d8a8.jpg)
mage overlay

**Comment by vvoovv** [comment]
You seem to use an outdated version of the blender-osm addon. Please download the latest version of the addon using the link in your purchase confirmation e-mail.
