### ISSUE TITLE
blenderGIS

### ISSUE THREAD

**Issue by teejay008** [vvoovv/blender-geo#143]
can someone pls help . have been try to use blendergis addon on my blender 2.79 but after i successful install it from file when i click on it to enable it , it gives me error. pls can any one help....... same thing goes with blenderosm addon.

**Comment by vvoovv** [comment]
BlenderGIS is a separate addon.

Please provide more details about the problem including some screenshot to illustrate the problem.

**Comment by teejay008** [comment]
Thanks for reply , I qm new to all of this , but what am saying is that I am using blender 2.79 and after I have followed the installation process properly for blenderosm and blenderGis addons  ,when I try to enable it , it gives error
![15828760542661773340941](https://user-images.githubusercontent.com/61524647/75520986-11e96200-5a07-11ea-8dfa-669c9b0463be.jpg)that's for blenderOsm
![158287619990276703858](https://user-images.githubusercontent.com/61524647/75521147-5f65cf00-5a07-11ea-8ad9-e1963f4f04b0.jpg)for blenderGIS

**Comment by vvoovv** [comment]
BlenderGIS is another addon. We don't have any connection to BlenderGIS

**Comment by vvoovv** [comment]
Please try the following solution:
https://blender.stackexchange.com/a/106056/14200

**Comment by teejay008** [comment]
Solution failed

**Comment by vvoovv** [comment]
Try to install Blender 2.82.

**Comment by teejay008** [comment]
I have but it is slow on my laptop, can you help make it fast, am using
window 7 bit 64 Intel 3000 graphics card

**Comment by vvoovv** [comment]
Can't help here.
