### ISSUE TITLE
About importing maps

### ISSUE THREAD

**Issue by anima02** [vvoovv/blender-geo#148]
I'm Japanese and I'm sorry if English is hard to read. When I import MAP with blender2.79, the texture is not pasted and everything turns black, please let me know the solution.

**Comment by vvoovv** [comment]
Have you set the _Viewport Shading_ to _Material_?

**Comment by anima02** [comment]
Is it the shading of the property shelf? It is multi-textured, but in
texture mode it is colored but no texture is attached, what should I do?

2020年3月16日(月) 16:21 Vladimir Elistratov <notifications@github.com>:

**Comment by vvoovv** [comment]
Please use _3D realistic_ mode to import textured buildings (the letter _r_ on screenshot below):
![](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/tool_shelf_osm_from_server_premium.png)

The option _Viewport Shading_ is shown on the screenshot below:
![image](https://user-images.githubusercontent.com/613295/76737402-c4e0ec00-6779-11ea-9663-dca992a9eb01.png)

**Comment by anima02** [comment]
The texture was displayed when I made the Cyclis render, is this a
specification?
[image: キャプチャ.PNG]
[image: キャプチャ02.PNG]

2020年3月16日(月) 17:34 Vladimir Elistratov <notifications@github.com>:

**Comment by vvoovv** [comment]
Yes, the render engine must be set to Cycles.
I can't see your images. Please answer via Github.com rather via e-mail.

**Comment by anima02** [comment]
Thank you, it ’s okay!

2020年3月16日(月) 19:47 Vladimir Elistratov <notifications@github.com>:

**Comment by vvoovv** [comment]
Thank you for using our addon!
