### ISSUE TITLE
SRTM : Nothing loaded in blender 2.76

### ISSUE THREAD

**Issue by harseld** [vvoovv/blender-geo#15]
Hi,

I tried the srtm import module with blender 2.76 and tried to open (several times, playing with the options) a hgt file (N38W113.hgt) from the USGS. I can't see anything in my scene. In blender outliner, I can see a SRTM object, but nothing visible when I select it.
Did I missed a point ?

**Comment by vvoovv** [comment]
Try to increase far clipping distance of the 3D View camera and the camera used for rendering.

**Comment by harseld** [comment]
Thanks for your quick answer !
OK, I can now find it in camera perspective view. It's upside down (facing -z axis) and offset towards +z. However, I still can't see it in the modeling (face, side, top) views.

**Comment by vvoovv** [comment]
Select the terrain mesh in the Outliner. Then select in the menu View -> View Selected. Pressing . (dot) in the Numpad gives the same effect

**Comment by harseld** [comment]
OK,
That did it ! Thanks a lot for your help and your nice work !

**Comment by vvoovv** [comment]
Thank you for your interest!
