### ISSUE TITLE
Scene becomes black and white after reloading

### ISSUE THREAD

**Issue by morph3us-net** [vvoovv/blender-geo#150]
![WhiteMaterials](https://user-images.githubusercontent.com/43741267/76850963-b4e40d80-6848-11ea-9c90-f5d723a19f30.jpg)

I uploaded an image from this scene yesterday, everything was fine.
Now all of the sudden everything is either black or white...

[Info: Read library:  'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: Unable to open 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend': No such file or directory
Warning: Cannot find lib 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend'
Warning: LIB: Material: 'commercial.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial.2' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial.3' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial.4' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial_ground_level.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial_ground_level.2' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial_ground_level.3' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'commercial_ground_level.4' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'brick_color' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'roof_tiles_color.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'roof_tiles_color.2' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'roof_tiles_color.3' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'roof_tiles_color.4' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'residential.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'residential_ground_level.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'plaster_color' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'plaster_color.1' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>'
Warning: LIB: Material: 'plaster_color.2' missing from 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend', parent '<direct>']

Seems it doesnt find the materials scene anymore, however it is definitely there.
This material linking seems a very bad idea...

**Comment by morph3us-net** [comment]
![WhiteMaterials2](https://user-images.githubusercontent.com/43741267/76852023-bdd5de80-684a-11ea-955e-ff7247376e2e.jpg)

Okay, the totally white image problem seems to be linked to evee.
When rendering with Cycles, it at least renders something.
Strange... Still... The white buildings should have materials on them...

**Comment by vvoovv** [comment]
Material linking is the feature used by many Blender user on every day basis. It should work.

Blender can't find the file _S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend_
> Warning: Unable to open 'S:\01_Projekte_Aktuell\200316_amf_Wilderswil\01_3D\assets\building_materials.blend': No such file or directory

Please check if the file is there.

**Comment by morph3us-net** [comment]
It is.

**Comment by morph3us-net** [comment]
Okay, seems there was a network error here.
I was on the server, I even started the scene from there, but somehow the Drive Name had a red cross over it. So I double clicked that and now it works. (Seems it reconnected the Server with S only afterwards, which is wierd and I dont know why that happened...)

I would love an option to import those materials into the scene automatically, however.
Just for general purposes.

Edit:
I am pretty sorry for having caused a ruckus... It drove me mad for 2 hours...

**Comment by vvoovv** [comment]
One could also use the following feature of Blender to make materials local:
Select all Blender objects by pressing the `A` key
Then Menu -> _Object_ -> _Relations_ -> _Make Local..._ -> _All_

**Comment by morph3us-net** [comment]
OMG! SUCH A TIME SAVER! Thank you so much for this tip!
