### ISSUE TITLE
Please help me, I have no success with "custom url" via google to import an overlay

### ISSUE THREAD

**Issue by haamic** [vvoovv/blender-geo#152]
#101
Hello,
Please help me, I have no success to import an overlay via "custom url" on google.
How do I enter the url? 
"**https://mt.google.com/vt/lyrs=m&x={x}&y={y}&z={z}**" or "**http://mt.google.com/vt/lyrs=m&x={x}&y={y}&z={z}**" and replace the x y z with the tile values + zoom ?
e.g. "https://mt.google.com/vt/lyrs=m&x={12345}&y={67890}&z={12}" ??? or completely different?
please help, thanks
Greetings Micha

**Comment by vvoovv** [comment]
Just paste it as is. No edit is necessary.
