### ISSUE TITLE
Problem with blender with premium version

### ISSUE THREAD

**Issue by programercek** [vvoovv/blender-geo#153]
Hello,

I got error in premium version. In free version works very well.
What can be problem?

![eqwe211232131](https://user-images.githubusercontent.com/10598350/77893513-4e151a00-7274-11ea-8c29-ef4c941fe9b8.png)

**Comment by vvoovv** [comment]
Please try to restart Blender.

**Comment by programercek** [comment]
thanks works!

**Comment by vvoovv** [comment]
Thank you for using the addon!
