### ISSUE TITLE
How to add image overlay from local imported .osm file 

### ISSUE THREAD

**Issue by xf05888** [vvoovv/blender-geo#154]
Hello, 

I imported a whole-city osm file and want to  add the image overlay (It says they're 99 tiles image to download) and apply it.

But I really confused that why it isn't display  at all, **so is this feature not supported?**

**Comment by vvoovv** [comment]
It is supported. Please read the documentation how to import an overlay:
https://github.com/vvoovv/blender-osm/wiki/Documentation#image-overlay-import

To view the image overlay set the option _Viewport Shading_ to _Look Dev_ or _Rendered_. The option is normally located at the top of the Blender 3D View as shown on the [screenshot](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/viewport_shading.png).
