### ISSUE TITLE
Error message on importing OSM-data referencing a script that can not be set

### ISSUE THREAD

**Issue by Scythwolf** [vvoovv/blender-geo#155]
Hi!
I just installed blender-osm to test it. After fresh installation of the addon I imported terrain, followed by image overlay. That worked fine, just as it shold. Unfortunately I ran into problems with 'OpenStreetMap'-import. Upon clicking 'import' I get the error message: The script file doesnt exist. I searched if other had the same problem but noone had. One person on youtube gave me a hint. I should change the advanced settings. Unfortunately I have none: This field is empty. 
Here are the screenshots. My guess is that something went wrong upon installation? 

Screenshots: https://imgur.com/a/cneFlCM

Further information on that error:
`bpy.data.window_managers["WinMan"].addon_search = "osm"
The directory for data in the addon preferences doesn't exist
bpy.context.space_data.recent_folders_active = 2
The script file doesn't exist
The script file doesn't exist
The script file doesn't exist
The script file doesn't exist
The script file doesn't exist
bpy.ops.object.editmode_toggle()
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
bpy.ops.object.editmode_toggle()
bpy.ops.object.delete(use_global=False)
Deleted 1 object(s)
bpy.context.scene.blender_osm.dataType = 'terrain'
bpy.ops.object.shade_smooth()
bpy.ops.blender_osm.import_data()
bpy.context.scene.blender_osm.dataType = 'overlay'
bpy.ops.blender_osm.import_data()
Overlay import is finished!
bpy.context.scene.blender_osm.dataType = 'osm'
The script file doesn't exist
`

**Comment by vvoovv** [comment]
You probably set something in the field "Setup script". That's an advanced option. Please leave it empty.

**Comment by vvoovv** [comment]
Sorry. That field was empty

**Comment by vvoovv** [comment]
Please save your Blender file after the error pops up and save the file for examination to prokitektura@gmail.com

**Comment by Scythwolf** [comment]
Thanks. I sent you a mail. There is a link to the file uploaded to gdrive. Thought this is better since the file is 28 mb. The .blend has all external files packed into it.

**Comment by vvoovv** [comment]
I checked your file out. Thank you for the feedback.
The field "Setup script" was NOT empty. Please leave it empty. It's an advanced option.

**Comment by Scythwolf** [comment]
Tahnk you very much! When advanced options was mentioned I was looking at the advanced options inside the Preferences - addons. Thanks

**Comment by vvoovv** [comment]
Thank you for using the blender-osm addon!
