### ISSUE TITLE
Bad behaviour when click in the Select button

### ISSUE THREAD

**Issue by mongat** [vvoovv/blender-geo#156]
When I click the Select button, Thunderbird mail client is open.
I am using Ubuntu 18.04, Blender 2.83.
When invoking Blender from a terminal, the following appears in the terminal:

console.log: WebExtensions: Loading packed extension from /home/_username_/.thunderbird/8eo4jlyq.default/extensions/sendlaterbutton@thunderbird-mail.de.xpi
Extension error: NetworkError when attempting to fetch resource. :0 :: startup@resource://gre/modules/Extension.jsm:2236:29

What am I doing wrong?

Thanks

**Comment by vvoovv** [comment]
Please try to set the default web-browser in the setting of your Operating System.

**Comment by vvoovv** [comment]
Never experienced that problem before.

**Comment by mongat** [comment]
Thank you. I define the default web browser as Google Chrome, and now is
working perfectly. My default Web browser was firefox before.
My OS is Ubuntu 18.04. It seems that I must keep as the default browser
Google Chrome.

**Comment by vvoovv** [comment]
Thank you for using the blender-osm addon!
