### ISSUE TITLE
TypeError: L.tileLayer.bing is not a function

### ISSUE THREAD

**Issue by d8sconz** [vvoovv/blender-geo#159]
I have just downloaded and installed the addon but when I click the select button the map won't load in the browser. This is the error from the browser console - 
TypeError: L.tileLayer.bing is not a function
    main http://prokitektura.com/blender-osm/extent/extent.js:79

Firefox 74.0(64bit) Linux

**Comment by vvoovv** [comment]
I am unable to reproduce the problem.
Everything works for me in Firefox 75.0 on Windows.

**Comment by d8sconz** [comment]
Can Linux have anything to do with it? I'm on a linux machine.

regards,
ps. I'm able to use the addon by manually entering coordinates, but browser
would be great

**Comment by vvoovv** [comment]
> Can Linux have anything to do with it? I'm on a linux machine. regards, ps. I'm able to use the addon by manually entering coordinates, but browser would be great

I don't think so. Could you please try it on Chrome?

Another alternative is https://www.openstreetmap.org/export
* Zoom to your area of interes
* Press "Manually select a different area"
* Select your area with the interactive selection box
* Copy the link under "Overpass API" to the clipboard (right mouse button click -> copy)
* Press the button "paste" on the blender-osm panel in Blender
![image](https://user-images.githubusercontent.com/613295/79105784-01ecce00-7d7a-11ea-9c78-b1301b235ad0.png)

**Comment by d8sconz** [comment]
Sorry for delay. Downloaded chrome and it works. Removed chrome and opened
firefox and the map (tab was still open) also worked! Go figure.

Thanks for your help

**Comment by vvoovv** [comment]
I am glad to know that it works for you!

**Comment by d8sconz** [comment]
Actually just tried it again and it's not working again. Obviously
something to do with Chrome vs Firefox. I'll just keep on the manual route,
but FYI

**Comment by vvoovv** [comment]
Try the method with the https://www.openstreetmap.org/export described above.

**Comment by d8sconz** [comment]
Yep, have done. Works a treat. Having the browser selector though, for the
one opportunity I had, was absolutely brilliant. It's a great addon
