### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Gavinfreeman1134** [vvoovv/blender-geo#16]
Hey vvoovv!
I hope you're still active. I've seen you replying in many forums to your addon.
My problem is simple, I can't reach the download link. Everytime I click on the download link, only a .text file opens in my browser.
Though I would really find your addon amazing. Is there any way to sort it out? Am I just blind or the link is broken for  some reason?
Thanks for the great work by the way!

**Comment by Gavinfreeman1134** [comment]
Never mind. I solved it. It was me. :) Thank you :)

**Comment by vvoovv** [comment]
Good,that you solved it yourself :)
