### ISSUE TITLE
Failed to activate module

### ISSUE THREAD

**Issue by Teclis01** [vvoovv/blender-geo#162]
Modules Installed () from 'D:\\Downloads\\blender-osm-2.3.24.zip' into 'C:\\Users\\teclis\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-osm-2'

It's the first time for me to use this module. Others modules can be installed and activated.
It seems that the behavior is for at least the 4 last release (free one).
The error happens when I try to activate the plugin.

**Comment by vvoovv** [comment]
Please read the [README](https://github.com/vvoovv/blender-osm/tree/release#important) file:

> Unless you are a developer, please get the addon [here](https://github.com/vvoovv/blender-osm/#blender-osm-openstreetmap-and-terrain-for-blender).
