### ISSUE TITLE
Support to OMAP file format

### ISSUE THREAD

**Issue by Symbian9** [vvoovv/blender-geo#17]
Please, modify OSM import addon for OrenOrienteering Mapper file format.
* http://github.com/openorienteering/mapper

OMAP is XML based and in some way similar to OSM XML file structure.

**Comment by vvoovv** [comment]
You'd better create a separate add-on for OMAP using OSM add-on as the reference.

**Comment by vvoovv** [comment]
I can develop the OMAP add-on provided funding is available.

**Comment by Symbian9** [comment]
Here is issue on OOMapper project page
https://github.com/OpenOrienteering/mapper/issues/657
