### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by C-Rage** [vvoovv/blender-geo#171]
Hi there
I appreciate the work you're putting into this, it's really great.
Unfortunately, I get this error:
![image](https://user-images.githubusercontent.com/65631973/82386528-ce394e00-9a73-11ea-8b7f-3952d7239c56.png)

My coordinates were pretty small, as you suggested, but I can't get buildings to come across now.

**Comment by vvoovv** [comment]
@C-Rage thank you for the bug report!

I'd suggest to remove the old version, restart Blender, then install the new one.

**Comment by C-Rage** [comment]
Hi Vlad
Will try again.

Stay safe and kindest regards!

Craig Easton
[signature_197956588]

**Comment by Vangelou123** [comment]
i have the same problen, I have new clean installation of blender 2.79 and the same error,no previous osm installed

**Comment by Vangelou123** [comment]
![1111](https://user-images.githubusercontent.com/69665645/90218173-653a4b80-ddc0-11ea-88e4-115adc01e9b6.png)

**Comment by vvoovv** [comment]
@Vangelou123 
Your problem is different. Please see #211
