### ISSUE TITLE
Lowering the number of vertices

### ISSUE THREAD

**Issue by al1brn** [vvoovv/blender-geo#172]
When importing large areas, the number of vertices could be far too much for Blender.
I wrote a little enhancement to reduce the number of vertices:
When importing a terrain, the user can select a reduction ratio (from 100% to 0,00028%)

In the example below, I imported a 10x10 area (Lon 30 to 40, lat 50 to 60). Without reduction, it represents more than 1 billions vertices. Applying 0.0001% ratio, it is only 130 k.

I'm not familiar with Github and contribution, not sure how I can pull this request.

Alain

<img width="296" alt="Capture d’écran 2020-05-24 à 16 48 07" src="https://user-images.githubusercontent.com/31390327/82757604-cfef7280-9de1-11ea-80d1-aab2ffb0e861.png">
<img width="236" alt="Capture d’écran 2020-05-24 à 16 48 22" src="https://user-images.githubusercontent.com/31390327/82757610-d5e55380-9de1-11ea-8662-ae50994a002a.png">
<img width="233" alt="Capture d’écran 2020-05-24 à 16 48 44" src="https://user-images.githubusercontent.com/31390327/82757612-d8e04400-9de1-11ea-99f1-bc7ba2c5f12f.png">

Here is the result with an area 10° x 10°:

![untitled](https://user-images.githubusercontent.com/31390327/82757623-eac1e700-9de1-11ea-9afd-a90e74c0699a.png)

**Comment by vvoovv** [comment]
Hi Alain,
Thank you! I'll review it this week.

**Comment by vvoovv** [comment]
Imported a large part of Caucasian mountains:

![image](https://user-images.githubusercontent.com/613295/83383183-45180480-a3ed-11ea-9a1f-a8ee08543834.png)

**Comment by vvoovv** [comment]
The code has been integrated to the addon so I am closing this issue.
