### ISSUE TITLE
increase resolution terrain texture

### ISSUE THREAD

**Issue by solido3d** [vvoovv/blender-geo#174]
Hello, I would like to know if it is possible to increase the resolution of the terrain image to have more detail. Thank you

**Comment by vvoovv** [comment]
Hi @solido3d ,

The resolution of the satellite imagery is calculated automatically by the addon, so the total size of the resulting texture does not exceed some threshold. Namely 256 image tiles (256x256 pixels), i.e. 4096x4096 pixels.

The first option to try is to decrease the size of your area of interest.

The other option would be to split the terrain into a number of parts and set each terrain part in the field "Terrain" on the addon panel. Then import the overlay image for the chosen terrain part.

The addon also checks if the resulting zoom is provided at all for an area of interest. If the resulting zoom is not provided, the same check is performed for the zoom decreased by one.

It's also possible to increase the threshold. Open Python Console in Blender. Copy and paste the line below:
`C.scene.blender_osm.maxNumTiles = 256`
Substitute `256` for a larger value and press Enter. Try to import the satellite imagery again.

**Comment by solido3d** [comment]
Thank you so much for everything. it was just what i was looking for. How
easy it seems when someone knows. really grateful

**Comment by solido3d** [comment]
Thank you so much for everything. it was just what i was looking for. How easy it seems when someone knows. really grateful

**Comment by vvoovv** [comment]
Thank you for purchasing the blender-osm addon!

Please let me know if you have any further questions!
