### ISSUE TITLE
import module Error

### ISSUE THREAD

**Issue by Andy-Leo** [vvoovv/blender-geo#177]
My blender is installde by snap on ubuntu 18.04
python 3.7
It happened when i enable the addon:
**ModuleNotFoundError:No module named 'blender-osm-2'**

**Comment by vvoovv** [comment]
Please get the addon from https://gumroad.com/l/blender-osm (the base version) or https://gumroad.com/l/blosm (the premium version).

**Comment by Andy-Leo** [comment]
> Please get the addon from https://gumroad.com/l/blender-osm (the base version) or https://gumroad.com/l/blosm (the premium version).

It works,Thanks. Very nice addon
