### ISSUE TITLE
import crashes [dev] -- TrapezoidChainedRV

### ISSUE THREAD

**Issue by Zkir** [vvoovv/blender-geo#179]
import crashes [dev]:
![image](https://user-images.githubusercontent.com/874906/84090330-25d73380-a9fa-11ea-9879-861df28d3c2a.png)

See the attached osm file
[vladimir.zip](https://github.com/vvoovv/blender-osm/files/4749107/vladimir.zip)

**Comment by vvoovv** [comment]
Levels can't be created for a gabled roof at the moment.

**Comment by Zkir** [comment]
Tested on the latest DEV Branch -- OK.
