### ISSUE TITLE
Most of buildings need recalculate normals to outside

### ISSUE THREAD

**Issue by Symbian9** [vvoovv/blender-geo#18]
I try few different OSM data sets, and always get similar results: most number of building after import in Blender (when use any thickness bigger then zero) needed fix their normals orientation.
One of data set ("Olney.osm") I get from here:
* http://wiki.openstreetmap.org/wiki/Maperitive/SampleRenderings

So, think, its a bug of OSM import script.

**Comment by vvoovv** [comment]
There is already a ticket for that problem, See #1.
