### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by KamilKucharsk1** [vvoovv/blender-geo#183]
When I'm trying to run a several scripts in a row I get HTTP Error 429: Too Many Request and I have to wait some time after that. Is there any way to get around it? Terrain which I select isn't as large it is about hundred tiles (small part of a city). Line 66 is `bpy.ops.blender_osm.import_data()` from my script, but also when I`m importing it by user interface of addon get the same result (without my script Traceback)

![obraz](https://user-images.githubusercontent.com/37003583/85018728-f77df480-b16d-11ea-8e23-5e014d4b6fc9.png)

**Comment by vvoovv** [comment]
Hi @KamilKucharsk1 
Could you please provide some description what content you were trying to download? Is it overlay imagery? Which one?

**Comment by KamilKucharsk1** [comment]
I have add better description now. It's OpenStreetMap import.

**Comment by vvoovv** [comment]
Ok, thank you for the feedback!

Here are the thing to try:
* Try it again later.
* If you need to import the area again, note the collection name (e.g. _map_67.osm_), find it in the folder _/blender/osm_ and use the option _import from file_ to import it.
* Try another OSM server (the option at the very bottom of the addon preferences)

**Comment by KamilKucharsk1** [comment]
Thank you for the suggestions.
I tried another OSM server it helped me.
