### ISSUE TITLE
Premium version -  AttributeError: 'RoofFlatMulti' object has no attribute 'noWalls'

### ISSUE THREAD

**Issue by Rehvaro** [vvoovv/blender-geo#185]
Hello

I've just bought Blender-OSM, and I have a problem importing a region. I use Blender 2.83.0, with the 2.3.28 version of the addon.

Here is what I do:
-Opening the addon tab
-Click paste (I have the coordinates from the website opened by "select" in my clipboard : 2.28739,48.85122,2.30809,48.86143).
-I choose terrain and import
-I choose image overlay and import
-I choose OpenStreetmap, activate the "3D simple" option, uncheck everything except buildings, let the rest by default, and click import.
-After a few second I get : AttributeError: 'RoofFlatMulti' object has no attribute 'noWalls'.
-If I choose "3D realistic", the import get me: "AttributeError: 'RoofFlatMultiRealistic' object has no attribute 'noWalls'".

![blenderosmerror](https://user-images.githubusercontent.com/1692086/85220634-862c8480-b3ad-11ea-9b41-0d207820289a.jpg)

Could a fix be made ?
Thank you

Best regards,
Fabien

**Comment by vvoovv** [comment]
Hi @Rehvaro 
Thank you for reporting the bug. We'll fix it today.

**Comment by vvoovv** [comment]
The problem has been fixed. Please download the latest version (v2.3.29) using the link in your purchase confirmation message. Sorry for the inconveniences.

**Comment by Rehvaro** [comment]
Hello

It works very well. It's perfect !

Thank you very much. The issue can be closed as resolved :)
