### ISSUE TITLE
[dev] a lot of warnings in console

### ISSUE THREAD

**Issue by Zkir** [vvoovv/blender-geo#186]
There are a lot of warnings in console:

```
assign as a type annotation: BlenderOsmPreferences.dataDir
assign as a type annotation: BlenderOsmProperties.maxLat
Warning: class BLOSM_OT_create_materials contains a property which should be an annotation!
Warning: 'PanelBlosmSettings' doesn't contain '_PT_' with prefix & suffix

```
And a lot of others: see the attached file

[Church-vozdvizhenskoe.log](https://github.com/vvoovv/blender-osm/files/4815652/Church-vozdvizhenskoe.log)

**Comment by vvoovv** [comment]
Warnings are due to Blender 2.79 support. I'll get rid of warnings after stopping Blender 2.79 support
