### ISSUE TITLE
[dev] Import crashes -- "KeyError: buildings"

### ISSUE THREAD

**Issue by Zkir** [vvoovv/blender-geo#187]
![image](https://user-images.githubusercontent.com/874906/85338289-a7df5600-b4ea-11ea-8cd5-9fe572fd12b1.png)

see also the log file
[Church-vozdvizhenskoe.log](https://github.com/vvoovv/blender-osm/files/4815729/Church-vozdvizhenskoe.log)

Original osm files can be found here
https://github.com/Zkir/blender-osm/tree/dev/test/samples

**Comment by vvoovv** [comment]
That's due to the latest development to support texture atlases. I'll fix it later this week.

**Comment by Zkir** [comment]
Tested on the latest DEV branch -- OK.
