### ISSUE TITLE
Bathymetry oddness

### ISSUE THREAD

**Issue by jgwinner** [vvoovv/blender-geo#192]
When importing an area including terrain along a coastline, I get some weird heights.

In particular, some of the terrain seems to be higher than some of the buildings. 

For example, see the piers around Monaco:

Is this a known issue and does the "Pro" version fix this problem? Where does the Bathymetry data come from?

![image](https://user-images.githubusercontent.com/10425170/86499937-b88d9880-bd42-11ea-9cb1-f0b45cb081a8.png)

**Comment by jgwinner** [comment]
Area is around: 7.39886,43.70961,7.46272,43.75698

**Comment by vvoovv** [comment]
The premium version uses the same source for the terrain.

It's basically the SRTM data set with some additions. More details can be found [here](https://github.com/vvoovv/blender-osm/wiki/Terrain).

**Comment by jgwinner** [comment]
I was sort of hoping you were combining two DEM's and the edge was where it was blended wrong :)

Hmm ... not sure what to do then. I was hoping not to have to clean up by hand, was trying to create an automated process.

I'll follow up with them!

Thanks, I'll close this.

**Comment by vvoovv** [comment]
Yes, some editing of the terrain is required in the Blender EDIT and/or SCULPT modes for that case.

**Comment by jgwinner** [comment]
Do you know if there is any other terrain data out there that might be better, although not as well suited for what you're doing? (the issue of course then would be registration with your fantastic output). 

        == John ==

**Comment by vvoovv** [comment]
I am not aware on another terrain data set with global coverage. It's possible to import OpenStreetMap in any geograpical projection using bpyproj addon: https://github.com/vvoovv/blender-osm/wiki/Documentation#custom-map-projections
