### ISSUE TITLE
Download not listed on website?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [vvoovv/blender-geo#202]
I can't find the download for your website.

**Comment by vvoovv** [comment]
The addon can be downloaded for free [here](https://gumroad.com/l/blender-osm).

**Comment by umustbeloggedintododat** [comment]
Ah I found it out already

**Comment by umustbeloggedintododat** [comment]
Also is there a 2.79 version or is it not possible?

**Comment by vvoovv** [comment]
As of today, Blender 2.79 is still supported.

**Comment by umustbeloggedintododat** [comment]
OK.

**Comment by umustbeloggedintododat** [comment]
Thanks! I imported an area of my town. It worked fine in 2.79.

Two questions:
It would've been cool if it added trees. Are trees a plan?
Are building textures a thing?

**Comment by vvoovv** [comment]
Import of forests and separate trees along with textured buildings is available in the premium version:
https://gumroad.com/l/blosm

**Comment by umustbeloggedintododat** [comment]
Aw, well that sucks. I'm not a paid program user.

**Comment by vvoovv** [comment]
Well, full source code is available at https://github.com/vvoovv/blender-osm/tree/release
Consider that you pay for textures and materials rather than for the program.

**Comment by umustbeloggedintododat** [comment]
Ok.

**Comment by umustbeloggedintododat** [comment]
I found the premium and the base so I mixed those together and it is telling me for trees and building materials which I don't have...
