### ISSUE TITLE
Download massive terrain?

### ISSUE THREAD

**Issue by klydra** [vvoovv/blender-geo#203]
Hi,
Is there maybe a way to automate this addon in a way to maybe slowly download the whole world?
The calculation power and potential time would be no problem, but automation via for example macros seems kind of odd...
Any answer(s) would be very much appreciated!

**Comment by vvoovv** [comment]
It's possible to download the terrain for large areas, for example the whole Alps using the option "vertex reduction" in the "Terrain" panel:

![image](https://user-images.githubusercontent.com/613295/87232382-3d258a00-c3c7-11ea-9f13-7012689a9649.png)

**Comment by klydra** [comment]
Thanks, I didn't knew that.
Basically, I thought, that when the online selector tools responds with too big, I can't process the map.
My problem is, that I pretty much need the whole world with Ratio 100% for terrain and OpenStreetMap.
Can you name the maximum possible size for each?
Because, as soon as I get in the millions of vertices, the number even turns negative for some reason...
Basically only the terrain would be a massive (-)830,476,144,799 vertex count.
If I'd know the maximum size for a pull from OpenStreetMap and the "terrain", I could divide the whole world in individual pieces and when finished place them together.
Possibly I could also automate that with a script, because blender is open source?
I have sadly no experience with python scripts for blender, although a fair knowledge of python, so any suggestions would also be welcome...

Problem for all scenarios I've tested :
![image](https://user-images.githubusercontent.com/40038209/87243258-e787c680-c434-11ea-8579-a801d5d4cf68.png)

**Comment by vvoovv** [comment]
May I know why you wants to import the whole world? What is target application is about? You might want to reply me via e-mail prokitektura@gmail.com

**Comment by vvoovv** [comment]
How to reproduce the error? What are the coordinates of the area of interest that caused the error?

**Comment by klydra** [comment]
I just noticed, that I slightly misunderstood the cord inputs to that extent, that the value of min was higher than max.
That apparently results, I suspect due to no input checking, in an error, where the vertex count turns negative and a 500 Bad Request Response from OpenStreetMap.
I would close this issue for now, but would reopen it, should there be anymore errors I encounter.
Thanks for your help.
