### ISSUE TITLE
Support for Blender 2.83.2

### ISSUE THREAD

**Issue by Zkir** [vvoovv/blender-geo#205]
Blender 2.83.2 is out.
However, the plugin does not installs for this verison.

Please help.

**Comment by vvoovv** [comment]
I can't reproduce the problem.

**Comment by Zkir** [comment]
Let's discus this via skype in such a case.
Because i still can reproduce it.

**Comment by Zkir** [comment]
Ok, it works now. 
Thank you.
Maybe it was some glitch.
