### ISSUE TITLE
add OSM tags as vertex group

### ISSUE THREAD

**Issue by mirlip** [vvoovv/blender-geo#21]
Hi vvoovv,
Really great osm importer and really fast. Would it be possible in the "one mesh" mode to have the tags added as vertex groups like in the official blender osm importer? Your plugin is much better, and this functionality would make it perfect :)

**Comment by vvoovv** [comment]
What is the use case behind your request?

**Comment by mirlip** [comment]
Sometime, some OSM data are way to big to be imported as separate objects (Blender will not succeed after 2 hours of import because their are too many objects created). But mixing streets, building and all in one mesh is messy. 
Vertex groups would allow to keep the OSM information intact, while making the file to successfully import.

**Comment by vvoovv** [comment]
There is no need for Blender vertex groups to avoid mixing streets and buildings. Just do 2 imports:
1) Check only "Import buildings"
2) Check only "Import roads and paths"

**Comment by mirlip** [comment]
Yes it works. Thank you for the answer and sorry for delay.
