### ISSUE TITLE
Blender crash at high resolution overlay

### ISSUE THREAD

**Issue by co1yzha** [vvoovv/blender-geo#210]
I change the max number of tiles, which generates a level 17 mapbox satellite image download.  I can see the image is loaded into the drive. But When Blender is trying to tile them together, blender always crash. 

Just wondering if there is a way to avoid the crash, or to load the high resolution satellite image. 

Many thanks.

**Comment by vvoovv** [comment]
I'd suggest to divide the terrain into 4 parts and import the satellite imagery for each part separately.

**Comment by co1yzha** [comment]
@vvoovv 

Thx a lot for the suggestion.
