### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Vangelou123** [vvoovv/blender-geo#211]
I have a new installation of blender 2.79 no previums omp version installed
![1111](https://user-images.githubusercontent.com/69665645/90218061-1e4c5600-ddc0-11ea-9b49-ffb2352c2fa6.png)

**Comment by vvoovv** [comment]
Blender 2.8x was released more than one year ago, so support of Blender 2.79 has been dropped.
Please update to Blender 2.8x.
