### ISSUE TITLE
(request/help) Power of 2 texture selection box for Terrain Exporting

### ISSUE THREAD

**Issue by DaleHat** [vvoovv/blender-geo#212]
ive been messing with the selection box trying to figure out how to get a Square and for the texture of the terrain to be a power of 2 so far the cloeset i got was 2048x2560

also it appears that the texture overhangs on the terrain, i assume its because the selection box i used wasnt matched up to the zoom i extracted.
![image](https://user-images.githubusercontent.com/5893597/90953359-5f7fde00-e430-11ea-904c-3bc3b15c2a04.png)

any help would be greatly aperciated 

also itd he handy if the selection box numbers could be interacted with in the web browser to easily change one specfic direction without having to move the mouse with godly percsion

**Comment by DaleHat** [comment]
i managed to get one bit of land really close to a power of 2
lon diff .0130
lat diff .0075
equals 5120x5120 at 19zoom

however im almost positive there is a overlap because when i timesd the difference by 2 my expected resolution shoulda been 10240x10240 however it ended up being 9984x10240

**Comment by vvoovv** [comment]
Hi @DaleHat ,

May I know why you need a square texture?

**Comment by DaleHat** [comment]
Working on making a 1:1 scale Map in Fallout 4 using your addon to pull the terrain and texture of areas so far i think i got alot of the math worked out tho im about to have todo another Scale test to make sure the map is 1:1 scale with fallout's scale.
![peep](https://user-images.githubusercontent.com/5893597/91076536-49774680-e605-11ea-89d5-4921538d3f57.png)

as it turns out i dont think the texture really needs to be a power of 2 but if its not it'll throw a error but it hasnt crashed the Creation kit yet.
the process is a bit of a hassle mainly because a area has to be split into multiple 'chunks' and selecting those chunks dont always output a power of 2 texture

**Comment by DaleHat** [comment]
![image](https://user-images.githubusercontent.com/5893597/91077027-fe116800-e605-11ea-9795-cec25352446f.png)
this is the error that'll pop up when the model isnt using a texture that is a power of 2

**Comment by DaleHat** [comment]
to quote a post i found on reddit

'The engine has an area of -64 to +63 (128 Cells or 4.65 miles wide) along the X-axis, and -128 to +127 (256 Cells or 9.3 miles tall) along the Y-axis.'

ideally id like to make the area a square that'd cover 4.65 miles X 4.65 miles

**Comment by vvoovv** [comment]
Yes, it would require some scripting.

I'd propose the following solution.

Given the desired texture width W and height H, set the import coordinates so:
(deltaLon in meters)/(deltaLat in meters) = W/H

Perform the import

Read the UV coordinates of the terrain corners and use them to cut a sub-image from the texture. That sub-image should have the same ration W/H

Scale the image uniformly to the required dimensions (power of 2).

**Comment by DaleHat** [comment]
i'll try that out thank you :D
