### ISSUE TITLE
Blender OSM

### ISSUE THREAD

**Issue by cpg0816** [vvoovv/blender-geo#214]
I installed the Premium version of Blender OSM. However, the percentage of lit windows is not appearing in the selection.
I'm using Blender 2.90
![OSM lit windows](https://user-images.githubusercontent.com/67248929/92217856-d1ddcd00-eeca-11ea-85b5-8c826524918a.jpg)

**Comment by vvoovv** [comment]
@cpg0816 
Lit windows aren't yet supported in the experimental mode.
Please uncheck the option _Enable experimental features_ in the addon preferences to get lit windows,

**Comment by cpg0816** [comment]
Hi Vladimir,

Thank you very much for the prompt response.

Charlie.
