### ISSUE TITLE
Unable to enable the blender-osm addon

### ISSUE THREAD

**Issue by Akshaytripathi7** [vvoovv/blender-geo#215]
I downloaded the BLENDER OSM base version and i tried installing the addon in blender but the addon isnt enabling in blender and a weird messae pops up ! Could you please help me in solving this ? 
![cfjdff](https://user-images.githubusercontent.com/52707635/92724080-ad309c00-f387-11ea-815e-105ee699453f.png)

**Comment by vvoovv** [comment]
Blender 2.80 has been released more than a year ago. Please upgrade to it.

**Comment by vvoovv** [comment]
Blender 2.79 is not any longer maintained.
