### ISSUE TITLE
Unable to install ccorrectly

### ISSUE THREAD

**Issue by gossizappz** [vvoovv/blender-geo#216]
When installing the free version, it states to upgrade to 2.8x required. I'm running 2.83.6. Have removed and installed several times with no luck.
![image](https://user-images.githubusercontent.com/4251871/93013665-ea966300-f5ed-11ea-92de-3c16f155a40f.png)
Regards

**Comment by vvoovv** [comment]
Hi @gossizappz 
Your version is at least one year old. Note that it looks completely diffrent. Please get the latest one from https://gumroad.com/l/blender-osm.
![image](https://user-images.githubusercontent.com/613295/93022395-df453680-f5f1-11ea-9cdc-b954f342f28f.png)

Curious where you got your version.

**Comment by gossizappz** [comment]
Hi, I downloaded again from Gumroad and all is fine. Thank you for your prompt reply.

**Comment by gossizappz** [comment]
Hi Vladimir, thank you for your prompt help. I have downloaded again from
Gumroad and all is good now. I don't know what happened with the first
download.

Once again, thank you. I will look at getting the paid version.
Kind regards
Phil
