### ISSUE TITLE
 how to solve this problem  Please set a directory with assets (building_materials.blend, vegetation.blend) in the addon preferences or addon GUI!

### ISSUE THREAD

**Issue by Ubaydullo2020** [vvoovv/blender-geo#217]

**Comment by Ubaydullo2020** [comment]
Please set a directory with assets (building_materials.blend, vegetation.blend) in the addon preferences or addon GUI!

**Comment by vvoovv** [comment]
Please set the folder for assets as described in the [documentation](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#video-tutorial).

**Comment by Ubaydullo2020** [comment]
aaa how to find such an asset

**Comment by vvoovv** [comment]
Click the download link in your purchase confirmation email. There will be two files: _blender-osm.zip_ and _assets.zip_.
Download both of them. Then follow the [installation instructions](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#video-tutorial).

**Comment by fabrizioschiano** [comment]
In order to have the assets you need to pay, correct?

**Comment by vvoovv** [comment]
> In order to have the assets you need to pay, correct?

@fabrizioschiano 
It's the setting of the premium version.
