### ISSUE TITLE
Terrain not centered in Blender Grid map

### ISSUE THREAD

**Issue by jcheamit37** [vvoovv/blender-geo#219]
So everything seems to be okay with OSM in Blender 2.9 with selecting and pasting the coordinates into Blender the first few times, but recently, the terrain went off center and is positioned somewhere where I can't bring it back to the start. It also seem to be really small which explains the short load times I'm new to using Blender so I don't know how to bring the object back but the the cursor is aligned fine.
This is me zoomed out with 1,000,000m clip end.
![Terrain not centered](https://user-images.githubusercontent.com/56267925/94328322-89707700-ff7f-11ea-922c-75645bb92115.PNG)

If I try adjusting the end focal to more than the above it gets more visible but the screen gets covered in static.

![clip end zoomed out](https://user-images.githubusercontent.com/56267925/94328731-cf7b0a00-ff82-11ea-81df-0f16006d0a1f.PNG)
This is the clip view setup

**Comment by vvoovv** [comment]
Hi @jcheamit37 

Every subsequent import is done relative to the very first one.

If your import areas are very far away from each other, the options are:
* Check the option _Ignore existing georeferencing_
OR
* Restart Blender
