### ISSUE TITLE
Use UTM to standardize projection

### ISSUE THREAD

**Issue by domlysz** [vvoovv/blender-geo#22]
Hi vvoovv,

I've recently needed to refactoring how I handle georeferencing informations in BlenderGIS. Time to talk about compatibility! I know it's already an old discussion and I made no progress last year but its better late than never.

So, I try to match the work already initiate by you and Lukas on [dxf importer](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/DXF_Importer), especially I've reused the SRID convention to specify the map projection. [Here](https://github.com/domlysz/BlenderGIS/wiki/Gereferencing-management) I try to describe more precisely my work.

However my tool is still not completely compatible with blender-geo. In BlenderGIS, it's possible to hack the SRID to pass directly a proj4 string as explained [here](https://github.com/domlysz/BlenderGIS/issues/10), so I can include in my tool a special predefined CRS to build the corresponding proj4 string. But I don't specially want to maintain the support of proj4 string, because I think most of the case EPSG codes are enough.

Likewise, I'm not really happy with the solution used in dxf importer, because it specify the custom transverse mercator through a special keyword and, at all, it's not a standard way to define a projection.

So I think maybe a better solution would be to use UTM in blender-geo to standardize the projection and maintain acceptable distortions. Each UTM zone has a dedicated EPSG code : 326xx for north hemisphere and 327xx for south. I think UTM formula is pretty close to the one you actually use but needs some extra code to determine the zone. Maybee there are some helpful functions [here](https://github.com/Turbo87/utm).

What do you think ?

Regards

**Comment by vvoovv** [comment]
I think Blender is a 3D modelling software, not a specialized GIS software. So here are my conclusions taken into account that point.
1) The key task of geographical importers is to load data with real dimensions without distortions.
2) I don't think it's a good idea to overload Blender users with very specific GIS terms like projections, SRID, EPSG codes, etc.

The current solution with Transverse Mercator works quite well to solve those problems. So I'd prefer to keep it.

**Comment by domlysz** [comment]
Thanks for your answer

I understand your opinion, especially keeping the OSM importer simple as most as possible is important considering the large audience that may interest.

For my part, I'm not afraid to introduce GIS terms because its how geographics data are handle at all and I can't build importer for specifics formats like shp or geotiff without talking about georeferencing or projection.

However, I'm not really in favor to introduce reprojection capabilities to Blender, even if I finally come to this to improve my tool and offers new interesting functions. For me it's an help for solving some situation not a finality and I really encourage users to preprocess their data beforehand, in a dedicated software.

The important thing is not reprojection but georeferencing. Some people ask for compatibility between addons which handle georeferencing informations and I think it's significant. But to achieve this keeping track of all georeferencing infos is essential : scene origin geolocation and map projection that all, not a big deal. 

 I can hack my tool like dxf importer to handle the special case of blender-geo transverse mercator however it will be better if we can converge to a more standard way, and need your cooperation here.

I don't think this modificiation have a huge impact for end-user of osm importer:
- you don't need to bother user about reprojection, SRID or EPSG, just add this information in scene propeties, most of user will don't care about this but some others can rely on it.

- The scale error within each zone of UTM distortion remains less than 0.1 percent. I think its very acceptable and can't imagine any user complains about this.

Hope you reevaluate your position !

Regards

**Comment by vvoovv** [comment]
The current solution with Transverse Mercator works perfectly for me and other users of the _blender-geo_ add-on. It perfectly solves the problems I mentioned in my previous message:
1) negligible distortion
2) simple to use

So I don't see the need to use other projections.

You may assume in your code that if the Blender scene has custom attributes _longitude_ and _latitude_ and no specific attribute about projection, then the Blender scene is in the Transverse Mercator with the center in _longitude_ and _latitude_.

**Comment by domlysz** [comment]
ok no problem understand your point
