### ISSUE TITLE
Invalid Syntax When Installing OSM Basic version

### ISSUE THREAD

**Issue by iamonanasus** [vvoovv/blender-geo#220]
Hello! I was _super_ excited to use this plugin and just purchased the basic version to start with for $6 yesterday.

When installing it onto my 2.79b version of Blender (still a somewhat newb and 2.79 is what I'm most accustomed to atm) - I get an Invalid Syntax message.

![image](https://user-images.githubusercontent.com/71942139/94347716-1d802400-fffc-11ea-9b72-f42ea09801a7.png)

I don't know how to fix what this error notification is telling me.

Can anyone help me understand how to get this addon going on my computer? Would be soooo appreciated.

**Comment by vvoovv** [comment]
Hi @iamonanasus 

Blender 2.80 has been released more than a year ago. Please upgrade to it.
Blender 2.79 is not any longer maintained.
