### ISSUE TITLE
Nothing will import

### ISSUE THREAD

**Issue by eryan5** [vvoovv/blender-geo#221]
Every time I try to import my map, it errors out and gives me this message. 
I was following the instructions on this video step by step until I reach 4m:20s mark 
https://www.youtube.com/watch?v=NW_djQS_N8U
Every time I press import it gives me the access denied screen. Is there possibly something I missed or overlook?

![image](https://user-images.githubusercontent.com/49933101/94638556-3f9dce80-02a8-11eb-991a-aa0122dd21c7.png)

**Comment by vvoovv** [comment]
Please set a valid folder with the write permissions in the addon preferences.
[Here](https://github.com/vvoovv/blender-osm/wiki/Documentation#video-tutorial) are the installation and usage instructions:

**Comment by eryan5** [comment]
> Please set a valid folder with the write permissions in the addon preferences.
> [Here](https://github.com/vvoovv/blender-osm/wiki/Documentation#video-tutorial) are the installation and usage instructions:

That worked. Thanks!
