### ISSUE TITLE
Getting error while trying to Import for Export

### ISSUE THREAD

**Issue by BilodeauIsADev** [vvoovv/blender-geo#222]
Here is the error code i am getting while trying to Import for Export. I won't work at all
![Untitled1](https://user-images.githubusercontent.com/72462615/95232661-d26fc900-07d2-11eb-8efd-6147cd8b48e5.png)

**Comment by vvoovv** [comment]
Hi @Masterofpoulet,

I was unable to reproduce the problem.

Could you please import your area of interest again and send me a screenshot of the Blender System Console (Top Menu -> Window -> Toggle System Console)?

**Comment by BilodeauIsADev** [comment]
Hi @vvoovv For some reason i simply reinstalled the addon from scratch doing the proper procedure from the documentation and the problems went away! Thanks anyway for the help. The only thing i could think about that could have fixed the problems is that i unchecked the relative path when selecting my assets folder. Love the addons btw :) Thanks
