### ISSUE TITLE
Importing Terrain in Blender 2.90

### ISSUE THREAD

**Issue by JoeOlafs** [vvoovv/blender-geo#223]
I'm running into problems when trying to import the terrain for a map in blender 2.90. I can import the image overlay and the image overlay but this is the error that comes up when trying to import the terrain
![Screenshot 2020-10-10 103803](https://user-images.githubusercontent.com/67959441/95649172-da867c00-0ae4-11eb-9ac0-f77a7c352763.png)

**Comment by vvoovv** [comment]
Hi @JoeOlafs 
What are the coordinates of your area of interest? I'll try to reproduce the problem.

**Comment by JoeOlafs** [comment]
This is Manhattan so the terrain is not a big issue, it's pretty flat. 
I tried to do it with a terrain that is has mountains and it worked there. 
![Screenshot 2020-10-10 110705](https://user-images.githubusercontent.com/67959441/95649899-c17fca00-0ae8-11eb-88e7-6d16ec71bc1f.png)

**Comment by vvoovv** [comment]
I was unable to reproduce the problem.

I guess there was a download problem.
I'd suggest to remove the files
{data folder in the addon preferences}/terrain/N40W075.hgt.gz
{data folder in the addon preferences}/terrain/N40W074.hgt.gz
and try importing the terrain again.
