### ISSUE TITLE
How is the way to get clear Roads on a terrain? 

### ISSUE THREAD

**Issue by ThatsHero** [vvoovv/blender-geo#226]
![Roads](https://user-images.githubusercontent.com/66516360/96447477-3dc58c00-1212-11eb-8fc3-4251c8404bc6.png)

**Comment by vvoovv** [comment]
You can increase the _Offset_ in the settings of the Shrinkwrap modifier for the Blender object that represents a road:

![image](https://user-images.githubusercontent.com/613295/96455471-f47f3780-1225-11eb-8705-d4844390e7c1.png)
