### ISSUE TITLE
Question: Get data for GPX track points

### ISSUE THREAD

**Issue by sgofferj** [vvoovv/blender-geo#227]
I'm trying to create an animation based on a GPX track. For the moving marker, I create an animation which is as long as the track was in real time. Then I add an object constraint that lets a marker follow the track. So far that works pretty nicely.
In addition to the moving marker, I'd like to create text objects which display the coordinates, altitude, heading, etc. at the current point of the animation. Can I get those in any way from the track?

**Comment by vvoovv** [comment]
Hi @sgofferj 
I think some coding is required to accomplish your task.
Could it be a screen overlay with the required information instead of text objects?

**Comment by sgofferj** [comment]
I'm kinda coming from overlays. I used to use a self-knitted PERL script that converts GPX to srt subtitles. I also used the GoPro dashboard software a while and gpx-animator.
Blender was supposed to be my next step to have a cool 3D HUD.
I might have figured out a workflow where I convert the GPX to GeoJSON and read that and feed it into animation nodes but that's a pretty complex workflow.

**Comment by vvoovv** [comment]
Here is an example Blender modal operator that writes some messages as Blender 3D View overlay:
https://github.com/vvoovv/blender-osm/blob/release/__init__.py#L513

The code for GPX is located in two places:
* [GPX parser](https://github.com/vvoovv/blender-osm/blob/release/parse/gpx/__init__.py)
* [3D geometry creation](https://github.com/vvoovv/blender-osm/blob/release/gpx/__init__.py) out of the parsed data

**Comment by sgofferj** [comment]
Thanks! With the GPX parser code and animation nodes I might be able to wire something up.
