### ISSUE TITLE
setup script error?

### ISSUE THREAD

**Issue by itneveroccurred** [vvoovv/blender-geo#228]
![Screenshot_271](https://user-images.githubusercontent.com/41230905/97515386-2c852980-194e-11eb-90b1-a25c6265d426.png)

How do I use the premium.py as my setup script? I just keep getting that error.

**Comment by itneveroccurred** [comment]
![Screenshot_272](https://user-images.githubusercontent.com/41230905/97517384-55a7b900-1952-11eb-8800-6d44e5c3edbf.png)

I also get this error when trying to use realistic_dev.py as my setup script,.

**Comment by vvoovv** [comment]
Hi @itneveroccurred 

The custom setup script is located in the _Advanced_ section. I'd advise you to keep it empty.

**Comment by vvoovv** [comment]
You could also try the _experimental_ mode that supports export of textures as described [here](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#export-of-the-imported-scene). Internally it uses the setup script _realistic_dev.py_. But again, I'd advise to keep the option _Setup script_ empty.
