### ISSUE TITLE
How to set zoom level for image overlay ?

### ISSUE THREAD

**Issue by TheFamousRat** [vvoovv/blender-geo#229]
Hey,
I want to get high resolution imagery of a specific zone of the world (mount Everest). The MapBox data was really unconclusive so I looked for a custom URL, and I found ESRI to give pretty good results (url : https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg ). 
However an annoying problem is that Blender-osm is that Blender OSM fixes the zoom level at 19, while this url doesn't seem to give images above zoom level 13. How can the maximum zoom level be specified ? I tried changing in the source code but that definitely doesn't seem to be the most practical way to go about it.
Thanks,
TheFamousRat

**Comment by vvoovv** [comment]
The maximum number of tiles is calculated by the addon to not exceed the maxim number of tiles.

So try to increase the maximum number of tiles to get a higher zoom:

![image](https://user-images.githubusercontent.com/613295/98385341-ea4f9c80-205f-11eb-98a8-72f0b1a807ed.png)

**Comment by TheFamousRat** [comment]
Thanks a lot, that solves partly the issue. I can't seem to go under 128, is that intended ?

**Comment by vvoovv** [comment]
Yes, the assumption was that otherwise the resolution of the overlay imagery would be to low.

**Comment by vvoovv** [comment]
Just curious, why do you prefer to use BlenderGIS?

**Comment by vvoovv** [comment]
_ArcGIS Satellite_ is now the default satellite imagery in the addon.

**Comment by LSC1759** [comment]
hi, how about when you want to use higher zoom level. for example z=23, but blosm caps to z=19.

**Comment by vvoovv** [comment]
Hi @LSC1759 

At the moment the maximum zoom is set in the code in the lines [398-404](https://github.com/vvoovv/blosm/blob/release/overlay/__init__.py#L398) of the module `blosm/overlay/__init__.py`
