### ISSUE TITLE
add a __init__.py and add bl_info

### ISSUE THREAD

**Issue by mirlip** [vvoovv/blender-geo#23]
Hi voov,
Would it be possible to put all the files in a folder with an __init__.py and add the bl_info part at the beginning. Missing bl_info gives bad performances.
Example of bl_info for addons:

> bl_info = {
>     'name': 'blender GEO',
>     'author': 'Voov',
>     'version': (1, 0),
>     'blender': (2, 7, 7),
>     'location': 'Toolshelf',
>     'description': 'import OSM etc',
>     'wiki_url': '',
>     'tracker_url': '',
>     'category': 'Import'}

**Comment by vvoovv** [comment]
bl_info is already there:
https://github.com/vvoovv/blender-geo/blob/master/io_import_scene_osm.py

**Comment by mirlip** [comment]
It seems it's not enough for blender. The console has many warning when your addons are activated about missing bl_info giving poor performance. I copied the bl_info above in all of the script and it solved the problem.

**Comment by vvoovv** [comment]
Which warning do you have?

**Comment by mirlip** [comment]
> fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\test\\AppData\\Roaming\\Blender Foundation\\Blender\\2.77\\scripts\\addons\\plugin_buider.py'
And it's the same for all the .py parts.

**Comment by vvoovv** [comment]
You don't need plugin_builder.py
Just download [io_import_scene_osm.py](https://raw.githubusercontent.com/vvoovv/blender-geo/master/io_import_scene_osm.py)

That's also stated in the installation [instructions](https://github.com/vvoovv/blender-geo/wiki/Import-OpenStreetMap-(.osm)#installation)

**Comment by mirlip** [comment]
Ok, I understand now. Maybe to help other user not reading this thread, it would be good to make a separate folder for files that are not plugins. Thank you for your support.
