### ISSUE TITLE
Importing forest and separate tree do not work.

### ISSUE THREAD

**Issue by Xiarno** [vvoovv/blender-geo#231]
Blender 2.90.1
OSM Premium addon v2.4.28
Windows 10
Directory to store downloaded OSM & terrain files has been setup correctly.
Directiry with assets has been setup correctly.

Importing forest and separate tree do not work. It return this error:

![image](https://user-images.githubusercontent.com/24660485/99884640-d5494080-2bfd-11eb-8d9e-cbfb973430e9.png)

**Comment by vvoovv** [comment]
Hi @Xiarno 

Thank you for reporting the issue! It's related to the API change in the latest version of Blender.

I'll provide the fix tomorrow.

**Comment by vvoovv** [comment]
The fix is ready.

Please download and install it using the link in your purchase confirmation email.

Sorry for inconvenience.

**Comment by FuuChang1002** [comment]
The same problem occurs in the free version; the blender version occurred in both 2.83 and 2.90.
Nothing can be imported from both the server and the file except terrain and textures.

**Comment by vvoovv** [comment]
@FuuChang1002 
Your problem is a different one. Please open a new issue and attach some screenshots to illustrate your problem.
