### ISSUE TITLE
Nothing can be imported from both the server and the file except terrain and textures.

### ISSUE THREAD

**Issue by FuuChang1002** [vvoovv/blender-geo#232]
the blender version occurred in both 2.83 and 2.90.
Nothing can be imported from both the server and the file except terrain and textures.
![スクリーンショット 2020-11-25 012829](https://user-images.githubusercontent.com/74979467/100236158-a40ba000-2f70-11eb-9f1b-ca21843af5ee.png)

**Comment by vvoovv** [comment]
I'd like to repoduce the problem. Please send the OSM file to prokitektura@gmail.com

**Comment by FuuChang1002** [comment]
Today I sent you the zip I downloaded from GUMROAD. 
This is what caused the error this time.

The subject line of the email is "FuuChang1002"
