### ISSUE TITLE
No Sidebar Menu (MacOS, Blender Version 2.91.0)

### ISSUE THREAD

**Issue by gideongrinberg** [vvoovv/blender-geo#233]
I'm brand new to Blender, so I'm probably doing something dumb here. Any help is much appreciated.

### What's the issue?
I installed blender-osm by downloading the zip and installing it in the addons section of the preferences. When I open the right sidebar by pressing <kbd> N </kbd>, all I see are the <kbd> Item </kbd>, <kbd> Tool </kbd>, and <kbd> View </kbd> options but not the osm menu. 

### What have I tried?
I also tried enabling it via <kbd> Tool </kbd> -> <kbd> Filter Add-ons </kbd> -> <kbd> Import - Export blender-osm </kbd>. I downloaded the addon [here](https://gumroad.com/l/blender-osm).

### System Information
**Blender Version:** 2.91.0 (2.91.0 2020-11-25)  ⬅️  This could be the issue
**Operating System & Version:** MacOS Catalina 10.15.7
**System Python Version (doesn't matter afaik, but I might as well just in case)**: Python 3.8.1 via PyEnv

I've looked through most of the issues, and I don't really see a solution that applies to me. I'll try this on my Windows machine later today. Let me know if you need any more information.

Thanks in advance,
@gideon357

**Comment by gideongrinberg** [comment]
<del>As an update, I tested this on my Windows box running 2.9.0. It doesn't work. </del> Fixed on Windows, not Mac

**Comment by vvoovv** [comment]
Hi @Gideon357 
How did you fix it on Windows?

Is the Blender-OSM addon available in the list of Blender addons on Mac?
Edit -> Preferences -> Add-ons -> type _osm_ in the search box

**Comment by vvoovv** [comment]
no feedback

**Comment by gideongrinberg** [comment]
My sincere apologies for the delayed reply. The OSM addon is indeed on the list.

**Comment by vvoovv** [comment]
If the addon is in the list and enabled, then everything should be ok,
