### ISSUE TITLE
Downloading Overlay in Python 

### ISSUE THREAD

**Issue by ryanchen26** [vvoovv/blender-geo#234]
I'm trying to use your addon to automate the setup of an environment, but the overlay image tile download function only occurs after the script has finished executing. Ideally I'd like to save the blender file with the complete scene (including the ground texture) as the last step in the python script,  So the work around for will be using a bat file to trigger scripts, sleep, trigger more scripts, sleep, and then save the blend file.  Is there an easier way? Thanks!

Example: 
bpy.context.scene.blosm.dataType = 'osm'
bpy.ops.blosm.import_data()

bpy.context.scene.blosm.dataType = 'overlay'
bpy.ops.blosm.import_data() 

# Animate some stuff, then...
bpy.ops.file.pack_all()
bpy.ops.wm.save_as_mainfile(filepath="myScene.blend")

#The overlay doesn't get packed or saved because it hasn't downloaded yet - not until the script ends, but the file is already saved.

**Comment by vvoovv** [comment]
Hi @ryanchen26 

Thank you for the very useful question.
I've made a few [changes](https://github.com/vvoovv/blender-osm/commit/cac9c9e340f84dae8726618a981b6895605d0c70) in the separate branch [command_line](https://github.com/vvoovv/blender-osm/tree/command_line). I hope it solves your problem.

Please install the addon from https://github.com/vvoovv/blender-osm/archive/command_line.zip for testing.
Add the line
```python
bpy.context.scene.blosm.commandLineMode = True
```
in your script.

Please let me know if it works for you. Then I'll merge it to the main branch.

**Comment by vvoovv** [comment]
The solution from the _command_line_ branch is now the part of the release version (2.4.30 and above).

**Comment by ryanchen26** [comment]
Well done. Just tested it and it works! Thanks!
