### ISSUE TITLE
Unable to enable add-on after importing it

### ISSUE THREAD

**Issue by otisasswhoop** [vvoovv/blender-geo#237]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/76539260/103042084-6a658f00-4546-11eb-94f5-100e97842ac2.png">

**Comment by otisasswhoop** [comment]
I don't know what the issue was but it resolved itself. The add-on is now installed.

**Comment by vvoovv** [comment]
It's recommended to the previous version of the addon and restart Blender before installing a new one.
