### ISSUE TITLE
Import Open Street Map Error

### ISSUE THREAD

**Issue by VenturaG** [vvoovv/blender-geo#24]
When I attempt to import an .osm file, three perpendicular lines (like axes) appear along with the following error:

<img width="739" alt="screen shot 2016-07-09 at 6 59 31 pm" src="https://cloud.githubusercontent.com/assets/20375702/16710741/bde117f0-4607-11e6-8be9-81d963326529.png">

**Comment by vvoovv** [comment]
Could you please provide the related .osm file?

**Comment by maclaud** [comment]
same error for me ( in linux, mac and win10 - blender 2.7.7 [also try 2.7.4- 2.6.9]) but only with osm files that contain height properties, small cities and towns flat work ok

**Comment by vvoovv** [comment]
@maclaud please attach your .osm file

**Comment by maclaud** [comment]
[mapNY.osm.zip](https://github.com/vvoovv/blender-geo/files/356015/mapNY.osm.zip)
this is the map that i download from this tutorial: https://www.youtube.com/watch?v=i4ySFm4ey9U
it have been used successfully by other people

**Comment by VenturaG** [comment]
I tried with all of these files, mine are from NY as well and should have height properties.  I used the same tutuorial as maclaud.



[Archive.zip](https://github.com/vvoovv/blender-geo/files/356034/Archive.zip)

**Comment by vvoovv** [comment]
@maclaud @VenturaG 
I reproduced the error. I'll fix it as soon as possible.

**Comment by vvoovv** [comment]
Please reinstall the add-on and try it again.
