### ISSUE TITLE
No module named 'realistic.material.colors'

### ISSUE THREAD

**Issue by LadyRover** [vvoovv/blender-geo#241]
Hi,

I like to import the realistic buildings, but get an error "No module named 'realistic.material.colors'"
I am using the commercial [version.](url
![OSM Issue](https://user-images.githubusercontent.com/45069608/105606224-62dd1400-5d98-11eb-9af2-8c368d0241b1.jpg)
)
Any idea whats going on?

Thanks,

Fran

**Comment by LadyRover** [comment]
A restart seems to have fixed it ;-)

**Comment by vvoovv** [comment]
Hi @LadyRover 

It's recommended to delete the previous version of the addon and restart Blender before installing a new one.
