### ISSUE TITLE
Cantdownlad to blender plllugin

### ISSUE THREAD

**Issue by 1nky** [vvoovv/blender-geo#242]
Hi I've used the old long time ago way of getting osm data into blender. I have installed the addon in  2.82 and 2.9 and in both cases i get a 502 bad gateway error .. I also started an open map account but still not resolving to the server... is this an issue or am i doing something wrong?
thanks 
![image](https://user-images.githubusercontent.com/35410735/109428601-9e9a7780-79ef-11eb-92d8-7669f60dba2f.png)

**Comment by vvoovv** [comment]
Hi @1nky 

Please try to import your area of interest again. Alternatively you can set another OSM server at the bottom of the addon preferences.

**Comment by 1nky** [comment]
Thank you VladimirThe issue has resolved now .... thanks a lot ... great add on btw.

    On Monday, 1 March 2021, 09:45:56 GMT, Vladimir Elistratov <notifications@github.com> wrote:  
 
 


Hi @1nky

Please try to import your area of interest again. Alternatively you can set another OSM server at the bottom of the addon preferences.
