### ISSUE TITLE
3D Buildings LOD

### ISSUE THREAD

**Issue by Xurx0r** [vvoovv/blender-geo#243]
I'm working in a project with 3d buildings and looking for high LOD 3d buildings like this

[Image_02](https://www.dropbox.com/s/xw8uybsqnbr37dd/0.jpg?dl=0)
[Image_01](https://www.dropbox.com/s/pwkfnjm1e6i1fji/1.jpg?dl=0)

What services offer this kind of building LOD?

Thanks

**Comment by vvoovv** [comment]
https://3dwarehouse.sketchup.com
