### ISSUE TITLE
Install issue in linux blender 2.92

### ISSUE THREAD

**Issue by gilcolgate** [vvoovv/blender-geo#244]
After installing, there is no side toolbar to find the Osm button in. You can find the sidebar if you select Compositioning, but and you find a tool and  view menu, but there is no Osm button.

It seems like Blender layout has changed and maybe I should use an old version?

**Comment by vvoovv** [comment]
Hi @gilcolgate 

Press the key `N` to activate the right side bar. There should be a tab _osm_.
