### ISSUE TITLE
Import 3d realistic - failed - slash vs backslash problem in paths?

### ISSUE THREAD

**Issue by Danielmannn** [vvoovv/blender-geo#247]
Hi I found another problem and it looks like the system path vs OSM paths for the folder structers are conflicting each other.

![grafik](https://user-images.githubusercontent.com/83009280/115714506-79830f00-a377-11eb-9586-48b895515f7a.png)

**Comment by vvoovv** [comment]
The subfolder _default_ is missing in the path mentioned in the warning.

May I see your addon preferences window with the path to the assets?

**Comment by Danielmannn** [comment]
![grafik](https://user-images.githubusercontent.com/83009280/115755094-3e93d200-a39d-11eb-97b2-f427846affea.png)

**Comment by Danielmannn** [comment]
hm the folder is there though 
![grafik](https://user-images.githubusercontent.com/83009280/115755343-89ade500-a39d-11eb-8b59-c5a07384b298.png)

**Comment by vvoovv** [comment]
Thank you for the feedback.

I'll try to reproduce your file tree structure at my computer. I'll get back to you later

**Comment by vvoovv** [comment]
Very strange. I tried to simulate your settings (see the screenshot). Only the disk name differs from yours.
Everything worked for me as expected.

![image](https://user-images.githubusercontent.com/613295/115896434-191dcb80-a464-11eb-9562-09cf62e0c778.png)

**Comment by vvoovv** [comment]
Can you try a path to the assets on another drive?

**Comment by Danielmannn** [comment]
sorry I have so much to do. I did not try it but I think it is a windows related problam. I cant even opwn W: via the command line window... I will check at some point when i get to it.

**Comment by vvoovv** [comment]
I am going to close the issue for now. Please reopen it if you have more details.
