### ISSUE TITLE
FIXED: Error importing Realistic 3D buildings

### ISSUE THREAD

**Issue by Stilton0502** [vvoovv/blender-geo#248]
![error](https://user-images.githubusercontent.com/28845760/116224929-229b8200-a749-11eb-9b01-55c3f9a93d5d.png)

**Comment by Stilton0502** [comment]
Restarting Blender resolved the issue

**Comment by vvoovv** [comment]
Please try restarting Blender. Will it help?

**Comment by vvoovv** [comment]
You message was 10 seconds earlier :)
I's recommended to delete a previous version of the Blender-OSM add-on and restart Blender before installing a new one.
