### ISSUE TITLE
Controlling Blender.osm with Python

### ISSUE THREAD

**Issue by AmineZouitine** [vvoovv/blender-geo#252]
Hi for a project I use your addon in Prenium version, and I would like to be able to generate a map from a Blender script by giving it coordinates (the 4), I'm totally new in blender scripts and I can't do what I want to do.
Do you have an example of code that generates a city with buildings so that I understand how it works?

**Comment by vvoovv** [comment]
Hi @AmineZouitine,

Check the option _Python Tooltips_ in the Blender Preferences.

![image](https://user-images.githubusercontent.com/613295/119959710-ef991800-bfac-11eb-8f2b-699dcced1bcf.png)

Then hover over the required fields in the addon panel to find out how to access them in Python:

![image](https://user-images.githubusercontent.com/613295/119960405-98477780-bfad-11eb-9d7f-02f0b65f041d.png)

For example:
```python
import bpy
bpy.context.scene.blosm.maxLon = 20.5
```

Once all options are set, execute the line below:
```python
bpy.ops.blosm.import_data()
```
