### ISSUE TITLE
Use Blender 3drealistic mode with python

### ISSUE THREAD

**Issue by AmineZouitine** [vvoovv/blender-geo#253]
Hello, I try to use the realistic mode with a python script but I have an error in the console, while the same script with the classic or 2D mode works very well (I obviously have the prenium addon).

```python
import bpy
bpy.context.scene.blosm.minLat = 49.5413351
bpy.context.scene.blosm.maxLat = 49.5503351
bpy.context.scene.blosm.minLon = 3.9560897
bpy.context.scene.blosm.maxLon = 3.9699606
bpy.data.scenes["Scene"].blosm.dataType = "osm"
bpy.data.scenes["Scene"].blosm.mode = "3Drealistic"
bpy.ops.blosm.import_data()
```

**Comment by vvoovv** [comment]
Please post the error.

**Comment by AmineZouitine** [comment]
> 
> 
> Hello, I try to use the realistic mode with a python script but I have an error in the console, while the same script with the classic or 2D mode works very well (I obviously have the prenium addon).
> 
> ```python
> import bpy
> bpy.context.scene.blosm.minLat = 49.5413351
> bpy.context.scene.blosm.maxLat = 49.5503351
> bpy.context.scene.blosm.minLon = 3.9560897
> bpy.context.scene.blosm.maxLon = 3.9699606
> bpy.data.scenes["Scene"].blosm.dataType = "osm"
> bpy.data.scenes["Scene"].blosm.mode = "3Drealistic"
> bpy.ops.blosm.import_data()
> ```

**Comment by AmineZouitine** [comment]
My bad
