### ISSUE TITLE
Generate building from single shapefile

### ISSUE THREAD

**Issue by pangyyyyy** [vvoovv/blender-geo#254]
Hi, I've purchased the premium version and I really enjoy using this tool to create realistic building models from osm. I have 3 questions:
1. I would like to generate a building using a single shapefile/ building footprint instead of the whole osm file, how can I do that?
2. I also noticed that features like balconies, windows, and doors are available in the code but I did not see any option to add these features in the add-on. How can I incorporate those features into my generated building?
3. I can only select `gabled` and `flat` roof shapes in my add-on. I noticed there are other cool roof shapes like `hipped` or `dome` available in the code. How would I be able to change the roof shape to other types?

Hope to get your advice on this, and thanks for the great tool!

**Comment by vvoovv** [comment]
Hi @pangyyyyy,

Thank you very much for purchasing the Blender-OSM addon!

> 1. I would like to generate a building using a single shapefile/ building footprint instead of the whole osm file, how can I do that?

You can draw a single building footprint in JOSM (the OSM desktop editor), save it to your local drive and import it with the Blender-OSM addon.

> 2. I also noticed that features like balconies, windows, and doors are available in the code but I did not see any option to add these features in the add-on. How can I incorporate those features into my generated building?

Those features will be available later.

> 3. I can only select `gabled` and `flat` roof shapes in my add-on. I noticed there are other cool roof shapes like `hipped` or `dome` available in the code. How would I be able to change the roof shape to other types?

Those roof are generated if the related roof shapes are tagged in OpenStreetMap. Copy the string with the coordinates 101.5880,3.0421,101.5942,3.0488 to the clipboard and paste it to the addon panel with option _Enable experimental features_ checked. Import this area. It is densely packed with hipped roofs.

**Comment by pangyyyyy** [comment]
Cool, thank you so much! Looking forward to the new features!
