### ISSUE TITLE
Set dataDir from script

### ISSUE THREAD

**Issue by AmineZouitine** [vvoovv/blender-geo#256]
Hello, I'm trying to install the addon directly via script, so I have to install and activate it on blender (which is done) but I would like to set the data directory and the asset directory (I have the premium version) but I can't set these fields.

```python
import bpy, os, sys

argv = sys.argv
argv = argv[argv.index("--") + 1:]  # get all args after "--"
bpy.ops.preferences.addon_install(filepath=argv[0], overwrite=True)
bpy.ops.preferences.addon_enable(module='blender-osm')

if(not(os.path.isdir(argv[1]))):
    os.mkdir(argv[1])

bpy.ops.BlosmPreferences.dataDir = argv[1] # not working 

bpy.ops.wm.save_userpref()
```
![Capture](https://user-images.githubusercontent.com/53370597/123955461-ed5e1b00-d9a9-11eb-9598-88e96c05da8d.PNG)

**Comment by vvoovv** [comment]
Here is the correct code:

```python
import bpy
bpy.context.preferences.addons["blender-osm"].preferences.dataDir = "your_path"
```
