### ISSUE TITLE
HTTP Error 429: Too Many Requests -- when trying to load 3D building geometry in premium version

### ISSUE THREAD

**Issue by derekeden** [vvoovv/blender-geo#257]
I suppose I pressed it too many times... I bought the premium version and I was trying to test every setup script for the 3D realistic building textures. I was doing this to see what they all looked like and what would be the best looking one for my area.

I now receive the error:

HTTP Error 429: Too Many Requests

when I press the Import button to bring in 3D building geometry.

Is there a limit I can do in a certain time period? Is this temporary or permanent?

Thanks

**Comment by vvoovv** [comment]
Hi @derekeden 

Thank you very much for purchasing the Blender-OSM addon.

You can try it again later. Alternatively you can set another OSM server at the bottom of the addon preferences.

**Comment by derekeden** [comment]
Thanks, it ended up just working after 15min or so. Lesson learned! And thanks for the tip about the server.

Much appreciated.
