### ISSUE TITLE
Premium version won't install in Blender 2.93

### ISSUE THREAD

**Issue by BrotherShamus3** [vvoovv/blender-geo#260]
I had the premium version installed in 2.8 but for whatever reason, I can only install the free version in 2.93.

**Comment by vvoovv** [comment]
Please provide additional information. Some screenshots would be helpful

**Comment by BrotherShamus3** [comment]
I'm not sure what I could send for screenshots.  I just tried to install it
like any add-on (Edit, Preferences, Install, etc) and it seems like Blender
just won't install it.  The installation process works fine for the free
version though.  I'll try to re-download the premium version and try it
again today.

**Comment by vvoovv** [comment]
The addon zip-archive should be called _blender-osm.zip_ and have the size approximately 815 KB.

Most likely you were trying to install the file _blender-osm_(premium).zip_ which has a much larger size.
_blender-osm.zip_ is contained inside _blender-osm_(premium).zip_. Please extract blender-osm.zip out of _blender-osm_(premium).zip_ and install _blender-osm.zip_.

Alternatively, you could download _blender-osm.zip_ and _assets.zip_ separately and install the file _blender-osm.zip_.

Please inform me if that solved your problem.

**Comment by BrotherShamus3** [comment]
My apologies... you're absolutely correct.  I'm going to visit the 'bugs'
page and edit my comment to reflect my error.  Thanks for responding... it
really is a great add-on!
