### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by chrislandau** [vvoovv/blender-geo#261]
![image](https://user-images.githubusercontent.com/2086128/130367825-bed3577a-65fd-4bb9-8250-123cfc11c815.png)
 Using Blender 2.90.1

**Comment by chrislandau** [comment]
Or rather, it installed, but this is what I see when I enable in addon.

**Comment by BrotherShamus3** [comment]
Totally my mistake.  I forgot to unzip the blender-osm (premium) file and then install the blender-osm.zip from there.  I've got it installed again and it's working beautifully.  One of my favourite add-ons!

**Comment by vvoovv** [comment]
Hi @chrislandau 

Please try restarting Blender.
