### ISSUE TITLE
issues - blender 2.9.1 randomly crashing and buildings in new york not being generated

### ISSUE THREAD

**Issue by nigelmerle** [vvoovv/blender-geo#264]
building in new york area are not generated and cannot get other data as well, blender freezes and sometimes crashes

**Comment by vvoovv** [comment]
Hi @nigelmerle,

Please attach a screenshot with the addon panel.

**Comment by nigelmerle** [comment]
Im telling you that no buildings are downloading, do i need a screenshot for that?
Addon is version 2.5.1, im using token
I have tried to use different data service, not working.

I am trying to generate new york buildings

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vvoovv** [comment]
> Please attach a screenshot with the addon panel.

I need to see the addon settings  you used for the import.

**Comment by nigelmerle** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vvoovv** [comment]
Sorry, I can't see any screenshot or attachment. Please paste the screenshot of the addon panel with the import settings directly at the webpage https://github.com/vvoovv/blender-osm/issues/264

**Comment by vvoovv** [comment]
no feedback

**Comment by nigelmerle** [comment]
You are just a hungry motherfucker, all you care is making money with these gis information which is free to the public


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
