### ISSUE TITLE
what projection/units do the imports come in?

### ISSUE THREAD

**Issue by derekeden** [vvoovv/blender-geo#265]
Hi, I purchased the premium add-on, and am trying to make a georeferenced scene with other georeferenced data I have outside of OSM.

I can't seem to figure out what projection the buildings/maps come in as? I am choosing a bounding box in latlon, but the units clearly seem to be meters or feet. Everything is always centered at 0,0 in my scene. I've also tried using the bpyproj add-on to specify a projection. The imports still come in the exact same spot.

How can I specify a target projection, or know what the projection is so I can reproject myself? How can I stop the data from importing at the scenes origin, and actually import in their georeferenced location?

Thank

**Comment by vvoovv** [comment]
By default the transverse Mercator projection is used. The central meridian of the projection comes through the center of the imported scene. That ensures that the distortions are negligible in the vicinity of the center of the imported scene. If import another area after the initial import, it will be made relative the initial import unless the option _Ignore existing georeferencing_ is checked. Additional information can found [here](https://github.com/vvoovv/blender-osm/wiki/Georeferenced-Blender-Scene). 

PROJ.4 parameters of the default projection:

```
+proj=tmerc +a=6378137 +b=6378137 +lat_0=<lat> +lon_0=<lon> +k_0=1 +x_0=0 +y_0=0 +units=m
```
where `<lat>` and `<lon>` are equal to the custom attributes _lat_ and _lon_ of the active Blender scene or to another center of the import

**Comment by vvoovv** [comment]
A custom map projection can be used with the _bpyproj_ addon as described [here](https://github.com/vvoovv/blender-osm/wiki/Documentation#custom-map-projections).

**Comment by ibaris** [comment]
Can you clearly provide a way, on how to export an OBJ file with actual *lat,  lon* or *ECEF* coordinates? Even with the PROJ4 string and the transformation with GDAL or PyProj, the coordinates get squashed and I am not able to use the converted OBJ file.

**Comment by vvoovv** [comment]
@ibaris 

I replied to you via email.

**Comment by ibaris** [comment]
Oh 😄 Thank you for your kind help and patience!

**Comment by rakeshshrestha31** [comment]
@vvoovv Great work with blosm! Is it possible to make the steps to export obj with WGS/ECEF coordinates public?

> @ibaris
> 
> I replied to you via email.

**Comment by vvoovv** [comment]
@rakeshshrestha31

Please provide more details about your task.

**Comment by rakeshshrestha31** [comment]
@vvoovv I want to overlay georeferenced 3D reconstructions from photogrammetry tools on top of the meshes from Google 3D tiles/OSM, for that I need the two meshes to be in same frame of reference (ideally WGS84). I’ll have to shift the two meshes closer to origin during visualization, but I need them to be in ECEF frame in the beginning

**Comment by vvoovv** [comment]
@rakeshshrestha31 

It's up to you to decide which way to take:
* transform OpenStreetMap or Google 3D Tiles to the projection of your data
* transform your data to the projection of OpenStreetMap or Google 3D Tiles

The default projection used by the addon to represent OSM data is describe [above](#issuecomment-918069289).

Google 3D Tiles are in the ECEF coordinate system. Their transformation by the addon is described [here](/vvoovv/blosm/issues/400#issuecomment-1753029980).

**Comment by rakeshshrestha31** [comment]
@vvoovv Thank you for the clarification. The raw glb files from Google 3D Tiles serves my purpose
