### ISSUE TITLE
Could not find assets building_materials.blend in Mac OS

### ISSUE THREAD

**Issue by artemiusgreat** [vvoovv/blender-geo#267]
Continuation of this [issue](https://github.com/vvoovv/blender-osm/issues/105) but for Mac OS. 
My blender version is 2.93, not sure I have 2.79 folder in Application Support directory. 
I can't import the map using `OpenStreetMap` option in the sidebar because it complains that I haven't specified the folder that contains all materials. 
I tried to search for all `blend` files in the OSM installation folder, but it shows that I have only 3 of them on the screenshot. 
Where can I get those materials or where were they saved in Mac OS?

![image](https://user-images.githubusercontent.com/5140879/135711477-45f1e600-a6ce-4352-adc4-26348dc43ea1.png)

**Comment by vvoovv** [comment]
Please download and unpack the other file (assets.zip) from Gumroad. Set the path in the field "Directory with assets" in the addon preferences to the directory that contain the unpacked files from _assets.zip_.

Please refer to the addon [documentation](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#video-tutorial) on how to install and use the addon.

**Comment by artemiusgreat** [comment]
Yes, my bad, forgot to download another archive. Thank you.
