### ISSUE TITLE
How to keep the water area flat? 

### ISSUE THREAD

**Issue by artemiusgreat** [vvoovv/blender-geo#268]
The water area has 2 hills in the place where the bridge connects to the surface. 
Any suggestion of how to separate the water from the actual surface and make it flat? 

![image](https://user-images.githubusercontent.com/5140879/135712241-3790192d-c2b8-42a4-a717-9eb64c45e4e3.png)

**Comment by vvoovv** [comment]
Unfortunately the terrain data aren't perfect.

* Select the terrain object and switch to the EDIT mode.

* Select the vertices of a problem hill. Press the keys `S` `Z` `0`. The selected area becomes flat.
