### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by taylorcody96** [vvoovv/blender-geo#27]
I have no experience coding but I want to download the OpenStreetMap add-on for Blender and I was directed here to Github. When I open the link it's just code, of which I have no idea to deal with.

**Comment by enzyme69** [comment]
Let me help a bit:

This is probably the only script you need to get start with importing OSM map into Blender:
https://github.com/vvoovv/blender-geo/wiki/Import-OpenStreetMap-(.osm)

If you are familiar with Blender Add-On installation, grab "io_import_scene_osm.py" above and install as normal Add-On.

Then you simply download the OSM map area, and then File-Import from Blender.

**Comment by vvoovv** [comment]
@enzyme69 thanks! I have nothing to add :)
