### ISSUE TITLE
Question: Setting the addon Preferences programatically

### ISSUE THREAD

**Issue by liorGameDev** [vvoovv/blender-geo#272]
I'm using the premium version, and installing it programmatically.
Is there a way to set the "Directory to store downloaded OpenStreetMap and terrain files" path programmatically?
It seems not to work without it

**Comment by vvoovv** [comment]
You can set like this:
```python
import bpy
bpy.context.preferences.addons["blender-osm"].preferences.dataDir = "/path/to/folder"
```
