### ISSUE TITLE
Error when loading image overlay

### ISSUE THREAD

**Issue by Tleviss19** [vvoovv/blender-geo#273]
Report: Error
Python: Traceback (most recent call last):
Fle init_.py", line 205, in execute
return self.importoverlay(context)
Fle init_.py", line 395, in importoverlay
a.overlay.prepareImport(minLon, minLat, maxLon, maxLat)
Fle init_.py", line 130, in preparelmport
0.5 * math.log2(
ValueError: math domain error
location: <unknown location>:-l

**Comment by vvoovv** [comment]
Hi @Tleviss19

Please post a screenshot of the addon panel (the addon panel is located in the tab _osm_ on the right side of Blender's 3D Viewport). That's needed to reproduce your problem.

**Comment by vvoovv** [comment]
no feedback
