### ISSUE TITLE
Image Ovelay won't load from linux server

### ISSUE THREAD

**Issue by liorGameDev** [vvoovv/blender-geo#276]
Mapbox's images just won't load from a Linux server.
When moving the request out of the `try`:
https://github.com/vvoovv/blender-osm/blob/6a66a1fc0569d7a17b3c85713822341d6b0a748b/overlay/__init__.py#L274

I got `CERTIFICATE_VERIFY_FAILED` Error.

A solution suggested here:
https://devtalk.blender.org/t/ssl-certificate-verify-failed/11921

And worked for me is adding:
```
ctx = ssl._create_unverified_context()
tileData = request.urlopen(tileUrl, context=ctx).read()
```

**Comment by vvoovv** [comment]
Please provide more details. Some screenshot would be helpful.

**Comment by liorGameDev** [comment]
Added some details with a solution @vvoovv

**Comment by vvoovv** [comment]
@liorGameDev 

Thank you you for your time to investigate the issue. I'll test it and integrate it into the next addon release.

**Comment by vvoovv** [comment]
Hi @liorGameDev 

I've added your solution to the addon code. Please update the addon.

Thank you for your assistance!
