### ISSUE TITLE
Does not work with blender 3.0

### ISSUE THREAD

**Issue by TheBest6337** [vvoovv/blender-geo#277]
I wanted to use Blender OSM in Version 3.0, but it doesn't work for me.

**Comment by vvoovv** [comment]
Hi @TheBest6337 

The addon works in Blender 3.0

Please provide more information. Some screenshots would be helpful.

**Comment by franMarz** [comment]
I'm trying to enable the add-on premium version 1.0.22 in Blender 3.0 and this error arises:

![osm_error_b3 0](https://user-images.githubusercontent.com/58062362/146695893-9d603b57-6e65-475d-bd38-5257e30bde0c.jpg)

**Comment by franMarz** [comment]
Other user is reporting this:

[https://blenderartists.org/t/blender-osm-openstreetmap-and-terrain-for-blender/608089/471?u=franmarz](https://blenderartists.org/t/blender-osm-openstreetmap-and-terrain-for-blender/608089/471?u=franmarz)

**Comment by vvoovv** [comment]
Hi @franMarz 

You addon is very old. The current addon version is 2.5.1

Please download the addon using the link in you purchase confirmation email. If you didn't preserve it, please send a message to prokitektura@gmail.com

**Comment by supercazzola75** [comment]
hi valdimir, i found a small bug in the latest version of the addon on blender 3.0.
The "bevel" panel is not by default on object, and you have to do it manually.
Greetings
![Screenshot_1](https://user-images.githubusercontent.com/38128070/148920000-bea03880-ada2-4bbc-afd3-c88db52ef3fb.jpg)

**Comment by vvoovv** [comment]
Hi @supercazzola75 

Thank you for reporting the issue!

I aware of that problem. It will be fixed in the next release.

**Comment by Moon-developer** [comment]
Hi, I got the premium version and tried installing it. Getting the following on blender 3.0 when I try to enable it:
![image](https://user-images.githubusercontent.com/28895292/149182426-1fe9e58d-474f-4082-8129-579a4bc5e0b5.png)

**Comment by vvoovv** [comment]
@Moon-developer 

Does it work after restarting Blender?

**Comment by Moon-developer** [comment]
The good ol "Turn it off and on again" did the trick 🤦‍♂️ why didn't I try this first.

**Comment by vvoovv** [comment]
> hi valdimir, i found a small bug in the latest version of the addon on blender 3.0. The "bevel" panel is not by default on object, and you have to do it manually. Greetings

Hi @supercazzola75

The problem has been fixed. Please update the addon.

**Comment by supercazzola75** [comment]
hi valdimir, i can't install version 2.5.4 on blender 3.1.
any idea?
txs
