### ISSUE TITLE
(Feature request) UDIM

### ISSUE THREAD

**Issue by lehuan5062** [vvoovv/blender-geo#278]
It would be great if the terrain can be mapped in UDIM and use the downloaded texture tiles instead of merging into one image.

**Comment by vvoovv** [comment]
Hi @lehuan5062,

Thank you for this feature request. I didn't know about the UDIM before.

Unfortunately the concept of UDIM has a significant limitation in Blender. The maxim number of tiles is 10 horizontally and 100 vertically.

**Comment by lehuan5062** [comment]
Thanks, will close this!
