### ISSUE TITLE
Georref. Blender Scene - help needed

### ISSUE THREAD

**Issue by CPRMgeo** [vvoovv/blender-geo#28]
Hello,

Congratulations for all efforts in comunicate Blender whith mercator rules!

All python modules worked fine, exception for one: Python module transverse_mercator 

I cant see this module working inside Blender, in the same way as indicated in preview (site page). 

What i am doing wrong?

regards

**Comment by vvoovv** [comment]
Please provide the details what is wrong with transverse_mercator

**Comment by CPRMgeo** [comment]
My mistake, after the last email i located my error.

Every thing it's right

many thanks

2016-09-26 23:11 GMT-03:00 Vladimir Elistratov <notifications@github.com>:
