### ISSUE TITLE
Only one building imports

### ISSUE THREAD

**Issue by fuctrevor** [vvoovv/blender-geo#281]
Every time I try to import the buildings from a section of my city only one building gets imported. . All the roads load fine and I can even import parts of New York and LA with 100s of buildings. For some reason though I still cant figure out my small section of city. The only thing I can think of is there is not enough data but I can load buildings from random towns in the middle of nowhere and Im fairly positive there is more data for my city. Any help is appreciated

-117.27427,33.21196,-117.26210,33.21681

![bruh](https://user-images.githubusercontent.com/98875222/152121169-3ef81fa0-4070-4324-95d7-f5805eea8d8a.png)

**Comment by vvoovv** [comment]
Hi @fuctrevor 

Yes, your area of interest contains only a single building at OpenStreetMap. Please see the map [here](https://www.openstreetmap.org/#map=17/33.21111/-117.27296).

Please note, that data in the OpenStreetMap are created by thousands of volunteers around the world. Some area may have less attention of the volunteer mappers. It's quite easy to start mapping at OpenStreetMap. Zoom to your area of interest at https://www.openstreetmap.org and press the "Edit" tab. An interactive tutorial will be offered. After completing the tutorial you can proceed to mapping.
