### ISSUE TITLE
MapBox Custom Style URLs are "too long" to save as a directory name in Windows

### ISSUE THREAD

**Issue by adachis** [vvoovv/blender-geo#286]
I made a custom style, copy/pasted the URL, and then got an error (see screenshot below) where the add on seems to be wanting to save a directory for it that's named as the entire URL.

<img width="1920" alt="Screenshot 2022-02-17 19 15 57" src="https://user-images.githubusercontent.com/327643/154610923-eaf8f7ad-69f0-4d90-ac88-cefddaa309d8.png">

I tested the streets-11 URL that you provided another user as an import solution for the standard street maps to see what would happen and that worked because the URL was shorter.  I also confirmed the directory was being named after that entire URL so it does seem to be an issue with how long the URL is due to the custom style ID.  I'm going to be looking for workarounds but I'm not confident I can find one.  If you have any suggestions please let me know.  Thanks!

**Comment by vvoovv** [comment]
Hi @adachis 

Thank you for reporting the problem. It will be fixed in one of the next releases.
The workaround for now is to use a shorter path. In your case it could be _C:\Users\micro\Dropbox\Blender OSM\data\_.
Sorry for the inconveniences.

**Comment by vvoovv** [comment]
We removed the Mapbox key from the path, so the path on the file system is significantly shorter now.

Please update the addon.
