### ISSUE TITLE
Cannot install blender-osm (premium) into ver 3.0.0 on Windows 10 (it appears)

### ISSUE THREAD

**Issue by kelleysislander** [vvoovv/blender-geo#289]
I purchased the blender-osm (premium) and does not install for me.  I was able to get what appears to be the basic osm addon as there is no "thank you" message for purchasing, and no field is presented to define my assets path.  I went to my Mac version Blender 3.0.0 and installed the addon there, and I do see the additional field for the vegetation assets so I did get the premium version on the Mac, from the same file I used on Windows.

As I read in the earlier, related trouble ticket, I was to expand the blender-osm_(premium).zip to get at the blosm.zip.  Mine is the file at 814.1 kb and it does not install the premium version.  Please see the accompanying screenshot.

![purchase_confirmation](https://user-images.githubusercontent.com/552098/156901838-0c5dbee4-6527-4c57-8b58-bce947c93a19.png)
![Screenshot_no_thankyou_or_assets_field_windows](https://user-images.githubusercontent.com/552098/156901865-57f8ca1f-e397-4991-9224-10d18b1a8730.png)

**Comment by vvoovv** [comment]
Hi @kelleysislander 

Thank you for purchasing the Blender-OSM addon!

Please double check the file blosm.zip you are trying to install. Is it really the file that you have successfully installed on Mac?

I'd also suggest to remove the base version and restart Blender before installing the premium version.

Looking forward to your feedback.

**Comment by kelleysislander** [comment]
Closing this. I deleted the base version as the docs say to do, then installed the premium version and it was fine.
