### ISSUE TITLE
Import 3D file (wrl) from solidwork - failed - IndexError: list index out of range

### ISSUE THREAD

**Issue by bay123ANDI** [vvoovv/blender-geo#290]
hello everybody
I'am a beginner in blender and python.  I have a question when I Import 3D file format (wrl) for solidwork to blender, i got this notification. i tired searching in internet how to fix its, and i got nothing to do. i hope someone can help me whit its problem.
hopefull.

![image](https://user-images.githubusercontent.com/83327997/157587220-b0a1a96f-1c16-4caf-8dbf-34b34f5c3801.png)

  This is the program in line 2013 or less, thank you
 
 colors = geom.getChildBySpec(['ColorRGBA', 'Color'])
    if colors:
        if colors.getSpec() == 'ColorRGBA':
            rgb = colors.getFieldAsArray('color', 4, ancestry)
        else:
            # Array of arrays; no need to flatten
            rgb = [c + [1.0] for c in colors.getFieldAsArray('color', 3, ancestry)]

        color_per_vertex = geom.getFieldAsBool('colorPerVertex', True, ancestry)
        color_index = geom.getFieldAsArray('colorIndex', 0, ancestry)

        d = bpymesh.vertex_colors.new().data
        if color_per_vertex:
            cco = [cco for f in processPerVertexIndex(color_index)
                       for v in f
                       for cco in rgb[v]]
        elif color_index:  # Color per face with index
            cco = [cco for (i, f) in enumerate(faces)
                       for j in f
                       for cco in rgb[color_index[i]]]
        else:  # Color per face without index
            cco = [cco for (i, f) in enumerate(faces)
                       for j in f
                       for cco in rgb[i]]
        d.foreach_set('color', cco)

**Comment by vvoovv** [comment]
Sorry,
your problem isn't related to our addon Blender-OSM.

Please submit an issue to the support of X3D plugin.
