### ISSUE TITLE
Need Buildings bottom faces (single mesh)

### ISSUE THREAD

**Issue by geobuilding** [vvoovv/blender-geo#292]
[blender-osm](https://github.com/vvoovv/blender-osm) is very power addon! Thanks fou you awesome work!

I'm using blender-som to create city model, and export as gltf, then render with Three.js
buildings bottom faces(single mesh) is useful with Threejs click event.

is there any quick methods to fix some code, or need more work？
Hope add this feture 

Thanks

**Comment by vvoovv** [comment]
Hi @hong4k

Do you need this for the textured output (3D realistic mode) or for solid output with no textures (3D simple mode)?

**Comment by geobuilding** [comment]
Thans for reply.

umm.. I mean import building,currently only the roof and wall. 

roof (✓)
wall(✓)
bottom 

we need bottom faces to do more.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/21072150/161944783-902727d1-69e8-44f2-9c70-9de7fddd6e38.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/21072150/161944834-b259a2fa-7066-4bd7-9097-8e4987ab9c6f.png">

**Comment by vvoovv** [comment]
Are using the base version or the premium one?

**Comment by geobuilding** [comment]
Base version

**Comment by vvoovv** [comment]
Did you edit the code of the addon to get the bottom faces?

I expected to provide you a solution this week.

**Comment by geobuilding** [comment]
No, I manually added the bottom faces of the building using blender:joy:, but this is only suitable for small buildings. I think this requirement may be rarely needed, so I closed the issue. I still look forward to the official automated solution.:smirk:

Thanks

**Comment by vvoovv** [comment]
Hi @hong4k 

Please download the file [base_3dprint.py](https://gist.githubusercontent.com/vvoovv/612c617c3a81027a4cfe97b8147dd599/raw/ecffe1cd463157c1afccc64c59855e9ab6c02a3c/base_3dprint.py). Save it with the extensions .py.

Set the option "Setup script" at the bottom of the addon panel to the path the file _base_3dprint.py_. You should get the bottom faces for buildings.

**Comment by geobuilding** [comment]
:clap::clap::clap: It works perfect.Thanks so much 

<img width="952" alt="image" src="https://user-images.githubusercontent.com/21072150/163671537-eb3b819f-8ed3-4954-8e1d-24f53df0f0a3.png">
