### ISSUE TITLE
ERROR – What is the fix? thank you!

### ISSUE THREAD

**Issue by fafberlin** [vvoovv/blender-geo#293]
<img width="904" alt="Screenshot 2022-04-07 at 11 14 17" src="https://user-images.githubusercontent.com/90459642/162165088-c3c59989-a6e4-49a7-9bce-637ab9e83810.png">

**Comment by fafberlin** [comment]
i seem to be finding no way to fix this issue – any ideas? i am on the premium version. thanks for your work

**Comment by vvoovv** [comment]
Hi @fafberlin 

Thank you for purchasing the premium version!

It seems that you enter the coordinates manually. I also noticed that minimum and maximum longitudes are equal. That can't be the case.

Please use press the button "select" to select the coordinates for your area of interest.

Looking forward to your feedback.

**Comment by fafberlin** [comment]
thanks for the reply – that however is not the case. i copied them from the web page...

**Comment by fafberlin** [comment]
<img width="1435" alt="Screenshot 2022-04-07 at 11 34 57" src="https://user-images.githubusercontent.com/90459642/162169289-0e8c4252-0dcc-48fc-9ecd-212028808ddc.png">

**Comment by vvoovv** [comment]
Please send a screenshot of the addon panel on the right side of the 3D View.

**Comment by fafberlin** [comment]
<img width="302" alt="Screenshot 2022-04-07 at 11 46 36" src="https://user-images.githubusercontent.com/90459642/162171576-66349f1e-329f-4a7a-839e-ef1a07935fce.png">

**Comment by vvoovv** [comment]
I was able to import the terrain for your area of interest:

![image](https://user-images.githubusercontent.com/613295/162174000-19ffde79-77fc-41df-b43d-954016d14185.png)

I think a problem with downloading a terrain part occurred.

Could you please show me the context of the folder _[the directory for the addon data]/terrain_?
I also need to the the size of the files in that folder.

**Comment by fafberlin** [comment]
<img width="820" alt="Screenshot 2022-04-07 at 12 06 37" src="https://user-images.githubusercontent.com/90459642/162175600-ab86b70f-84b4-46f3-a275-1dbeacb2996f.png">

**Comment by fafberlin** [comment]
like this? thank you!

**Comment by vvoovv** [comment]
This a folder with assets.

But I need the subfolder _terrain_ in the folder with addon data.

**Comment by fafberlin** [comment]
this folder is empty

**Comment by vvoovv** [comment]
Can you try to import the terrain for a small area, say 200 x 200 meter?

**Comment by fafberlin** [comment]
<img width="597" alt="Screenshot 2022-04-07 at 12 16 18" src="https://user-images.githubusercontent.com/90459642/162177246-f376c3b9-b740-41d0-91c4-ba3c602a118c.png">

**Comment by fafberlin** [comment]
same error....

**Comment by vvoovv** [comment]
You can manually copy the file [N46E007.hgt.gz](https://github.com/vvoovv/blender-osm/files/8441871/N46E007.hgt.gz) to the subfolder _terrain_. The addon will use it to build the terrain for your area of interest.

**Comment by fafberlin** [comment]
but i will need it in the future for different places. is there no way to fix this?

**Comment by vvoovv** [comment]
Can you show the output in the Blender's System Console when you try to import a terrain:
Window -> Toggle System Console

**Comment by fafberlin** [comment]
i dont have that option on mac

**Comment by vvoovv** [comment]
> i dont have that option on mac

Try to start Blender from the terminal and send me the output in the terminal.

**Comment by vvoovv** [comment]
Here is direct link to the terrain:
http://s3.amazonaws.com/elevation-tiles-prod/skadi/N46/N46E007.hgt.gz
The addon tries to download it.

Can you download it by click on it?

**Comment by fafberlin** [comment]
<img width="697" alt="Screenshot 2022-04-07 at 12 33 13" src="https://user-images.githubusercontent.com/90459642/162180122-054f2456-6ed0-49aa-b430-935cd2fa9526.png">

**Comment by fafberlin** [comment]
what do i do with the file? i am sorry i dont understand.

**Comment by vvoovv** [comment]
> what do i do with the file? i am sorry i dont understand.

Simply try to download the file from a web browser. The addon somehow can't download it. I want to check if you can download it from the web browser.

**Comment by fafberlin** [comment]
yes i can download it. its in my downloads now

**Comment by vvoovv** [comment]
Let's localize the problem.

Please open the Python Console in Blender and paste the following commands:
```
from urllib import request
request.urlretrieve("http://s3.amazonaws.com/elevation-tiles-prod/skadi/N46/N46E007.hgt.gz", "", None, None)
```
Press Enter after each command.

**Comment by vvoovv** [comment]
Here is the output for me on Windows:
```
>>> from urllib import request
>>> request.urlretrieve("http://s3.amazonaws.com/elevation-tiles-prod/skadi/N46/N46E007.hgt.gz", "", None, None)
('C:\\Users\\vvoovv\\AppData\\Local\\Temp\\tmphnbqty05', <http.client.HTTPMessage object at 0x000001FF7855A0E0>)
```

**Comment by fafberlin** [comment]
<img width="413" alt="Screenshot 2022-04-07 at 13 04 33" src="https://user-images.githubusercontent.com/90459642/162185235-4558aa2b-133b-4873-830c-c537505100d5.png">

**Comment by fafberlin** [comment]
<img width="411" alt="Screenshot 2022-04-07 at 13 04 42" src="https://user-images.githubusercontent.com/90459642/162185265-bcee7f78-9106-44bd-8196-e015b0a5c150.png">

**Comment by fafberlin** [comment]
this is mine

**Comment by vvoovv** [comment]
Will it cause the error we try to download something different, for example:

```
request.urlretrieve("http://blender.org", "", None, None)
```

**Comment by fafberlin** [comment]
yes

**Comment by vvoovv** [comment]
Can you try importing OpenStreetMap data for a small area, 200x200 meters?

Can you try importing a satellite imagery for a small area, 200x200 meters?

**Comment by fafberlin** [comment]
<img width="1552" alt="Screenshot 2022-04-07 at 15 04 34" src="https://user-images.githubusercontent.com/90459642/162205322-b7f5778b-9ea3-4705-a8f8-9d87645996c3.png">

**Comment by fafberlin** [comment]
open streetmap also wont work

**Comment by vvoovv** [comment]
Just want to be sure if the import of the satellite imagery was successful. Can you switch the _Viewport Shading_ from _Solid_ to _Material Preview_ and check if the satellite imagery is there?

**Comment by fafberlin** [comment]
unfortunately no...
<img width="1552" alt="Screenshot 2022-04-07 at 15 29 24" src="https://user-images.githubusercontent.com/90459642/162210216-d6683283-9459-4c21-8163-7d3f4b1259c9.png">
t

**Comment by vvoovv** [comment]
The addon relies on Python's core libraries to download different data. The libraries are supplied with Blender.

There is an strange problem that it isn't possible to download anything through the libraries on your computer.

A walkaround for the import of the terrain would be to start Blender from the Terminal, copy the URL from the Terminal output, download the file through the web browser and save it to the _terrain_ subfolder.

What else can be done?

Try the addon on another computer.

Try reinstalling Blender.

Try earlier versions of Blender

I can refund you the price you paid for the addon if nothing helps.

**Comment by fafberlin** [comment]
in this case it would be nice if you could refund the price. thank you! and thanks for your time trying to fix it. who knows what the problem is...

**Comment by vvoovv** [comment]
Sorry for the inconveniences!

Please send the email you used for the purchase to prokitektura+support@gmail.com

**Comment by fafberlin** [comment]
i fixed it! i feel so stupid, but it was actually little snitch that was blocking the network traffic

**Comment by vvoovv** [comment]
Great!

May I know what the exact problem was?

**Comment by fafberlin** [comment]
sure! it was just little snitch that blocked all network traffic from blender – so no wonder no downloads were possible.

**Comment by vvoovv** [comment]
Ok.

Thank your for your patience!

**Comment by vvoovv** [comment]
Since I am on Windows, I didn't know that Little Snitch is the name of a program for Mac. So I couldn't understand that term and tried to translate it literally :)
