### ISSUE TITLE
blender crashes

### ISSUE THREAD

**Issue by kqmeta** [vvoovv/blender-geo#294]
Im trying to import manhattan to create a map for my spider man game but as soon as I click Import, it crashes. I've waited 15+ min but its still not working.
![blender](https://user-images.githubusercontent.com/94103858/162611107-ad8285ce-301b-4676-88c4-fa0a7136f7ca.png)

**Comment by vvoovv** [comment]
Hi @dvds0009 

What is the output in Blender's System Console (Window -> Toggle System Console)?

**Comment by vvoovv** [comment]
no feedback
