### ISSUE TITLE
Blender 3.1 cannot be installed

### ISSUE THREAD

**Issue by luanluan-l** [vvoovv/blender-geo#295]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/43394507/165127033-38a5c57c-66d5-461b-bdc3-1124f1b7e317.png">

**Comment by vvoovv** [comment]
Hi @luanluan-l 

Please try restarting Blender.

**Comment by iancoetzer** [comment]
Good morning, same here, blender 3.1 and cannot enable the add-on

**Comment by iancoetzer** [comment]
<img width="722" alt="Screenshot 2022-05-07 at 10 26 34" src="https://user-images.githubusercontent.com/7976311/167246161-7c9289d1-7cdc-4fb8-9700-a5c26477027f.png">

<img width="343" alt="Screenshot 2022-05-07 at 10 30 26" src="https://user-images.githubusercontent.com/7976311/167246209-3d483cd3-24d5-4589-98fe-2ea0cb9f2e1d.png">

**Comment by vvoovv** [comment]
Hi @iancoetzer 

* Type _osm_ in the search box at the top of the list of addons. 
* Remove all versions of the addon
* Restart Blender
* Install the addon as usual

I hope this helps.

**Comment by iancoetzer** [comment]
I only have the one "osm" addon, tried restarting blender and same error.
<img width="620" alt="Screenshot 2022-05-07 at 14 01 56" src="https://user-images.githubusercontent.com/7976311/167253463-c28b2450-d16b-449f-986b-9ee5b3d622a7.png">

**Comment by vvoovv** [comment]
Did you try removing it and restarting Blender?

**Comment by iancoetzer** [comment]
Hi, yes I have just  tried this with no luck:
1. removed the add on
2. restarted blender
3. installed it again
4. same error message when i try and enable it with the checkbox

**Comment by iancoetzer** [comment]
Please see short video of the steps I took to remove the addon and reinstall.

https://user-images.githubusercontent.com/7976311/167261958-6bc5982f-da5b-44cb-abfe-85a4d5400ceb.mov

**Comment by vvoovv** [comment]
I'd recommend installing the latest version of the addon (2.5.4).
Remove the previous version and restart Blender before installing the latest one.

**Comment by iancoetzer** [comment]
I am using version (2.7.9) of the addon?

**Comment by vvoovv** [comment]
> I am using version (2.7.9) of the addon?

Yes :)
It won't work in Blender 3.1.

**Comment by jgwinner** [comment]
So only version 2.54 or 2.4.21 work with Blender 3.1?

**Comment by vvoovv** [comment]
@jgwinner 

2.4.21 is the last version that work in Blender 2.79. It won't work in Blender 3.1

Later version should work in Blender 3.1. However I'd recommend to always have the latest version (currently 2.5.5).

**Comment by elpaulli** [comment]
The Add-on installs but does not appear in the list of installed Add-ons - I am new to Blender and using the 3.2.1 version of blender, does the base version of the add-on work? And how can I tell what version of the plugin I am currently using? On a Mac

**Comment by vvoovv** [comment]
@elpaulli 

What is the size of the file you are trying to install?

**Comment by elpaulli** [comment]
494 KB - ZIP FILE and when I expand its the folder with blender-osm

**Comment by vvoovv** [comment]
> 494 KB - ZIP FILE and when I expand its the folder with blender-osm

The size seems to be ok. I need to see your actions to help. Please try to make a screencast of your actions and upload it here.

**Comment by elpaulli** [comment]
https://www.speak-easysports.com/fantasy/Screen%20Recording%202022-07-19%20at%2012.29.45%20PM.mov

Let me know if that works.. just threw it on a folder on an out of date site.

**Comment by vvoovv** [comment]
@elpaulli
The actual size of the file must be 483 Kb.

Please send the file for examination to the address prokitektura+support@gmail.com
