### ISSUE TITLE
"RuntimeError: Error: Registering panel class: 'PanelBlosmExtent' has category 'osm'" upon attemping to enable add-on.

### ISSUE THREAD

**Issue by beefjerkyzxz** [vvoovv/blender-geo#296]
![image](https://user-images.githubusercontent.com/10701540/165811391-cf5a97e8-e424-44ae-a0b8-8e11fe2cfb4f.png)

I get this error upon attempting to enable the add-on in blender 3.0.1, then installed the new version and got it on 3.1.2 as well.

Any help is appreciated, thanks in advance.

Full error reads as follows,

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\Jesse\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-osm\__init__.py", line 596, in register
    gui.register()
  File "C:\Users\Jesse\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender-osm\gui\__init__.py", line 924, in register
    bpy.utils.register_class(c)
RuntimeError: Error: Registering panel class: 'PanelBlosmExtent' has category 'osm'

**Comment by vvoovv** [comment]
Hi @beefjerkyzxz 

There maybe two versions of the addon at once.

Please check it out by typing _osm_ in the search field.
Delete all versions of the addon.
Restart Blender.
Install the addon as usual.

**Comment by beefjerkyzxz** [comment]
It was not the two versions, However I found by downloading the version from the gumroad link, uninstalling the plugin, restarting then installing the gumroad blosm version it was able to activate successfully. Thank you for your help.

**Comment by jianchenc** [comment]
> 

I have the same problem. Could you send me the download link of gumload? Thank you!

**Comment by vvoovv** [comment]
Hi @jianchenc 

You can get the addon at https://prochitecture.gumroad.com/l/blender-osm. Enter 0 (zero) in the price field.
