### ISSUE TITLE
Image overlay imports blank rectangle

### ISSUE THREAD

**Issue by seffylmz** [vvoovv/blender-geo#297]
I'm using blender-osm (premium) on blender version 3.1.2. Unfortunately, importing the image overlay for a city area in Germany does not work properly. I get a blank rectangle without the image for each overlay source. (I did add the mapbox token)
Any help for that?

**Comment by vvoovv** [comment]
Please check which image overlay type you are using.

_Mapbox Satellite_ should work.

I guess you are using _ArcGIS Satellite_.

I can confirm the issue for the _ArcGIS Satellite_.

I tried to load the imagery several times. Sometimes it worked for me. Often I get "Too many redirects" for some or all image tiles.

I'll monitor the situation for a few days and let you know. In the meantime you can use the Mapbox satellite imagery.

**Comment by seffylmz** [comment]
I tried all of them. Mapbox satellite does not work either.

Edit: When I check "Save overlay to file" the requested images are saved but not showing up on blender

**Comment by vvoovv** [comment]
Please send the coordinates of your area of interest.

**Comment by seffylmz** [comment]
Sure. 9.72693,52.38000,9.80229,52.41069

**Comment by vvoovv** [comment]
> Sure. 9.72693,52.38000,9.80229,52.41069

I worked for me:

![image](https://user-images.githubusercontent.com/613295/166241212-5b240e1d-b24b-4479-95f7-1975ae2b4938.png)

**Comment by vvoovv** [comment]
Please check your network settings.

**Comment by vvoovv** [comment]
The new version of the addon has a field in the preferences to enter an ArcGIS access token.
Here is a short description on how to get the token: https://github.com/vvoovv/blender-osm/wiki/Getting-ArcGIS-access-token
