### ISSUE TITLE
Error when importing buildings 

### ISSUE THREAD

**Issue by Darkmikas** [vvoovv/blender-geo#298]
Good afternoon, I bought the premium version, but when I try to download the buildings I get this error
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

**Comment by vvoovv** [comment]
Hi @Darkmikas,

Which version of the addon are you using?

**Comment by Darkmikas** [comment]
The newest 2021.05.07

**Comment by Darkmikas** [comment]
Just bought and installed it today

**Comment by vvoovv** [comment]
Can you import satellite imagery?

**Comment by Darkmikas** [comment]
Yes, the landscape and textures are loaded and imported

**Comment by vvoovv** [comment]
We are aware of this problem, but can't reproduce it. Can you contact us via e-mail prokitektura+support@gmail.com so we can send you a fix to test?

**Comment by Darkmikas** [comment]
Emailed

**Comment by vvoovv** [comment]
fixed
