### ISSUE TITLE
keyerror "602962656" can not load osm file

### ISSUE THREAD

**Issue by imcake** [vvoovv/blender-geo#30]
As the result in the pic below, blender can not load osm file, looking forword to a answer, big THX!

![error](https://cloud.githubusercontent.com/assets/3276093/19214783/834adb04-8dbe-11e6-90a8-115ba7af6775.png)

**Comment by vvoovv** [comment]
please attach your OSM file

**Comment by imcake** [comment]
@vvoovv thanks! see the file below.
[Berlin.zip](https://github.com/vvoovv/blender-geo/files/519051/Berlin.zip)

**Comment by vvoovv** [comment]
I fixed the problem. Please install the new version of the add-on and try it again
