### ISSUE TITLE
"The directory with assets ... doesn't contain the file building_materials.blend. Please set a directory..."

### ISSUE THREAD

**Issue by SusanaHewitt** [vvoovv/blender-geo#302]
I did exactly what the CG Geek did. I have a mapped terrain, and a saved texture. But when I click on import for OpenStreetMap, this is what I get. Both the terrain and the other directory (terrain is a subdirectory of the other one) are set. I'm trying to get a very large chunk of New York City (-74.08486,40.69975,-73.81714,40.87977). I am using the premium version.

**Comment by vvoovv** [comment]
Hi @SusanaHewitt 

Thank you for using our addon!

Please set an additional setting in the addon settings: Directory with settings. This setting is marked with the letter (g) on the image https://github.com/vvoovv/blender-osm/wiki/Premium-Version#installation.

The directory should point to the folder that is the result of unpacking the file _assets.zip_.
