### ISSUE TITLE
Is there a way to load custom arcgis overlays with a token?

### ISSUE THREAD

**Issue by liorGameDev** [vvoovv/blender-geo#303]

**Comment by vvoovv** [comment]
The URL template for standard ArcGIS layers has the form:
`https://ibasemaps-api.arcgis.com/arcgis/rest/services/{layer}/MapServer/tile/{z}/{y}/{x}?token={token}`

The addon substitutes `{layer}` for the layer name (for example, _World_Imagery_ for the satellite imagery). It also substitutes `{token}` for an ArcGIS token.

You can compose your URL template similarly and paste it after selecting the _custom_ overlay type.

**Comment by liorGameDev** [comment]
Thank you! @vvoovv 
I get `'The filename or extension is too long'`
When writing:
`bpy.context.scene.blosm.overlayUrl = "https://ibasemaps-api.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}?token=" + arcgistoken`

**Comment by vvoovv** [comment]
Please update the addon. This problem was fixed in the recent versions.

**Comment by liorGameDev** [comment]
I updated to current version and got:
`RuntimeError: Error: [WinError 206] The filename or extension is too long: 'C:\\Users\\LiorT\\Documents\\blender-osm_(premium)\\overlay\\ibasemaps-api.arcgis.com!arcgis!rest!services!World_Imagery!MapServer!tile!{z}!{y}!{x}!token=AAPKf6ba994a20a24c3eb98f0a3c50bfec659rmi46Wa7qTETg-ytBM4qGla1v_1IiHxOf9IEjy2ugPf6GanQ4IXgn0ALO22MvBZ'`

**Comment by vvoovv** [comment]
Is it for the _custom_ overlay type, right?

The addon doesn't remove the access token from the path to the cached imagery tiles. However it does remove the access token for the ArcGIS or Mapbox overlay types.

If you need it for the _custom_ overlay type, use a shorter path to the addon data, for example, `C:\blosm`.

**Comment by liorGameDev** [comment]
Thanks,
Do you know what can replace `World_Imagery` in this link? Do you know of a refference?
Thanks!

**Comment by vvoovv** [comment]
You can also try
Ocean/World_Ocean_Base
Elevation/World_Hillshade

See [here](https://www.esri.com/arcgis-blog/products/developers/developers/open-source-developers-time-to-upgrade-to-the-new-arcgis-basemap-layer-service/) for the details.

**Comment by liorGameDev** [comment]
Thanks!

**Comment by liorGameDev** [comment]
@vvoovv 
In Mapbox, a map i designed in their studio could be used as a custtom overlay in blosm.
I saw it is possible to design a custom map in arcgis. Is it possible to fetch tiles from it into blosm, as well?

**Comment by vvoovv** [comment]
A URL template will be required. We have a custom ArcGIS map, please give a URL, so I will be able to check if we can get the URL template for it.
