### ISSUE TITLE
geometry node

### ISSUE THREAD

**Issue by luanluan-l** [vvoovv/blender-geo#307]
Why is there no geometry node in my OSM

**Comment by vvoovv** [comment]
Hi @luanluan-l 

I need more details about your problem. Please attach some screenshots to illustrate your problem.

**Comment by luanluan-l** [comment]
Hi,@vvoovv
Please look at my screenshot. There is a lack of geometric nodes in blosm, which is different from that shown in your document.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/43394507/180114205-589adfd9-28ca-4963-a5ac-369fffc03d54.png">

**Comment by vvoovv** [comment]
Please update the addon. The current version of the addon is 2.6.3.

**Comment by luanluan-l** [comment]
Thank you!
