### ISSUE TITLE
Terrain import 

### ISSUE THREAD

**Issue by hbenzako** [vvoovv/blender-geo#308]
Hello 

I am testing the solution by following the steps exactly https://github.com/vvoovv/blender-osm/wiki/Documentation#terrain-import . Unfortunately 
I have an error message which is the following: 

bpy.context.scene.blosm.dataType = 'terrain'
bpy.context.scene.blosm.dataType = 'osm'
bpy.context.space_data.clip_end = 10000
<urlopen error [WinError 10061] No connection could be established because the target computer expressly refused it>

Thanks for your help

**Comment by vvoovv** [comment]
Hi @hbenzako,

Could you please send a screenshot with the messages in the Blender Console (Window -> Toggle System Console)?

**Comment by hbenzako** [comment]
![image](https://user-images.githubusercontent.com/105211402/180227097-b14531a3-a6b1-470b-9cc0-b8be039a99bb.png)

**Comment by hbenzako** [comment]
Thanks

**Comment by vvoovv** [comment]
Please check your network connections: firewalls, vpn, etc, The might block the network connection.

Other possible reason. There might be another addon for Blender that constantly using network connection (machine3) and prevents from downloading the terrain.
