### ISSUE TITLE
No more tree import option?

### ISSUE THREAD

**Issue by jcav258** [vvoovv/blender-geo#309]
Hi, is there still a way to import 3D trees/forests? I am only seeing forests as surfaces. Thanks

**Comment by vvoovv** [comment]
Hi @jcav258 

3D forests and trees can be imported in the premium version in the "3D realistic" mode.

**Comment by jcav258** [comment]
Hi,
I purchased and installed the premium version, but still I do not see the
"3D realistic" mode and those options.
[image: image.png]

Please help?

Thank you,
Jason

**Comment by vvoovv** [comment]
Let's do the following.

* Please delete all versions of the Blender-OSM.
* Restart Blender
* Install the file blosm.zip for the premium version. It must have the size 812 Kb, If it has the size 483 Kb, than it's the base version.

**Comment by jcav258** [comment]
That worked, thank you!
