### ISSUE TITLE
No menu for the plugin - no buildings when importing osm

### ISSUE THREAD

**Issue by gaetanquentin** [vvoovv/blender-geo#31]
I have downloaded the latest zip file and installed it.

When i use it the only choices in the plugin menus are : 
  - scale bar
  - in utm coordinates
  - retreive osm tags as vertex groups.

on youtube some made video where we can see other choices:
 - import buildings
 - import natural
 etc...

Is this ok? These choices has disappered?

And when importing an osm file, i see only wires , no buildings surfaces, as seen too on youtube demos.
Why?

Regards.

**Comment by vvoovv** [comment]
I looks like you downloaded a different add-on. Mine is [here](https://github.com/vvoovv/blender-geo/wiki/Import-OpenStreetMap-(.osm))
