### ISSUE TITLE
Blender crashes when zoom level is greater than 18

### ISSUE THREAD

**Issue by myrisee** [vvoovv/blender-geo#314]
Im trying to export landscape with high overlay resolution, 
I tried mapbox, arcgis and google (with custom url) but I failed with every option. Plugin downloads all tiles and im be able to see those tiles in the cache folder. But when download finishes it tries to sticth those tiles and my blender just crashes.

My Enviroment
blosm premium downloaded from gumroad
Blender 3.2.1
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
Installed RAM	16.0 GB (15.9 GB usable)

# Python backtrace
  File "C:\Users\myilm\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blosm\overlay\__init__.py", line 205 in finalizeImport
  File "C:\Users\myilm\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blosm\__init__.py", line 580 in modal

**Comment by myrisee** [comment]
Tried with 2.80 version result is same

**Comment by vvoovv** [comment]
Please send a screenshot of the import settings.

**Comment by myrisee** [comment]
![resim](https://user-images.githubusercontent.com/9747463/182038676-7e2674a8-94dd-4865-8e23-3b9df4d8c6aa.png)
![resim](https://user-images.githubusercontent.com/9747463/182038685-6c64fd98-aba8-49eb-ac9d-2a28e2dda50b.png)

**Comment by vvoovv** [comment]
Thank you for the feedback.

There size of the resulting texture is too big. Decrease the number of tiles or split your terrain into a number of parts and import the overlay separately for each part.
