### ISSUE TITLE
Not all buildsings importing

### ISSUE THREAD

**Issue by happyendingioan** [vvoovv/blender-geo#315]
I'm quite new to this plug-ing so excuse me if I'm doing something wrong. Not all buildings seem to be importing for me. I'm getting all large building and some large blocks of small residential buildings importing but others just dont import. All roads and eveything else import though. 

I'm importing a suburban area of Plymouth UK at the moment

**Comment by vvoovv** [comment]
Hi @happyendingioan 

Sorry for the delay with the reply. May I know the coordinates of your area of interest? If you prefer to keep them private, you can send them to prokitektura+support@gmail.com

**Comment by happyendingioan** [comment]
Hi there, 



Thanks for getting back to me. Is this helpful? 

https://osm.org/go/eun3AXP?layers=Y&way=401207894

**Comment by vvoovv** [comment]
I removed the private information (a signature, etc) from your reply. Please reply directly on Github to not expose your private information.

Is your area of interest marked with orange line on the screenshot below?

![image](https://user-images.githubusercontent.com/613295/182824293-d3ffefa8-b8d6-4c79-8b9a-33bc18a9f71e.png)

**Comment by happyendingioan** [comment]
No, but that is the centre focus. I need to create a 3D map of the surrounding 10K or so. 



All the large commercial buildings import and some of the residential buildings but most of the residential buildings don't import. Are there settings I can tweak to be able to bring them in, or is it just a limitation?

**Comment by vvoovv** [comment]
Those buildings aren't simply available in the OpenStreetMap database. The buildings available in the OpenStreetMap database can be seen at https://osm.org. Please note that OpenStreetMap is a wiki-alike projects with contributions from thousands of volunteers.

It's quite easy to start editing OpenStreetMap. Zoom to your area of interest at https://osm.org. Press the "Edit" tab. An interactive tutorial will be offered. After completing the tutorial, one can proceed to map editing.

**Comment by happyendingioan** [comment]
Ah, I see. So if I add the buildings to OSM using the edit tools, they will import for me any anyone else in future?

**Comment by vvoovv** [comment]
Yes, the buildings will be available for everyone.

I'd recommend to add the following tags for each building footprint:
* `building:levels` (for the maximum number of storeys)
* `roof:shape` with possible values `flat` (the default roof shape), `hipped`, `gabled`, `dome`, `pyramidal`
