### ISSUE TITLE
No OSM building textures (3D realistic premium)

### ISSUE THREAD

**Issue by morgankohler** [vvoovv/blender-geo#316]
Am I missing something? I have my import settings the same as in https://github.com/vvoovv/blender-osm/issues/310. 
![image](https://user-images.githubusercontent.com/53620460/186497109-d50a9058-d8f7-440b-83f9-31f533667bfc.png)

**Comment by vvoovv** [comment]
Hi @morgankohler 

Thank you for purchasing the Blender-OSM addon!

> Am I missing something?

Yes :) 

Set the option Viewport Shading to _Material Preview_ or _Rendered_ to see textured scene. The option is normally located at the top of the Blender 3D View as shown on the [screenshot](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/viewport_shading.png).

It was mentioned in the [documentation](https://github.com/vvoovv/blender-osm/wiki/Premium-Version#installation).

**Comment by morgankohler** [comment]
Thanks. Not too familiar with blender!
