### ISSUE TITLE
image overlay stops with error

### ISSUE THREAD

**Issue by SuperKLA** [vvoovv/blender-geo#319]
Hello everyone,
I am facing following issue.

![image](https://user-images.githubusercontent.com/17930543/190997601-e02dedc6-3da5-4e86-aa25-5c80e971d0ae.png)

I am trying to get a map overlay. Like this.
![image](https://user-images.githubusercontent.com/17930543/190997828-f8e814c6-00df-4044-a3bc-2ab2c21c2e38.png)

It downloads the images, but stop after the last one. What can I do?

I am using following Blender version
![image](https://user-images.githubusercontent.com/17930543/190997988-91966b20-0c3a-4dcd-ba8c-c1e7110ef863.png)

**Comment by vvoovv** [comment]
Hi @SuperKLA 

Blender 2.79 isn't supported anymore. Please install the latest stable version of Blender (currently 3.2).

**Comment by SuperKLA** [comment]
Thank you for you help, it solved my issue
