### ISSUE TITLE
Vertex spikes in terrain, road, footpath data

### ISSUE THREAD

**Issue by ei8htzer0** [vvoovv/blender-geo#320]
I'm unsure if this is a blender-osm issue or just an OSM issue, but the data I'm working with has vertices on the coastline and along some of the roads and footpaths rendered way high "up in the sky", making it impossible to zoom in. Has anyone else experienced this issue/know how to fix it?

![image](https://user-images.githubusercontent.com/5581676/193137623-3e479c2c-55e2-4118-b30c-3c1c0805f74f.png)

**Comment by vvoovv** [comment]
Hi @ei8htzer0 

This a known problem with the underlying terrain data. Please take look at #291 for the details.

**Comment by ei8htzer0** [comment]
Thanks, @vvoovv!
