### ISSUE TITLE
Close buildings (adding ground floors)

### ISSUE THREAD

**Issue by olivierpascal** [vvoovv/blender-geo#322]
Hello,

Is it possible to 'close' buildings by adding a ground floor?

Thanks!

**Comment by vvoovv** [comment]
Hi @olivierpascal 

Yes, that's possible.

Download the file [base_buildings_with_floor.py](https://github.com/vvoovv/blender-osm/blob/setup_scripts/base_buildings_with_floor.py) and set the path to it in the field "Setup script" at the bottom of the addon panel.

**Comment by olivierpascal** [comment]
Thank you @vvoovv. Now my buildings have floor but no more textures 😂😅 I would prefer to have both haha

**Comment by vvoovv** [comment]
Sorry, this setup script was designed for the 3D base mode.
