### ISSUE TITLE
My building vertices are dissolved

### ISSUE THREAD

**Issue by olivierpascal** [vvoovv/blender-geo#323]
Hello, how to prevent blosm to dissolve near-coplanar building vertices on rendering?

**Comment by vvoovv** [comment]
Hi @olivierpascal 

Please point to the problem building.

**Comment by vvoovv** [comment]
Please also provide more details about the problem.

**Comment by olivierpascal** [comment]
Sure, I'll try to illustrate it. Here is a building my OSM file:

![b_osm](https://user-images.githubusercontent.com/2182039/197256083-1c32fadf-b4a1-4a2b-bd71-df5a2669210d.jpg)

And here is the exported building via BLOSM:

![b_dae](https://user-images.githubusercontent.com/2182039/197256182-e4da3a3c-9cbf-4fb5-842f-e7e69165510e.jpg)

The issue is that one face is dissolved, and the central vertex has been removed. I have not been able to determinate if the dissolving is from the addon or from Blender.

**Comment by vvoovv** [comment]
Thank your for your feedback.

The addon does remove straight angles.

**Comment by olivierpascal** [comment]
Could you please point me toward the right file to patch? Thank you!

**Comment by vvoovv** [comment]
Why do you want to preserve this vertex?

**Comment by olivierpascal** [comment]
Found it, I added `Polygon.straightAngleTan = 0` in `__init__.py:baseInit()`.

**Comment by olivierpascal** [comment]
I want to preserve this vertex because my pipeline has to match the footprint of the exported building with an external file to reconstruct individual building entities and add metadata.
