### ISSUE TITLE
height mapping is dependent on chosen terrain area

### ISSUE THREAD

**Issue by momentmal** [vvoovv/blender-geo#324]
If i choose to subdivide a terrain area of interest into multiple tiles and import them seperately (to avoid huge textures and to distribute geometry details onto multiple objects) with identical georeferencing , i get mismatching height values at the borders of the imported tiles (tiles can't be put next to each other seamlessly). 
It would be great to have a checkbox to allow for "unscaled" import of the heightvalues of the SRTM data in order to get matching borders (if that is a feasable thing to do - or a a similar solution to avoid this issue) 

Example: Dividing area "8.5,48.4,10.0,49.2" into 4 tiles:
8.5,48.8,9.25,49.2
9.25,48.8,10.0,49.2
8.5,48.4,9.25,48.8
9.25,48.4,10.0,48.8

![blenderOSM_003_1tile_rendered](https://user-images.githubusercontent.com/9054832/198830420-281f86ef-c4c0-44b1-a963-b7970b26006f.jpg)
![blenderOSM_004_4tiles_rendered](https://user-images.githubusercontent.com/9054832/198830424-ecc25bf6-dfec-4129-b0e4-89ae0af2e89b.jpg)

**Comment by vvoovv** [comment]
Hi @momentmal,

We'd advise you to download the terrain for the whole area and subdivide it into a number of separate Blender objects. Then you can import the satellite imagery for each of those Blender objects as described [here](https://blenderartists.org/t/blender-osm-openstreetmap-and-terrain-for-blender/608089/505?u=vvoovv).
