### ISSUE TITLE
The directory for data in the addon preferences doesn't exist

### ISSUE THREAD

**Issue by gurwodla** [vvoovv/blender-geo#325]
Hello.
It's my first time to see Blender-osm, and I'd like to ask you a question because there was an error while performing the basic process

<img width="496" alt="화면 캡처 2022-11-08 163109" src="https://user-images.githubusercontent.com/117715112/200501578-bfcc43db-31c1-4400-b5f8-f032f6411bfd.png">

After setting it up like in the picture above, I connected to osm and set up a rectangular area and copied it.
After that, an error occurred in the process of trying to import terrian after returning to the blender and paste.

![image](https://user-images.githubusercontent.com/117715112/200502021-24800f18-4d77-4a30-9eef-ef47cd4a73c4.png)

What am I doing wrong? Please tell me the solution

**Comment by vvoovv** [comment]
Hi @gurwodla 

Thank you for using our addon!

There is something wrong with the folder you set for the downloaded OpenStreetMap and terrain data. Is it a network path?

**Comment by gurwodla** [comment]
Thank you for your answer.
As you advised, I modified the network path and proceeded again.
It's been resolved clearly !!

Thank you so much :)
