### ISSUE TITLE
Timed Out issue

### ISSUE THREAD

**Issue by hokutonanto** [vvoovv/blender-geo#327]
I installed OSM 2, 6, 4 from Gumroad, added the ArcGIS key, but when I try to import the map I get a `Timed Out` error

![image](https://user-images.githubusercontent.com/23059969/205170285-f7490ec0-38f1-48c0-9ba0-59e46249bad2.png)

I guess it's not compatible with Blender 3.3.1?

**Comment by vvoovv** [comment]
You can set another OSM server at the bottom of the addon preferences or try the import later.

**Comment by hokutonanto** [comment]
The other server, Mapbox, requires a credit card, even if the registration is free.
I tried with ArcGIS other times with no luck. 

I guess this issue may apply to the premium version as well?

**Comment by vvoovv** [comment]
I meant this setting in the addon preferences:

![image](https://user-images.githubusercontent.com/613295/205352466-ac24276b-6b58-449b-99c6-02bfefc5aaa3.png)

**Comment by hokutonanto** [comment]
Got it.
So, the 8 cores gives the Timed Out warning I posted above.
The other two, give this other time out:
![image](https://user-images.githubusercontent.com/23059969/205360715-00f2bcfc-1db2-4c24-9657-ca16d40275a8.png)

**Comment by vvoovv** [comment]
Please check your network settings (VPN. firewall etc). Also other addons for Blender (e.g. BlenderKit) may block the network connection.
