### ISSUE TITLE
Red roofs from asset package

### ISSUE THREAD

**Issue by Cynosurae** [vvoovv/blender-geo#328]
The default blender-osm premium asset package has a lot of red roof coloration, which looks out of place when applied to temperate North American cities that typically have neutral/gray-colored roofs. I followed the instructions in the video tutorial for creating a new asset pack, removed the obviously red roof tile texture, and added several gray-ish roof tile textures instead, marked as "cladding/roof tiles".

However, when I attempted to import buildings using this new asset pack, the red roofs actually got **more** frequent. Additionally, the blender console complains a lot about being "unable to delete files", which does not happen when using the default asset pack.
![vanredroofs_noterr](https://user-images.githubusercontent.com/78236932/205514415-8078aef3-ad8c-4eb0-98d6-09f7a455e705.PNG)
![vanredroofsworse_noterr](https://user-images.githubusercontent.com/78236932/205514419-348ae7d5-64bd-4c55-90e4-3d62bd3e2bdf.PNG)
![unableconsole](https://user-images.githubusercontent.com/78236932/205514431-620862ec-6269-469b-86eb-870aa85be2e8.PNG)

Am I missing some step in the process here?

**Comment by vvoovv** [comment]
Hi @Cynosurae 

Roof colors should be also changed in the style definitions.

Open the folder you set for the addon assets. The proceed to the folder with name of your custom asset package. Then proceed to the folder _style/building_. Open all files there except _main.pml_ and check if they have a entry like the one below:

```css
roof {
	roofCladdingColor:
            ...
            if (item["roofCladdingMaterial"] == "roof_tiles") per_building(random_weighted(
                (#8a5c4d, 1),
                (#c57a63, 1),
                (#a6653f, 1)
            ))
            ...
}
```

You might want to changed the colors there and save the resulting file.

**Comment by Cynosurae** [comment]
Thank you! I didn't realize there was more to the roof coloration- I have much more realistic-looking building colors now. Thank you for the quick response!
