### ISSUE TITLE
Various options missing in 3D Realistic panel

### ISSUE THREAD

**Issue by ThomasW776** [vvoovv/blender-geo#329]
Various options appear to be missing in the premium version under 3D Realistic such as the "Percentage of lit windows", "level height" and the various roof options.

Attached is an example of what I can view. 
![image](https://user-images.githubusercontent.com/20466336/205761939-3ba7b95b-9372-4cb2-af79-2b02190f1c57.png)

And here is an image from the docs displaying what I'd expect to see.

![image](https://user-images.githubusercontent.com/20466336/205761804-282dbd32-7838-4a9a-aed4-a849632b3257.png)

Blender versions tested: 3.2, and 3.3.1, both prompt similar lack of options.

Is it possible that this error is caused by the lack of a mapbox API key or is this a separate issue?

Thank you for your time.

**Comment by vvoovv** [comment]
Hi @ThomasWarnasch

To get those option please uncheck the option _Enable experimental features_ at the bottom of the addon preferences.
