### ISSUE TITLE
blender-osm (premium)

### ISSUE THREAD

**Issue by Digger6059** [vvoovv/blender-geo#331]
just loaded some of the building textures from textures.com the ones you show in your video but they won't load into the assets file when I try to set the path. this is as far as I can make it on your video.

Thanks 
            Kenny

**Comment by vvoovv** [comment]
Hi @Digger6059 

Please make a screencast or screenshots of your action. It's difficult to give recommendation without detailed information.

**Comment by Digger6059** [comment]
I tried to send pics in github but that wasn't working eather LOL.

**Comment by vvoovv** [comment]
Just copy and past the screenshots.

**Comment by Digger6059** [comment]
Is there a size limit or file type I need to have for the pics? I keep getting an error message. ( Something went wrong, and we can't process that file)

**Comment by Digger6059** [comment]
I tried copy past.  I have also tried to use jpeg files as well to no avail.

**Comment by Digger6059** [comment]
Will do, thanks!

**Comment by Digger6059** [comment]
I am just going to send these to you here because it won't load these at
Github if you look at them I have added comments.

**Comment by vvoovv** [comment]
I didn't receive the screenshots from you.

**Comment by Digger6059** [comment]
That's odd, my email said it was sent. all try again.

**Comment by Digger6059** [comment]
do you have a home email you can send to me?

**Comment by Digger6059** [comment]
OK I figured it out I wasn't seeing the warning at the bottom of the blender screen about only having 27 characters so I had o rename all the textures that I downloaded sorry for any inconvenience. 
Thanks a bunch
