### ISSUE TITLE
Terrain import error

### ISSUE THREAD

**Issue by mikej2020** [vvoovv/blender-geo#332]
Hi all,
I am keep getting following error for a specific area in USA, 

I'm receiving this:
![Screenshot 2022-12-22 at 8 38 59 AM](https://user-images.githubusercontent.com/62732711/209168132-27a610be-c03d-4f01-b3fe-1143ed599b0a.png)

Any feedback would be much appreciated.
Thanks

**Comment by vvoovv** [comment]
Hi @mikej2020 

You set a folder for the addon data in the addon preference. Please show the content of its subfolder _terrain_.

**Comment by mikej2020** [comment]
![Screenshot 2022-12-22 at 8 38 59 AM](https://user-images.githubusercontent.com/62732711/209180955-3d36ca84-0d23-4b84-9ecc-f9c17c329250.png)

The above is the content of its subfolder of terrain. It works for other terrain

**Comment by mikej2020** [comment]
![Screenshot 2022-12-22 at 10 38 35 AM](https://user-images.githubusercontent.com/62732711/209181292-76f33c0f-09c5-472b-91ba-a498a73f0952.png)

The above is the content of its subfolder terrain. It works for other terrain.

**Comment by vvoovv** [comment]
Please delete the file with the zero size and try the import again. There was probably a download error.

**Comment by mikej2020** [comment]
It is working, thanks!
