### ISSUE TITLE
Blender 2.79 import / export issue

### ISSUE THREAD

**Issue by MisamotoGames** [vvoovv/blender-geo#333]
i dont see both of them help me

i just installed it idk how to use it

**Comment by vvoovv** [comment]
Please use the latest version of Blender (currently 3.4)

**Comment by MisamotoGames** [comment]
but i cant update upper 2.79 because of my gpu

**Comment by MisamotoGames** [comment]
i tried to update but blender just gave me gray screen and crashed i use intel hd and i think uhmm this plugins is from 7 years ago? idk i saw some forks that edited 5 even 8 years ago but there must be a older version that supports because i need to make better city with LOD for my game

**Comment by MisamotoGames** [comment]
i can enable the lastest version of blender osm but i cant see import and export

**Comment by MisamotoGames** [comment]
is that normal?

**Comment by MisamotoGames** [comment]
oh wait... i think i find it leme see
