### ISSUE TITLE
GPU not utilized?

### ISSUE THREAD

**Issue by Natotela** [vvoovv/blender-geo#335]
G'd evening! 
First I'd like to thank for this add-on.
Second - I noticed Blender gets stuck, CPU utilization rockets while GPU is not used (RTC 3070, 8gb VRAM out of which 1gb was used, and not more than 3% proc' util). Then it crashed without even saving the mapbox token.
Any recommendations?

**Comment by vvoovv** [comment]
Hi @Natotela 

More details area needed. Were you importing the satellite imagery?

**Comment by Natotela** [comment]
Forgive my total noobness, I cannot recall entirely step by step but I had downloaded the imagery even before it crashed. I think I tried to undo and redo the whole thing and then blender crashed - although it happened to me earlier, before I played with osm.

Doing it again: Tiles set to 256; for now it seems fine.

btw, under Terrain Overlay in the documentation there's a broken link 
"You may want to edit the mesh of the imported terrain in the Blender EDIT or SCULPT modes. In the EDIT mode you may find useful [proportional editing](https://docs.blender.org/manual/en/dev/scene_layout/object/editing/transform/control/proportional_edit.html#edit-mode)."

**Comment by vvoovv** [comment]
> btw, under Terrain Overlay in the documentation there's a broken link

Thanks for reporting! I've just fixed it.
