### ISSUE TITLE
importing says timed out 

### ISSUE THREAD

**Issue by caputoons** [vvoovv/blender-geo#338]
i have been trying to import a location from google map but it keeps showing timed out i dont know what could be the problem.

**Comment by vvoovv** [comment]
What exactly were you trying to import?

The Blender-OSM doesn't provide import from Google Maps.

**Comment by caputoons** [comment]
I followed the instructions as stated,I selected a location from the and
copy pasted it but it was bringing timed out so if Its not importing
location from Google maps how can I creative a city via it??

**Comment by vvoovv** [comment]
The addon can import data from OpenStreetMap (OSM) database.

If there is a time out error, try again later or set another OpenStreetMap server at the bottom of the addon preferences.
