### ISSUE TITLE
The height of some buildings does not correspond to the one indicated in the OSM tag

### ISSUE THREAD

**Issue by dgtfer** [vvoovv/blender-geo#339]
the height of some buildings does not correspond to the one indicated in the OSM tag
In this example the industrial building should be 22m high, and it is actualy 13.5m
![image](https://user-images.githubusercontent.com/126405430/221420469-abb7862a-f16b-4040-8f83-4869b9b95ea7.png)

**Comment by vvoovv** [comment]
Hi @dgtfer 

Currently height with units are ignored. I am going to fix it this week.

**Comment by vvoovv** [comment]
The problem has been fixed. Please download and install the latest version of the addon as described in the [documentation](https://github.com/vvoovv/blender-osm/wiki/Documentation#installation).
