### ISSUE TITLE
Ubuntu Install Addon Problem

### ISSUE THREAD

**Issue by alperokur** [vvoovv/blender-geo#343]
Hi I am trying to install the addon on Ubuntu. I'm getting an error like in the photo, how do I fix the problem? Thank you in advance for your help and interest

![Ekran Görüntüsü - 2023-03-22 11-24-21](https://user-images.githubusercontent.com/36308747/226842551-66dd0d08-7d32-4344-8e9d-f58c6a3d89ee.png)
![Ekran Görüntüsü - 2023-03-22 11-24-28](https://user-images.githubusercontent.com/36308747/226842562-71dab9d2-37d5-4ee3-aab2-ae3d0d22bd4a.png)

**Comment by vvoovv** [comment]
Hi @alperokur 

You were trying to install a very old version of the addon. Please get the latest version at https://prochitecture.gumroad.com/l/blender-osm
