### ISSUE TITLE
Problems installing blender-osm plugin in Blender version 3.4

### ISSUE THREAD

**Issue by Amos-research9725** [vvoovv/blender-geo#344]
![image](https://user-images.githubusercontent.com/56807418/228135359-1b435e5a-8566-4fcd-8405-fa394a34231f.png)
When I install this plugin, an error is reported when I do the checkbox, the log content is inside the screenshot, I don't know what happened

**Comment by vvoovv** [comment]
Hi @Amos-research9725 

Please restart Blender and try installing the addon again.

**Comment by Mysakshi2104** [comment]
Hi,

I am also facing the same issue, I have restarted the Blender but it did not work.

![Blender Error](https://user-images.githubusercontent.com/131029947/232575105-1042e5d9-a6fc-4d4d-aaed-543d4c8f6432.jpg)

**Comment by vvoovv** [comment]
@Mysakshi2104 

The version you downloaded is for Blender 2.79.
Please get the addon at https://prochitecture.gumroad.com/l/blender-osm
