### ISSUE TITLE
geoJson import : "name 'Polygon' is not defined" error

### ISSUE THREAD

**Issue by Minigoer** [vvoovv/blender-geo#345]
Hello,
Thanks a lot for your add-on.
I'm trying out your new feature for importing GeoJson files on Blender-OSM 2.6.5 (using Blender version 3.2.2).
I would like to import an additional data layer in GeoJson format.
However, I am not sure how the import process works.

Does the import only cover the features already provided by Blender-OSM (osm tags as "building", "highway", "railway", "meadow", "grassland" ...)?
My goal is simply to import much more complete data that is not available from OSM, such as custom shapefiles converted as geoJson.

Currently, when I try to import the GeoJson file, Blender-OSM returns an error message "name 'Polygon' is not defined" on a red box. There is no additional information in the Python console or terminal.
The GeoJson file is valid in QGIS.

Do you have any idea where the problem might be coming from?
Thank you in advance for your help!
Fred

![image](https://user-images.githubusercontent.com/6884024/229560278-56a1ae0a-0213-41c7-909b-e729ae5036e1.png)

![image](https://user-images.githubusercontent.com/6884024/229560518-74f4f92e-1db5-40b1-a3a3-d6089ea2486c.png)

**Comment by vvoovv** [comment]
Sorry, support of GeoJson was not finished. It came to the release version by mistake.

**Comment by Minigoer** [comment]
Ok, no problem. Thanks for your quick reply !
Does this feature intend to import custom data?

**Comment by vvoovv** [comment]
Yes, the idea was to import custom data not related to OpenStreetMap.
