### ISSUE TITLE
OSM Tab not showing in Blender

### ISSUE THREAD

**Issue by foxyskippy** [vvoovv/blender-geo#350]
Hi all,

after installing the add-on I'm not seeing the OSM tab when toggling the panel. I only see Item, Tool and View.

I got the 2.6.5. version.

**Comment by vvoovv** [comment]
Hi @foxyskippy 

Was the addon sucessfully intalled. Can you find the addon in the list of addon?

**Comment by foxyskippy** [comment]
Hi @vvoovv 

It looks properly installed.

![image](https://user-images.githubusercontent.com/20426173/236919439-89dd5aa5-636c-439b-8d37-0789ed368652.png)

**Comment by mkolcun** [comment]
Same here, no osm tab anywhere in the viewport.
Blender 3.5.0

Works with 3.4.1

**Comment by vvoovv** [comment]
It works as usual on Blender 3.5.1.

We would recommend:
* Delete all previous versions of the Blender-OSM addon. Type _osm_ is the search box above the list of addons to find them.
* Restart Blender
* Install Blender-OSM addonn

If that doesn't help, check if there are errors in the Blender console and send them back to us.
