### ISSUE TITLE
Way to check if overlay import is finished in Python

### ISSUE THREAD

**Issue by BastelBaus** [vvoovv/blender-geo#352]
Some help ´needed;

```
bpy.data.scenes["Scene"].blosm.dataType = 'overlay'
bpy.ops.blosm.import_data()

```
returns directly "{'FINISHED'}" although it is still processing the downloads in the background. IS there any way to check when the background tasks are finished programmatically. 

BR,
BastelBaus

**Comment by vvoovv** [comment]
Hi @BastelBaus 

Please add the line
```python
bpy.context.scene.blosm.commandLineMode = True
```
at the beginning of your script. Then it will work in the synchronous mode.

**Comment by BastelBaus** [comment]
thanks, works beautifull!
