### ISSUE TITLE
Are the premium purchase tiers in any way different?

### ISSUE THREAD

**Issue by Architector4** [vvoovv/blender-geo#354]
As [Blender is licensed under GNU GPL v2 or later](https://www.blender.org/about/license/), addons written for it, if distributed, [must be licensed under the same license.](https://www.blender.org/support/faq/#using-blender-9) The same license enforces that software under it can always be freely used or distributed to others however the person who has a copy of it sees fit, as long as they also distribute its source together.

I assume the addon is written in Python, so the caveat about distributing the source with the software doesn't matter (as Python source *is* the software), but the rest of that fact does seem to be in conflict of what the premium pricing tiers suggest.

That is all to say, any premium version purchase tier would also be licensed under GPL, meaning the purchaser has full legal right to modify and distribute it to 100 more users around their studio or any friends and foes they see fit.

From there, I'm asking: is the thing the purchaser gets from different products any different depending on the tier, or do they all give the exact same addon, where the user is free to choose how much they want to support the project?

The description doesn't seem to mention any difference between the tiers either. I assume the "1-2 users" and such on the different tiers are a suggestion in relation to how much it would be nice for the user to pay?

**Comment by vvoovv** [comment]
Hi @Architector4 

The addon's source code is distributed under the GPL license. Moreover, the addon's source code is hosted on Github:
* https://github.com/vvoovv/blender-osm/tree/release (the release version)
* https://github.com/vvoovv/blender-osm/tree/dev (the development version)

The development version contains some assets (textures, materials, definitions of building styles, etc) along with the addon code. The assets are NOT provided under the GPL license. They can't be distributed by the user and must be used in accordance with the purchased tier.

I hope that helps.

**Comment by Architector4** [comment]
Thank you for the information.
