### ISSUE TITLE
Why limit size, technically?

### ISSUE THREAD

**Issue by Preplan9464** [vvoovv/blender-geo#355]
Just curious!

**Comment by vvoovv** [comment]
Hi @Preplan9464 

Did you mean the size of the area of interest? Blender may crash and become non-responsive with large scenes.

Also, you can enter the coordinates manually in the addon panel.

**Comment by ewebgh33** [comment]
Hi @vvoovv 
Came here looking for documentation on import size limits, if any.

What is the recommended largest size import please? Here I seem to be able to bring in large sizes if ONLY terrain, but OSM hangs.

I am trying to assemble a US city and so far areas of 50km x 50km and 25km x 25km have failed. Smaller is going to be a heck of a job piecing back together. What size should I be aiming to get buildings and streets? 

15x15km? 10x10? 5x5?

Once I know, I can probably set up a spreadsheet to calculate the offsets, save each import as it's own blend file, and go from there.

**Comment by vvoovv** [comment]
Hi @ewebgh33 

> I am trying to assemble a US city and so far areas of 50km x 50km and 25km x 25km have failed.

How did they fail? What was the error message?

**Comment by ewebgh33** [comment]
@vvoovv Well when I say fail, Blender hung, I left it for over an hour but nothing happened. 
I'm slowly working my way down in size,
20km x 20km roughly, just worked. So maybe that is what I should aim for?

I have 64gb RAM and the machine should be powerful enough but I suppose a dense city area has a lot of geo.
Do you have a recommendation for size import that I should aim at for tiles, to avoid errors?

**Comment by vvoovv** [comment]
@ewebgh33 

A larger area means a longer processing time. So you've just found the right size for you experimentally.
