### ISSUE TITLE
Extrude Base Artifacts Issue 

### ISSUE THREAD

**Issue by ClickClocks** [vvoovv/blender-geo#357]
Hi, I'm trying to apply a Extrude Base to the Terrain but for some reason some extrange artifacts apears. It seem the edges are not paralle. Any solution to this? 

Please see the following  image to understand:
https://ibb.co/g6xdh57

https://ibb.co/D9MXrxC

What would be the best way to extrude it and create a base and avoid these artifacts? Cheers

**Comment by vvoovv** [comment]
Sorry, I can't understand what's wrong from your descriptions. More details would be desirable.

**Comment by ClickClocks** [comment]
HI, Thanks for you reply, Did you check the Pictures? 

Have you ever try to created a base for the Terrain? otherwise would be lool like is flying? 

Terrain Render Without Base:
https://ibb.co/N2YZKVb

Terrain Render With Base:
https://ibb.co/D9MXrxC

As you can see when I create the Base this generate some weird texture artifacts instead of been a flat color. I think this is caused because the edges (or points) are not paralel (maybe there is another reason)

https://ibb.co/C2wBf8k

Maybe if you try what I did you may understand. let me know if you. need more explanation. Cheers

BTW: Other Similar Plugings offer the option to Created a 3D Base for the Terrain, would be amazin to have this functionality in further version.

**Comment by vvoovv** [comment]
By the way, you can simply paste you images here (Ctrl + V).

**Comment by vvoovv** [comment]
Did you mean the artifacts shown on the image below?

![image](https://github.com/vvoovv/blosm/assets/613295/7b45ae82-14b3-4d75-ab4e-376e67ffb9f5)

**Comment by ClickClocks** [comment]
yes those artifacts

**Comment by vvoovv** [comment]
For now you can apply a material with the flat color to the faces that form the terrain basement.
