### ISSUE TITLE
Website not working?

### ISSUE THREAD

**Issue by Sh1nk1r0** [vvoovv/blender-geo#361]
http://prochitecture.com/blender-osm/extent/?blender_version=3.0&addon=blosm&addon_version=2.7.1 just a  white screen please help

**Comment by vvoovv** [comment]
Seemingly one of the Javascript libraries used by the webpage is somehow blocked for you.

Please press Ctrl + Shift + I, find the errors in the Developers Tools and send us a screenshot.

**Comment by vvoovv** [comment]
You can also enter the coordinates manually in the addon panel.
