### ISSUE TITLE
Google 3D Tile: Settings

### ISSUE THREAD

**Issue by victorluv** [vvoovv/blender-geo#362]
Hi I would like to check if there is any possibility for adding more setting to the Google 3D Tiles: Combine textures or material in blender, or change material assignment on import, textures size or create atlas etc.

I'm trying to pull the highest data quality from their source while the data is fine, it would generate crazy amount of material and textures, I'm looking for the way to manage that
Could this be a feature request for the premium version?

**Comment by vvoovv** [comment]
Hi @victorluv

The first feature will be a button to replace the materials in the selected object with export-ready material or custom materials.

The other features will require more time to consider and implement.

**Comment by victorluv** [comment]
that sounds wonderful thank you very much :) @vvoovv looking forward to it, not try to rush but when you do you think you will put the replace the materials in the selected object with export-ready material or custom materials button?

**Comment by vvoovv** [comment]
I hope that feature should be ready the next week.

**Comment by vvoovv** [comment]
Materials of Google 3D Tiles can now be automatically replaced with export-ready or custom ones. Details are in the [documentation](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials).

Please install the latest version of the addon (currently 2.7.2).

**Comment by victorluv** [comment]
Mate Thank you so much, that's awesome I got a few more questions about the tool I'll shoot you an email :) 
![image](https://github.com/vvoovv/blosm/assets/139854338/77643976-dc64-43d8-bf49-1b3a2959f9bd)

**Comment by Klammetostie** [comment]
Hi Vvoovv, thank you very much for your recent updates!. I had some great results already this week trying various areas. Exporting the imported Google 3d tiles to fbx format works, however when I press "replace materials"  in the menu, the tile grid becomes visible (with the join 3d tiles enabled), also in the rendering showing clearly black stripes where the tiles are not seamlessly merged. 
Google 3d tiles imported:
![G3D_mountains_lv districs_normal](https://github.com/vvoovv/blosm/assets/139920638/2271ed0d-4ca1-4f11-91f7-7b0c18434c06)
After 'replacing materials':
![G3D_mountains_lv districs_replaced mat](https://github.com/vvoovv/blosm/assets/139920638/2a1690f1-7ce3-4586-ac46-f13da2b9663e)
Wireframe:
![G3D_mountains_lv districs_replaced wireframe](https://github.com/vvoovv/blosm/assets/139920638/139bdaa8-a9c5-4d11-b625-369e4b271d86)

Any idea what can cause this and how to fix it? I've used the Google Model Importer plugin with the LilyTexturePacker plugin before, to merge the imported tiles into one mesh and then merge all seperate materials/textures into one .jpeg, and it worked flawlessly somehow, not showing any seam between the tiles. Any suggestions would be welcome.

**Comment by vvoovv** [comment]
Hi @Klammetostie 

The addon relies on the built-in glTF importer to import 3D Tiles. The coordinates in a 3D Tile  are in meters relative to the center of the Earth. That means millions of meters on each axis. The glTF addon imports them as-is. The Blosm addon applies geometrical transformations to bring the 3D Tiles to the center of Blender's system of reference.

I think those huge original coordinates is the reason for the gaps. They can't be fixed without changing the code of the glTF addon.

**Comment by garylzimmer** [comment]
> Hi @Klammetostie 
> 
> 
> 
> The addon relies on the built-in glTF importer to import 3D Tiles. The coordinates in a 3D Tile  are in meters relative to the center of the Earth. That means millions of meters on each axis. The glTF addon imports them as-is. The Blosm addon applies geometrical transformations to bring the 3D Tiles to the center of Blender's system of reference.
> 
> 
> 
> I think those huge original coordinates is the reason for the gaps. They can't be fixed without changing the code of the glTF addon.

Would it help anything if you "stitched" the tiles together prior to the transformation process?

**Comment by vvoovv** [comment]
@garylzimmer 

Stitching is performed before applying the geometrical transformations.

**Comment by HIBOULEDUC** [comment]
cette application est géniale, mais en effet la liaison entre les dalles serait un plus, je n'ai pour ma part pas réussi à lancer LilyTexturePacker, que j'utilise depuis un peu plus de deux ans.
le seul problème avec LilyTexturePacker est qu il est impossible d'importer dans sketchup une seule texture.

**Comment by vvoovv** [comment]
@Klammetostie 

> The tile grid becomes visible (with the join 3d tiles enabled), also in the rendering showing clearly black stripes where the tiles are not seamlessly merged.

See also #430.

**Comment by DiBop** [comment]
Is there any way to make the meshes and UVs not so crazy? I am trying to replace a couple of things and trying to work with the UVs are driving me bananas!


Here is my issue:
![2024-04-12_14-53-01](https://github.com/vvoovv/blosm/assets/479367/458ac98a-bd17-444d-8953-80d7d848db3b)


IT's crazy looking! 

Any help is appreciated!

**Comment by vvoovv** [comment]
Hi @DiBop 

I can't see from your screenshot how it's related to the Blosm addon.
