### ISSUE TITLE
Failed attempt to import Google 3D Tiles (Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found)

### ISSUE THREAD

**Issue by StarsiderSWG** [vvoovv/blender-geo#363]
Hello,

I'm using Blender 3.6.0 and the Premium version of Blosm to import Google 3D Tiles. However, I get the following error:

**Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found**

I'm aware of another individual here who posted a similar error, except it read Error 403: Forbidden. The solution to that issue was to enable the Map TIles API, which I have already done. I've also copied and pasted the Mapbox token and Google 3D Tiles Key token in the Preference options for the Blender add-on. I am able to import plain OSM data. This error only occurs when I select "Google 3D Tiles" and attempt to import.

Thanks for any assistance on this!

**Comment by vvoovv** [comment]
Hi @StarsiderSWG 

We can try to reproduce your problem. Please send your Google 3D Tiles key and your area of interest to prokitektura+support@gmail.com

**Comment by StarsiderSWG** [comment]
> Hi @StarsiderSWG
> 
> We can try to reproduce your problem. Please send your Google 3D Tiles key and your area of interest to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com)

Thanks, I just sent an email with the key and the latest coordinates.

**Comment by vvoovv** [comment]
I replied to you via email.

**Comment by StarsiderSWG** [comment]
> > Hi @StarsiderSWG
> > We can try to reproduce your problem. Please send your Google 3D Tiles key and your area of interest to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com)
> 
> Thanks, I just sent an email with the key and the latest coordinates.

Thank you very much for your assistance. To those here reading, the problem was a fault in my end in not properly setting up the Billing account information. Once I updated my billing information, the error no longer appeared and I was able to load Google 3D sceneries. Closing the issue now.

**Comment by StarsiderSWG** [comment]
Closing due to the issue being resolved by updating billing info.

**Comment by HH-DesignTechnology** [comment]
Hi - I have the same problem. Getting the HTTP 400 error. any help?

**Comment by HH-DesignTechnology** [comment]
> Hi - I have the same problem. Getting the HTTP 400 error. any help?

This is the exact error if it helps:
Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad Request

**Comment by vvoovv** [comment]
Hi @HH-DesignTechnology 

Please send your Google 3D Tiles Key to prokitektura+support@gmail.com. I'll check it out.

**Comment by ayush179959** [comment]
Hey I'm having the same error 
http error 400m bad request
@vvoovv please help

**Comment by vvoovv** [comment]
Hi @ayush179959 

Please send your Google 3D Tiles Key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by mipahes** [comment]
Hey I'm having the same issue as fellow folks above
(Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad Request)
can you please help me? @vvoovv

**Comment by vvoovv** [comment]
Hi @mipahes

Please send your Google 3D Tiles Key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by mipahes** [comment]
Hey, I fixed it in the meantime, thanks for the reply anyway.
The billing info wasn't set up properly...

**Comment by TinUnity** [comment]
@vvoovv i send you a 3D key, please check for me, tksssss

**Comment by vvoovv** [comment]
@TinUnity 

The solution to your problem is given in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by OlivierCaronFrance** [comment]
Bonjour, j'ai une erreur 403, pouvez vous m'aider ? Merci
Et j'ai bien activé map tiles api

**Comment by vvoovv** [comment]
Hi @OlivierCaronFrance 

The solution to your problem is given in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by OlivierCaronFrance** [comment]
Salut vvoovv
comme je l'ai écrit j'ai bien activé Map Tiles Api comme décrit dans la FAQ
![Map Tiles API](https://github.com/vvoovv/blosm/assets/156086748/5f7978d2-5eba-4c5c-846f-6bb7fe4c1ed3)

**Comment by vvoovv** [comment]
It looks for me like this on the page https://console.cloud.google.com/google/maps-apis/api-list (The Map Tiles API is active):

![image](https://github.com/prochitecture/blosm/assets/613295/97bc073f-6357-4b1b-b118-8444be34d7b0)

**Comment by vvoovv** [comment]
@OlivierCaronFrance 

Please paste a screenshot of the error you are getting.

**Comment by OlivierCaronFrance** [comment]
@vvoovv 
![erreurr blender](https://github.com/vvoovv/blosm/assets/156086748/f69d3269-b6e8-4a7a-af35-b06c71fa5ea4)

**Comment by vvoovv** [comment]
@OlivierCaronFrance 

If Map Tiles API is active, I don't see the other option than deleting everything and creating a key again.

**Comment by iver7044** [comment]
@vvoovv I am having the same issue as many of the people on here. I can nt get the google map tiles to come into Blender via OSM. I get the following message: "unable to process the root URI of the 3D Tiles: HTTP error 400: Bad request. I have enabled the Google map tile API and billing info looks correct. Any help would be appreciated.

**Comment by vvoovv** [comment]
Hi @iver7044 

Please send your Google 3D Tiles Key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by TarasRoman** [comment]
Hello, I have the same error described above. Can you help me?

**Comment by vvoovv** [comment]
Hi @TarasRoman 

If it's 403 or 404 error, see the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq).

If it's the error similar to the one in #443, install the latest version of the Blosm addon (currently 2.7.4)

**Comment by TarasRoman** [comment]
![Screenshot_6](https://github.com/vvoovv/blosm/assets/158461779/2eb469c9-70a3-498d-bb40-bddfb07cd162)

i have this one eror

**Comment by vvoovv** [comment]
@TarasRoman

Please also check the solutions for the 403 and 404 errors in the FAQ. Often that helps to solve the 400 error.

**Comment by Blacksmith-cyber** [comment]
Hi we are having the exact problem with bloom when trying to do Google 3D tiles we get "unable to process the root URI of the 3D tiles: HTTP error 400 bad request"

**Comment by vvoovv** [comment]
Hi @Blacksmith-cyber

Please check the solutions for the 403 and 404 errors in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation. Often that helps to solve the 400 error.

**Comment by Blacksmith-cyber** [comment]
I’ve gone through the FAQ the payment info seems correctSent using the mobile mail appOn 21/02/2024 at 14:43, vvoovv wrote:
                
            
            
                
                    From: "vvoovv" ***@***.***>Date: 21 February 2024To: "vvoovv/blosm" ***@***.***>Cc: "Mention" ***@***.***>,"Blacksmith-cyber" ***@***.***>Subject: Re: [vvoovv/blosm] Failed attempt to import Google 3D Tiles (Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found) (Issue #363)
                
                
Hi @Blacksmith-cyber
Please also check the solutions for the 403 and 404 errors in the FAQ section of the documentation. Often that helps to solve the 400 error.

**Comment by vvoovv** [comment]
@Blacksmith-cyber 

Please send to prokitektura+support@gmail.com
* a screenshot of your addon settings and
* your Google 3D Tiles key as a text

**Comment by j099107927** [comment]
Hello, I have the same error about error 400 , and I have tried solving the problem of 403 and 404, still error . Can you help me?

**Comment by Folkeir** [comment]
Hi. I got the same Error. "Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad Request"

From what I can see Billing is all set up and 3D Tiles is active.

**Comment by vvoovv** [comment]
Hi @Folkeir 

Please send a screenshot of your addon preferences to prokitektura+support@gmail.com. I'll check it out.

**Comment by dealessandrij** [comment]
@vvoovv I am having a similar problem (Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad Request). Even though I updated the payment methods, it still doesn't work. Could you help me?

**Comment by vvoovv** [comment]
Hi @dealessandrij 

I've just got an email from you. Often people enter a URL instead of the key. The actual Google 3D Tiles key starts with the string _AIza_.

Please update the value of your Google 3D Tiles key in the preferences of the Blosm addon.

**Comment by dealessandrij** [comment]
Thank you so much for the quick response!
It worked :)

I wish you a good day!!!

Il mar 7 mag 2024, 11:54 vvoovv ***@***.***> ha scritto:

**Comment by wolfie138** [comment]
i have an AIza key and am getting the error, w/ a 404 code

**Comment by vvoovv** [comment]
Hi @wolfie138 

The solution to you problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by javiercrmd** [comment]
@vvoovv I have tried to import different areas and nothing appears in Blender, I have activated maps tiles and nothing, I don't get any errors, is there a solution?

![imagen_2024-07-07_194517809](https://github.com/vvoovv/blosm/assets/174976842/b331defc-44d7-4901-ac7c-79132a120018)

**Comment by vvoovv** [comment]
Hi @javiercrmd 

It's a basic Blender thing, Select the object `Google 3D Tiles` in Blender's Outliner and zoom to the selected object by pressing the button `.` (dot) on the Numpad.

**Comment by Jagadeeswaran22** [comment]
unable to process the root uri of the 3d tiles http error 404: not found i checked in F&Q they said i have Billing issue this future have charges ?

**Comment by vvoovv** [comment]
Hi @Jagadeeswaran22 

As describe in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation, please verify that everything was entered correctly in your billing account.

**Comment by javiercrmd** [comment]
> Hi @javiercrmd
> 
> It's a basic Blender thing, Select the object `Google 3D Tiles` in Blender's Outliner and zoom to the selected object by pressing the button `.` (dot) on the Numpad.

Hi @vvoovv 
I followed the steps you mentioned but I can´t visualize it, any other ideas?

**Comment by vvoovv** [comment]
Hi @javiercrmd 

Please post a screencast or a number of screenshots, so I will be able to understand what you did and what your problem was about.

**Comment by klim2478** [comment]
Good morning. I have exactly the same problem ajko @vvoovv. Everything is loaded without errors, I just don't see the imported object_map. I'm sure it's some kind of bug in the settings, but I can't find it. Can you advise me? I work on NTB, nothing happens when I press the dot. Thank you
![Výstřižek](https://github.com/user-attachments/assets/78e3355b-f79f-4f54-808a-8139f77f3f6e)

**Comment by vvoovv** [comment]
Hi @klim2478,

>  I work on NTB, nothing happens when I press the dot.

Alternatively, you can press `F3`, type `View Selected` in the search field and press Enter.

**Comment by klim2478** [comment]
Great, that helped.
Thank you
Jan


po 7. 10. 2024 v 22:35 odesílatel vvoovv ***@***.***> napsal:

**Comment by RahmaAyari** [comment]
it shows "unable to process the root uri of the 3d tiles http error 500 forbidden internal server error"  Knowing that I activated the Map tiles and set the billing account! any help please ?

**Comment by vvoovv** [comment]
Hi @RahmaAyari 

Please send your Google 3D Tiles key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com).

I'll check it out.

**Comment by klim2478** [comment]
Thank you, I have everything sorted out,
have a nice day.
Jan

ne 9. 3. 2025 v 17:06 odesílatel vvoovv ***@***.***> napsal:

**Comment by Guts355** [comment]
![Image](https://github.com/user-attachments/assets/6f4fbca8-f543-4080-a3c1-59eb62de7de3)

Hey @vvoovv, My issue is the same, I've set up the payment methods and everything seems to be fine, but when I import the city it just doesn't come, or it's hidden idk, I can see it in the outliner tho. Please help me with this 

Thankyou.

**Comment by vvoovv** [comment]
Hi @vvoovv 

I can see on your screenshot that the import was successful. Select the imported mesh object in the Outliner and press the button `.` (dot) on your NumPad to zoom into the imported mesh object. I hope this helps.

**Comment by roccofattorigiuliano-cell** [comment]
hi @vvoovv  im having an error: 400 trying to import a google 3d tiles map into blender and also "unable to process root URI". I've already spoken with Google assistance and everything looks good on their end but my request are not going trough. What can i try to do to fix this?

**Comment by vvoovv** [comment]
Hi @roccofattorigiuliano-cell 

Hi @roccofattorigiuliano-cell 

Please to prokitektura+support@gmail.com:
* your Google 3D Tiles key as a text
* a screenshot of your preferences of the Blosm addon where you set your Google 3D Tiles key

I'll take a look.

**Comment by pachvisuals** [comment]
Hi everyone, unfortunaely I started getting the dreaded forbidden error. It worked fine just 2 weeks ago... rechecked API key, billing etc everything seems set up ok. Blender 4.3.2 and blosm_2.7.20. can anyone please help? thank you

**Comment by vvoovv** [comment]
Hi @pachvisuals 

What error are you getting?

**Comment by pachvisuals** [comment]
@vvoovv "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden

**Comment by vvoovv** [comment]
@pachvisuals 

Please see #644

**Comment by pachvisuals** [comment]
but then how did it work 2 weeks ago? O.o

**Comment by vvoovv** [comment]
@pachvisuals 

You can contact Google support.

**Comment by ahmettEmre** [comment]
@vvoovv "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden

**Comment by vvoovv** [comment]
Hi @ahmettEmre 

If you are based in EU/EEA, please see #644
