### ISSUE TITLE
'BlenderApp' object has no attribute 'init3dTiles'

### ISSUE THREAD

**Issue by MC-Emir** [vvoovv/blender-geo#365]
Hi. I am new in Blender and Blosm. Blender version is 3.6.1. I read blosm setup documantation. But I have an error when I want to create  Google 3d Tiles. The error is 'BlenderApp' object has no attribute 'init3dTiles'. What am I doing wrong? or What is missing? Thank you for your help.

**Comment by vvoovv** [comment]
Hi @MC-Emir 

Please try restarting Blender.

If it didn't help, please try the following actions:
* Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing osm in the search box in the Blender preferences.
* Restart Blender
* Install the latest version of the Blosm addon.

**Comment by MC-Emir** [comment]
Thank you for your help. It works.
