### ISSUE TITLE
Exporting textures to other programs for Visualization purposes

### ISSUE THREAD

**Issue by chazguz** [vvoovv/blender-geo#366]
Hi!

Thank you for making this awesome add-on. I am learning Blender as we speak just to learn this process and the tool you've developed. 
I am currently trying to use a chunk of an urban area as a backdrop for a rendering for a design competition, but I am afraid I am getting stuck with exporting the textures out of blender. I have unpacked the textures as mentioned in your post, and a textures folder has been created where my blender file is saved. But afterwards any file I export fails to grab the textures correctly, OBJ files have maps created in them but their JPGs are missing and the MTL file does not have them properly assigned. I am not sure what do to here....anybody?

After unpacking the textures, do I have to repack them into the blender file? i.e. replacing all the material image nodes with the corresponding image that is located in file location textures folder? If that's the case, is there a way to do this automatically? I have tried making this location a source location for textures in the document but that did not work. Please help. I am totally lost here.

Thanks

**Comment by vvoovv** [comment]
Hi @chazguz 

Please try exporting your scene to FBX.

**Comment by chazguz** [comment]
Hi! Thanks for your reply. I realized what the problem was. I had switched the Replace Materials with tab with Custom and this was impacting the export. An OBJ file was produced effectively with the textures applied and it looks amazing! I will try FBX next! 

Thank you so much!
