### ISSUE TITLE
how to increase google 3d map download speed?

### ISSUE THREAD

**Issue by poodarchu** [vvoovv/blender-geo#367]
thanks for your excellent work, I've purchased the premium version, and I found that the google 3d tiles download speed is extremely slow (less than 100KB/s). I've tried VPNs at different location (e.g., Japan, US), but it seems that no help. How can I speed up the downloading for Google Map 3D tiles using Blosm?

**Comment by vvoovv** [comment]
Hi @poodarchu 

Please note that this time also include the time to temporary save each tile on a hard drive and import it to Blender.

Later a parallel import of 3D Tiles may be implemented using Python's threads. Currently we are busy with other tasks.
