### ISSUE TITLE
Is the "Buildings with more details" the corresponding to finest resolution of the 3D model in Google Map / Earth?

### ISSUE THREAD

**Issue by poodarchu** [vvoovv/blender-geo#368]
I find that the finest texture obtained by blosm is lightly worse than that in original google earth / maps, how can I get the finest texture in google map?

**Comment by vvoovv** [comment]
Could you please provide some screenshots to illustrate your finding?

**Comment by poodarchu** [comment]
![Screenshot 2023-08-02 at 9 17 33 AM](https://github.com/vvoovv/blosm/assets/11813362/e87f7a29-d759-42db-ac75-88dfaf22541e)
left blosm | right google map

**Comment by poodarchu** [comment]
![Screenshot 2023-08-02 at 9 28 38 AM](https://github.com/vvoovv/blosm/assets/11813362/0e247dac-3035-49ba-b4b4-14bd7627f613)
Here is another example

**Comment by vvoovv** [comment]
Yes, the textures at Google Maps seem to be a bit more detailed. At the moment I'd prefer to keep the addon as-is.

**Comment by poodarchu** [comment]
what causes this difference? Can I modify the add-on by my self to change this parameter?

**Comment by vvoovv** [comment]
You can play with the values of the dictionary `_geometricErrorRanges ` in the file [blosm/threed_tiles/manager.py](bloms/threed_tiles/manager.py#L16)

**Comment by vvoovv** [comment]
Hi @poodarchu

It seems that Google Maps and Google Earth do provide more detailed textures at the maximum level of details.

It's possible to load Google 3D Tiles in a web browser to check that. Copy the code from the section _Simple example_ from the page [Work with a 3D Tiles renderer](https://developers.google.com/maps/documentation/tile/use-renderer?hl=en#simple-example) to your text editor. Find the string `YOUR_API_KEY` using the search functionality of your texture editor and replace it with your Google 3D Tiles Key. Save the file with the extension _html_ and open it in a web browser.

**Comment by leekyyoon99** [comment]
Hi, I have a question about blosm "buildings with more details" option.
There is no error but when I import using "buildings with more details" option
then only terrain is on the blender.
what is problem? Please help

**Comment by vvoovv** [comment]
@leekyyoon99 

Probably Google Cloud does not provide 3D buildings for your area of interest. Please read the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) in the documentation on how to see the areas with 3D buildings.

**Comment by leekyyoon99** [comment]
Thank you!!

**Comment by leekyyoon99** [comment]
Hi, sorry I have one more question about blosm and UnrealEngine.
I successfully imported google 3d tiles using "blosm" option buildings with more details, thanks to your advice
But when I tried to convert it to FBX file and exported for Unreal Engine 4.25.
But actually It didn't work well.
Could you recommend addons or solution that can change 3d google map blender file to FBX file compatible to Unreal Engnine?
I want Geo referenced frame in Unreal engine for drone simulation.

Thank you for reading

**Comment by vvoovv** [comment]
@leekyyoon99 

Please refer to the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) in the documentation.

**Comment by leekyyoon99** [comment]
Thank you !
