### ISSUE TITLE
Blender Osm unable to download the tile image

### ISSUE THREAD

**Issue by korotovool** [vvoovv/blender-geo#369]
I have an issue when try to import image overlay, please help! 
After importing, the image overlay had appeared just totally black.
<a href="https://imgur.com/hlInyYF"><img src="https://i.imgur.com/hlInyYF.jpg" title="source: imgur.com" /></a>

**Comment by vvoovv** [comment]
Hi @korotovool 

Please check your ArcGIS access token. Why is it made of circles?

**Comment by korotovool** [comment]
I'd just copied the token while set it in hide value. Fixed!
