### ISSUE TITLE
Material setting when importing Google Tiles

### ISSUE THREAD

**Issue by warchildmd** [vvoovv/blender-geo#370]
When you import tiles, the material that is created in Blender doesn't react to scene lights as it's using an emission sharer.

![image](https://github.com/vvoovv/blosm/assets/1886059/c977e59c-3c95-4fa4-ba64-c256e6357898)

It would be useful to have a setting to replace that Emission with a Principled BS
![image](https://github.com/vvoovv/blosm/assets/1886059/f51a7f17-b182-40eb-bf2a-42ab45972d8a)

Importing the tiles creates hundreds of "materials" for different portions of the map and if you want to make the map react to light, you have to do hundreds of material changes.

I've no lights in this scene, and manually changed a couple of materials (to make them interact with scene light):

![image](https://github.com/vvoovv/blosm/assets/1886059/515d5326-5a97-4edc-831d-5f8c50181286)

**Comment by vvoovv** [comment]
Hi @warchildmd 

Please refer to the [documentation ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) (the section _Export and Custom Materials_).
