### ISSUE TITLE
The directory for data in the addon prefs doesn't exist

### ISSUE THREAD

**Issue by nduper** [vvoovv/blender-geo#371]
Hi,
Please can you tell me what am I doing wrong?
Thank you very much.
![1](https://github.com/vvoovv/blosm/assets/141636935/23e11fbd-cf00-465b-b92c-49f9af46f800)
![2](https://github.com/vvoovv/blosm/assets/141636935/2b9fc6e2-088f-4181-b70e-8dcc1840a073)
![3](https://github.com/vvoovv/blosm/assets/141636935/78bc8040-7dc2-4e48-a6b3-d18c9981951b)

**Comment by vvoovv** [comment]
Hi @nduper 

Please check if the folder `F:\BLENDER\OpenStreetMap_BLOSM_directory` does exist and has the correct access rights.

**Comment by nduper** [comment]
![4](https://github.com/vvoovv/blosm/assets/141636935/70d5bb9f-4f8b-4672-886c-699ed1b2831a)

**Comment by nduper** [comment]
It has the usual access rights, as any other created folder. Or there is need for special access rights?

**Comment by vvoovv** [comment]
Is it a network drive? I'd recommend trying a different drive on your hard disk.

**Comment by nduper** [comment]
No, it's a local drive.

**Comment by vvoovv** [comment]
Please try changing something: the drive, using a simple name for the path, etc.

**Comment by nduper** [comment]
I changed the drive, with same result. I'll try shorter name.

**Comment by nduper** [comment]
I tried the shorter name, but no luck.

**Comment by vvoovv** [comment]
There is a check in the addon code. You can perform the same check yourself. Open Python Console in Blender.
Then
```python
import os
os.path.isdir("F://Blender//BLOSM_OpenStreetMap_directory")
```
Press `Enter` after each line. If the output of the last line is False, the error message is displayed by the addon.
