### ISSUE TITLE
building:levels:underground

### ISSUE THREAD

**Issue by axelos** [vvoovv/blender-geo#373]
Hello,

I propose add the height underground for the polygons building:levels:underground=*

Example use :

![Building levels underground](https://fccl-vandoeuvre.fr/divers/temp/building_levels_underground)

Way in OSM : https://www.openstreetmap.org/way/716771494

Documentation : https://wiki.openstreetmap.org/wiki/Key:building:levels:underground

https://github.com/vvoovv/blosm/issues/372

**Comment by vvoovv** [comment]
The underground levels are hidden under the terrain and can't be seen. So the underground levels can be simply ignored as it is the case now.

**Comment by axelos** [comment]
The example in the OpenStreetMap documentation confirms what you're saying. I will modify the buildings in the database.

https://wiki.openstreetmap.org/wiki/Key:building:levels#Example

Thanks for your help.
