### ISSUE TITLE
How to export the google map 3d tiles in blender as PLY format while keeping the texture?

### ISSUE THREAD

**Issue by poodarchu** [vvoovv/blender-geo#374]
I tried to export the downloaded 3d mesh and its textures into a single ply file, and opt-on texture related option in the export as pannel. but when I open the ply file with MeshLab / open3d, it shows that no texture is applied.

**Comment by vvoovv** [comment]
Please check if export to FBX works for you.

**Comment by Absinthze** [comment]
I've tried a few things to get FBX to export textures, still haven't figured it out.   Going from Blender to 3ds MAX.  I think its because its a "Mix Shader so the bitmap is not linked directly to the Diffuse in blender.  (I dont know blender)

**Comment by vvoovv** [comment]
@Absinthze 

Please create a new issue for your problem and provide more details.

**Comment by Absinthze** [comment]
The work around seems to be using the Simplygon addon in blender to bake the textures before exporting.

**Comment by Costas73** [comment]
For me it didn't work
