### ISSUE TITLE
A valid directory for data in the addon preferences isn't set

### ISSUE THREAD

**Issue by zaryar001** [vvoovv/blender-geo#376]

**Comment by vvoovv** [comment]
Hi @zaryar001 

Please set that directory as described in the [documentation](https://github.com/vvoovv/blosm/wiki/Documentation#video-tutorial).

**Comment by tamilselvans-lang** [comment]
**A valid directory for data in the addon preferences isn't set**
I am Using Blender for Direct map building into the blender software and I got this Issue. anyone if tell me. How to solve this problem.

Using Blosm Addon

**Comment by vvoovv** [comment]
Hi @zaryar001 

Please set that directory as described in the [documentation](https://github.com/vvoovv/blosm/wiki/Documentation#video-tutorial).
