### ISSUE TITLE
plugin installed according to instructions but no "blosm" tab appears when I hit "n"

### ISSUE THREAD

**Issue by JohnProphet** [vvoovv/blender-geo#377]
I tried uninstalling and reinstalling a few times but I get nothing.

No blosm tab after install. Fresh install into the latest version of Blender.
[
![blosm error](https://github.com/vvoovv/blosm/assets/87950318/1e2ea075-f137-4b5d-827c-34ed070914d8)
](url)

**Comment by vvoovv** [comment]
Hi @JohnProphet 

Is there an error message?

What version of Blender are you using?

**Comment by JohnProphet** [comment]
I rebooted my PC and reloaded Blender and now Blosm tab is there!  blender v3.6.2
