### ISSUE TITLE
trying to use Blender osm but i keep getting 'A valid directory for data in the addition preferences isn't set' 

### ISSUE THREAD

**Issue by Parson23** [vvoovv/blender-geo#378]
![image](https://github.com/vvoovv/blosm/assets/143203480/1b567ac7-4d9e-4246-86dc-72858b6de24d)

(don't know if the screen shot worked) 

basically every time I try and import I get the message 'A valid directory for data in the addition preferences isn't set'

any help is greatly appreciated :)

**Comment by vvoovv** [comment]
Hi @Parson23 

Please set a valid directory for the addon data in the addon preferences as described in the documentation:
https://github.com/vvoovv/blosm/wiki/Documentation#video-tutorial
