### ISSUE TITLE
Module error- No module named "realistic"

### ISSUE THREAD

**Issue by JoaoZin38** [vvoovv/blender-geo#379]
this error appears when i try to enable the addon
![image](https://github.com/vvoovv/blosm/assets/138620794/86555fe3-4ac9-4c92-9f70-9c08f0d84e42)

**Comment by vvoovv** [comment]
Hi @JoaoZin38 

Please try restarting Blender.

If it didn't help, please try the following actions:
* Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing osm in the search box in the Blender preferences.
* Restart Blender
* Install the latest version of the Blosm addon.
