### ISSUE TITLE
Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Oeuh** [vvoovv/blender-geo#380]
Hi, I have followed the process to set Google 3D Tiles. I have the key with the related rights, and Map Tiles API enabled. But when I press "import", I get the following error message:
`Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found`

Do you know what I could have done wrong?

I use Blender 3.6.0 and Blosm 2.7.2

Many thanks

**Comment by vvoovv** [comment]
Hi @Oeuh 

There was a similar problem in #363. The problem was in not setting up the Billing account information properly.

**Comment by Oeuh** [comment]
Indeed... Thanks!

**Comment by vvoovv** [comment]
What exactly was missing?

**Comment by Oeuh** [comment]
My credit card was disabled from the bank (since I lost it a month ago). Google asks the bank for a 0.00 amount, but does not clearly warn the user when not working

**Comment by vvoovv** [comment]
Thank you for the details!
