### ISSUE TITLE
blosm premium. Google 3d Tiles returning a 2d flat image. 

### ISSUE THREAD

**Issue by saibakatar** [vvoovv/blender-geo#381]
![image](https://github.com/vvoovv/blosm/assets/15951261/928ab84c-035c-4f07-ba98-01cb2a79a0ca)

Hi. 
Trying to use Blosm Premium, and had set up the Google Tiles by putting in the api key. 
However, when I try to import data for location what I'm getting is a flat 2d image.

**Comment by vvoovv** [comment]
Hi @saibakatar 

Most likely your area of interest doesn't have a detailed 3D mesh for buildings. You can check it [here](https://earth.google.com/web/@0.04318032,-0.21948713,-8.86749053a,22261460.54461666d,35y,0h,0t,0r/data=CjkSNxIgZDY1OGRjYWIzNjlhMTFlOGFjNmU2OWJjN2I2ZDI2Y2EiE2xheWVyXzNkY292ZXJfcGFuZWw).
