### ISSUE TITLE
Massive dropoff for 3d Tile Requests

### ISSUE THREAD

**Issue by nanogram** [vvoovv/blender-geo#382]
![image](https://github.com/vvoovv/blosm/assets/14881073/1f9a47a5-f93b-4cde-9dee-324168d32e25)
![image](https://github.com/vvoovv/blosm/assets/14881073/46885d8f-a70a-4bba-a043-44d4f03a2b50)

When loading city, started off at 271 API requests per min & dropped off to 25 after 3 hours. 12k/min is the ceiling.
Not sure if this is due to plugin bogging down after a bit.
It also looks like there's currently no limit for 3d tile requests per day.

**Comment by vvoovv** [comment]
Hi @nanogram 

Thank you for sharing the information.

The addon doesn't limit the download of 3D Tiles in any way. The addon downloads the tile consecutively, one after another. A possible optimization would be to download the tiles in parallel, like a we browser does.
