### ISSUE TITLE
Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [vvoovv/blender-geo#385]
Hi,
I have installed Blender 3.6.2 and recently activated a Google 3D Tiles Key as well as Maps Tiles API.

When trying importing Google 3D tiles in Blender I get the error: 

"Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden"

Does the google email used to activate all the three token (ArcGIS, Mapbox and Google 3D Tile) be the same?

Thanks in advance,

Martina

**Comment by vvoovv** [comment]
Hi @MartinaBarbiFivecomm

You can use different email addresses for each of ArcGIS, Mapbox and Google 3D Tiles.

The solution to the 403 error can be found in the documentation https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq (the section FAQ).
