### ISSUE TITLE
Google 3D Tiles: not the highest LOD available?

### ISSUE THREAD

**Issue by WarnerV** [vvoovv/blender-geo#386]
Hi,

I'm comparing a downloaded set at BLOSM "buildings with more details" LOD and comparing it to what I see in Google Earth. It seems that there's at least one Level of Detail missing (see attached/below). I'm using Blender 3.6 and BLOSM v2.7.2.

Is this something that may be fixed? Is Google just not providing it?

![BlenderOSM](https://github.com/vvoovv/blosm/assets/18480113/a9020817-3460-4f0c-ba25-24f96e884a66)
![GoogleEarth](https://github.com/vvoovv/blosm/assets/18480113/3680ce2b-45ab-4ae8-b375-e14fcd2fd36b)

**Comment by vvoovv** [comment]
Hi @WarnerV 

It seems that Google Maps and Google Earth do provide more detailed textures at the maximum level of details.

It's possible to load Google 3D Tiles in a web browser to check that out. Copy the code from the section _Simple example_ from the page [Work with a 3D Tiles renderer](https://developers.google.com/maps/documentation/tile/use-renderer?hl=en#simple-example) to your text editor. Find the string `YOUR_API_KEY` using the search functionality of your texture editor and replace it with your Google 3D Tiles Key. Save the file with the extension _html_ and open it in a web browser.

**Comment by vvoovv** [comment]
See also #368.

**Comment by WarnerV** [comment]
Hi @vvoovv 

That's unfortunate - thank you for providing the details on this.

I suggest that everyone reading this goes to [https://developers.google.com/maps/support](url) and provides feedback to Google expressing disappointment (click on the 'send feedback' button).

Here's a template for what you might write:

> Hi,
> 
> It's a wonderful development that Google is opening up the APIs for Maps/3DTiles. 
> 
> Sadly, to the great disappointment of many, the most detailed images quality (LOD) is not available.
> 
> This leads to results significantly inferior to what can be seen on Google Earth and seriously impacts the potential of applications built on the data.
> 
> It would be great if Google can reconsider this approach.
