### ISSUE TITLE
Google 3D Tiles: Gaps between tiles

### ISSUE THREAD

**Issue by WarnerV** [vvoovv/blender-geo#387]
Hi there,

Downloading Google 3D Tiles using BLOSM, I'm seeing gaps in between the tiles (+/- 1m wide at the most). I'm using Blender 3.6 and addon v2.7.2. 

Is this expected behavior?

Cheers,
W

**Comment by vvoovv** [comment]
Hi @WarnerV 

The addon relies on the built-in glTF importer to import 3D Tiles. The coordinates in a 3D Tile are in meters relative to the center of the Earth. That means millions of meters on each axis. The glTF addon imports them as-is. The Blosm addon applies geometrical transformations to bring the 3D Tiles to the center of Blender's system of reference.

I think those huge original coordinates is the reason for the gaps. They can't be fixed without changing the code of the glTF addon.

**Comment by vvoovv** [comment]
See also #430
