### ISSUE TITLE
Blosm premium - I can't bake the textures and export it to unity

### ISSUE THREAD

**Issue by llx001** [vvoovv/blender-geo#388]
What i am trying to do is to import a generated city into Unity but blender doesn't seems to be able to bake the texture.
I am using Blender v3.6

**Comment by vvoovv** [comment]
Hi @llx001

Export of an OpenStreetMap scene is described in the [documentation](https://github.com/vvoovv/blosm/wiki/Premium-Version#export-of-the-imported-scene).

**Comment by llx001** [comment]
Shoot, I am very sorry, somehow I didn't find it. It works like a charm, although question: Can it also add the emissive textures to it? Because without the experimental settings I had slider with the percentage of windows and now I don't.
I need all windows to have an emission mapped to them. Can this be done? (The game uses the emission strength to turn on and off the night lights)

**Comment by vvoovv** [comment]
Unfortunately the emissive textures aren't processed at the moment. That will be fixed in the future releases.
