### ISSUE TITLE
Missing OSM Categories

### ISSUE THREAD

**Issue by PhiKuz** [vvoovv/blender-geo#390]
![image](https://github.com/vvoovv/blosm/assets/121882300/e9726ffd-b393-40c8-b0e7-c4c81b01ab58)
![image](https://github.com/vvoovv/blosm/assets/121882300/8451e6a8-7442-46a3-b389-5bbbc46a0374)

I noticed that Maproom for 3ds Max includes the "leisure=park" category. I was wondering if there was a way to have blosm include additional categories like this one. I was hoping to find a use for the "Setup Script" option, but I couldn't find anything on it in the documentation.

Thanks!

**Comment by vvoovv** [comment]
Hi @PhiKuz

The areas within a park should be mapped as forests, grass, etc.

You can use the following setup script as a template:
https://github.com/vvoovv/blosm/blob/setup_scripts/base_landuse.py

Add the condition for the park at the line 63 of that script:
```python
    osm.addCondition(
        lambda tags, e: tags.get("leisure") == "park",
        "leisure_park",
        polygon
    )
```
