### ISSUE TITLE
Support for airport taxiways and runways

### ISSUE THREAD

**Issue by measuredweighed** [vvoovv/blender-geo#391]
Thank you for the wonderful plugin. Are there plans to support airport taxiways/runways in the future, or is this already possible and something I've missed? Attached is a screenshot of Heathrow Airport (LHR) featuring geometry for most internal roads, but sadly no sign of any taxiways or runways.

![1](https://github.com/vvoovv/blosm/assets/1234600/c055b76b-cad7-4dc2-acc2-f925183b0e40)
<img width="1243" alt="2" src="https://github.com/vvoovv/blosm/assets/1234600/685b56f4-f52a-47dc-b46a-beb254bad3aa">

**Comment by vvoovv** [comment]
Hi @measuredweighed 

It's possible to import taxiways and runways via a setup script

* Download the Blender [file](https://github.com/vvoovv/blosm/blob/setup_scripts/assets/profile_aeroways.blend) with the profiles for the curves representing taxiways and runways. Append the curves to your Blender file

* Save the Python [file](https://github.com/vvoovv/blosm/blob/setup_scripts/base_aeroways.py) to your hard drive. Set the path in the option _Setup Script_ to that file

* Now you can import your area on interest.

**Comment by ewebgh33** [comment]
Apologies for commenting on an old issue.
Just to clarify, we append the curves to the blank blender file (or whatever file we're working on) and add the path for the py script to "Setup Script" option, _before_ doing the terrain and OSM import?
Thanks

**Comment by vvoovv** [comment]
@ewebgh33 

Yes, before an import.
