### ISSUE TITLE
Terrain Scale and Image Overlay

### ISSUE THREAD

**Issue by MutterOberin** [vvoovv/blender-geo#392]
I noticed the following behavior: When importing a terrain and subsequently scaling the terrain object the import of texture overlay breaks. The extents for the overlay are not calculated correctly anymore, since the scaled terrain coordinates are used. 

Is this behavior intentional?

**Comment by vvoovv** [comment]
Hi @MutterOberin 

We'd recommend scaling the terrain after the overlay import.

**Comment by MutterOberin** [comment]
Thank you for the quick answer! Will do it this way.
