### ISSUE TITLE
blosm activation error message

### ISSUE THREAD

**Issue by sueki** [vvoovv/blender-geo#393]
i got an error message when I tried to activate in Blender 3.5 and 3.6

see attached.
![blosm_error_message](https://github.com/vvoovv/blosm/assets/232598/5b217725-a0da-43f9-8635-b15e68e8f3cb)

thanks

**Comment by vvoovv** [comment]
Please get the addon from Gumroad https://prochitecture.gumroad.com/l/blender-osm and follow the installation and usage [instructions](https://github.com/vvoovv/blosm/wiki/Documentation#video-tutorial).
