### ISSUE TITLE
Terrain Curvature

### ISSUE THREAD

**Issue by MutterOberin** [vvoovv/blender-geo#394]
When creating a terrain the height profile is correctly created but the earth curvature is missing. The terrain is basically flat. Is there a way to create correct curvature?

**Comment by vvoovv** [comment]
Getting the earth curvature with the default projection is not possible. However the earth curvature is preserved in Google 3D Tiles.

**Comment by MutterOberin** [comment]
Thank you very much! 

As a workaround I do the following: I generate a Grid with appropriate subdivisions for the ROI. Recalculate all vertex positions from georef to cartesian using some scripts and then project the terrain via shrinkwrap modifier. This way the terrain has the correct earth curvature. Currently the height profile is lost with this approach. For this the height information has to be baked as displacement map before projection.
