### ISSUE TITLE
Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by HH-DesignTechnology** [vvoovv/blender-geo#398]
Getting this error when importing Google 3D Tiles

**Comment by vvoovv** [comment]
Hi @HH-DesignTechnology

Please send your Google 3D Tiles Key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by nextwave1980** [comment]
I am having the same problem. I have an API key and have enabled Map Tiles API... but still getting 400: bad request. any idea?

**Comment by vvoovv** [comment]
Hi @nextwave1980

Please send your Google 3D Tiles Key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by Wiser2001** [comment]
Same issue. I got premium today but no luck with Google 3D so far, I get: There was an error when processing the URI https://title.googleapis.com/v1..... HTTP Error 400: Bad Request.

**Comment by vvoovv** [comment]
@Wiser2001 

I can confirm the problem. It looks like Google has changed something recently. We are currently investigating the problem. I'll report back to you as soon as possible.

**Comment by vvoovv** [comment]
@Wiser2001 

The problem has been fixed. Please please see #443.
