### ISSUE TITLE
Pulling Google 3D tiles stops after 8-11 files

### ISSUE THREAD

**Issue by kyle1373** [vvoovv/blender-geo#399]
![image](https://github.com/vvoovv/blosm/assets/59634395/bf24001b-eaf5-49f8-880f-cf2777ff0f30)

I went through the documentation to pull 3D google tile data on the "buildings with more detail" option using the premium version of Blosm. Everything goes smoothly up until it gets at around 8-11 files, in which it stops downloading more files. I noticed that there's a `current_file.glb` that occasionally appears and disappears, but the file count does not increase beyond that. I've tried to download on different areas and get the same result. However, when I try on the lowest setting, it downloads with no issues. It's when I get to the higher details that the download issues arise. I've been doing a lot of research and can't seem to pinpoint the issue.

**Comment by vvoovv** [comment]
Hi @kyle1373

Please note that a scene with "buildings with more detail" may contain thousands of 3D tiles. It takes a considerable time to download them.

You can open Blender's System Console (Window -> Toggle System Console) and check if the import is still running.

**Comment by kyle1373** [comment]
Thanks for the reply! I ran the add-in a few times with logs and noticed that it would run successfully anywhere from 5 seconds to 2 minutes or so before halting indefinitely. Here's when it starts:
![image](https://github.com/vvoovv/blosm/assets/59634395/e4b1e59d-bd3c-4469-be58-ba81c194ba5c)

And after 40 seconds, this is where it gets stuck:

![image](https://github.com/vvoovv/blosm/assets/59634395/91b69b46-360e-47a5-b797-fb78fa4aa41d)

It's been this way for around 15 minutes, so I'm not sure if it's still running or if it actually did stop working.

**Comment by vvoovv** [comment]
What are the coordinates of your area of interest?

**Comment by kyle1373** [comment]
Small update: it turns out that it does freeze on occasion (sometimes maybe up to 20 minutes), but then it resumes afterwards at normal speed. Not entirely sure why this is the case, as I haven't fully diagnosed the problem. Either way, the issue has been resolved on my end.

> What are the coordinates of your area of interest?

In case you want to explore it a bit more, I was pulling geographic data for the University of California, San Diego specifically on the highest detail mode.

To anyone reading this, definitely open Blender terminal to see the process of pulling data and check the print statements. If it stops randomly, give it time. It may resume eventually. Thanks	!
