### ISSUE TITLE
Additional OSM Attributes 

### ISSUE THREAD

**Issue by owy9999** [vvoovv/blender-geo#401]
Hi 

I just bought the premium version. Absolutely amazing. Thanks a lot. 

Is there a way to get additional OSM attributes like

https://wiki.openstreetmap.org/wiki/Key:golf 

golf=tee; area
golf=green; area
golf=bunker; area
golf=fairway; area
golf=rough; area
golf=water_hazard; area
golf=[ateral_water_hazard; area
golf=cartpath=; line (path for golf carts)
golf=path; line (path for walking)

golf=hole; line; ref=name1 in blender_ ; par=name2 ==> golf=hole ==> in Blender golf_hole_1_3 or even better 
if there is a name: name=Tea olive ==> Blender golf_hole_Tea_Olive_1_3

Can I add OSM attributes myself? 

many thanks in advance

owy

**Comment by vvoovv** [comment]
Hi @owy9999 

That can be accomplished with the help of a custom setup script. The examples of the scripts can be found [here](https://github.com/vvoovv/blosm/tree/setup_scripts). The option to set the path to a setup script is located at the bottom of the addon panel.

Insert a similar code between the lines
```python
# custom setup begins
```
and
```python
# custom setup ends
```

**Comment by owy9999** [comment]
Hi

Thanks for the fast answer.

Unfortunately I am not that strong in Python. Could you please provide a 
single script for a golf attribute? That would be great. I think the 
rest I could then try myself.

Many thanks in advance

owy9999


------ Originalnachricht ------
Von "wyss" ***@***.***>
An "vvoovv/blosm" 
***@***.***>
Datum 09.10.2023 16:51:38
Betreff Re[2]: [vvoovv/blosm] Additional OSM Attributes (Issue #401)

**Comment by owy9999** [comment]
Hi, I did it! Works perfect. Thx

**Comment by owy9999** [comment]
Hi vvoovv

Thanks. It worked great so far. Is there additional documentation for 
custom scripting?

I should set a color for the polygons, lines
I should set a thickness for lines / a number in the middle of a line

I was looking for ArcGis API, there are different API's. Which one is 
correct? JSON?

Best regards

owy9999


------ Originalnachricht ------
Von "vvoovv" ***@***.***>
An "vvoovv/blosm" ***@***.***>
Cc "owy9999" ***@***.***>; "Mention" 
***@***.***>
Datum 09.10.2023 15:44:58
Betreff Re: [vvoovv/blosm] Additional OSM Attributes (Issue #401)

**Comment by vvoovv** [comment]
You can edit the materials and profiles of Blender curves right in Blender.
