### ISSUE TITLE
Is it possible to use Python code directly?

### ISSUE THREAD

**Issue by pwayner** [vvoovv/blender-geo#405]
I would like to script this process. There are several references to a command line version but I don't see it any more. 

TIA

**Comment by vvoovv** [comment]
Hi @pwayner

Yes, it's possible to run the addon in the batch mode.

Below is an example script:

```python
import bpy
# set coordinates of your area of interest
bpy.context.scene.blosm.maxLat = 52.39022
bpy.context.scene.blosm.minLon = 4.90856
bpy.context.scene.blosm.maxLon = 4.91183
bpy.context.scene.blosm.minLat = 52.38855

# set other parameters of the addon

# finally, import the data
bpy.ops.blosm.import_data()
```

Then start Blender in the background mode and execute the script (see the full list of the command line arguments at https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html):

```
blender --background --python /path/to/python/script.py
```

I hope this helps.

**Comment by pwayner** [comment]
Thanks very much for the pointer.

**Comment by pwayner** [comment]
Are there any other fields that can be set?

**Comment by vvoovv** [comment]
Yes, all fields of the addon can be set that way.

Enable Python tooltips to see the names of the addon fields:
Main menu -> Edit -> Preferences -> Interface -> Check _Python Tooltips_
