### ISSUE TITLE
Materials set to emit

### ISSUE THREAD

**Issue by StuNewsub** [vvoovv/blender-geo#406]
Is it possible to change the global material properties when importing from google tiles? All material properties are set to emit meaning that accurate lighting/rendering is impossible without changing thousands of textures. It would make this already amazing addon perfect. Thanks

**Comment by vvoovv** [comment]
Hi @StuNewsub 

Please refer to the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation.
