### ISSUE TITLE
Calling operator "bpy.ops.import_scene.gltf" error, could not be found

### ISSUE THREAD

**Issue by ghostsofviikki** [vvoovv/blender-geo#407]
![image](https://github.com/vvoovv/blosm/assets/49210349/7a8c270b-39ae-4b1b-a776-175c0b791c7b)

Starting to have this error 20.10.2023. I have the premium version. Nothing else changed. I tried regenerating my API key, same result. I checked my google API credentials, nothing seems to indicate my API key is not working. 

It was working fine a day before. May I ask anyone else has the same issue?

**Comment by vvoovv** [comment]
Hi @ghostsofviikki 

Please install the latest version of Blender and the import again.

**Comment by ghostsofviikki** [comment]
ok. I was using 3.6.1 with the addon and no problems. I updated it to 3.6.5 yesterday and it seems to have failed. I just downloaded 4.1alpha and installed the addon and now it is working. May I ask what is the reason behind this behavior?

**Comment by vvoovv** [comment]
Check if the glTF addon is enabled. It is enabled in Blender by default.

![image](https://github.com/vvoovv/blosm/assets/613295/09752ab2-8a20-4b3b-ac7f-3770ddfb55b4)

**Comment by ghostsofviikki** [comment]
![image](https://github.com/vvoovv/blosm/assets/49210349/cbfe0bfb-dfbf-421a-9cb3-26354929493c)
OMG you are a genius! I turned it off for some reason! Thank you! Problem solved.
