### ISSUE TITLE
Shadows not working on imported blosm mesh

### ISSUE THREAD

**Issue by pveierland** [vvoovv/blender-geo#408]
Hi,

Thank you for a great addon!

When creating an object using the Blosm addon, shadows are not properly cast when setting up a light source and an object on top of the Blosm imported surface. Adding a regular plane mesh provides a correct shadow.

(When using the Google 3D tiles import data source.)

Is there a way to configure the imported Blosm mesh to support having shadows casts onto it?

**Comment by vvoovv** [comment]
Hi @pveierland 

Please refer to the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation.

**Comment by pveierland** [comment]
Thank you - that fixed it! It might be good to add a comment in the documentation that this will fix lighting and shadows, to make it easier to find for beginners.
