### ISSUE TITLE
"Property type does not match input socket '(- Blosm or ADE -)'" on Modifier tab

### ISSUE THREAD

**Issue by oyoungRE** [vvoovv/blender-geo#410]
I set up this add-on yesterday and was testing it out with success and using it with Buildify. As of today when I generate a map with buildings I am getting the "Property type does not match input socket '(- Blosm or ADE -)'" on the GeometryNodes modifier. I did not get this warning yesterday AT ALL. I did a fresh install of blender 3.6, blosm, and buildify but I am still getting this error. 
![Screenshot 2023-10-20 103054](https://github.com/vvoovv/blosm/assets/40611647/e6364652-9c22-4204-95be-05a254e7465d)

**Comment by vvoovv** [comment]
Hi @oyoungRE

Sorry, we can't support you with the issues related to Buildify.
