### ISSUE TITLE
Google Maps 3D import is a bit tilted

### ISSUE THREAD

**Issue by Oeuh** [vvoovv/blender-geo#412]
Hello,

When importing a Google Maps sample, I realize that the surface obtained is slightly inclined. Would it be possible to add a functionality correcting that tilt?

The sample: 2.29975,48.8418,2.38815,48.8774

Screenshot: [https://zupimages.net/up/23/43/aksy.png](url)

Many thanks for this amazing add-on!

**Comment by vvoovv** [comment]
Hi @Oeuh 

> Would it be possible to add a functionality correcting that tilt?

I don't think so. It may be caused by the change of the altitude of the Earth's surface.

**Comment by Oeuh** [comment]
Hi @vvoovv,

Thanks for your quick answer. It adds difficulty when remodeling an area, and the previous method [https://github.com/eliemichel/MapsModelsImporter](url) hadn't any tilt. But I understand that fixing that could be difficult.
