### ISSUE TITLE
BLOSM addon using script

### ISSUE THREAD

**Issue by HITESH2002-JAIN** [vvoovv/blender-geo#414]
I am trying to add **BLOSM addon** to Blender 3.6.5 in workstation using python script

```
import bpy
bpy.ops.preferences.addon_install(filepath="/home/hitesh/blosm_premium/blosm.zip")
bpy.ops.preferences.addon_enable(module="blosm")
bpy.context.preferences.addons['blosm'].preferences.dataDir = "/home/hitesh/3d_tiles/"
bpy.context.preferences.addons['blosm'].preferences.assetsDir = "/home/hitesh/blosm_premium/assets/"
bpy.context.preferences.addons['blosm'].preferences.googleMapsApiKey = ""
```
This is throwing a warning:

> Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-18 23:31:25)
> reloading addon: blosm 1699194854.8329778 1699194886.6611388 '/home/hitesh/.config/blender/3.6/scripts/addons/blosm/__init__.py'
> Modules Installed () from '/home/hitesh/blosm/blosm.zip' into '/home/hitesh/.config/blender/3.6/scripts/addons'
> Info: Modules Installed () from '/home/hitesh/blosm/blosm.zip' into '/home/hitesh/.config/blender/3.6/scripts/addons'
> **WARN (bgl): source/blender/python/generic/bgl.c:2660 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.**

Then I tried importing google 3d tiles for a big area patch wise which throws an error 

```
> Error: No 3D tiles were imported. 0 errors occured during the import. See the System Console.
> Error: Python: Traceback (most recent call last):
>   File "/home/hitesh/3d_tiles/tiles_script.py", line 38, in <module>
>     divide_area(min_lat, max_lat, min_long, max_long, area_size_km)
>   File "/home/hitesh/3d_tiles/tiles_script.py", line 26, in divide_area
>     bpy.ops.blosm.import_data()
>   File "/opt/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
>     ret = _op_call(self.idname_py(), None, kw)
> RuntimeError: Error: No 3D tiles were imported. 0 errors occured during the import. See the System Console.
> 
> Blender quit
```

I tried importing the same area using UI and it is working. 
The rest part of script is working locally to import large areas patch wise except the first few steps of adding the blosm addon which I did manually in my PC.

**Comment by vvoovv** [comment]
Hi @HITESH2002-JAIN 

Please some clear steps to reproduce the problem.

The following worked for me:

```
blender.exe /path/to/blender_file_with_settings.blend -P /path/to/script.py
```

Where the content of `script.py` is
```python
import bpy
bpy.ops.blosm.import_data()
```

**Comment by HITESH2002-JAIN** [comment]
Hello @vvoovv 
I am trying to import 3d tiles for a large area patch wise. I have written a python script that will add the blosm addon, enable it and download the tiles. 
```
import bpy
bpy.ops.preferences.addon_install(filepath="/home/hitesh/blosm_premium/blosm.zip")
bpy.ops.preferences.addon_enable(module="blosm")
bpy.context.preferences.addons['blosm'].preferences.dataDir = "/home/hitesh/3d_tiles/"
bpy.context.preferences.addons['blosm'].preferences.assetsDir = "/home/hitesh/blosm_premium/assets/"
bpy.context.preferences.addons['blosm'].preferences.googleMapsApiKey = ""
def divide_area(min_lat, max_lat, min_long, max_long, step_size_km):
    lat_range = max_lat - min_lat
    long_range = max_long - min_long

    step_size_lat = step_size_km / 110.574
    step_size_long = step_size_km / (111.320 * max_lat)

    current_min_lat = min_lat
    while current_min_lat < max_lat:
        current_max_lat = min(current_min_lat + step_size_lat, max_lat)
        current_min_long = min_long
        while current_min_long < max_long:
            current_max_long = min(current_min_long + step_size_long, max_long)
            # Perform import with the current coordinates
            bpy.data.scenes["Scene"].blosm.maxLat = current_max_lat
            bpy.data.scenes["Scene"].blosm.minLat = current_min_lat
            bpy.data.scenes["Scene"].blosm.maxLong = current_max_long
            bpy.data.scenes["Scene"].blosm.minLong = current_min_long
            bpy.ops.blosm.import_data()

            current_min_long += step_size_long
        current_min_lat += step_size_lat
max_lat =  52.57030
min_lat =   52.56238
max_long = 13.39039
min_long =  13.37457
area_size_km = 0.25
bpy.data.scenes["Scene"].blosm.dataType = 'google-3d-tiles'
bpy.data.scenes["Scene"].blosm.lod0f3dTiles = 'BUILDINGS_WITH_DETAILS'
bpy.data.scenes["Scene"].blosm.relativeToInitialImport = True
divide_area(min_lat, max_lat, min_long, max_long, area_size_km)
```

I tried running the code on workstation using the command 
`

> ./blender --background --python /home/hitesh/3d_tiles/tiles_script.py

`
first few lines of the code is giving a warning 


> WARN (bgl): source/blender/python/generic/bgl.c:2660 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.

Then it is returning an error while importing the google 3d tiles
```
Error: No 3D tiles were imported. 0 errors occured during the import. See the System Console.
Error: Python: Traceback (most recent call last):
  File "/home/hitesh/3d_tiles/tiles_script.py", line 38, in <module>
    divide_area(min_lat, max_lat, min_long, max_long, area_size_km)
  File "/home/hitesh/3d_tiles/tiles_script.py", line 26, in divide_area
    bpy.ops.blosm.import_data()
  File "/opt/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: No 3D tiles were imported. 0 errors occured during the import. See the System Console.

Blender quit
```

Locally, I have added the blosm addon manually and then tried running the rest part of the script which was running well. I am confused what is causing the problem. Do we need to resolve the warning before moving forward ?

**Comment by vvoovv** [comment]
A quick view on your script revealed an error.

`bpy.data.scenes["Scene"].blosm.maxLong` should be replaced with `bpy.data.scenes["Scene"].blosm.maxLon`, i.e. no `g` at the end.

**Comment by HITESH2002-JAIN** [comment]
Thanks @vvoovv. It has solved the problem.
