### ISSUE TITLE
Google tiles

### ISSUE THREAD

**Issue by odds57** [vvoovv/blender-geo#415]
Google tiles: Unable to process the root URI of the3D Tiles. HTTP error403: Forbidden
I have an API.
Terrain is OK from import Terrain. I live i Oslo, but I get the same error when try to open av place in Rome, Italy.

How do I solve this?

**Comment by vvoovv** [comment]
Please see the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
