### ISSUE TITLE
Exported 3D Google Tiles Display in Black and White: Texture Issue

### ISSUE THREAD

**Issue by HITESH2002-JAIN** [vvoovv/blender-geo#416]
I have imported google 3d tiles for a specific region of berlin using blosm addon. 
![Screenshot from 2023-11-10 11-03-54](https://github.com/vvoovv/blosm/assets/76439813/11821935-5f2e-409f-b175-424e2175592d)

I've taken the following steps to export the region in point cloud format:
1. Clicked on 'Export Ready' and selected the 'Replace Materials' option.
2. Saved the Blender file after making these changes.
3. Unpacked all the textures used in the project.
4. Attempted to export the file in PCD format.
5. Opened the exported PCD file in an online 3D viewer.

However, the resulting 3D image lacks textures; it appears entirely black and white. The issue persists across different export formats(.ply, .obj).
Link to PCD file: [https://drive.google.com/file/d/1tCaJAHNd0orT337d_DjlvpVEjHAyLGtf/view?usp=sharing](url)

**Comment by vvoovv** [comment]
Sorry, PCF format is not among the default export formats supported by Blender.

Please try exporting to FBX.

**Comment by HITESH2002-JAIN** [comment]
I tried that but it is not exporting textures. How to export 3d file along with textures ?

**Comment by vvoovv** [comment]
Please follow the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation and double check every step.
