### ISSUE TITLE
Exporting Google 3D Tiles - Texture-less FBX

### ISSUE THREAD

**Issue by MWH-VDC** [vvoovv/blender-geo#420]
Hello!

I have a google maps 3d tile api key. I am able to import into blender with Blosm the area I am focusing on, with full textures.

However when I export to FBX and import this into Twinmotion, the entire file is textureless and a beige.

Screenshots provided.

Thanks for your help!

![screenshot 1](https://github.com/vvoovv/blosm/assets/150946315/580145d8-2145-4e88-bc52-89c8d3419141)
![screenshot 2](https://github.com/vvoovv/blosm/assets/150946315/2b869b10-5d75-4209-a00e-371e96803ae1)
 color

**Comment by vvoovv** [comment]
Hi @MWH-VDC

Please refer to the section "Export and Custom Materials" of the [documentation](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials).

**Comment by MWH-VDC** [comment]
As of the latest update I am having this error again. and I have followed the steps perfectly @vvoovv

**Comment by MWH-VDC** [comment]
@vvoovv
