### ISSUE TITLE
Using google 3d tiles will output only flat surface

### ISSUE THREAD

**Issue by Straxx69** [vvoovv/blender-geo#422]
I'm having an issue that google 3d tiles will output only a flat surface. I looked up [https://developers.google.com/maps/coverage](url) and it shows that the country (Slovenia) is covered. So I did some initial testing in the capital city to see if I can use it for my project. Then I tried exporting the tiles in another city that's roughly 25km away from the capital city and it will not generate buildings. Does this mean there's no 3d data for this area, or am I missing something? The location in question is Grosuplje, Slovenia.

In case I can't use 3D tiles, what would be second best option?

**Comment by vvoovv** [comment]
Hi @Straxx69 

Unfortunately Google Maps do not provide 3D content for your of interest (Grosuplje). Please read the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) of the documentation on how to see the the exact borders of the areas covered with the 3D content.

**Comment by vvoovv** [comment]
You can import OpenStreetMap data for your area of interest.
