### ISSUE TITLE
3D tiles without textures

### ISSUE THREAD

**Issue by Mitko88** [vvoovv/blender-geo#424]
I get 3D tiles without textures. I use Blender 4.0.
![image](https://github.com/vvoovv/blosm/assets/8992310/f3002207-3c01-40cc-a60c-0399f741bdce)

**Comment by vvoovv** [comment]
Hi @Mitko88 

Please refer to the section [Basic Usage](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#basic-usage) of the documentation on how to change the _Viewport Shading_.
