### ISSUE TITLE
Google Maps 3D tiles 

### ISSUE THREAD

**Issue by bsm3285** [vvoovv/blender-geo#427]
![1111111111111111](https://github.com/vvoovv/blosm/assets/152702400/016bb69c-4ec0-4cce-bc0c-df828670c229)

![1111111111111111](https://github.com/vvoovv/blosm/assets/152702400/d17923f5-0c08-4e5c-9b2d-cbbcace68af2)
I used Google Maps 3D tiles, but the buildings are not appearing in 3D. (blender 4.0)

**Comment by vvoovv** [comment]
Hi @bsm3285

Please read the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) of the documentation on how to see the exact borders of the areas with the 3D content (buildings, trees).
