### ISSUE TITLE
Can't bring Any buildings. All i see is a gray floor...

### ISSUE THREAD

**Issue by sy990123** [vvoovv/blender-geo#429]
Hi, i really need your help.
I bought premium version, and Open street map works very well.
And I solved the issue about API key. there is no error message.
but I can't bring any buildings. All i can see in my screen is a gray floor.
I don't know what to do.
please help me

![20231208_230050](https://github.com/vvoovv/blosm/assets/153297008/19b035d5-9d36-43dd-a909-f05c1c162067)

**Comment by vvoovv** [comment]
Hi @sy990123 

Please read in the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) of the documentation how to find, if your area of interest is covered with the 3D content (building, trees).
