### ISSUE TITLE
Area imported is an order of magnitude more than was selected

### ISSUE THREAD

**Issue by lucaspereirasuarez** [vvoovv/blender-geo#432]
Using the selection tool, I selected an area approximately 0.1x0.2km. When this was imported to Blender with Google 3D Tiles, the area was something closer to 2x3km, encompassing a decent chunk of a city, instead of a few buildings. Token was double checked, and the import was done using Blender 4.0. Denver is given as an example of this, as Google lists it as a city with this data.

![screenshotfromselection](https://github.com/vvoovv/blosm/assets/118428973/500bee35-de1e-422b-b93d-23990c8750b8)
![screenshotfromblender](https://github.com/vvoovv/blosm/assets/118428973/ea56be50-d824-492d-9c61-2f3f682e85ce)

**Comment by vvoovv** [comment]
Hi @lucaspereirasuarez 

That issue is mentioned in the Warning section of the documentation:
https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#warning

Google Cloud return a significant number of 3D Tiles beyond the requested area of interest.
