### ISSUE TITLE
"None Type" has not attribute "Name" when import my building type (None-buildify)

### ISSUE THREAD

**Issue by ta2x30** [vvoovv/blender-geo#434]
I received the error mentioned in the title when trying to import my own building. I am looking for guides how to structure my blend file appropriately for OSM import. Thanks.

Anh

**Comment by vvoovv** [comment]
Please paste some screenshot that would help to reproduce the problem.

**Comment by ta2x30** [comment]
<img width="661" alt="Screenshot 2023-12-15 at 12 47 02 PM" src="https://github.com/vvoovv/blosm/assets/44478995/a2ee0907-7a63-4abc-a4c7-071670a9505a">

I don't have much of a screenshot of the import per se, except the error I mentioned. But attached is the 3D Blender I am trying to populate the city with. In fact, my ultimate objective is to selectively modify the city scape with different types of buildings, not just with Buildify. Any suggestions of how to do that would be appreciated.

**Comment by vvoovv** [comment]
Sorry, we can't provide support for this task.
