### ISSUE TITLE
How to automatically separate each tile into an object that has only one material?

### ISSUE THREAD

**Issue by massimovendola** [vvoovv/blender-geo#435]
When importing tiles, even if they aren't joined automatically after import, some of the tiles have two materials or even three on a single object. Is there a way to automate separating each so that each object only has one material?

I use the following script to separate the tiles joined tiles by material, but it takes a really long time to process.

> import bpy
> 
> for obj in bpy.context.selected_objects:
>     for slot in obj.material_slots:
>         mat = slot.material
>         if mat is not None:
>             bpy.ops.object.select_all(action='DESELECT')
>             obj.select_set(True)
>             bpy.context.view_layer.objects.active = obj
>             bpy.ops.object.material_slot_select()
>             bpy.ops.mesh.separate(type='MATERIAL')

Is there another way to do this faster?

**Comment by vvoovv** [comment]
Hi @massimovendola 

There are a number of tutorials on Youtube on how to bake multiple materials into a single texture map. For example, https://www.youtube.com/watch?v=wG6ON8wZYLc
