### ISSUE TITLE
Importing Ocean Tiles from OpenStreetMaps

### ISSUE THREAD

**Issue by jarvisar** [vvoovv/blender-geo#437]
When importing from OpenStreetMaps, I make sure "Import Water Objects" is checked, yet no ocean tiles are ever imported. Only lakes and rivers. Normally I would just remove all parts of the terrain below sea level, but for some reason it appears ocean terrain is higher than sea level.

Vancouver:
![blender_g4mgJAYToJ](https://github.com/vvoovv/blosm/assets/55147029/aba06cd8-e755-4a4a-8639-966d9f494477)
Includes Lost Lagoon in Stanley Park (upper left corner) but does not include ocean tiles.

**Comment by jarvisar** [comment]
For a potential workaround:

1. Remove Shrinkwrap modifier from coastlines and add Solidify with a small thickness 
2. Extrude down to intersect with the terrain where water meets land
3. Add a Boolean modifier to the terrain targeting the coastlines, then apply it to cut the terrain into two parts
4. Enter "Edit" mode for the terrain and select all the vertices; press P to open separate menu and select "by Loose Parts"
5. The ocean terrain should be split to a separate mesh; from here I personally delete it

![blender_lrKmUPvNzk](https://github.com/vvoovv/blosm/assets/55147029/2e5222a9-4761-432f-a96e-364ff7a53b7b)

**Comment by jarvisar** [comment]
For a potential workaround:

1. Remove Shrinkwrap modifier from coastlines and add Solidify with a small thickness 
2. Extrude down to intersect with the terrain where water meets land
3. Add a Boolean modifier to the terrain targeting the coastlines, then apply it to cut the terrain into two parts
4. Enter "Edit" mode for the terrain and select all the vertices; press P to open separate menu and select "by Loose Parts"
5. The ocean terrain should be split to a separate mesh; from here I personally delete it

![blender_lrKmUPvNzk](https://github.com/vvoovv/blosm/assets/55147029/2e5222a9-4761-432f-a96e-364ff7a53b7b)

**Comment by vvoovv** [comment]
Hi @jarvisar 

You seemingly found it out yourself that oceans and seas are mapped as coastlines in OpenStreetMap rather than areas.

Great that you proposed a workaround.
