### ISSUE TITLE
Export OSM to .fbx does not include textures

### ISSUE THREAD

**Issue by lijecaru** [vvoovv/blender-geo#438]
I imported the map following the procedure [here](https://github.com/vvoovv/blosm/wiki/Premium-Version#export-of-the-imported-scene). But the .fbx file does not include textures. I am using Blender 4.0 and got the premium version of the add-on.

**Comment by vvoovv** [comment]
Hi @lijecaru 

Please attach some screenshot to illustrate your problem.

**Comment by lijecaru** [comment]
This is how the buildings look in Blender:
![blender_full](https://github.com/vvoovv/blosm/assets/9829633/d0b277aa-408f-4d88-8fc4-b19f3d99bd5f)

I export as fbx and get the following:
![blankblender](https://github.com/vvoovv/blosm/assets/9829633/bfb2061d-aa97-4324-b5e0-4a6e22bcc4a6)

If I "unwrap" each surface, the texture gets applied and is exported in the 3D object, but the dimensions of the texture get distorted. Plus, I would prefer not to do this for each individual surface.

**Comment by vvoovv** [comment]
Please refer to the documentation on how to export an imported OpenStreetMap scene:
https://github.com/vvoovv/blosm/wiki/Premium-Version#export-of-the-imported-scene

**Comment by lijecaru** [comment]
I followed those instructions, I specified it in the first message in this thread.

**Comment by vvoovv** [comment]
Please check that both options are checked:

* `Enable experimental features` at the bottom of the addon preferences:
![image](https://github.com/vvoovv/blosm/assets/613295/2c42da21-fdeb-4e6a-a2e5-19fc35d9f2a7)
* `Import for export` on the addon panel:
![image](https://github.com/vvoovv/blosm/assets/613295/5d1cb75e-1b57-4ec6-a57c-b80f6355327d)

Then try importing your exported FBX file back to Blender.

**Comment by lijecaru** [comment]
I have followed the required steps. Blender can open the .fbx file and show the textures (Material preview). But other programs (Unreal Engine) cannot. However, if I individually apply textures to the surfaces, they appear in the exported fbx file. How can I debug this? Or this doesn't work for importing to other programs?

**Comment by vvoovv** [comment]
> How can I debug this?

Is there anything in the log window of Unreal Engine?
