### ISSUE TITLE
Textures are not exported in the correct order to dae file

### ISSUE THREAD

**Issue by fredmarkus** [vvoovv/blender-geo#439]
I have built a workflow where I import data from Google 3D tiles and then export both an stl and a dae file. For the dae file, I follow the workflow provided in the wiki. 
1. I select the tile ` bpy.data.objects['Google 3D Tiles'].select_set(True)`
2. I set export-ready `bpy.context.scene.blosm.replaceMaterialsWith = 'export-ready'`
3. I replace the materials. `bpy.ops.blosm.replace_materials()`
4. I save the dae using collada_export. `bpy.ops.wm.collada_export(args)`. 

I had to change the invoke() function to an execute() in the function class BLOSM_OT_ReplaceMaterials(bpy.types.Operator) in order to use it in code, as otherwise I would receive an invalid operator error. When I do this and then load the dae, I see that the mesh does not match the overlay. 

![image](https://github.com/vvoovv/blosm/assets/80588263/ea99c33d-7c6c-4a10-b401-a1b2160f729f)

My question is now: 
Is there a different way to replace the materials using code? Or is there something else I am doing incorrectly. 

Thanks

**Comment by vvoovv** [comment]
Hi @frede791 

Please try to it manually via GUI. Will it work?

**Comment by fredmarkus** [comment]
Yes. This works. However, it is not a viable solution for me. Is there a way to run the material_replace function in code? As far as my understanding goes, the current implementation is only meant to be clicked in the GUI.

**Comment by vvoovv** [comment]
Try exporting it to FBX. Will it work?

**Comment by fredmarkus** [comment]
You mean using the gui or the API? I don't think my issue is the export to dae, but rather the material replacement?

**Comment by vvoovv** [comment]
The material replacement works ok via API as I can see.

**Comment by fredmarkus** [comment]
Based on the picture above? Or based on the function provided for material replacement?

**Comment by vvoovv** [comment]
How can the problem be reproduced? Please provide the detailed instruction.

**Comment by fredmarkus** [comment]
you may require a google 3D tiles api key as well as the blosm.zip in the same directory as the code below. 
Here is the script i use to generate my meshes and textures:

```
API_KEY = <YOUR_KEY>

    parser = argparse.ArgumentParser(description='Map creation using Blender')

    parser.add_argument('--name', help='Name of the world', required=True)
    parser.add_argument('--coordinates',nargs='+', help='Corner points of the map in order W, S, E, N', required=True)
    parser.add_argument('--world_store', help='Path to world storage directory', required=False)
    parser.add_argument('--lod', help='Level of detail for map', required=False, default="lod3")
    parser.add_argument('--data_type', help='Data type for map', required=False, default="osm")

    args = parser.parse_args()
    args.coordinates = [float(elem) for elem in args.coordinates[0].split(',')]

    # Set up environment variables to look for models for simulation
    args.world_store = os.path.expanduser(args.world_store)

    # Generate stl file folder
    if not os.path.exists(f'{args.world_store}/{args.name}') or not os.path.exists(f'{args.world_store}/{args.name}/materials'):
        os.makedirs(f'{args.world_store}/{args.name}/materials')


    # Enable blosm addon
    bpy.ops.preferences.addon_install(overwrite=False, filepath="./blosm.zip")
    bpy.ops.preferences.addon_enable(module="blosm")

    bpy.context.preferences.addons["blosm"].preferences.googleMapsApiKey = API_KEY
    bpy.context.preferences.addons["blosm"].preferences.dataDir = '/home/fremarkus/blender/street_maps'

    # Specify coordinates of corner points
    bpy.context.scene.blosm.maxLat = args.coordinates[3]
    maxLat = bpy.context.scene.blosm.maxLat

    bpy.context.scene.blosm.minLat = args.coordinates[1]
    minLat = bpy.context.scene.blosm.minLat

    bpy.context.scene.blosm.maxLon = args.coordinates[2]
    maxLon = bpy.context.scene.blosm.maxLon

    bpy.context.scene.blosm.minLon = args.coordinates[0]
    minLon = bpy.context.scene.blosm.minLon

    bpy.context.scene.blosm.lodOf3dTiles = f'lod{args.lod}'
    bpy.context.scene.blosm.join3dTilesObjects = True
    bpy.context.scene.blosm.relativeToInitialImport = True
    bpy.context.scene.blosm.gpxProjectOnTerrain = False
    bpy.context.scene.blosm.terrainPrimitiveType = "triangle"
    bpy.context.scene.blosm.materialType = "fo"
    bpy.context.scene.blosm.osmServer = "vk maps"
    bpy.context.scene.blosm.railways = True
    bpy.context.scene.blosm.dataType = args.data_type

    # Replace materials with export ready materials
    bpy.context.scene.blosm.replaceMaterialsWith = 'export-ready'

    # Integrate Google 3d TIles
    bpy.ops.blosm.import_data()

    bpy.data.objects['Google 3D Tiles'].select_set(True)
    bpy.ops.blosm.replace_materials()

    # Save blender file
    if args.data_type == 'google-3d-tiles':
        bpy.ops.wm.save_mainfile(filepath=f'/home/fremarkus/blender/street_maps/{args.name}.blend')
        bpy.ops.file.unpack_all(method='USE_LOCAL')

    # bpy.ops.object.select_all(action='SELECT')

    # Export mesh to stl
    bpy.ops.export_mesh.stl('INVOKE_DEFAULT',filepath=f"{args.world_store}/{args.name}/materials/{args.name}.stl",check_existing=False,global_scale=1)
    
    if args.data_type == 'google-3d-tiles':
        bpy.ops.wm.collada_export(filepath=f"{args.world_store}/{args.name}/materials/{args.name}.dae",check_existing=False,export_mesh_type_selection="view",use_texture_copies=True)

    # Move images to correct folder
    if args.data_type == 'google-3d-tiles':
        os.system(f'cp /home/fremarkus/blender/street_maps/textures/* {args.world_store}/{args.name}/materials/ -r')

    # Determine altitude of location and center of map
    c_lat = (minLat + maxLat)/2.
    c_lon = (minLon + maxLon)/2.

    # Make request for altitude
    if args.data_type == 'google-3d-tiles':
        base_url = 'https://maps.googleapis.com/maps/api/elevation/json'
        response = response = requests.get(f'{base_url}?locations={c_lat},{c_lon}&key={API_KEY}')

    if args.data_type == 'osm':
        c_elevation = 0

    if args.data_type == 'google-3d-tiles':
        c_elevation = response.json()['results'][0]['elevation']

    # Generate correct sdf file
    os.system(f'cp /home/fremarkus/auterion/simulation-gazebo/world_template.sdf {args.world_store}/{args.name}/{args.name}.sdf')

    with open(f'{args.world_store}/{args.name}/{args.name}.sdf', 'r') as file:
        filedata = file.read()
        file.close()

    filedata = filedata.replace('#ELEVATION#', str(c_elevation))
    filedata = filedata.replace('#NAME#', args.name)

    with open(f'{args.world_store}/{args.name}/{args.name}.sdf', 'w') as file:
        file.write(filedata)
        file.close()
        
```

I then use the meshes in the Gazebo simulator. This is where the screenshot originated from.

**Comment by vvoovv** [comment]
What are the coordinates of your area of interest? What was the resolution?

**Comment by fredmarkus** [comment]
I used these coordinates: 8.51548,47.36380,8.51938,47.36633 representing the corner points of the area of interest. 
Resolution is set at lod3. For the code above this just means providing 3. 
The arguments are as follows: `--name any --coordinates=8.51548,47.36380,8.51938,47.36633 --lod 3 --data_type google-3d-tiles`

**Comment by vvoovv** [comment]
I tried exporting your area of interest to Collada and it worked well.

Sorry, we don't have resource to help you with debugging your script.

**Comment by fredmarkus** [comment]
Did you use the use export-ready materials? Did you use the GUI or the API?

**Comment by vvoovv** [comment]
GUI, exported-ready materials, unpacking textures.

**Comment by fredmarkus** [comment]
What speaks against providing an execute function in the `BLOSM_OT_ReplaceMaterials(bpy.types.Operator)` class? I don't currently see a way to replace materials cleanly using the api

**Comment by vvoovv** [comment]
Call it this way:
```python
bpy.ops.blosm.replace_materials("INVOKE_DEFAULT")
```

**Comment by fredmarkus** [comment]
I have tried this. I throws an error for me:

`ERROR (wm.operator): source/blender/windowmanager/intern/wm_event_system.cc:1554 wm_operator_invoke: invalid operator call 'BLOSM_OT_replace_materials'`

**Comment by fredmarkus** [comment]
Ok. It appears that my texture models was messed up. I managed to resolve my issue by cleaning up. Below a screenshot of the result:
![image](https://github.com/vvoovv/blosm/assets/80588263/cb9c9961-cbe0-4ad1-a8be-4c29afeb05b5)

Thanks for your help! I would still consider enabling replace_materials in the API by providing an execute function.
