### ISSUE TITLE
Invalid string to paste

### ISSUE THREAD

**Issue by desmondlorenzini** [vvoovv/blender-geo#440]
![image](https://github.com/vvoovv/blosm/assets/115326797/972711b0-8580-429e-93e3-4b66cfb56ffb)
 I have copy and pasted my api key like 5 times now. I have map tiles enabled. Why isn't it working?

**Comment by vvoovv** [comment]
Hi @desmondlorenzini 

Please show a screenshot of the addon settings. I'd like to see the directory for the addon data.

**Comment by desmondlorenzini** [comment]
[image: image.png]

**Comment by vvoovv** [comment]
> [image: image.png]

No image was attached. Please reply from the web-browser.

**Comment by desmondlorenzini** [comment]
Oops, sorry about that. Here you go: 
![image](https://github.com/vvoovv/blosm/assets/115326797/308f40ab-f637-46e1-a99b-0033284472bf)
And just incase that didn't work here's the file:
![Untitled](https://github.com/vvoovv/blosm/assets/115326797/5419414a-b5fa-4685-b334-54fe2c0c64a5)

**Comment by vvoovv** [comment]
Could you please show the content of the directory `C:\CityExports\Exports\3d_tiles\google`?

**Comment by desmondlorenzini** [comment]
![image](https://github.com/vvoovv/blosm/assets/115326797/51f91cdb-278b-4d47-9863-315893c293b5)

**Comment by vvoovv** [comment]
Could you try a totally different directory for the addon data instead of the current one:

![image](https://github.com/vvoovv/blosm/assets/613295/60f8b838-ae38-4a13-8cbe-50de65899a57)

**Comment by desmondlorenzini** [comment]
Didn't work. I put it in the downloads folder.
![image](https://github.com/vvoovv/blosm/assets/115326797/991fa793-dc49-4ae5-b2da-7836ad1f4bef)

**Comment by vvoovv** [comment]
The reason for that problem is not yet clear for me. Let's try to debug it.

* Open the folder `threed_tiles` in the directory marked below.

![image](https://github.com/vvoovv/blosm/assets/613295/e0e57398-454d-439c-9344-1133fbef2464)

* Temporarily rename the file `manager.py` in the folder `threed_tiles`.

* Extract the file `manager.py` from the zip-archive [manager.zip](https://github.com/vvoovv/blosm/files/13858937/manager.zip) to the folder `threed_tiles`.

* Restart Blender

* Paste the content of Blender's console with errors after an unsuccessful import.

**Comment by desmondlorenzini** [comment]
![image](https://github.com/vvoovv/blosm/assets/115326797/54e7c121-14a4-4633-b7c9-a9b91c3e09da)

**Comment by vvoovv** [comment]
The actual description of the error is at the very end of this long error message. Please find it and paste it here.

**Comment by desmondlorenzini** [comment]
Could it be the fact that I'm on blender 2.90? 
![image](https://github.com/vvoovv/blosm/assets/115326797/a4fdbeb4-282c-4a11-b1e9-3ff081642c6d)

**Comment by vvoovv** [comment]
I think you have found the cause of the problem. Blender's built-in glTF importer can't import Google 3D Tiles in the earlier versions of Blender. Please install the latest stable version of Blender.

**Comment by desmondlorenzini** [comment]
Ah I see. Thanks so much for all the help.
