### ISSUE TITLE
Roads and Bridges not Importing Correctly

### ISSUE THREAD

**Issue by johnm21-creator** [vvoovv/blender-geo#442]
I did read the other thread with someone having similar issues but I cannot seem to resolve this. I am importing roads and bridges using openstreetmap. I tried just importing using 3D simple and 3D realistic on separate occasions and this happens on the 3D simple version, nothing is imported for roads and paths on the realistic version. The simple version seems to just import lines that follow the terrain, no actual bridges show up. As shown in the photo below, this is downtown pittsburgh. There should be around 9 bridges in this, but they're just showing up as lines across the river. Am I messing up on the import somehow? I followed along with a few tutorials and keep getting the same result. 

I'm using Mapbox.

![Screenshot 2024-01-09 162938](https://github.com/vvoovv/blosm/assets/156136304/4608a8f9-4669-4ce0-ad3c-4c6e61b72806)
![Screenshot 2024-01-09 163036](https://github.com/vvoovv/blosm/assets/156136304/0d2749ff-0455-4796-a4fa-9c6a7ca2ec10)
![Screenshot 2024-01-09 163059](https://github.com/vvoovv/blosm/assets/156136304/a843d00c-d49d-43af-a46b-a035c0d9148a)

**Comment by vvoovv** [comment]
Hi @johnm21-creator 

You are right, no real bridges are imported at the moment. We are busy with generating realistic streets, but that's a very complex task.
