### ISSUE TITLE
Issue after pressing import i sent images 

### ISSUE THREAD

**Issue by Sutnaar** [vvoovv/blender-geo#444]
Please help with this issue, google cloud is currently down idk if that could be the case. ty for help

![photo_5836976644391290777_w](https://github.com/vvoovv/blosm/assets/156366946/8aaa73e2-2e9b-4ea9-936c-7c2bcaa3a3e9)
![photo_5836976644391290773_x](https://github.com/vvoovv/blosm/assets/156366946/3f2eb53a-af54-4c0e-8ff4-3df42db25cc2)

**Comment by vvoovv** [comment]
Hi @Sutnaar 

Please update the addon. More details can be found at #443

**Comment by Sutnaar** [comment]
Thank you very much, I also had a question, If i buy the premium version,
do i get the same results as 3D tiles?


čt 11. 1. 2024 v 21:41 odesílatel vvoovv ***@***.***> napsal:

**Comment by vvoovv** [comment]
Probably I didn't understand your question.

Import of Google 3D Tiles is also a part of the premium version.
