### ISSUE TITLE
No 3D tiles were imported. 1 errors occured during the import. See the System Console.

### ISSUE THREAD

**Issue by MWH-VDC** [vvoovv/blender-geo#445]
All of a sudden I now get this error when trying to use Blosm:

No 3D tiles were imported. 1 errors occured during the import. See the System Console.

My billing information is up to date. Everything for the Maps API is enabled.

**Comment by vvoovv** [comment]
Hi @MWH-VDC 

Please update the addon. More information can be found at #443

**Comment by MWH-VDC** [comment]
Thank you so quickly updating the addon and fixing the problem!
