### ISSUE TITLE
Texture-less FBX - Since Update 

### ISSUE THREAD

**Issue by MWH-VDC** [vvoovv/blender-geo#446]
Same issue as https://github.com/vvoovv/blosm/issues/420

I followed the instructions perfectly, when exporting the FBX from blender and importing into twinmotion or maya, it is completely blank,.

In twin motion it is looking for the referenced materials but they all show up white.

**Comment by vvoovv** [comment]
Hi @MWH-VDC 

Please try importing your FBX file back to Blender.

**Comment by MWH-VDC** [comment]
Same thing happens

**Comment by JMarshQPK** [comment]
I tried to get any file type to export from Blender with materials. I finally got .glb (GLTF binary) to work in TwinMotion.

**Comment by vvoovv** [comment]
@MWH-VDC 

Please double check that you don't miss a single step from the [documentation](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials).

**Comment by MWH-VDC** [comment]
> I tried to get any file type to export from Blender with materials. I finally got .glb (GLTF binary) to work in TwinMotion.

GLB Worked. and then GLB to Paint 3D to FBX worked to get it into Maya...

However Microsoft changed Paint3d and took away the FBX exporter. sooo You need an older version of Paint 3D...
you can get an earlier version of paint3D from here: https://www.filehorse.com/download-paint-3d/old-versions/ i recommend version 6.2004.20027


@vvoovv I made sure, I'm wondering if the recent changes with Google tiles caused this. Because I was daily doing this without error until they updated.

**Comment by vvoovv** [comment]
@MWH-VDC 

Just checked export to FBX with subsequent import back to Blender. It worked for me as usual.

You can make a video screenshot of your actions.

**Comment by MWH-VDC** [comment]
I get the data from the google tiles. I make sure the file is saved where I want it. 
I unpack the resources according to the tutorial in the same directory.
I then export.

Still coming out white when I re-import.

![image](https://github.com/vvoovv/blosm/assets/150946315/d206b051-2b33-4b9c-aeb1-90062b9a168b)

![image](https://github.com/vvoovv/blosm/assets/150946315/93b9f3b8-4743-4d96-80cd-de31a61e25d6)

**Comment by vvoovv** [comment]
@MWH-VDC 

Did you also press the button _Replace Materials_ on the addon panel?

**Comment by MWH-VDC** [comment]
> @MWH-VDC
> 
> Did you also press the button _Replace Materials_ on the addon panel?

That was it!
