### ISSUE TITLE
Google 3D tiles is not working for some reason.

### ISSUE THREAD

**Issue by Unixety** [vvoovv/blender-geo#448]
![Screenshot (238)](https://github.com/vvoovv/blosm/assets/120604636/9585a4c1-2be9-4fd3-b6c3-2a92c37d7e69)
I don't know why this is showing up like this.

**Comment by vvoovv** [comment]
Hi @Unixety 

Please try restarting Blender.

**Comment by Unixety** [comment]
in what way?

**Comment by vvoovv** [comment]
Please close Blender and open it again.

**Comment by Unixety** [comment]
it works now thanks!
