### ISSUE TITLE
Tiles not loading corectly in fbx when export

### ISSUE THREAD

**Issue by Alohapendeho** [vvoovv/blender-geo#450]
![3ds max test import fain](https://github.com/vvoovv/blosm/assets/156465160/c930334b-f607-46f8-91df-3321265522ed)
Hello, I tried to export with textures the Google 3d Tiles, but when I open them in Another program such as 3D Studi Max the textures are not correctly assembled. Is there any way this can be fixed?
Moreover, even if I select a smaller region in BLOSm and paste the coordinate intro the add-on the program brings out more data. Is there a solution for this problem

**Comment by vvoovv** [comment]
What version of Blender are you using?

**Comment by Alohapendeho** [comment]
3.6

**Comment by vvoovv** [comment]
Export of a large scene can be tricky.

I suggest trying an export of a smaller scene.

**Comment by Alohapendeho** [comment]
I tried to make the rectangle 1x1 but it still imported the entire site. What do you recommend? How can I import a smaller scene?

**Comment by vvoovv** [comment]
Try a smaller resolution. 1x1 km with the maxim resolution will result in a quite large scene.

It isn't possible to influence what Google outputs for the given area.
