### ISSUE TITLE
No 3D tiles were imported. 1 errors occured during the import. See the System Console.

### ISSUE THREAD

**Issue by Tarasmakarov2003** [vvoovv/blender-geo#451]
When I try to import a Google Tiles map, the following error appears.
![image](https://github.com/vvoovv/blosm/assets/156532067/384ffe29-cce2-496d-8204-f57705a4775f)
 the console writes the following.
![вопрос](https://github.com/vvoovv/blosm/assets/156532067/6282cc74-0860-4317-b79f-eb4c884e4021)

the collection of google 3d tiles also appears, but is empty
![image](https://github.com/vvoovv/blosm/assets/156532067/ae816c86-4617-4c3b-a417-97774f702412)

I've already tried reinstalling the plugin, updating the blender, maybe it's a problem with the key, but what should I do then?

**Comment by vvoovv** [comment]
Please install the latest version of the addon (currently 2.7.3). More details can be found at #443.
