### ISSUE TITLE
Google 3D Tiles (Buildings with more details) empty layer & viewport

### ISSUE THREAD

**Issue by ZPeladeau** [vvoovv/blender-geo#454]
<img width="302" alt="Screenshot 2024-01-21 at 1 53 30 PM" src="https://github.com/vvoovv/blosm/assets/157323185/92590a0b-3e64-408b-a3ff-94ee5ee17956">

When clicking import I get the an empty layer of the Google 3D Tiles although nothing appears under it to edit neither on the main viewport as I would get with any other selection of setting. 

Thanks for helping.

**Comment by vvoovv** [comment]
Hi @ZPeladeau 

There must be an error message. Please paste a screenshot of the error.

**Comment by ZPeladeau** [comment]
<img width="1728" alt="Screenshot 2024-01-22 at 12 54 08 AM" src="https://github.com/vvoovv/blosm/assets/157323185/1b9a930f-2e83-4936-8213-e413f74daaec">

All I have is this, I am fairly new to Blender where can I find the error messages... I searched Youtube and Google and I can't seem to get anything. Thank you

**Comment by vvoovv** [comment]
Please start Blender from the terminal as described [here](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/macos.html) and perform an import.

Please paste here the output in the terminal.

**Comment by ZPeladeau** [comment]
The error message is popping up for the first time,
![Uploading Screenshot 2024-01-25 at 7.50.46 PM.png…]()

**Comment by ZPeladeau** [comment]
<img width="1728" alt="Screenshot 2024-01-25 at 7 50 46 PM" src="https://github.com/vvoovv/blosm/assets/157323185/ba1ef8b6-b58f-40b9-8c76-73e7987504f6">

**Comment by vvoovv** [comment]
Please show a screenshot of your addon settings. In particular I'd like to see what was entered in the field `Google 3D Tiles Key`.

You can send the screenshot to prokitektura+support@gmail.com
