### ISSUE TITLE
Loading multiple maps at the same time

### ISSUE THREAD

**Issue by fredmarkus** [vvoovv/blender-geo#455]
Hello,

I am currently trying to parallelize the loading of multiple osm tiles. I run into an issue that the filepath is used by several tiles simultaneously. I have looked at the source code and identified the `downloadOsmFile` as the culprit as it seems to assign the name based on an incrementing counter. My idea would be to add an optional argument through which you can set a custom name. If you think this could be useful I can make a PR to add this?

![Screenshot from 2024-01-22 14-16-45](https://github.com/vvoovv/blosm/assets/80588263/857fef2d-3adc-4062-b397-78d7a8579e81)

**Comment by vvoovv** [comment]
Hi @frede791 

Import of files with a custom name is already supported:
![image](https://github.com/vvoovv/blosm/assets/613295/592370a9-43c3-4f77-bf4a-543213bd376c)

One needs to select `file` instead of `server` in the field `Import from:` and then set a path to the OSM file.

**Comment by fredmarkus** [comment]
I'm not sure this is the use case I have? My idea is to parallelize the download from a server directly. So i run the `import_data` function that downloads the osm map from a server and this imports with a fixed name based on the counter. This doesn't work for me as I want to run the import_data function for lots of tiles simultaneously and to my understanding the counter stops this from happening.

**Comment by vvoovv** [comment]
A possible solution would be to download the required files with a custom script and then import them with the existing addon code.

**Comment by fredmarkus** [comment]
The additional overhead from downloading, importing and arranging the tiles in blender is not worth it in my opinion. I have made minor extensions to the source code to enable the functionality I need. If you feel that this would be useful, I can make a PR?

**Comment by vvoovv** [comment]
What does the extension do?

**Comment by fredmarkus** [comment]
Enables custom name support when downloading terrain data or osm tiles. What kind of formatter do you use? When I try to save my git changes I seem to change empty lines?

**Comment by vvoovv** [comment]
How is the custom name defined?

**Comment by vvoovv** [comment]
I need to understand if your solution is specific for your project or if it's a general-purpose.
