### ISSUE TITLE
Replace Materials button with export-ready. python error

### ISSUE THREAD

**Issue by AlexDmss** [vvoovv/blender-geo#456]
Hello,

I'm facing an issue with blender 4.0.2 and blosm addon. 
I'm trying to export a model generated by Google 3D tiles to get properly the textures. I'm following this process :[https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials]

However, when I click on "replace materials", the below error occurs:

```
Python : Traceback (most recent call last):
  File "C:\Users\dumaal01\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\gui\__init__.py", line 261, in invoke
    self.replaceWithExportReadyMaterials(context)
  File "C:\Users\dumaal01\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\gui\__init__.py", line 292, in replaceWithExportReadyMaterials
    templateMaterial.node_tree.nodes["Principled BSDF"].inputs['Base Color'],
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

```
Is there anyway to solve this issue ? 
Thanks for your help

**Comment by vvoovv** [comment]
Hi @AlexDmss 

Let's test the following. Select any mesh object and open the material tab. Delete all material slots. Press the `New` button.

![image](https://github.com/vvoovv/blosm/assets/613295/cffa8f66-2bec-4495-8b19-fb00a4d7cf00)

Please paste a screenshot of the geometry nodes for the material created after pressing the `New` button.

**Comment by AlexDmss** [comment]
Hello, thanks for your quick reply.

I'm quite new to blender so i hope this is what you expect.
![image](https://github.com/vvoovv/blosm/assets/158488460/0c17c6ba-7010-4b7a-b6a8-5c43473e3d9a)

**Comment by vvoovv** [comment]
This error can happen if a different language (non-English) is set in the Blender preferences. Please check this out.

**Comment by AlexDmss** [comment]
Right, this was set to french. After doing what you requested and setting Blender to English it works fine. Thank you very much !
