### ISSUE TITLE
Blender Blosm Error: "No 3D tiles were imported. 1 errors occured during the import. See the system Console"

### ISSUE THREAD

**Issue by coreplay7** [vvoovv/blender-geo#457]
I have been getting this issue in blender with blosm addon. 
"No 3D tiles were imported. 1 errors occured during the import. See the system Console"

![Screenshot 2024-02-03 175606](https://github.com/vvoovv/blosm/assets/158743247/75ea2b36-a018-4671-bc2f-551ed25febd2)

I have tried changing the API key, and this error still exists in blender 4.0 and blender 3.5

**Comment by vvoovv** [comment]
Please install the latest version (currently 2.7.4) of the Blosm addon. See also #443.
