### ISSUE TITLE
WinError 5 Access is denied

### ISSUE THREAD

**Issue by Kacsasrac** [vvoovv/blender-geo#458]
Hey,
I have the 2.7.4 blosm and 4.0.2 blender. After finishing your installation process I have problems importing.
Clicking the import button, it shows the following:
![image](https://github.com/vvoovv/blosm/assets/159020028/4e33f367-8537-4b93-b9a3-ad58b36ba868)
Cheers!

**Comment by Kacsasrac** [comment]
SOLVED: run blender as administrator

**Comment by vvoovv** [comment]
I'd recommend setting another folder for the addon data in the addon preferences. The folder should not require the administrator privileges.
