### ISSUE TITLE
Contribute to free version of code

### ISSUE THREAD

**Issue by fredmarkus** [vvoovv/blender-geo#459]
Hello,

Is there a way to contribute to the free version of the code? I cannot find a branch that contains the free version of the source code, only the premium version. Alternatively, I can make a PR to the dev branch directly but I would not know how exactly these changes would affect the premium version.

**Comment by vvoovv** [comment]
The branch [release](https://github.com/vvoovv/blosm/tree/release) is the one to send a PR. It contains the code for both base and premium versions. Basically, the main difference between the premium and the base versions is assets (facade textures) supplied with the premium version.

**Comment by fredmarkus** [comment]
Ok thanks. I have made a PR https://github.com/vvoovv/blosm/pull/460 with the ideas I previously brought up.
