### ISSUE TITLE
Problem: "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by DimiVellis** [vvoovv/blender-geo#461]
Hi, I am new in all this and i want help with this. I read all posts but i can't solve my problem.
![Screenshot_1](https://github.com/vvoovv/blosm/assets/159856381/c753491c-0182-443e-8017-b487a8b90103)

![Screenshot_2](https://github.com/vvoovv/blosm/assets/159856381/6a30eac5-ca4f-47d7-a287-d7492c1fcbee)

**Comment by vvoovv** [comment]
Hi @DimiVellis 

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
