### ISSUE TITLE
3d title map doesnt work

### ISSUE THREAD

**Issue by hilalbzky** [vvoovv/blender-geo#463]
Hı , I did everything right but blender is not responding when I press the import button. why is this happening? Can you help me

**Comment by vvoovv** [comment]
Please provide more details about the problem. Are there error messages? Some screenshots would be helpful.

**Comment by hilalbzky** [comment]
![IMG-20240216-WA0006](https://github.com/vvoovv/blosm/assets/159920149/3ff9a157-c198-4c4c-b504-e0212411c10d) 
it doesn't respond like this and can't add the map. I waited for so long but it still didn't happen anything.

**Comment by vvoovv** [comment]
@hilalbzky 

Please read the [Warning](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#warning) section of the documentation about the scene size at the maximum level of details.

**Comment by vvoovv** [comment]
Please begin with the import of your area of interest at a smaller level of details.

**Comment by vvoovv** [comment]
![blosm_2 7 6](https://github.com/vvoovv/blosm/assets/613295/5bc1e823-d19d-4d90-b08e-1f15bbf4bccd)

I hope you can now import exactly the desired rectangular area.

Please update the Blosm addon. The latest version of the addon is now 2.7.6.
