### ISSUE TITLE
No module named 'blosm-2' in Blander  2.83.2

### ISSUE THREAD

**Issue by FloksiPet** [vvoovv/blender-geo#464]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blosm-2'

for blender 2.83.20 tried many different versions. either these versions are for newer versions of blender, or give an error, or give not working. if possible give a link to a working version for my blender, or how to fix this error. Thanks.

**Comment by vvoovv** [comment]
Hi @FloksiPet 

Please get the addon from [here](https://prochitecture.gumroad.com/l/blender-osm) (the base version) or [here](https://prochitecture.gumroad.com/l/blosm) (the premium version).
