### ISSUE TITLE
Large import of Google 3D Tiles - optimization 

### ISSUE THREAD

**Issue by Raybalong** [vvoovv/blender-geo#465]
Hi,
Thank you for the great work on this awesome addon!

I’m trying to import an entire (Relatively small european)  city with the 3D tiles into blender, with the ”buildings with details” LOD. For my intended purpose of the 3D data, I cannot go into lower details.

I have followed “best practice”, tried to import smaller chunks at a time, but it always comes to a point where blender is no longer able to keep up and freezes in the viewport.
I’m running a decent setup, GPU - RTX 4080, 64 GB DDR5 RAM. I can however see that the GPU caps out at 100% 3D usage, while RAM also starts to struggle.

My question then, is if is even possible to do larger scale areas with the 3D tile data?
Are there any ways to optimize the Blender settings, object settings, baking??, to make it able to run?

I would not care about long render times, but need to be able to work in the viewport.

Thanks!

**Comment by vvoovv** [comment]
Hi @Raybalong 

I can suggest importing a smaller part of the city with a large LOD and the rest of the city with a small LOD.

**Comment by Raybalong** [comment]
Thank you for the answer.

This is a method I have used, but does not really satisfy my needs.
Are there no settings or anything like it, that can limit or optimize how much Blender can see/process at any given time?

**Comment by vvoovv** [comment]
Unfortunately I am not aware of this kind of setting.

**Comment by Jean1995** [comment]
> Hi @Raybalong
> 
> I can suggest importing a smaller part of the city with a large LOD and the rest of the city with a small LOD.

Is there a simple way to import different parts of the map with different levels of detail?
If I repeat the process of importing with different levels of details with different extents, I get some overlaps at the edges of the map.
Is there a recommended way to avoid this? I would like to import a few parts of a city with high details, and important the surroundings with a lower level of detail.

**Comment by vvoovv** [comment]
Hi @Jean1995 

I recommend importing different parts of the map with different levels of detail and removing the overlapping part in the Edit mode. The rectangle selection method (the default one) or the circular selection (the key `C`) can be used to quickly select the mesh for deletion.

**Comment by vvoovv** [comment]
![blosm_2 7 6](https://github.com/vvoovv/blosm/assets/613295/5bc1e823-d19d-4d90-b08e-1f15bbf4bccd)

I hope you can now import exactly the desired rectangular area.

Please update the Blosm addon. The latest version of the addon is now 2.7.6.
