### ISSUE TITLE
Blosm Error - Not working

### ISSUE THREAD

**Issue by darik124** [vvoovv/blender-geo#467]
@vvoovv 
I've been trying to use the free version, I have tried to remove and re-download the add-on but this problem continues to pop up

<img width="451" alt="Screen Shot 2024-02-27 at 11 02 30 AM" src="https://github.com/vvoovv/blosm/assets/161494163/645b498f-53c2-488f-990a-7c8ea55d4b3a">

**Comment by vvoovv** [comment]
Hi @darik124 

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
