### ISSUE TITLE
No 3D tiles were imported. 1 errors occurred during the import. See the System Console.

### ISSUE THREAD

**Issue by elvinflutter** [vvoovv/blender-geo#468]
No 3D tiles were imported. 1 errors occurred during the import. See the System Console.

What the problem in Blosm

**Comment by vvoovv** [comment]
Hi @elvinflutter 

What version of the addon are you using?

**Comment by vizible3d** [comment]
I had this issue today using Blender 4.0 and blosm 2.7.5 Your python fix from a previous thread sorted it though. Thanks!

C.scene.blosm.cacheJsonFiles = False

**Comment by vvoovv** [comment]
@vizible3d 

`cacheJsonFiles` is set to `False` by default in Blosm 2.7.5.

**Comment by vizible3d** [comment]
I think it migrated the settings from my previous version when I reinstalled blender. I was using 2.7.3 and blender 3.6.2 when i first had the problem. I tried installing blender 4.0 and 2.7.5 as my first fix and it still didn't work. Adding you python script did though.

**Comment by vvoovv** [comment]
@vizible3d 

Maybe it was a Blender file saved with the old version of Blosm addon.

Try restarting Blender, ensure that it's a new file (`Ctrl` `N`) rather than a saved one, paste `C.scene.blosm.cacheJsonFiles` and press `Enter` in Blender's Python console to check its default value.

**Comment by mikelortega** [comment]
Setting `C.scene.blosm.cacheJsonFiles = False` did the trick for me.

**Comment by vvoovv** [comment]
@mikelortega 

Please install the latest version of the Blosm addon (currently 2.7.5). That problem was fixed there.
