### ISSUE TITLE
1 issue, and a few questions on how to use

### ISSUE THREAD

**Issue by DuckersMcQuack** [vvoovv/blender-geo#469]
Issue 1: When i import larger areas from google maps 3d tiles, i get Tiles, tiles001, tiles002 etc.. in blender, but only the last tile gets a model, how come? When i tried a larger 10x11 kilometer area, i got 4 tile collections/folders, but only last 4'th had a model i could alter. How come i only get a model of the last tile group and not the first 3?

Question 1: How come either if it's a small 1x1 kilometer or a 10x10, it still takes hours, and almost 20k tiles for each import? Shouldn't less area need less tiles? Or is it the smaller areas i choose, the more zoomed in it will be, like with regular google maps, and the more details i get? So if i want an entire "postcode" worth of maps, i'd want like a grid of quarter kilometers? Or what do i choose to get the best results?

Question 2: How do i effectively stitch smaller imports together? I tried "relative to initial import", does that only work if the first initial square import is unaltered to snap the second one to the map coordinates from the first? Like not made smaller to not go way past viewport? Or what's the best effective way of stitching them together in blender? Or do i need to "snap together by eye" then join and fix manually from there to look good?

Question 3: As it's imported as a plane, and buildings/bridges looks bad/spiky, but on google maps it's fine, is that due to imported as a plane, and i can see through it's inaccurate shapes,  is there a way to fix those? Or is that simply the area not having enough vertices per object to make it nice enough looking due to not being a popular area?

Question 4:  What's the best course of action to apply the map onto a "cube" to make it 3dprintable to replace one face of a cube with the map section i desire to 3d print?

**Comment by vvoovv** [comment]
Hi @DuckersMcQuack 

Thank you for using the Blosm addon.

Could you please provide some screenshots to illustrate your issues and questions.
