### ISSUE TITLE
I could upload 3d models in free version but the premium is giving me trouble, it says Error 403 

### ISSUE THREAD

**Issue by Alvanaldis14** [vvoovv/blender-geo#470]
Hi
At first I installed the free version, but then I decided to buy the premium version, while the free one did not have any problems to upload 3d models, the premium version that I installed could not upload anything. It only says that there is an error, but I have not clue what to do. Can you help me please?
Kind regards,
![Screenshot 2024-03-03 211722](https://github.com/vvoovv/blosm/assets/162074779/70978451-fbcc-4ccf-9956-e79aca5a672c)

**Comment by TherealDC27** [comment]
I downloaded the Premium version today, and am having the exact same issue.

**Comment by vvoovv** [comment]
Hi @Alvanaldis14 and @TherealDC27 

The solution to the 403 problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
