### ISSUE TITLE
Textures are not exported with fbx file

### ISSUE THREAD

**Issue by OlegBogosyan** [vvoovv/blender-geo#471]
[
![image](https://github.com/vvoovv/blosm/assets/90595549/f7229d67-028d-48a2-827b-669ae566808a)
](url)
![image](https://github.com/vvoovv/blosm/assets/90595549/a3ac102a-ff2c-4626-9870-7cc4810ce31f)
When importing a scan into 3d max, textures are not loaded. Although they are loaded in a folder, and the file was exported to fbx with path mode (copy).

**Comment by vvoovv** [comment]
Hi @OlegBogosyan 

Please select the object `Google 3D Tiles` and show me the `Material` tab like on the screenshot below:

![image](https://github.com/vvoovv/blosm/assets/613295/77ba1638-3d43-4ef7-8d97-7f260cbf350c)

**Comment by Uncle3d** [comment]
@vvoovv  , I'm sorry, I was writing through a friend of mine. I'm the one with the problem. 
![image](https://github.com/vvoovv/blosm/assets/162895352/02512996-2cda-4d6c-9829-6af7ce799335)

**Comment by vvoovv** [comment]
You seemingly forgot to press the button `Replace Materials` before unpacking textures. That's also mentioned in the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation.

![image](https://github.com/vvoovv/blosm/assets/613295/4610a4b4-7144-4cc0-b3cb-c81c744adaec)

**Comment by emilio2270** [comment]
I pressed 'Replace Materials' button, it shows errors. What do youthink with this problem? Thank you!
![240312_1500](https://github.com/vvoovv/blosm/assets/29482195/498fe64c-f2be-4e07-b7f7-e47f988ee92f)

**Comment by Uncle3d** [comment]
@vvoovv thank you, it`s work

**Comment by vvoovv** [comment]
@emilio2270 

Please change the language of Blender's graphical user interface to English.
