### ISSUE TITLE
Textures are not exported to Unreal Engine when using OSM 

### ISSUE THREAD

**Issue by syl020119** [vvoovv/blender-geo#472]
I us the premium version of blosm, and import the OSM into blender, when I export the buildings via blender exporters (file->export->fbx) to Unreal Engine, I find that there is no texture in the buildings, Can you kindly give me some suggestions on solving this issue?
Thanks

**Comment by vvoovv** [comment]
Hi @syl020119 

Thank you for using the Blosm addon.

Please refer to the documentation:
* Google 3D Tiles (the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials))
* OpenStreetMap (the section [Export of the imported scene](https://github.com/vvoovv/blosm/wiki/Premium-Version#export-of-the-imported-scene))

I hope this helps.
