### ISSUE TITLE
Cant export fbx file with texture

### ISSUE THREAD

**Issue by koyyyyy** [vvoovv/blender-geo#475]
Hi,

ive been looking everywhere for a fix to export the google 3d tiles to .fbx with texture. Even unpacking or doing the copy instead of auto when exporting didn't work to fix this issue.
![image](https://github.com/vvoovv/blosm/assets/164423354/d2ce6389-242a-45f8-81f7-955112e7ac6f)

when re-opening the fbx file, it only shows up the mesh and just either white or purple texture.
![image](https://github.com/vvoovv/blosm/assets/164423354/24090398-b2e1-4154-8871-fccf97c9de95)
![image](https://github.com/vvoovv/blosm/assets/164423354/f0fe3163-1698-4f62-8dcd-48777d8857c4)

These are my before and after exporting the google tiles into fbx

Hopefully, i can get an answer for this issue.

**Comment by vvoovv** [comment]
Hi @koyyyyy 

Export of Google 3D Tiles is described in the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials). It consists of 2 steps:
* Pressing the button `Replace Materials`
* Unpacking textures after saving your Blender file

I hope this helps.
