### ISSUE TITLE
FBX) I told you to export it, but it doesn't work.

### ISSUE THREAD

**Issue by jongtaehwangbo** [vvoovv/blender-geo#476]
Can you tell me in detail how to export the material as it is? Or let me know by YouTube video

**Comment by vvoovv** [comment]
Hi @jongtaehwangbo 

Export is described in the documentation:
* [Google 3D Tiles](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) (the section "Export and Custom Materials")
* [OpenStreetMap](https://github.com/vvoovv/blosm/wiki/Premium-Version#export-of-the-imported-scene) (the section "Export of the imported scene")

I hope this helps.

**Comment by jongtaehwangbo** [comment]
I just want it to have color or texture when exporting to FBX and PLY. [The texture images will be written to the folder textures next to your Blender file. Finally, perform an export to a file next to your Blender file.] <- Even if I do this, my FBX or PLY file still doesn't have an RGB value. I want to use it for touch designers. Could you please tell me the details just once? I'm a beginner in 3D programs.

**Comment by vvoovv** [comment]
What are you trying to export? Google 3D Tiles or OpenStreetMap?

**Comment by jongtaehwangbo** [comment]
I trying Google 3D Tiles.

**Comment by vvoovv** [comment]
Did you try to follow the documentation on how to export your scene? Have your pressed the button `Replace Materials` after the import?

**Comment by jongtaehwangbo** [comment]
yes! 1.  Select Blender objects in question with Google 3D Tiles. The section Tools appears at the bottom of the Google 3D Tiles panel. Simply press the button Replace Materials to get export-ready materials for the selected objects.

2. First, save you Blender file with the imported Google 3D Tiles. Second, unpack all texture images: Main menu -> File -> External Data -> Unpack Resources. In the popup-window select Use files in current directory (create when necessary):

3. The texture images will be written to the folder textures next to your Blender file. Finally, perform an export to a file next to your Blender file.

However, the ply and texture files were only stored separately in the folder.

**Comment by vvoovv** [comment]
Please try exporting to FBX.

**Comment by jongtaehwangbo** [comment]
It works on the blender. But it's not getting the value from the touch designer.

**Comment by vvoovv** [comment]
If FBX export works for you, then everything is ok.

**Comment by jongtaehwangbo** [comment]
T.T Ok thank you !!!!! :)
