### ISSUE TITLE
Method to solve the problem on importing Google 3D Map Tiles data, accompanying with the Error Message "HTTP Error 400: Bad Request"

### ISSUE THREAD

**Issue by Hiro-Saeki** [vvoovv/blender-geo#477]
In Blender V4.02 application, by using the Addon  Blosm v1.0 , I have tried to import data of Google 3D MAP Tiles,
but this action was blocked with the Error message: 
"Unable to process the root URI of the 3D MAP Tiles: HTTP Error 400: Bad Request".

 In this case, in order to compose the Map Tiles API Request, I adopted the URI and API Key, as flowed.
(1) **"https://tile.googleapis.com/v1/3dtiles/root.json?key=YOUR_API_KEY"**
(2) with replacing the above "YOUR_API_KEY" with my valid API KEY "AIzaSy******************QNQUQ".

Beside this, I already confirmed that Map Tiles API is in enable status.

**Comment by vvoovv** [comment]
Hi @Hiro-Saeki 

The key is just AIzaSy******************QNQUQ. Please enter this string in the addon preferences.

I hope this helps.

**Comment by Hiro-Saeki** [comment]
Hellow! vvoovv-san,
In accordance with your advice, I tried again and I confirmed this problem just disappeared.
Thank you very much. I think you are very good person.
