### ISSUE TITLE
bad gltf & Error: Please select a file

### ISSUE THREAD

**Issue by evelinehong** [vvoovv/blender-geo#478]
when importing 3D tiles using bpy blosm, several errors occur

one is bad gltf, json error
the other one is  Error: Please select a file

**Comment by vvoovv** [comment]
Hi @evelinehong 

Please attach a screenshot of the error.

What version of Blender are you using?

**Comment by evelinehong** [comment]
It's getting normal now so I don't have a screenshot. I'm using  (v3.3.16)

Do you know if we could run several bpy import processes at the same time? When I tried to run 2 processes at the same time this error occurs.

Or is it the api limit?

**Comment by vvoovv** [comment]
Please install the latest stable version of Blender (currently 4.0.2).

The addon was not designed to run several import processes in parallel. But that can be accomplished with some walkarounds, like running two versions of Blender.

**Comment by evelinehong** [comment]
even with the studio version?

**Comment by evelinehong** [comment]
So blenders across different machines should work fine?

**Comment by vvoovv** [comment]
> So blenders across different machines should work fine?

Yes, I hope so.

**Comment by evelinehong** [comment]
![WeChat Screenshot_20240325204004](https://github.com/vvoovv/blosm/assets/32010547/36f5817e-3f05-4ff1-ad40-35dd93771009)
here's the screenshot

**Comment by evelinehong** [comment]
![WeChat Screenshot_20240325204224](https://github.com/vvoovv/blosm/assets/32010547/f999307a-8ae8-4965-8687-aebfdc0af144)

**Comment by evelinehong** [comment]
![Uploading WeChat Screenshot_20240325214723.png…]()

**Comment by vvoovv** [comment]
Are you running two imports in parallel?

What version of Blender are you using?

**Comment by evelinehong** [comment]
No I’m not

**Comment by vvoovv** [comment]
What version of Blender are you running?

**Comment by evelinehong** [comment]
v3.3.16

**Comment by vvoovv** [comment]
Please install the latest stable version of Blender (currently 4.0.2) and try again.
