### ISSUE TITLE
Blosm + Google Tiles issue

### ISSUE THREAD

**Issue by krone2000** [vvoovv/blender-geo#479]
Hey, I was trying to import a part of my city into blender through blosm and google tiles, I do everything accoring to the tutorial, including enabling theMap Tiles API without any restrictions, downloading the latest version of both blender and blosm, and yet get a response of: Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden

Do you have an idea of how can it be fixed?

**Comment by vvoovv** [comment]
Hi @krone2000 

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by krone2000** [comment]
"A: Most likely you forgot to enable the Maps Tiles API as described [here]"
As I have described - the Maps Tiles API is enabled, yet the issue still exists

**Comment by vvoovv** [comment]
Please send me a screenshot where I can see that the Maps Tiles API is indeed enabled.

**Comment by krone2000** [comment]
![proof](https://github.com/vvoovv/blosm/assets/164943536/57b21430-ee5b-48c5-a5e6-ffa696d0c247)

**Comment by vvoovv** [comment]
Thank you for your feedback.

What is the output of the URL https://tile.googleapis.com/v1/3dtiles/root.json?key=YOUR_API_KEY ?
Replace YOUR_API_KEY with your Google 3D Tiles key.

**Comment by krone2000** [comment]
{
  "error": {
    "code": 403,
    "message": "Map Tiles API has not been used in project 236021330475 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/tile.googleapis.com/overview?project=236021330475 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/tile.googleapis.com/overview?project=236021330475"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "tile.googleapis.com",
          "consumer": "projects/236021330475"
        }
      }
    ]
  }
}

**Comment by vvoovv** [comment]
Thing to try:

* Follow the advice: Map Tiles API has not been used in project 236021330475 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/tile.googleapis.com/overview?project=236021330475 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

* Check if the key is the same in your addon preferences and at the Google Cloud webpage. If not, copy the key from the Google Cloud to the addon preferences. I recall, that someone reported that the key was mysteriously changed in the Google Cloud.

**Comment by krone2000** [comment]
It started working now that I have re-enabled the API through this link
Thank you for help!

**Comment by DanielSantos998** [comment]
Hey guys, I'm trying out this add-on, but I keep getting the following error: 'Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found.' Can you help me out

**Comment by vvoovv** [comment]
@DanielSantos998 

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
