### ISSUE TITLE
google 3d tiles MAC iOS error 403: forbidden

### ISSUE THREAD

**Issue by EnricoCasagr** [vvoovv/blender-geo#481]
<img width="1512" alt="Screenshot 2024-04-08 alle 01 12 01" src="https://github.com/vvoovv/blosm/assets/166314555/442a367f-6ad1-4100-b06c-721e814ea674">

I don't know what else to do someone could explain me why it's not working?

**Comment by vvoovv** [comment]
Hi @EnricoCasagr,

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.
