### ISSUE TITLE
@mikelortega

### ISSUE THREAD

**Issue by tizianoseri** [vvoovv/blender-geo#482]
@mikelortega 

Please install the latest version of the Blosm addon (currently 2.7.5). That problem was fixed there.

_Originally posted by @vvoovv in https://github.com/vvoovv/blosm/issues/468#issuecomment-1999496866_
 
 Hi! How can I update my premium versione from 2.7.2 to the last one?

**Comment by vvoovv** [comment]
Hi @tizianoseri

You can always download the latest version of the addon using the link in your purchase confirmation email. Please contact me via  the email prokitektura+support@gmail.com if you didn't preserve your purchase confirmation email.
