### ISSUE TITLE
"show selected rectangle" just doesnt work

### ISSUE THREAD

**Issue by WhyIsNothingWorking** [vvoovv/blender-geo#483]
Hello, ive recently installed blender, blosm plugin, got my google key, enabled it, opened the menu in blender for Blosm and clicked select.

Then the website "choose map extent" appeared with map and the button: show selected rectangle.

It doesnt work. literally nothing happens when i click it. Ive tried to reset every single thing. nothing works. Ive managed to use it ONCE so it did work. Next day i wanted to use it like for real aaaand here we are.

Not sure if the image says anything or if it needed whatsoever, but it would be very very nice if IT WORKED :).

![image](https://github.com/vvoovv/blosm/assets/166800736/87536bea-f84e-4bf4-8348-5d5dea6dd3d0)

**Comment by vvoovv** [comment]
Hi @WhyIsNothingWorking 

I was unable to reproduce the problem. Does the problem still persist for you?

**Comment by vvoovv** [comment]
I've got a number of the reports today about the disappeared rectangle. One of the customers confirmed that it works again for him. I guess it was a temporary network problem. Please let me know if the rectangle works for you again.

Sorry for inconveniences.
