### ISSUE TITLE
Blosm in blender keep showing error when I try to import google map tile.

### ISSUE THREAD

**Issue by HL511** [vvoovv/blender-geo#484]
<img width="752" alt="Screenshot 2024-04-14 at 08 35 55" src="https://github.com/vvoovv/blosm/assets/160194854/b615786a-65b6-4b0a-a58c-ad26bd445790">

**Comment by vvoovv** [comment]
Hi @HL511,

Please set a folder for the addon data in the addon preferences as described in the [documentation](https://github.com/vvoovv/blosm/wiki/Documentation#installation). Specifically, set set the option (f) on the screenshot in the section Introduction.

**Comment by HL511** [comment]
It worked! Appreciate your help :) Also, do you know how to get this file ready for 3D printing or sending it over to Rhino without crashing? it's a big map

**Comment by vvoovv** [comment]
Sorry, I am not an expert in 3D printing.

Try exporting a small area first and open it in Rhino.
