### ISSUE TITLE
Shadow on imported 3D from Google

### ISSUE THREAD

**Issue by vincenzocas** [vvoovv/blender-geo#485]
Hi, I noticed that google 3D tileset has shadows baked in texture, is there any way to download it without shadows or to remove it?

**Comment by vvoovv** [comment]
Hi @vincenzocas

Unfortunately we can't influence the content provided by Google Cloud.

**Comment by vincenzocas** [comment]
Can’t you even change the day time?

**Comment by vvoovv** [comment]
It's possible to change the shaders of the Google 3D Tiles. Please refer to the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation.
