### ISSUE TITLE
Error Processing request

### ISSUE THREAD

**Issue by Andrei-Smolik** [vvoovv/blender-geo#486]
I am getting the following error messages in blender console: 
There was an error when processing the URI {uri} 
[Errno 2] No such file or directory: 'C:\\Users\\AndreiSmolik\\Downloads\\3d_tiles\\google\\....json'

**Comment by vvoovv** [comment]
Hi @Andrei-Smolik 

Please install the latest version of the Blosm addon (currently 2.7.5).
