### ISSUE TITLE
Empty and partial 3D Tiles

### ISSUE THREAD

**Issue by lowpolycosmonaut** [vvoovv/blender-geo#487]
Importing 3D tiles from Google at the highest setting seems to cull parts of the meshes - Not sure why. It is always the same tiles too.

![BLOSM](https://github.com/vvoovv/blosm/assets/133841516/b3cc8900-b018-4495-94f5-a20bc7371661)

**Comment by vvoovv** [comment]
Hi @lowpolycosmonaut 

What version of the addon are you using?

**Comment by lowpolycosmonaut** [comment]
@vvoovv 2.7.5

**Comment by vvoovv** [comment]
Most likely it is due to the problem described at #474
