### ISSUE TITLE
Unable to process the root URI of the 3d tiles: HTTP error 403 : Forbidden

### ISSUE THREAD

**Issue by luismagill** [vvoovv/blender-geo#488]
I have installed Blosm premium in blender 4.0.2  and the 3d tiles API key on its own an with all other keys giving me the same issue as stated in the title.  Unable to process the root URI of the 3d tiles: HTTP error 403 : Forbidden.

do you have a solution/

Kind regards

A L .

**Comment by vvoovv** [comment]
Hi @luismagill 

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

I hope this helps.
