### ISSUE TITLE
Add-on Imports in 2D instead of 3D 

### ISSUE THREAD

**Issue by JulianPasiArias** [vvoovv/blender-geo#489]
I want to add a selected map but the add-on imports it in 2D instead of 3D.
![Sin título](https://github.com/vvoovv/blosm/assets/107800875/84724cd9-862c-4f3e-889c-4c294c63189b)
![Sin título1](https://github.com/vvoovv/blosm/assets/107800875/f0dd509b-a0e4-4f12-8c8b-d10f5dcdbee8)

**Comment by vvoovv** [comment]
Hi @JulianPasiArias 

Most like Google Cloud doesn't provide 3D buildings for your area of interest. Please refer to the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) in the documentation on how to see the areas with 3D buildings.

**Comment by JulianPasiArias** [comment]
Its a place in Rusia, and the Doc says that it should import in 3D from there.

![image](https://github.com/vvoovv/blosm/assets/107800875/81fa7a39-2e81-4bf2-8d2a-3e2dfe466b0e)

**Comment by vvoovv** [comment]
Please note that Russia has only one black bullet. It means that only satellite imagery is available for Russia.
