### ISSUE TITLE
Option to import all ways

### ISSUE THREAD

**Issue by ChildishGiant** [vvoovv/blender-geo#491]
I'm trying to import an area with `aeroway=runway` and `aeroway=taxiway` and other elements like `barrier=hedge`. None of these ways are imported and I need them placing objects correctly. Instead of implementing all of these, I imagine a catch-all option to import all ways would solve this better than fixing just my case.

**Comment by vvoovv** [comment]
Hi @ChildishGiant 

The solution to this problem is described in #391

**Comment by ChildishGiant** [comment]
Thank you for that, I thought I searched but clearly not well enough! I don't see any similar way to import hedges and other ways so the request for a catch-all way import still stands

**Comment by vvoovv** [comment]
For the other stuff add the conditions between the lines 59 and 73 of the setup script [base_aeroways.py](https://github.com/vvoovv/blosm/blob/setup_scripts/base_aeroways.py).
