### ISSUE TITLE
Missing geometry in google 3d Tiles 

### ISSUE THREAD

**Issue by Lynchon83** [vvoovv/blender-geo#494]
Importing using the two highest levels of detail imports tiles with missing geometry. Im using v2.7.6.

![image](https://github.com/vvoovv/blosm/assets/45634961/40298b29-a141-4b2b-9ee4-f7d934404095)
![image](https://github.com/vvoovv/blosm/assets/45634961/fcf6c51e-aaff-4ac2-8f27-a564782dbe8d)

**Comment by vvoovv** [comment]
Hi @Lynchon83 

Thank you for reporting the problem.

I've found the cause of the problem. A release with the fix will be provided later today.

For a quick fix:
* Find the location of the addon folder (something like `C:\Users\*UserName*\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blosm` on windows)
* Open the addon file `blosm/threed_tiles/manager.py` in the text editor.
* Replace the line number 19:
`_minHeight = 0.` for `_minHeight = -1000.`

Here is the same area after the fix:

![image](https://github.com/vvoovv/blosm/assets/613295/ed5af43c-a14a-4075-8998-ab64e07925bd)

**Comment by vvoovv** [comment]
The problem has been fixed.

Please install the latest version of the Blosm addon (currently 2.7.7).

Sorry for the inconveniences.
