### ISSUE TITLE
A valid directory for data in the addon preferences isn't set

### ISSUE THREAD

**Issue by DertexNeverArrived** [vvoovv/blender-geo#495]
I activated tiling, put the key in the addon window, and followed every step correctly, but it's showing me an error nonetheless. Do you think I should wait after creating a Google Cloud? I didn't set limits either.

**Comment by vvoovv** [comment]
Hi @DertexNeverArrived 

Please set a folder for the addon data in the addon preference as described in the installation [instructions](https://github.com/vvoovv/blosm/wiki/Documentation#installation).

Namely, set the following field in the addon preferences:

![image](https://github.com/vvoovv/blosm/assets/613295/b124a899-8d74-406c-ba69-800fe113f289)
