### ISSUE TITLE
Replace materials error

### ISSUE THREAD

**Issue by ryota000000** [vvoovv/blender-geo#496]
I am using Blender 4.1, Blosm 2.7.7.
I want to export the imported google 3d tiles to FBX, but an error occurs when using Replace materials.
I would like to know the possible causes.
The following error occurs.

Python: Traceback (most recent call last):
   File "C:\Users\ryota\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blosm\gui\__init__.py", line 261, in invoke
     self.replaceWithExportReadyMaterials(context)
   File "C:\Users\ryota\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blosm\gui\__init__.py", line 292, in replaceWithExportReadyMaterials
     templateMaterial.node_tree.nodes["Principled BSDF"].inputs['Base Color'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^ ^
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**Comment by ryota000000** [comment]
Sorry. solved.
I solved the problem by changing the Japanese version to the English version.
If you have a similar problem, please change the language to English.

**Comment by vvoovv** [comment]
Hi @ryota000000,

Glad that you found the solution yourself!
