### ISSUE TITLE
difference in quality between google maps and downloaded model

### ISSUE THREAD

**Issue by Lynchon83** [vvoovv/blender-geo#499]
This might be something Google blocks but just to be sure, I've detected a difference in the quality of textures between the model that can be seen in the browser with the one downloaded. Any special reason for this?
to the left the model downloaded using the addon, to the right the model seen from the browser
![image](https://github.com/vvoovv/blosm/assets/45634961/c53e1b07-3be0-4e7a-b7ea-e6185f7af98c)

**Comment by vvoovv** [comment]
Hi @Lynchon83 

Please see the discussion at #386
