### ISSUE TITLE
BLOSM .FBX missing textures on import in c4d 

### ISSUE THREAD

**Issue by emotiondesigner** [vvoovv/blender-geo#500]
I am exporting my model out of Blender as .FBX
I made sure to set "path mode" to "copy" and clicked the "embed textures" icon.
With Selected objects checked.
However when I open my .fbx in c4d, it is missing textures. 
There are no images assigned to the materials.
They are just white solids. 

Can someone please explain what part of the process am I doing wrong?
There has to be a way to include textures. 
I tried doing the same thing with a basic cube and a .png file
and that imported into c4d fine. 
So, it seems like there is something about the way BLOSM is applying the textures to the materials that is different.

Any help would be greatly appreciated

I have attached 2 screenshots, 
1) showing the export settings in blender
2) showing the incoming scene in c4d

![Screenshot 2024-06-03 092859](https://github.com/vvoovv/blosm/assets/171602428/2fecb9bf-630a-4fe1-94c4-4505cc2d831e)
![Screenshot 2024-06-03 093109](https://github.com/vvoovv/blosm/assets/171602428/ff1ccbf8-c235-4c0a-b467-d107e10f8e1c)

**Comment by emotiondesigner** [comment]
Update, I tried to follow the documentation located here:
https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials
"Materials applied to imported Google 3D Tiles can't be exported. You can automatically replace those materials with export-ready ones. Select Blender objects in question with Google 3D Tiles. The section Tools appears at the bottom of the Google 3D Tiles panel. Simply press the button Replace Materials to get export-ready materials for the selected objects.

Two additional steps are required for an export. First, save you Blender file with the imported Google 3D Tiles. Second, unpack all texture images: Main menu -> File -> External Data -> Unpack Resources. In the popup-window select Use files in current directory (create when necessary):"

However, now the model comes in Black.
The materials have an image texture attached but there is no image, it is just pointing to the folder where the .fbx was saved
![Screenshot 2024-06-03 095658](https://github.com/vvoovv/blosm/assets/171602428/70659e66-3fb2-44aa-8431-15f72df078b1)

is there a way to export the textures for the materials to a specific folder so that my fbx is looking in the right place?

**Comment by vvoovv** [comment]
Hi @emotiondesigner 

There must be a folder `textures` next to your Blender file and texture files in this folder. Please check that out.

**Comment by vvoovv** [comment]
You can also try to import your FBX file back to Blender.

**Comment by emotiondesigner** [comment]
No, there's no texture file going to the folder. One of the exports (i've tried this a hundred times) created an .fbm folder but it was still black. 
If it was putting the textures next to the fbx, it would be really time consuming to have to relink all those materials manually. Depending on the size of your capture, there are a lot, i mean a lot of materials. It takes a long time just to open or save the project if that gives you an idea of how many files you would have to link and track down which ones are the right ones to link. 
I can see where the textures are going in blender but they are labelled with numbers and it would be hard to figure out which files to link. 
It would be preferred if there was just a way to export it and import it properly without rebuilding the entire model object by object texture by texture. 

I'll try importing the .fbx back into blender and see if that can be re-exported. But it seems like the .fbx doesn't have materials in it. I think the problem is more how BLOSM is applying materials to the mesh and how they are linked and how it deals with them when it exports, more than it being a problem with c4d knowing how to import an .fbx. 
I think the problem is on export, or more specifically the problem is with how its texturing the materials in a way that is different from adding a node and linking an image texture manually. So when you export it is not seeing a texture to embed in the fbx. At least thats what I think is going on.

**Comment by emotiondesigner** [comment]
Yep, confirmed. When i import the .fbx that I exported from blender back into blender, all the materials are blank with no image textures attached. 
![Screenshot 2024-06-03 110434](https://github.com/vvoovv/blosm/assets/171602428/5fb1e02f-735e-4054-9140-3431eddc0a74)

**Comment by vvoovv** [comment]
If you don't have the folder `textures` next to your Blender file with texture files, then you skipped the texture unpacking as described in the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation. Please unpack the textures as described there and ensure than you can import your FBX file with textures back to Blender.

**Comment by emotiondesigner** [comment]
Thanks for that. But what if when I click "External Data"/ "Unpack Resources" it says "No packed files to Unpack"
![Screenshot 2024-06-03 122448](https://github.com/vvoovv/blosm/assets/171602428/f25d3f78-ddcf-4ed3-b1e6-806b9e7f4f20)

**Comment by emotiondesigner** [comment]
Update, so It looks Like I was able to get it to work, by clicking "Replace Materials" in the Tools window while clicked on the material. 
And then going into the shader window and clicking "Unpack item" next to the image name on the "Base Color". 
![Screenshot 2024-06-03 142433](https://github.com/vvoovv/blosm/assets/171602428/b9cf5292-5082-44aa-8321-ad857b9d4e8c)
And then choosing "Write file to current directory (overwrite existing file)" it also says Unpack this file to an external file. 
![Screenshot 2024-06-03 142447](https://github.com/vvoovv/blosm/assets/171602428/3bace2a8-2f4f-4e2c-ae6f-bc71be0b1261)
Then i can see the file location and see that there are images in the texture folder. 
![Screenshot 2024-06-03 142612](https://github.com/vvoovv/blosm/assets/171602428/9510578a-8b79-4aec-9a86-d8a63dab9a9f)
Which when I export it, you can see some of the 3D tiles have textures on them. 
![Screenshot 2024-06-03 135418](https://github.com/vvoovv/blosm/assets/171602428/182905d9-fc92-4761-a90b-ffbf52ad0c3c)
The only problem is that this is a very laborious process. I chose a small square for testing. Literally one city block. 

And it has 145 meshes listed and each mesh has multiple textures. 
![Screenshot 2024-06-03 143759](https://github.com/vvoovv/blosm/assets/171602428/b2d30ab8-abca-470e-913e-61acd0b2a8a1)
![Screenshot 2024-06-03 143759](https://github.com/vvoovv/blosm/assets/171602428/b2d30ab8-abca-470e-913e-61acd0b2a8a1)
So I would have to do that 3 step process 145 times, times the number of textures on each mesh?
And thats 145 meshes for one small city block of los angeles.
![Screenshot 2024-06-03 143839](https://github.com/vvoovv/blosm/assets/171602428/ffc122ef-4d64-4760-b913-8f4f96388668)

What happens when I do a whole section of a city? The number of textures will be exponentially higher. 
There has to be a better way to do this. Or a way to batch the process?

Why is that not a default? 

None of the other videos or tutorials I saw said that you can't embed textures when you export or that you had to do this for every single texture on the grid in your scene. There has got to be an easier way. 

if not, this should be a feature request or an option for the Developers to consider.

**Comment by emotiondesigner** [comment]
Update: I got it to work. 
I'm not even sure how or why it worked this time. 
I think i just did Main menu -> File -> External Data -> Unpack Resources (as explained above)
But this time, instead of saying "No packed files to unpack" it saved all the images in the project to the directory inside a texture folder the way you would want it to work. 
I'm not sure exactly why it wasn't working before and why it worked with the project it worked with. 
I'm testing it on a larger scene now and it's taking a while. But when it works, I will share exactly how it worked in case anyone else runs into this problem in the future. 
[https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials](url)

**Comment by vvoovv** [comment]
I am glad that you got it to work.
