### ISSUE TITLE
I keep getting "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden" Error

### ISSUE THREAD

**Issue by TwistedChaoz** [vvoovv/blender-geo#501]
As stated in the title I keep getting the error but I enabled the maps API and it still doesn't work any help would be GREATLY appreciated. Thank you!

**Comment by vvoovv** [comment]
Hi @TwistedChaoz 

Please send your Google 3D Tiles Key to prokitektura+support@gmail.com. I'll check it out.

**Comment by vvoovv** [comment]
I can see that you applied API restrictions to your Google 3D Tiles key. Please remove them. 

Please also note that it's mentioned in the section [Google 3D Tiles Key](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#google-3d-tiles-key) of the documentation.

**Comment by TwistedChaoz** [comment]
Hello I turned off the restrictions is there anything else I need to do?

**Comment by vvoovv** [comment]
It should work now.

**Comment by TwistedChaoz** [comment]
It works now, thank you so much. I truly appreciate your help! Have a great
day.
