### ISSUE TITLE
Terrain not appearing [Premium version]

### ISSUE THREAD

**Issue by phynam** [vvoovv/blender-geo#503]
Hi there,

When I select an area in Western Canada (-123.29956,49.00961,-122.70081,49.37518) and click import, the terrain appears to be generated (the terrain layer is created), but I can't see it in Blender. 

- Importing the default location is working and terrain appears as expected
- I've tried setting a massive view endpoint but I still don't see it
- The correct elevation file is downloaded and exists in the cache folder 
- Importing a relatively small flat area in the same region also doesn't seem to work 

One thing to note is when I log the `minHeight` in `def importTerrain` - it always gives a huge negative value, while I notice the default location is positive - not sure if this impacts anything. 

It's quite possible this is a display / viewing issue on my end as I'm relatively new to Blender.

Any ideas what's going on here? 

Thanks! 

<img width="1667" alt="Screenshot 2024-06-09 at 12 46 45 PM" src="https://github.com/vvoovv/blosm/assets/8989809/5399d7cb-bce4-499f-a47d-2286daf2f796">

**Comment by vvoovv** [comment]
Hi @phynam 

To see the imported terrain in the viewport, increase the far clipping distance:

![image](https://github.com/vvoovv/blosm/assets/613295/3c8545b6-1984-4e8d-861f-ef13cb71561c)

**Comment by phynam** [comment]
Thanks @vvoovv - I had done that but it seemed like the terrain was just rendering miles away from the origin - I centered it and all working now.

**Comment by vvoovv** [comment]
A terrain is imported relative to the initial import. Uncheck the option` Relative to initial import` to ignore the initial import.
