### ISSUE TITLE
Some buildings are not generated from OpenStreet data

### ISSUE THREAD

**Issue by 3dimka** [vvoovv/blender-geo#504]
Using the latest premium version with Blender 4.

I imported OpenStreet 3D Realistic and 2D layers and some buildings were incomplete or missing.
I compared the same location on https://osmbuildings.org/?lat=47.09629&lon=37.54810&zoom=17.6&tilt=30 and it doesn't have the same issue.

screenshot (side by side): 
![image](https://github.com/vvoovv/blosm/assets/47431444/0965a3b1-b637-4991-b307-9460fedb3bd4)

The 3D Simple import produces a very similar issue.

P.S. I checked the Osm2World java tool and it has the same issue. Only osmbuildings.org doesn't have this issue.

**Comment by 3dimka** [comment]
After some digging I think I found what's the cause of the issue, although there's no easy fix I can think of.

The OSM Overpass API has a filtering issue, or maybe the data is poorly indexed. Retrieving data by the longitute/latitude rectangle does not return all the datapoints (nodes, ways) that fit inside the rectangle, thus the missing buildings and their parts.

Here's an example of query:

`
[out:xml];
(
  way[building](47.09524,37.54593,47.09772,37.54850);
  relation[building](47.09524,37.54593,47.09772,37.54850);
);
(._; >;);
out body;
`

![image](https://github.com/vvoovv/blosm/assets/47431444/265dd9a0-69fc-4f6c-be0b-8c83bed734a5)


However, if the .osm file is retrieved using different criteria, i.e. all relationships, it suddenly could return the previously missing data points.

here's an example of a query (notice, the relation doesn't have the [building] filter)
`
[out:xml];
(
  way[building](47.09524,37.54593,47.09772,37.54850);
  relation(47.09524,37.54593,47.09772,37.54850);
);
(._; >;);
out body;
`

![image](https://github.com/vvoovv/blosm/assets/47431444/ca4b6e6a-70b1-496a-8292-6897777136d5)
* notice how many building and elements are added that are both inside and outside of the given rectangle.

And if I then import both and combine together I see that some parts come from one file and some from another, and together they add up.

![image](https://github.com/vvoovv/blosm/assets/47431444/04c077aa-f309-4df8-b659-b31ffd1f3f91)

Right, and finally the https://osmbuildings.org and why they don't have this issue?
It seems that they fetch more data to their servers and filter using their own criteria.
You can tell the data is glitchy by clicking on one building and lots of other buildings get selected (black)

![image](https://github.com/vvoovv/blosm/assets/47431444/c1019dbe-3d83-4763-9e1e-2ccf590e64bc)

https://osmbuildings.org/?lat=47.09626&lon=37.54782&zoom=19.4&tilt=30

![image](https://github.com/vvoovv/blosm/assets/47431444/bf87246c-5ccd-4baf-8be6-03e0e912477f)


I hope this investigation might give some hints and directions.

**Comment by EvandroFCosta** [comment]
I'm having the same problem.  I'm using the free version and as far as I can see on the premium version, there shouldn't be any difference in number of models between the free and premium version.
The area I'm importing is:
-43.92556,-19.87816,-43.91816,-19.87123

**Comment by vvoovv** [comment]
Hi @3dimka 

Those buildings were not mapped in accordance with the OpenStreetMap [3D Simple Buildings](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings) specification:

The entire building outline should be filled with [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)=* areas, tagged with their respective height and other attributes. These areas may overlap each other or may be disjunct, depending on the building.

The outlines of those buildings were not filled with building parts.

I quickly fixed the buildings right in the OpenStreetMap database. The quickest way to fix them is just to add the tag `building:part=yes`.

![image](https://github.com/vvoovv/blosm/assets/613295/ce60dfbd-9da4-4d0a-b101-796b5a5c7078)

**Comment by vvoovv** [comment]
@3dimka 

The buildings on the screenshot above were imported with option `Enable experimental features` where hipped roofs area supported.

**Comment by vvoovv** [comment]
Hi @EvandroFCosta 

Please point to the problem buildings.

**Comment by 3dimka** [comment]
> @3dimka
> 
> The buildings on the screenshot above were imported with option `Enable experimental features` where hipped roofs area supported.

Thank you very much for the troubleshooting. It seems that overlapping ways that don't have building:part=yes are excluded in the addon, and fortunatelly fixing open data addresses the issues on case by case manner.   
Yes, I enabled the experimental features in the Addon preferences to enjoy extra features, thank you for the suggestion.

**Comment by EvandroFCosta** [comment]
> Hi @EvandroFCosta
> 
> Please point to the problem buildings.

The problem is the general house buildings are not imported. IOnly some big ones which apparently are special buildings (like a shopping mall or some other important named building) Probably the problem is the same as 3dimka.

![image](https://github.com/vvoovv/blosm/assets/106195948/b9fd2adf-8a35-4762-9989-694a259f239e)

> I quickly fixed the buildings right in the OpenStreetMap database. The quickest way to fix them is just to add the tag `building:part=yes`.

Is this something anyone can do? Can I find on google directions on how to fix this myself?

**Comment by vvoovv** [comment]
@EvandroFCosta 

Unfortunately, the majority of the buildings for your area of interest is not available in the OpenStreetMap database.

![image](https://github.com/vvoovv/blosm/assets/613295/254de986-3694-489f-ac32-37c861e035d4)

Please note that OpenStreetMap is a collaborative mapping project where everyone can contribute. To start contributing to OpenStreetMap, zoom to your area of interest, press the tab "Edit". An interactive tutorial will be offered. After completing the tutorial, you can proceed to editing OpenStreetMap.

Alternatively you can import Google 3D Tiles for your area of interest.
