### ISSUE TITLE
Cycles lighting: Google 3D

### ISSUE THREAD

**Issue by franzwessels** [vvoovv/blender-geo#505]
I succesfully loaded the topograpy form Google and the mesh looks great.  I'm trying to set up some ligthing but even with no light sources or HDRI, my mesh stays bright / lit.  Any ideas what may cause this?

**Comment by vvoovv** [comment]
Hi @franzwessels 

Please refer to the section [Export and Custom Materials](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#export-and-custom-materials) of the documentation.

**Comment by franzwessels** [comment]
Thank you so much for the help!
