### ISSUE TITLE
proplme de compatibilité

### ISSUE THREAD

**Issue by ssssushie** [vvoovv/blender-geo#506]
bonjour, voici ce que me dit mon blender

A Google 3D Tiles Key isn't set in the addon preferences

**Comment by vvoovv** [comment]
Hi @ssssushie 

Please set a Google 3D Tiles Key in the addon preferences as described in the [documentation](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#google-3d-tiles-key).
