### ISSUE TITLE
Unable to process the root URI of the 3D Tiles: <urlopen error [WinError 10060] 

### ISSUE THREAD

**Issue by HuaiCL** [vvoovv/blender-geo#507]
![Snipaste_2024-07-02_13-09-06](https://github.com/vvoovv/blosm/assets/174409441/63996a2d-b116-4ce5-9143-a212e6a5434a)

**Comment by vvoovv** [comment]
Hi @HuaiCL 

It looks like a network problem. Please check your network settings, including Proxy, VPN, Firewall, etc.
