### ISSUE TITLE
blosm error

### ISSUE THREAD

**Issue by 3mk-is-cr7** [vvoovv/blender-geo#508]
Hey there, I'm having an issue with Blosm. Every time I try to use it, I get the same error message: "A valid directory for data in the addon preferences isn't set." If anyone else has experienced this issue and knows how to fix it, please let me know. I'll attach some screenshots to help explain the problem.
![1](https://github.com/vvoovv/blosm/assets/174534080/6df86113-7e98-4254-96e0-042a981d6b53)
![2](https://github.com/vvoovv/blosm/assets/174534080/29720980-4ed6-464e-a4b4-33b97938ac58)

Appreciate the help!

**Comment by vvoovv** [comment]
Please set a directory for the addon data as described in the [Installation](https://github.com/vvoovv/blosm/wiki/Documentation#installation) section of documentation
