### ISSUE TITLE
how to convert from blender crs to WGS84 for vertical axis of GoogleEarth 3D mesh?

### ISSUE THREAD

**Issue by yshen47** [vvoovv/blender-geo#510]
First, thanks for the great work! I read about other posts that can convert xy from blender to WGS84. But what about vertical z axis? Is the unit for it meter? How to convert it known vertical datum?

**Comment by vvoovv** [comment]
Hi @yshen47 

All units are in meters.

**Comment by yshen47** [comment]
What's the reference system? What does it mean when z axis is 0?

**Comment by vvoovv** [comment]
Please refer to the section [Coordinate reference system](https://portal.ogc.org/files/102132#toc18) of the 3D Tiles specification.

The imported scene is then rotated and translated to be brought to the origin. Please refer to the code in the method [finalize](https://github.com/vvoovv/blosm/blob/v2.7.8/threed_tiles/blender.py#L41).
