### ISSUE TITLE
Need help for alignment after coordinate conversion from blender to UTM

### ISSUE THREAD

**Issue by yshen47** [vvoovv/blender-geo#512]
Hello again,

I am trying to align the downloaded 3d mesh from blender coordinate all the way to UTM. However, after converting the mesh vertices, I found the converted mesh is not aligned with ground-truth (the point cloud is one I double check with correct UTM). I am confused on what might goes wrong. Is there any precision issue in the process of parsing and preparing the 3d mesh in blosm? We can ignore vertical axis but x-y plane is not aligned.

More detail, here is the function I used to convert downloaded 3D mesh to UTM. 

import pyproj
import math
from pyproj import Transformer

class TransverseMercator:
    radius = 6378137.0
    
    def __init__(self, **kwargs):
        # setting default values
        self.lat = 0. # in degrees
        self.lon = 0. # in degrees
        self.k = 1. # scale factor
        for attr in kwargs:
            setattr(self, attr, kwargs[attr])
        self.latInRadians = math.radians(self.lat)
        
    def fromGeographic(self, lat, lon):
        lat = math.radians(lat)
        lon = math.radians(lon-self.lon)
        B = math.sin(lon) * math.cos(lat)
        x = 0.5 * self.k * self.radius * math.log((1.+B)/(1.-B))
        y = self.k * self.radius * ( math.atan(math.tan(lat)/math.cos(lon)) - self.latInRadians )
        return (x, y, 0.)
    
    def toGeographic(self, x, y):
        x = x/(self.k * self.radius)
        y = y/(self.k * self.radius)
        D = y + self.latInRadians
        lon = math.atan(math.sinh(x)/math.cos(D))
        lat = math.asin(math.sin(D)/math.cosh(x))
        lon = self.lon + math.degrees(lon)
        lat = math.degrees(lat)
        return (lat, lon)

WGStoUTM_transformer = Transformer.from_crs("EPSG:4326", "EPSG:26918")

bpy.ops.import_scene.gltf(filepath=os.path.join('mesh_before_convert.glb'))
with open(os.path.join(output_path, tile_id, 'metadata.json'), 'r') as f:
    metadata = json.load(f)
    bpy.context.scene["lat"] = metadata["lat"]
    bpy.context.scene["lon"] = metadata["lon"]
blenderprojection = TransverseMercator(lat=bpy.context.scene["lat"], lon=bpy.context.scene["lon"])        

# convert CRS
for obj in bpy.data.objects:
    for v_i in range(len(obj.data.vertices)):
        v = obj.data.vertices[v_i]
        co = obj.matrix_world @ v.co
        x_wgs, y_wgs = blenderprojection.toGeographic(co.x, co.y)
        x_utm, y_utm = WGStoUTM_transformer.transform(x_wgs, y_wgs)
        v.co.x, v.co.y = x_utm, y_utm
bpy.ops.export_scene.gltf(filepath=os.path.join( 'mesh_after_convert.glb'), use_selection=True) 
![Screenshot from 2024-07-15 13-24-53](https://github.com/user-attachments/assets/c833ae9d-f1aa-4b35-b3df-9a957b221068)

**Comment by vvoovv** [comment]
The Tranverse Merkator projection is not used for 3D Tiles.

**Comment by yshen47** [comment]
I see, so the downloaded 3d tiles already in some sort of UTM (since all units are metrics). Then, could you clarify the correct way to convert between the downloaded 3d crs to any known crs?

**Comment by vvoovv** [comment]
I think I already provided the answer in #510

**Comment by yshen47** [comment]
Okay, I think I got it, thanks!
