### ISSUE TITLE
How to know the Perfect Geographic coordinates of the integration point into Blender

### ISSUE THREAD

**Issue by tbenazzi** [vvoovv/blender-geo#515]
Hello @vvoovv ,

I'm wondering if it could be possible to add a tab which display the Geographic coordinates (lat,lon) of the origin integration point. 

Actually we have to give the LatLon Min Max but the integration point it not perfectly the centroid of this bounding box. 
For Us it would be very useful to know more precisely what are the coordinates of this point, ideally with 8 digits but I know that blender struggle with double precision coordinates. Maybe you can fetch this value when you request the data from outside.

If at least we can print this value into the console, it would be amazing

Blender GIS do that very well. where you can even choose the integration point by yourself

PS: Your tool is amazing dude

Cheers
Theo

**Comment by vvoovv** [comment]
Hi @tbenazzi 

Geographic coordinates of Blender's origin are set as custom attributes of Blender's active scene:

![image](https://github.com/user-attachments/assets/1732a382-30c2-4af8-86ff-9f9b88eea96b)

**Comment by tbenazzi** [comment]
@vvoovv perfect ! thanks 🙏🏻
