### ISSUE TITLE
unable to process the root uri of the 3d tiles http error 404: not found

### ISSUE THREAD

**Issue by Jagadeeswaran22** [vvoovv/blender-geo#516]
I am facing this issue "unable to process the root uri of the 3d tiles http error 404: not found" and i checked F&Q they said billing issue this Future have charges

**Comment by vvoovv** [comment]
Hi @Jagadeeswaran22 

As describe in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation, please verify that everything was entered correctly in your billing account.
