### ISSUE TITLE
error importing with python script

### ISSUE THREAD

**Issue by ckyr** [vvoovv/blender-geo#518]
I am using the python script template (https://github.com/vvoovv/blosm/blob/setup_scripts/base_landuse.py) to import multiple map items from openstreetmaps onto a terrain. It has been working with no issues for a while, I started having some issues the last few days. Specifically, I am trying to import using the script below, but I am getting an error: "Unable to execute the setup script! See the rror message in the Blender Console". If I use Terminal to see the details, the script is downloading the map components, saving the file and then stops before parsing the osm file (successful scripts continue with parsing).
Any idea why this is happening?
Appreciate any help.

    osm.addCondition(
        lambda tags, e: tags.get("id") == "136634092",
        "piste",
        wayManager
    )

     osm.addCondition(
        lambda tags, e: tags.get("id") == "136634118",
        "piste",
        wayManager
    )

     osm.addCondition(
        lambda tags, e: tags.get("id") == "136634106",
        "piste",
        wayManager
    )

     osm.addCondition(
        lambda tags, e: tags.get("id") == "136634121",
        "piste",
        wayManager
    )

**Comment by vvoovv** [comment]
This code snippet looks ok.
