### ISSUE TITLE
'BlenderApp' object has not attriburte 'init3dTiles'

### ISSUE THREAD

**Issue by allguard** [vvoovv/blender-geo#519]
![SNAG-0384](https://github.com/user-attachments/assets/173ea9f1-bbb9-46a3-b0e9-bcdfb316a1a3)
I should be able to access the southern section of Central Park, but I'm encountering an issue. I've applied my API key without restrictions in the Blosm add-on, specifically in the Google 3D Tiles section. However, when I try to import the Google Earth data, I receive the following error: 'BlenderApp' object has no attribute 'ini3dTiles'. This error occurs in both Blender 3.6 and Blender 4.2. Does Blosm support these versions of Blender, or is there something else I might be missing?

**Comment by vvoovv** [comment]
Please try restarting Blender. If it didn't help, please try the following actions:
* Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing "osm" in the search box in the Blender preferences.
* Restart Blender
* Install the latest version of the Blosm addon.
