### ISSUE TITLE
Low detail with the highest option selected

### ISSUE THREAD

**Issue by DanielSantos998** [vvoovv/blender-geo#520]
Hey guys,

I'm relatively new to this software and to Blender in general. I'm having an issue with my tiles map. I encountered the 404 error earlier but managed to resolve it. However, now when I import the data, it appears as a very low-detail model, even when I set it to the highest preset. Am i doing something wrong ? 

![Captura de tela 2024-09-03 163010](https://github.com/user-attachments/assets/3d4faee6-c825-471e-a040-bd65348fbf46)

**Comment by vvoovv** [comment]
Most likely you area of interest does not contain 3D buildings. You can read on how to see the areas with 3D buildings in the [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) section of the documentation.

**Comment by DanielSantos998** [comment]
> Most likely you area of interest does not contain 3D buildings. You can read on how to see the areas with 3D buildings in the [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) section of the documentation.

Sorry to botter again, could maybe point me to the exact section of the introduction where I can read that ? English is not my first language, so I am a little lost

**Comment by vvoovv** [comment]
![image](https://github.com/user-attachments/assets/cee6e959-7bfb-4172-82c0-73c9787aa537)
