### ISSUE TITLE
"Missing manifest" when installing

### ISSUE THREAD

**Issue by mktsewhoy** [vvoovv/blender-geo#523]
I have the latest version of Blender (4.2.1) and Blosm Free (2.7.5). When I install Blosm in the usual manner from the Add-ons menu, it returns with the error message, "Missing manifest from <install path/blender-osm-info.zip>" as seen below. Previous versions of Blender don't get the error message, but nothing happens:

![image](https://github.com/user-attachments/assets/783ab384-2ecf-4eb8-9d89-91a03458f33d)

**Comment by vvoovv** [comment]
Hi @mktsewhoy 

Please install the latest version of Blosm addon from Gumroad:
* [the base version](https://prochitecture.gumroad.com/l/blender-osm)
* [the premium version](https://prochitecture.gumroad.com/l/blosm)

**Comment by mktsewhoy** [comment]
Updated to 2.7.8 but still having the same issue.

**Comment by vvoovv** [comment]
Please paste a screenshot of the error.

**Comment by mktsewhoy** [comment]
This time I've managed to show the Info window. No other info about the error is shown.
![image](https://github.com/user-attachments/assets/b641d805-939f-4e13-9911-b59987839897)

**Comment by vvoovv** [comment]
What was the name of the file you were trying to install?

**Comment by mktsewhoy** [comment]
It's "blosm_2.7.8.zip" as downloaded from Gumroad. Attempted to install with the usual "Install from disk" process as I do with all other plugins.

**Comment by vvoovv** [comment]
Try removing the file <install path/blender-osm-info.zip> and then install _blosm_2.7.8.zip_ as usual.

**Comment by mktsewhoy** [comment]
Thanks, it works now.

**Comment by mktsewhoy** [comment]
BTW, how do I speed up the Google Maps import process, even though the polygon count isn't that high?

**Comment by vvoovv** [comment]
You can run multiple instances of Blender as described below.

For each instance of Blender assign a unique name:
bpy.context.scene.blosm.instanceName = "a_unique_name"

Then start the import as usual.

**Comment by mktsewhoy** [comment]
I just found out I can import low-poly meshes with "whole city" to use as background scenery. :)

**Comment by jagsfan2278** [comment]
Im getting the same error when trying to install addons for editing NMS

**Comment by vvoovv** [comment]
Hi @jagsfan2278 

Please install it from the `Add-ons` tab. You can also refer to the documentation section [Installation](https://github.com/vvoovv/blosm/wiki/Documentation#installation).
