### ISSUE TITLE
Advice for exporting meshes

### ISSUE THREAD

**Issue by mktsewhoy** [vvoovv/blender-geo#524]
Not a bug, but a word of advice: if you can't be bothered with the hassle of baking textures, then it's best to click "Replace materials with Export-ready", then export the map mesh as DAE instead of OBJ (no material info is properly stored) or FBX (often an error is generated with this format).

**Comment by vvoovv** [comment]
Hi @mktsewhoy 

Thank you for the advice. What error did you get with the export to FBX?

**Comment by mktsewhoy** [comment]
Here's a screenshot of it:
![image](https://github.com/user-attachments/assets/1953f696-eef5-4fe4-be92-5132a515bec4)

**Comment by vvoovv** [comment]
But it wasn't a Blender's native FBX exporter. Try Blender's native FBX exporter.

**Comment by mktsewhoy** [comment]
Found the problem. I installed a KN5 FBX aftermarket plugin which appears to have screwed up the native plugin.
