### ISSUE TITLE
error code 400: Bad Request

### ISSUE THREAD

**Issue by jchansen4** [vvoovv/blender-geo#526]
I am having issues with downloading a 3D map in Blender. I have the Blosm addon installed with all the necessary keys installed. I have the items needed to be enabled, enabled. I am getting an error message. 
unable to process the root URL of the 3D tiles HTTP Error 400: Bad Request. 
Please help, I am an idiot on all things computer related.
Thank you,
John
jhgifts4@gmail.com

**Comment by vvoovv** [comment]
Please send your Google 3D Tiles key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by vvoovv** [comment]
I am getting the 403 error for your key. The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by 64Pierre64** [comment]
Hi, i'm having the same issue.
with necessary keys / billing valid / API enable?
unable to process the root URL of the 3D tiles HTTP Error 400: Bad Request.
thank you!

**Comment by vvoovv** [comment]
Hi @64Pierre64 

Please send to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com):
* your Google 3D Tiles key as a text
* a screenshot of the addon preferences where you set your Google 3D Tiles key.

I'll have a look

**Comment by ZestBoss1** [comment]
Good Evening,

Unfortunately I am having the same issue here and seeing the same exact error message 'unable to process the root URL of the 3D tiles HTTP Error 400: Bad Request' can anyone help me I have everything setup the way it should.

**Comment by vvoovv** [comment]
Hi @ZestBoss1 

Hi @64Pierre64 

Please send to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com):
* your Google 3D Tiles key as a text
* a screenshot of the addon preferences where you set your Google 3D Tiles key.

I'll have a look
