### ISSUE TITLE
Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad request

### ISSUE THREAD

**Issue by uwerau1962** [vvoovv/blender-geo#528]
Hallo zusammen. Um es kurz zu machen: Win11 64bit, 32Gb RAM, 4GHz, Blender 3.6, Blosm 2.7.8 Premium. Ist also bezahlt. Google 3D Tiles aktiviert. 
Directory to store ... ist eingestellt.
Directory with assets ... ebenfalls eingestellt. Zip-Datei hierhin entpackt. War das falsch?
Importieren von Gebäudemodellen trotz Blender Update auf 3.6 erzeugt Fehlermeldung, siehe Titel. Was mache ich falsch, und welche Einstellungen muss ich noch tätigen? 
Vielen Dank im Voraus.

Mit freundlichen Grüßen
Uwe

**Comment by vvoovv** [comment]
Hi @uwerau1962

Please send your Google 3D Tiles key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll check it out.

**Comment by vvoovv** [comment]
I am getting the error `API key not valid. Please pass a valid API key`. Maybe you missed one or more characters at the end of the key when copied and pasted it?

**Comment by uwerau1962** [comment]
Hallo, ich habe das große I für ein kleines L gehalten. Das habe ich jetzt im gesamten Schlüssel korrigiert. Jetzt erhalte ich die Meldung "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden".
HELP!
Sincerely Yours
Uwe

**Comment by uwerau1962** [comment]
Hallo, ich habe das große I für ein kleines L gehalten. Das habe ich jetzt im gesamten Schlüssel korrigiert. Jetzt erhalte ich die Meldung "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden".

HELP!

Sincerely Yours

 

Uwe Rau

 

Mail          ***@***.***> ***@***.***

Help conserve the Environment. Please think bevor you print this E-mail. 

https://www.plant-for-the-planet.org/de 

https://www.ecosia.org/

 

Von: vvoovv ***@***.***> 
Gesendet: Donnerstag, 19. September 2024 17:54
An: vvoovv/blosm ***@***.***>
Cc: uwerau1962 ***@***.***>; Mention ***@***.***>
Betreff: Re: [vvoovv/blosm] Unable to process the root URI of the 3D Tiles: HTTP Error 400: Bad request (Issue #528)

 

I am getting the error API key not valid. Please pass a valid API key. Maybe you missed one or more characters at the end of the key when copied and pasted it?

**Comment by uwerau1962** [comment]
"Copy" und "Paste" funktioniert beim API Key übrigens nicht. Der Schlüssel muss von Hand eingegeben werden.

**Comment by vvoovv** [comment]
> "Copy" und "Paste" funktioniert beim API Key übrigens nicht. Der Schlüssel muss von Hand eingegeben werden.

There must be a button "Copy to the clipboard" near the key.

**Comment by vvoovv** [comment]
> Hallo, ich habe das große I für ein kleines L gehalten. Das habe ich jetzt im gesamten Schlüssel korrigiert. Jetzt erhalte ich die Meldung "Unable to process the root URI of the 3D Tiles: HTTP Error 403: Forbidden".

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by uwerau1962** [comment]
Hallo,
es funktioniert jetzt! Vielen, vielen Dank.

Mit freundlichen Grüßen
Uwe
