### ISSUE TITLE
better terrain geometry

### ISSUE THREAD

**Issue by BernardoI** [vvoovv/blender-geo#529]
Hello! I have the premium version of the blosm addon and it's great! However, I wonder if there's a way to get the terrain in better quality. 

I am trying to work on a tuscanian city, and when I download the terrain from the blosm addon, this is how it looks: 
![image](https://github.com/user-attachments/assets/d102a5b1-50af-408f-9a8b-901188059a72)
While the overall quality is good, you  can see that the coastline is all jagged, and that's not good. 

Is there a way to chose a different source for the terrain elevation?

In the blenderGIS addon you can chose from the OpenTopography DTM 30m model, which is much better, with no jagged coastline. However I cannot figure out if there's a way to georeference the 2 models (from BLOSM and BlenderGIS) in order to match them perfectly, or even better, if there's a way to chose the source of the elevation model in the BLOSM addon. 

Thank you!

**Comment by vvoovv** [comment]
Hi @BernardoI 

You can also use Google 3D Tiles to get the terrain.

**Comment by BernardoI** [comment]
Hi @vvoovv , thank you for your answer! Wouldn't I also get buildings with the google tiles? I would like to just get elevation data. I know that elevation data probably also includes buildings (I guess? not sure) but it comes in the form of a terrain, not buildings+terrain. Or am I missing something?

**Comment by vvoovv** [comment]
There are often complains that an area of interest doesn't contain 3D buildings in Google 3D Tiles. But your case is opposite :)

Just try it out. Anyway, you can try a lower resolution to get an area without 3D buildings.

**Comment by BernardoI** [comment]
thanks! I was hoping however, that in a premium addon you would have a bit more options when it comes to getting elevation. BlenderGIS has more options here, but I cannot however figure out how to make the 2 interact together with georeferencing

**Comment by vvoovv** [comment]
PROJ.4 parameters of the default projection:

```
+proj=tmerc +a=6378137 +b=6378137 +lat_0=<lat> +lon_0=<lon> +k_0=1 +x_0=0 +y_0=0 +units=m
```
where `<lat>` and `<lon>` are equal to the custom attributes _lat_ and _lon_ of the active Blender scene or to another center of the import.

**Comment by BernardoI** [comment]
Thank you! where should I use that text exactly?

**Comment by vvoovv** [comment]
I hope it can be used in BlenderGIS to import the required data in a Blosm projection.
