### ISSUE TITLE
invalid string to paste

### ISSUE THREAD

**Issue by uwerau1962** [vvoovv/blender-geo#530]
Hallo zusammen,

ich nutze seit einem Monat Blosm unter Win11 64bit. Beim Importieren von Gebäudemodellen, beim Anklicken von "paste" erscheint die Meldung "invalid string to paste". Ich habe eine Lizenz für einen Nutzer und privat. Ein paarmal hat es mit dem Importieren geklappt, aber dann war Schluss. Der Betrag für die Lizenz ist seltsamerweise noch nicht abgebucht.

**Comment by vvoovv** [comment]
Hi @uwerau1962

Instead pressing the button `paste`, paste the content of your clipboard here by pressing `Ctrl` `V`,

**Comment by uwerau1962** [comment]
Hallo, tut mir leid für die späte Antwort. Strg + V funktioniert auch nicht, aber eintragen der Koordinaten von Hand funktioniert. Damit bin ich auch erstmal zufrieden. Vielen Dank für die Antwort. Immerhin bin ich dadurch auf eine vorläufige Lösung gekommen. Im Prinzip funktioniert es ja jetzt.

**Comment by uwerau1962** [comment]
Thank you so much! Sincerely yours Uwe RauMail          ***@***.*** conserve the environment. Please think before you print this email.Von: vvoovv ***@***.***>Gesendet: Donnerstag, Oktober 3, 2024 3:18:05 PMAn: vvoovv/blosm ***@***.***>Cc: uwerau1962 ***@***.***>; Mention ***@***.***>Betreff: Re: [vvoovv/blosm] invalid string to paste (Issue #530)
Closed #530 as completed.
