### ISSUE TITLE
Tiles importing in different orientations

### ISSUE THREAD

**Issue by Kenzonian** [vvoovv/blender-geo#533]
When I import my tiles do not arrive as planned.  (Blender Ver 4.2.2)

<img width="960" alt="image" src="https://github.com/user-attachments/assets/14882451-d4bb-46a7-8308-c829e019a833">

Then I get this: 
![_ (Unsaved) - Blender 4 2 2 LTS 10_7_2024 1_04_12 PM](https://github.com/user-attachments/assets/d6800047-1e6d-4b65-bd3b-b9015370b4e8)

Thoughts?

**Comment by vvoovv** [comment]
Hi @Kenzonian 

Where are those objects `Mesh_0.049`, `Mesh_0.050`, etc, coming from?

**Comment by Kenzonian** [comment]
Theyre coming from blosm plugin inside blender. 
The blosom is set to 3d Tiles from Google, Groups of buildings.

**Comment by vvoovv** [comment]
Could make a screencast to show your actions that lead to this problem?

**Comment by Kenzonian** [comment]
There's no process. 
I took the Lat/Long from first screen shot, C/P into blosm plugin using the paste button in blender.
I selected the settings shown in the blender window and clicked import. 

If I'm missing somethjing I can do screen cast. but it was not that complicated.

**Comment by vvoovv** [comment]
I am unable to reproduce your problem with your settings. A screencast would very desirable.

![image](https://github.com/user-attachments/assets/4deb536d-2577-4a06-aefc-ae273c5d6872)

**Comment by Kenzonian** [comment]
The video was too big for github, so Here is the YT link:
https://youtu.be/wFRjnVzF5_8

**Comment by vvoovv** [comment]
Thanks, but there is only a web browser window in your screencast. Actually your actions in Blender are needed.

**Comment by Kenzonian** [comment]
My bad sorry. 

Here is the video of blender. https://youtu.be/C7VwqJYg2x8

**Comment by vvoovv** [comment]
Can you upload the resulting Blender file?

**Comment by Kenzonian** [comment]
I couldnt upload directly.

Here is the DB link: https://www.dropbox.com/scl/fi/y40aie6bvbnf0ldqxacw8/BlosmTest.blend?rlkey=wk3r3uazrxdw7dhl7vl6nzupx&dl=0

**Comment by vvoovv** [comment]
I imported it again right from you file and still was not able to reproduce the problem.

Are you running a custom Blender build?

**Comment by Kenzonian** [comment]
I downloaded stock blender last week.
but I have been messing with a lot of plugins and processes to get this to work, so maybe a clean install?

**Comment by vvoovv** [comment]
Yes, please try from a clean install.

**Comment by Kenzonian** [comment]
also does your file structure look like this?
![_ (Unsaved) - Blender 4 2 2 LTS 10_8_2024 9_37_15 AM](https://github.com/user-attachments/assets/1b896ad2-7b98-4444-b0e6-3759fa35da6a)
<img width="845" alt="Screenshot 2024-10-08 093936" src="https://github.com/user-attachments/assets/994ab362-8cfb-4a2d-81db-d165c53c5f3a">

**Comment by Kenzonian** [comment]
Also I "repaired blender" and got this result. I'm going to try a reinstall.
<img width="1921" alt="Screenshot 2024-10-08 094846" src="https://github.com/user-attachments/assets/ed3063b6-bd81-4304-a836-dac35aa50cf4">

**Comment by Kenzonian** [comment]
I've done a clean install but I noticed that some plugins came in again. One thing that's strange is that the tiles that are oriented different are always different. is ever the same tiles


Here is are the addons:
![Blender Preferences 10_8_2024 12_28_33 PM](https://github.com/user-attachments/assets/0996fa93-505a-45e5-aa58-aefdcd354654)

Here is the import.
![BlosmTest2  E__Dropbox_•Studio1thousand_PRODUX_SEWARD PARK LASER_BlosmTest2 blend  - Blender 4 2 2 LTS 10_8_2024 12_30_36 PM](https://github.com/user-attachments/assets/12be5bf3-dfaf-4eef-aa54-307c03809ac2)


here is the file:https://www.dropbox.com/scl/fi/avpdc62z202u86ht11uid/BlosmTest2.blend?rlkey=6jy02xkvdrisyocz516a7wt43&dl=0

**Comment by Kenzonian** [comment]
I deleted my last comment because it had sensitive info in the screen shot. 

Here it is again.
File: https://www.dropbox.com/scl/fi/avpdc62z202u86ht11uid/BlosmTest2.blend?rlkey=6jy02xkvdrisyocz516a7wt43&dl=0

<img width="1920" alt="Screenshot 2024-10-08 123800" src="https://github.com/user-attachments/assets/77d85793-721b-4ccc-8551-2517b0c860ad">

![Screenshot 2024-10-08 123912](https://github.com/user-attachments/assets/f7acd19d-53e5-4073-91cd-ebb12752e13b)

**Comment by Kenzonian** [comment]
PS this is the pro-version of Blosm

**Comment by vvoovv** [comment]
I noticed that you had set a Dropbox folder for the downloaded data. What if you set a non-Dropbox folder on your local drive?

**Comment by Kenzonian** [comment]
That worked. 

Amazing.

**Comment by Kenzonian** [comment]
What are some estimated areas in Km that you would feel comfortable at each of these detail settings?

For instance, after I got this to work, I immediately set the detail level to "buildings with more detail"

I'm happy to wait for an hour or so, but will this size Approx 1.9 x 2.3 km work with that level of detail?

**Comment by vvoovv** [comment]
> I'm happy to wait for an hour or so, but will this size Approx 1.9 x 2.3 km work with that level of detail?

It should finish importing within an hour.

**Comment by Kenzonian** [comment]
Great, I got it. I'll post a picture of the final output.

I appreciate your time and help figuring this out. The support is indispensable for a great product
