### ISSUE TITLE
[Solved] Unable to process the roof of the URI of the 3D Tiles: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by filippa1** [vvoovv/blender-geo#535]
I am trying to import google maps to render, but every time i press import this message appears. This only happens when i choose 3D Tiles instead of open street map for example. I have seen two people's report, but none of their solutions have worked for me. What can i do, i need to solve the issues as soon as possible. t=

**Comment by vvoovv** [comment]
Hi @filippa1 

Please send to prokitektura+support@gmail.com
* your Google 3D Tiles key as a text
* a screenshot of your preferences of the Blosm addon where you set your Google 3D Tiles key

**Comment by vvoovv** [comment]
The key was typed manually instead of copying it from Google Cloud and pasting to the preferences of the Blosm addon with the combination of keys `Ctrl` `V`.

The probability of a typing mistake is very high since the key is quite long.
