### ISSUE TITLE
There was an error when processing the URI https://tile.googleapis.com/.... : HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Ninjia315** [vvoovv/blender-geo#536]
I choose a large area 14km X 7 km and select 'building with detail' option to download it, it seems to only import 9266 3dTiles, 207 errors occurred during the import.  It looks like Google cut off the frequent API download request from the Blosm tool? 

does Anyone know How to solve such problem?

**Comment by vvoovv** [comment]
Your area of interest is quite large. Use the lowest level of details.

Alternatively divide your area of interest into a number of smaller areas.
