### ISSUE TITLE
Google 3D Tiles don't import in Blender 4.2

### ISSUE THREAD

**Issue by WH-Mods** [vvoovv/blender-geo#537]
I have the Blosm 2.7.10 and Blender 4.2, but the Google 3D Tiles don't import in this version... In Blender 3.4 it works, but in Blender 4.2 no. You can help me about that problem? I have the photo of the error to send here.

Sorry for my english, i'm from Brazil.

My API Keys is normal, it works in Blender 3.4
![Screenshot_27](https://github.com/user-attachments/assets/5b88bcea-4379-4aba-b172-ea79929f7393)

**Comment by vvoovv** [comment]
Hi @WH-Mods 

Please activate Blender's built-in glTF addon. It's enabled in Blender by default.

**Comment by WH-Mods** [comment]
Yeaaaahhh!!!!! Works, man! Thank you so much! I lost months trying fix this problem and it was so simple to solve. Thank you, again.
