### ISSUE TITLE
Exporting dosent include texture in FBX 

### ISSUE THREAD

**Issue by alirezabijandi** [vvoovv/blender-geo#543]
Does anyone know how to export it from blender so that the texture will include also tried every way I could to simply export as I always do but this time to texture is being export 
![Screenshot (340)](https://github.com/user-attachments/assets/8ef79b44-96ce-4225-80af-f681719982f6)
 in blender its perfect but when exporting to unity or any other software by FBX it doesn't have texture 
![Screenshot (339)](https://github.com/user-attachments/assets/de6befa0-a8c9-4c9d-bc62-26ba71635646)

**Comment by alirezabijandi** [comment]
just to add 

i have found the Export and Custom Materials section in the documentation. 

and i was only able to export all the textures in a folder and when imported to unity it was all messed up and i couldn't map them

![image](https://github.com/user-attachments/assets/3e8d765e-3ac5-4643-bac8-d0adc6639c75)
![image](https://github.com/user-attachments/assets/1364694c-5fc6-48a2-8741-342915605747)


as you can see i could import the textures and every material has a texture but not at the right place any ideas please

**Comment by vvoovv** [comment]
Hi @alirezabijandi 

Please try importing the exported file back to Blender. Will it work for you?

**Comment by vvoovv** [comment]
No feedback
