### ISSUE TITLE
Error occured in blender

### ISSUE THREAD

**Issue by Harini1213** [vvoovv/blender-geo#544]
Hi! I've the same error. Report: Error
Unable to process the root URI of the 3D Tiles: HTTP Error 404: Not Found. 
Can you please suggest a solution@vvoovv

**Comment by vvoovv** [comment]
Hi @Harini1213

The solution to this problem can be found in the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section in the documentation.

I hope this helps.
