### ISSUE TITLE
No 3D tiles were imported. 3 errors occured during the import. See the System Console.

### ISSUE THREAD

**Issue by MarkusSchille** [vvoovv/blender-geo#545]
I have an API key, payment setup, and 3D tiles enabled on Google. However, I am still receiving an error message in the info window. (see title).

Additionally, I don’t see any relevant information in the Python console. Am I checking the right place?

**Comment by vvoovv** [comment]
Please paste a screenshot with the output of Blender's System Console (Main Menu -> Window -> Toggle System Console).

**Comment by MarkusSchille** [comment]
Never mind, I downloaded the latest build and reinstalled and it worked again. Sorry for bothering you!
