### ISSUE TITLE
unable to process the root URL of the 3D Tiles: HTTP error 500: internal Server Error

### ISSUE THREAD

**Issue by BYA5000** [vvoovv/blender-geo#546]
blosm add-on in blender error "unable to process the root URL of the 3D Tiles: HTTP error 500: internal Server Error"

**Comment by vvoovv** [comment]
@BYA5000 

Please send me your Google 3D Tiles key to [prokitektura+support@gmail.com](mailto:prokitektura+support@gmail.com). I'll take a look.

**Comment by BYA5000** [comment]
I figuring it out. thank you.


    On Monday, November 4, 2024 at 03:29:42 AM EST, vvoovv ***@***.***> wrote:  
 
 


@BYA5000

Please send me your Google 3D Tiles key to ***@***.*** I'll take a look.
