### ISSUE TITLE
Very low quality LOD

### ISSUE THREAD

**Issue by SWEz11** [vvoovv/blender-geo#548]
Hello, I'm new in this, I wanna ask why when I press IMPORT the Loaded LOD are very bad quality, in google earth quality is much better then in blender. There's are example 
![image](https://github.com/user-attachments/assets/e39cfd72-9a8d-4a62-a001-e8c557605c3b)
![image](https://github.com/user-attachments/assets/2a5a9e95-bbdd-44de-953c-4c964c3cee19)

May I do something wrong? Thanks

**Comment by vvoovv** [comment]
Hi @SWEz11

Try importing at a higher level of details.

**Comment by SWEz11** [comment]
> Hi @SWEz11
> 
> Try importing at a higher level of details.

Hi, where I can change that?

**Comment by vvoovv** [comment]
The option _Level of details_ on the addon panel. Please refer to the section [Basic Usage](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#basic-usage) in the documentation.
