### ISSUE TITLE
Terrain does not import; creates infinitesimally small object

### ISSUE THREAD

**Issue by plymouthvan** [vvoovv/blender-geo#549]
I've been tinkering with this for several hours now. Very cool plugin. I can get building and road geometry to import, but I cannot get the terrain to import correctly. When attempting to import terrain, I can see the terrain layer is created, however, it's just an infinitesimally small point and nothing more. I thought maybe it was being generated really far away, or well beyond the clipping zone as some of the other posts have mentioned, but if I select the object in the list, and the hit the dot key to focus, it just zooms into a single point at 0,0,0.

I think the instruction information about the terrain is also somewhat scant. There is mention of an arbitrary mesh object ("You can also set a Blender object for the terrain imported before. Actually an arbitrary Blender MESH object can be set as a terrain in the field"), but then there isn't any other mention of what this means in the later information about terrain.

So, if I have the default cube selected when choosing import for the terrain, it just sets a material for the cube and creates the terrain object without any discernible mesh, and when I choose import for the terrain without any object selected, it creates the object without any discernible mesh. 

So, it seems whatever I do, I cannot get a mesh for the terrain.

I'm not new to blender, but I'm far from a wizard with it. So I'm struggling to determine whether there's something wrong with the plugin, or my configuration, or the way that I'm attempting to use it, and any help would be greatly appreciated.

**Comment by vvoovv** [comment]
Hi @plymouthvan 

Could you please paste some screenshots to illustrate your problem.

**Comment by plymouthvan** [comment]
It would be tricky to demonstrate through photos. But here's a short video:
https://www.dropbox.com/s/ykobk7nsyu91yd8/Screen%20Recording%202024-11-11%20at%208.38.46%E2%80%AFPM-720.mov?dl=0

In this recording, I'm not bothering to choose a different location and just keeping the default. It's the same regardless of the location. I start by setting the end clip to a huge number.

First, I keep the default cube selected, choose terrain and click import. You can see the cube's material is modified, and the terrain layer is created, but nothing else happens. I look around, zoom in and out, and finally press the dot button on the number pad, which zooms into a single point at 0,0,0.

I undo back to the original state.

Next, I delete the default cube and try to import the terrain again. This time the terrain layer is created like before, but nothing else happens. I zoom in and out, look around, and hit the dot key to focus on the selection, and again you can see it zooms into a single point at 0,0,0.

Finally, to demonstrate that other features are working, I import the infrastructure geometry using OpenStreetMaps. It takes a moment, but then the infrastructure geometry is imported successfully.

**Comment by vvoovv** [comment]
I guess you are using the latest version of the Blosm addon (2.7.10). Please install the latest version of Blender (currently 4.2) and try again. I hope this helps.

**Comment by plymouthvan** [comment]
Ah, yup. That did it. Thanks for the help!
