### ISSUE TITLE
error registering panel class

### ISSUE THREAD

**Issue by femboyrewr** [vvoovv/blender-geo#551]
trying to add to blender 4.0.2 and I keep getting this error

![Screenshot 2024-11-11 134239](https://github.com/user-attachments/assets/110da640-0946-414f-9ad4-de104f065825)

anybody know a solution or any kind of info on this error?

**Comment by vvoovv** [comment]
Hi @femboyrewr 

You probably have 2 addons installed: the old one with the name _blender-osm_ and the new one with the name _Blosm_. I'd suggest deleting both of them, restarting Blender and installing the Blosm addon again. You can find the addons by typing _osm_ in the search box. I hope this helps.

**Comment by femboyrewr** [comment]
> Hi @femboyrewr
> 
> You probably have 2 addons installed: the old one with the name _blender-osm_ and the new one with the name _Blosm_. I'd suggest deleting both of them, restarting Blender and installing the Blosm addon again. You can find the addons by typing _osm_ in the search box. I hope this helps.

hey @vvoovv 

Yeah I did have another addon just installed from a different link... I removed it off blender and uninstalled it from my pc but idk, anywhere I could look (file explorer etc) to see if its not 100% gone?

**Comment by vvoovv** [comment]
Sorry, I didn't understand what your problem is now. Can you find the installation file (the zip-archive)?

**Comment by femboyrewr** [comment]
> Sorry, I didn't understand what your problem is now. Can you find the installation file (the zip-archive)?

@vvoovv 

basically, I installed from gumroad (was called blosm.zip or something), and it enabled, but it had issues not actually loading the object...

so I removed it on blender and uninstalled of my pc, and installed directly from github (blender-osm.zip)... now im having this issue, where it wont enable and i get this error

**Comment by vvoovv** [comment]
Please unstall all instances of the Blosm or Blender-OSM addon, restart Blender and install the Blosm addon from Gumroad according to the [documentation](https://github.com/vvoovv/blosm/wiki/Documentation#installation).

**Comment by femboyrewr** [comment]
> Please unstall all instances of the Blosm or Blender-OSM addon, restart Blender and install the Blosm addon from Gumroad according to the [documentation](https://github.com/vvoovv/blosm/wiki/Documentation#installation).

@vvoovv 

uninstalling blender entirely and installing from gumroad has officially worked, thank you so much
