### ISSUE TITLE
No 3D tiles were imported. 20 errors occured during the import. See the System Console.

### ISSUE THREAD

**Issue by abat-joie** [vvoovv/blender-geo#552]
hi ! 

blender 4.0
blosm free 2.72.10

coordinate : 5.77801,43.12077,5.78773,43.12750

error : No 3D tiles were imported. 20 errors occured during the import. See the System Console.

console : There was an error when processing the URI https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NTUscGF0aD0zMDQyNjM2MDYwNjE3MTYzNSxjYWNoZV92ZXJzaW9uPTYsYWxpZ25tZW50X3ZlcnNpb249Uk9DS1RSRUVfOTg4X0dPT0dMRV9EQVRVTV8yMDI0MDgwN1QwNzUzWl9nZW5lcmF0ZWRfYXRfMjAyNDEwMTRUMTIwOFo.glb?session=CLuh7pfk1PCShQEQ3t7OuQY&key=**_MYKEY_**: Calling operator "bpy.ops.import_scene.gltf" error, could not be found

I have activate the API and billing are good.

Any ideas ? :)

**Comment by vvoovv** [comment]
Please enable Blender's built-in glTF importer. It was enabled by default.

**Comment by abat-joie** [comment]
fast and magical, thanks dude !
