### ISSUE TITLE
3D Tiles step by step guide

### ISSUE THREAD

**Issue by lmalone2** [vvoovv/blender-geo#556]
Is there a step by step guide to resolve 3D Tiles Issue? When the data imports there are no tiles shown. I am using blender 4.3 and understand there is an issue with this. Just wondered if there is a guide if I don't have Blender 4.2 available. 

![Screenshot 2024-11-25 114444](https://github.com/user-attachments/assets/0c5942ce-40ec-4821-9cb5-98c308832859)

**Comment by vvoovv** [comment]
Hi @lmalone2 

Please read the walk-arounds for Blender 4.3 at #555
