### ISSUE TITLE
No 3D tiles were imported. 22 errors occured during the import. See the System Console.

### ISSUE THREAD

**Issue by RonnieTik** [vvoovv/blender-geo#559]
Blender version: 4.3.0
Blosm version: 2.7.11

Activated API Key and i do have enable the glTF format. Is there any solutions, please help !!! Thanks a lot.
![error](https://github.com/user-attachments/assets/b095a260-9825-4d28-88bc-892a9706421d)

**Comment by vvoovv** [comment]
Hi @RonnieTik 

Please read #555 

Sorry for the inconveniences.

**Comment by RonnieTik** [comment]
> Hi @RonnieTik
> 
> Please read #555
> 
> Sorry for the inconveniences.

Don't mind it, now is working. Thank you so much!
