### ISSUE TITLE
'BaseManager' object has no attribute 'setGeometricErrorRange' ????

### ISSUE THREAD

**Issue by KDJ-000** [vvoovv/blender-geo#561]
![Screenshot 2024-12-02 220936](https://github.com/user-attachments/assets/81557ff4-32ff-49c8-ad4b-b63b18761ab8)

Hi There,

Amazing add-on, everything has worked perfectly in previous years. Currently looking to import 3D Tiles and receiving the error message attached?

Please advise, any help is greatly appreciated.

Thanks

**Comment by vvoovv** [comment]
Please try restarting Blender.
