### ISSUE TITLE
Not working: No 3d tiles were imported. xx errors occured during the import. See the system console.

### ISSUE THREAD

**Issue by lpcampagna** [vvoovv/blender-geo#562]
I followed severals tutorials and I cant figure out wath is the problem. The import just doesn't proceed. Here is the system console. Can You help me! Thanks!

![Screenshot 2024-12-04 155926](https://github.com/user-attachments/assets/6d3a9682-6622-468c-a920-0f53664dd677)

**Comment by vvoovv** [comment]
Hi @lpcampagna 

Please read #555 

Sorry for the inconveniences.
