### ISSUE TITLE
Empty collection

### ISSUE THREAD

**Issue by Dpanczak** [vvoovv/blender-geo#563]
When i try to import google 3d tile, only empty collection appears (blender 4.3.0) no error nothing
![obraz_2024-12-07_102425933](https://github.com/user-attachments/assets/3dfc5e81-ca7c-4ecf-b3b7-79255876e8db)

**Comment by vvoovv** [comment]
Please read #555 

Sorry for the inconveniences.

**Comment by Dpanczak** [comment]
But what is the solution, i've tried various combinations, uninstalling etc. and this is only thing what i see. Am i doing something wrong?

**Comment by vvoovv** [comment]
Walk arounds are given in #555
