### ISSUE TITLE
My city is flat, how do i fix it. and the data beside import only show "3d tiles" but not "Google 3d tiles" instead.

### ISSUE THREAD

**Issue by zim-png** [vvoovv/blender-geo#564]
![Screenshot 2024-12-09 145147](https://github.com/user-attachments/assets/00b1c677-65d4-4df4-8885-fa203d536ec7)

**Comment by vvoovv** [comment]
Hi @zim-png 

Mostly likely Google Cloud does not provide 3D buildings for your area of interest. Please read the section [Introduction](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#introduction) in the documentation on how to see the areas with 3D buildings.
