### ISSUE TITLE
Google Maps 3D tiles do not render as expected

### ISSUE THREAD

**Issue by D19cannon** [vvoovv/blender-geo#565]
Hi,

I ran into an unexpected behavior from the Google 3D tiles.
The add-on works fine, however, with the OpenStreetMap by the way.

I followed the steps in your documentation and checked out a few tutorials on YouTube where people are connected to their Google API and instantly render (part) a city. However, this does not seem to be the case for me.

After the import all that is rendered is a gray mesh object (see the screenshot below for full visuals).
Perhaps I am missing some configurations or something. Let me know if I am missing anything.

P.S. I am completely new to blender. So if I can test or find any logs for you, please give me proper instructions where to find the required information.

You've build an awesome tool! Keep up the good work!

Thank you!

<img width="1512" alt="Screenshot 2024-12-11 at 11 17 48" src="https://github.com/user-attachments/assets/e7ef38d8-419f-45fa-93c6-23988ede5de5">

**Comment by vvoovv** [comment]
Hi @D19cannon 

Set the option _Viewport Shading_ to _Material Preview_ or _Rendered_ to see a textured scene. The option is normally located at the top of the Blender 3D View. Please note that it's also mentioned in the section [Basic Usage](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#basic-usage) of the documentation.
