### ISSUE TITLE
Can't import terrain using blender 3.6 LTS or 4.0

### ISSUE THREAD

**Issue by Shizhen-Jia** [vvoovv/blender-geo#566]
It seems I can't import terrain using blender 3.6 LTS or 4.0, it's just a point even if I make adjustment to the view.

It seems the newest blender doesn't have this problem.

But I need some other addon that require blender under 4.0, is there a way to fix this or can I get a older version?

**Comment by vvoovv** [comment]
Hi @SJ00425 

Use Blender 4.2 or above
OR
Disable the modifier for the terrain.

**Comment by Shizhen-Jia** [comment]
Thanks! It's solved!!
