### ISSUE TITLE
OSM not importing correctly when using import Terrain  

### ISSUE THREAD

**Issue by Rs-2002** [vvoovv/blender-geo#567]
Hi there,

I am trying to import a selection of Bristol with buildings and terrain visible but whenever I try to import the 3d OSM data whilst pointing to terrain it doesn't seem to import everything how it is seen within the YouTube video linked in a part of the documentation ([Video](https://www.youtube.com/watch?v=Thx08Q4etVc)) 

Here is my attempt at importing terrain then osm data ontop:
https://github.com/user-attachments/assets/a298fffe-513b-4790-a1a3-e5b50a189404

when importing OSM data without pointing to the terrain object it will generate what I would like just there is no terrain below as would be expected

![image](https://github.com/user-attachments/assets/a559b26c-88eb-41e8-af51-543f30ce0dd6)

I am currently using the most up to date blender and blosm Version 

Any assistance would be helpful 

Thanks

**Comment by vvoovv** [comment]
Hi @Rs-2002 

Please use Blender 4.2 or later versions of Blender.

To see a terrain on older versions of Blender disable the modifier on the terrain.

**Comment by Rs-2002** [comment]
Thats embarrassing, my blender is really out of date, sorry  

thank you
