### ISSUE TITLE
Terrain not importing

### ISSUE THREAD

**Issue by AleceFoden** [vvoovv/blender-geo#568]
Something is wrong with Blosm on my laptop. When trying to import terrain, I do not receive any error message but I dont get any object imported. It appears as an empty with no geometry. Google tiles is working as normal. OpenStreetMap is failing to import buildings, I only get the 2D objects. 

Today before this issue began I updated blosm from the 2.7.2 version to 2.7.11 and it was working fine at first but randomly I experienced the issue importing terrain, I then purchased the premium version and got the same result.

**Comment by vvoovv** [comment]
Hi @AleceFoden 

Probably you are using an older version of Blender.

Please use Blender 4.2 or later versions of Blender.

To see a terrain on older versions of Blender disable the modifier on the terrain.

**Comment by AleceFoden** [comment]
Hi, thanks for your reply! 
Updating Blender to version 4.3.1 has worked for the terrain but now Google tiles are not working. I'm getting the message 'BaseManager' object has no attribute 'setGeometricErrorRange' ??

**Comment by AleceFoden** [comment]
Hey, thanks for your response. That worked :)
