### ISSUE TITLE
Missing Buildings

### ISSUE THREAD

**Issue by mexamillion** [vvoovv/blender-geo#569]
Good morning,
there are a couple of 3d buildings missing near the center area of Magdeburg city hall (Germany). I provided screenshots that show the area.
I guess its because some buildings are not labeled correctly. Could you please provide a quick workaround, so that all buildings in the area show up in blender?

One of the missing buildings is located here:
52.13189255733474, 11.638063456816491

If a quick fix isnt an option: being able to import geojson files created in Qgis could be another option of solving my issue pretty quickly, if you should happen to have a module for something like that.

Thank you and best regards,
Max

<img width="855" alt="Bildschirmfoto 2024-12-21 um 04 10 03" src="https://github.com/user-attachments/assets/eb78f7e9-ede0-4126-948a-dca7b438cf4f" />
<img width="944" alt="Bildschirmfoto 2024-12-21 um 04 10 55" src="https://github.com/user-attachments/assets/88c93172-1e87-4b69-b4c2-264b0e4ccbaa" />

**Comment by vvoovv** [comment]
Hi @mexamillion 

I replied to you via email.

**Comment by vvoovv** [comment]
Buildings must be mapped in accordance with the [Simple 3D Buildings](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings) specification.

In particular, the whole area of the building outline (OSM tag `building=yes`) must be completely covered by building parts (OSM tag `building:part=yes`).

So I drew the missing building parts for those buildings.

**Comment by vvoovv** [comment]
By the way, your area of interest is available in 3D with Google 3D Tiles.

**Comment by mexamillion** [comment]
Thank you very much!
