### ISSUE TITLE
not picture

### ISSUE THREAD

**Issue by U-DOKU** [vvoovv/blender-geo#570]
**Before I explain, I'm Japanese and can't ask questions in English, so I'll use translation to ask my questions. So I think there are some incorrect expressions and rude comments here and there.**

Specification software: blender4.1

When using blosm to obtain 3Dtile, in the video I received the instructions on, I was able to import images of cityscapes, but in mine, the tiles just create the terrain and the images themselves are not loaded.

Photography becomes the closest method to the object I want to create. I would like to add building textures to this like Google Earth.

If there is a workaround, I'd like to hear it.
![screenshot01](https://github.com/user-attachments/assets/2af2e34f-9d69-4460-bf4e-54f4f8dd4832)

If there is no such thing, I would like to receive an explanation that there is no such thing.

Sorry for my poor writing. I ask all the experts.

**Comment by U-DOKU** [comment]
Oh, maybe it's only available for a fee?

**Comment by vvoovv** [comment]
Hi @U-DOKU 

Please paste a screenshot of Blender's 3D View with the result of an import.

**Comment by U-DOKU** [comment]
![screenshot02](https://github.com/user-attachments/assets/9178efd7-7834-440f-90c3-d4c20da4939b)
![screenshot03](https://github.com/user-attachments/assets/f4151160-a932-4964-aaab-523697dae2eb)

Thank you for your reply.
I have attached two screenshots here.
The first image is the result of importing it into blender.
The second photo is a local photo taken from Googleearth.

If there is any other information you would like, I will provide it as soon as possible.

**Comment by vvoovv** [comment]
Set the option _Viewport Shading_ to _Material Preview_ or _Rendered_ to see a textured scene. The option is normally located at the top of the Blender 3D View as shown on the screenshot:

![image](https://github.com/user-attachments/assets/a3e02909-9f4b-47c5-9b3f-454ee122b5ce)

You can also refer to the section [Basic Usage](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#basic-usage) in the documentation.

I hope this helps.
