### ISSUE TITLE
http 400: Bad Request importing Google 3D Tiles

### ISSUE THREAD

**Issue by macattackpro** [vvoovv/blender-geo#572]
I've been able to import on "separate buildings" but when I choose to do "buildings with details" or "buildings with more details" I am getting an 'http 400: bad request' in the console.

I'm guessing the Google API is timing out due to the size of the area I'm trying to import and the number of tiles. Able to confirm? And if so, is there anything I can do to improve it without slicing and splicing the area I'd like to import?

![image](https://github.com/user-attachments/assets/d7e6ae3c-6b58-451c-9bfa-ca4bb5886af5)

**Comment by vvoovv** [comment]
Hi @macattackpro 

You seemingly requested too much 3D Tiles. Try subdividing your area or reducing the level of details.

**Comment by macattackpro** [comment]
I was afraid of that. I'll slice it up. Thanks!
