### ISSUE TITLE
single object import

### ISSUE THREAD

**Issue by ohadmanor** [vvoovv/blender-geo#65]
Hi, 

when I unchecked the 'Import as a single object' it get memory leak and Blender stuck.

I'm using Blender 2.78c the size of the osm file is 35MB.

any idea?

thanks

**Comment by vvoovv** [comment]
Your file is quite large and contains thosands of buildings.
Blender seemingly can't handle a huge amount of objects.

So either
* try a much smaller file
or
* import with the checked option _Import as a single object_

**Comment by ohadmanor** [comment]
thanks,

one more question maybe you can help me, I need to convert OSM building to glTF with geographic reference. how I can import the data from the OSM automatically?

thanks

and awesome job you done here!

**Comment by vvoovv** [comment]
You'll probably need to write a script.
Use [gltf exporter](https://github.com/Kupoman/blendergltf).
Use the code from [here](https://github.com/vvoovv/blender-osm/wiki/Georeferenced-Blender-Scene) to convert Blender coordinates to latitude and longitude.

**Comment by ohadmanor** [comment]
thanks,
