### ISSUE TITLE
Import osm Not Appearing on Drop-Down Import Menu

### ISSUE THREAD

**Issue by PaulDeCelle** [vvoovv/blender-geo#66]
I've installed Blender-osm from the .zip file on my Mac, and it appears in the User Preferences and can be enabled.  But when I open a new Blender project and go to File - Import, Import osm is not there as a pick.  I can enable other import addons like Import Images as Planes and they do appear.
So far, I've made sure the addon is in the proper scripts folder in Application Support, I've deleted and re-installed Blender (twice), I've deleted and re-installed Blender-osm more times than I can recall, but still nothing works.  This is driving me crazy - Can anyone help?

Thanks, 
Paul

**Comment by vvoovv** [comment]
Dear Paul,

Thank you for buying the blender-osm addon!

Please follow the [documenation](https://github.com/vvoovv/blender-osm/wiki/Documentation#openstreetmap-import-from-the-server). The addon GUI is located on the `osm` tab of the left side panel of the Blender _3D View_. The panel is also known as _Tool shelf_ and toggled with the `T` key.

**Comment by PaulDeCelle** [comment]
Thanks, that works!  My problem was that I'd been following a tutorial on YouTube with an older version that used the Import pick from the File drop-down menu.

**Comment by vvoovv** [comment]
Glad, that it works for you!
