### ISSUE TITLE
Can't extrude building after importing openstreetmap data

### ISSUE THREAD

**Issue by adaumas** [vvoovv/blender-geo#71]
Hello everyone,

I have an issue after importing openstreetmap data on blender i can't select roof and extrude them to make different buildings levels. I can't even select only the roof. when i right click it selected the whole building.
![forum](https://cloud.githubusercontent.com/assets/22083552/25218857/a8ff5902-25ac-11e7-911a-018c38e7a440.PNG)

**Comment by vvoovv** [comment]
Hello!

Please switch to the EDIT mode to select a roof face

**Comment by adaumas** [comment]
Thanks for your answer but i don't have the EDIT mode i only have object mode

**Comment by vvoovv** [comment]
Select a building and press TAB to switch to the EDIT mode

**Comment by adaumas** [comment]
thanks ! Sorry for the stupid question, i'm beginner on Blender

**Comment by vvoovv** [comment]
No problem!
Thank you for buying the blender-osm addon!
