### ISSUE TITLE
Cut objects off at the coordinate boundaries instead of overhanging

### ISSUE THREAD

**Issue by MMorpheus1** [vvoovv/blender-geo#72]
Hey,
is there any chance to add a feature (or is there already?) to "cut off" buildings, roads, etc. at the edge 
of my chosen boundaries (based on longitude/latitude) instead of "overhanging" everything?

Thanks!
Morpheus

**Comment by vvoovv** [comment]
You probably have a Blender object for the terrain in your case. There is also an auxiliary Blender object called Terrain_envelope (or MyCustomTerrainName_envelope). It is invisible in the Blender 3D Viewport. The envelope object is used to cut off areas (forest, grass, etc)

Use the envelope object to cut off Blender objects with buildings via BOOLEAN modifier.

**Comment by MMorpheus1** [comment]
Thanks for your quick respond!

Unfortunately this only kind of solves my problem.
I want to 3D print a certain area. If i cut off the buildings with the Boolean modifier, it results in an open mesh. This means, i can't really solidify or slice the model proper for my 3D printing. Even if i try to close the open faces of the buildings by hand, i get some problems with the slicing software.
Is there an option to close the mesh automatically?

**Comment by vvoovv** [comment]
I'd suggest you the following.

Provide some margin for the coordinates when you import a terrain. Then import OSM without the margin. In that case you are to avoid overhanging buildings.

**Comment by MMorpheus1** [comment]
Thanks for the hint, but I don't want to avoid the buildings. I need them cutted in parts, because i can't fit the hole city model on my 3D printer. Therefore I need the buildings in two pieces on each piece of the model.
I thought maybe i can already fix this with your great add-on, because then i could easily determine on which longitude i'll separate the model.
But i figured it's pretty easy to fix the open mesh by hand in Blender, so this works for me.
Thanks for the support!
