### ISSUE TITLE
Negative levels

### ISSUE THREAD

**Issue by clearbrian** [vvoovv/blender-geo#76]
Is there any way to import below ground levels. For instance Im trying to extract a model of a London Underground station.  The platform and tracks are below ground but the station entrance is level 1+. The Plugin UI changes -2 to 1. 
-0.07780,51.50964,-0.07597,51.51001

**Comment by vvoovv** [comment]
Thank for buying the blender-osm addon!

You could try the following:

Import your area of interest with the _Import as a single object_ GUI option unchecked.
Execute from the Blender text editor the following script:
```python
import bpy

layer = -2
layer = str(layer)

bpy.ops.object.select_all(action="DESELECT")

for obj in bpy.context.scene.objects:
    if obj.get("layer") == layer:
        obj.select = True
```
The code selects imported objects with layer=-2.  Move them to the desired height.
