### ISSUE TITLE
OpenStreetMap AddOn can't be enabled

### ISSUE THREAD

**Issue by massimo1957** [vvoovv/blender-geo#77]
Trying to enable the AddOn I get the following error message:
![grafik](https://user-images.githubusercontent.com/29654962/27477039-3fe430d2-580b-11e7-9be6-1ea6a6500e4b.png)

Any idea what's wrong in my installation? THX

**Comment by vvoovv** [comment]
The addon uses the module _mathutils.bvhtree_ mentioned in the error message. The module first appeared in Blender 2.76, but your version of Blender is 2.75.

Please use the latest version of Blender.

The requirement for the minimum version of Blender is also mentioned in the [documentation](https://github.com/vvoovv/blender-osm/wiki/Documentation#installation).

**Comment by massimo1957** [comment]
Thanks! Sorry, I didn't take care of the Blender version...
