### ISSUE TITLE
Blender OSM wont show importer

### ISSUE THREAD

**Issue by kelbybricker** [vvoovv/blender-geo#78]
Okay so when I install the OSM addon and enable it I go to the import options and its not there. The .osm import option does not show up. I WAS on blender 2.78 and I thought it was a compatibility issue but then i went to 2.76 and it still doesnt show up. And yes I saved user settings. 

![blender user preferences 6_26_2017 7_38_32 pm](https://user-images.githubusercontent.com/29719135/27566007-9aeb89aa-5aa7-11e7-8bd5-d652ac2d153f.png)

![blender 6_26_2017 7_40_52 pm](https://user-images.githubusercontent.com/29719135/27566009-a1014f00-5aa7-11e7-8e83-5c18726f8bc1.png)

**Comment by kelbybricker** [comment]
Oh and I tried an earlier version of the addon and it works just fine. So that means this is an issue with this version of the addon itself. However I need the new version for the terrain feature. Odd how no one has complained about this..

**Comment by vvoovv** [comment]
Thank you for buying the addon!

The addon GUI has been changed. It's no longer in File->Import.
Please follow the [documentation](https://github.com/vvoovv/blender-osm/wiki/Documentation#installation).
