### ISSUE TITLE
OSM: extrude height based on OSM height data

### ISSUE THREAD

**Issue by markov00** [vvoovv/blender-geo#8]
It will be very useful to import the height data to specify the height of each building http://wiki.openstreetmap.org/wiki/Key:height

**Comment by vvoovv** [comment]
Only a part of buildings have height tag set.

**Comment by markov00** [comment]
What about use the default thickness when building doesn't have height, and use the height on building with height value?

**Comment by kitsched** [comment]
Then it would be hard to differentiate between the buildings with real
height and those with default height. Anyway, if this is implemented I
think it would be best to be able to toggle it with a checkbox.

**Comment by vvoovv** [comment]
That's a more complicated issue. Many buildings have buildings:levels tag (number of floors).
Some buildings are modeled in accordance with [Simple 3D Buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_Buildings).

Unfortunately I don't have free time to deal with all those peculiarities

**Comment by mherweg** [comment]
I noticed that feature is included in version 1.1.0

Thank you!

**Comment by vvoovv** [comment]
@mherweg 3D stuff tagged via relations isn't yet treated

**Comment by esistderfred** [comment]
I am playing around with building up building meshes from osm tags like levels, heights and roof data.
May it be useful to create a new branch for this issue?

**Comment by vvoovv** [comment]
@esistderfred 
I don't think it's necessary right now. Just submit your pull request.

**Comment by vvoovv** [comment]
In the meanwhile support for the tags _height_, _min_height_, _building:levels_ and _building:min_level_ has been added!
Thank you for your feedback!
