### ISSUE TITLE
separate different values of the highway tag

### ISSUE THREAD

**Issue by harumscarum** [vvoovv/blender-geo#81]
thank you very much for your tool - just bought it!
can you please add an option to separate roads and paths since it is a different width

**Comment by vvoovv** [comment]
Roads and paths in OSM are defined by the tag [highway](http://wiki.openstreetmap.org/wiki/Key:highway#Values). I'll separate different values of the _highway_ tag in the next public release of the addon.

For now you can import roads with particular value of the _highway_ tag, convert them to Blender curves, set a desired size for the bevel object.

Open the link http://overpass-turbo.eu/s/qyk, then Export -> raw data, save the OSM file the with roads [highway=primary](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dprimary) only and import the file to Blender.

Substitute _primary_ in the request field for another desired value (e.g. [residential](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential)). Press Run and repeat the above steps.

**Comment by vvoovv** [comment]
done and released
