### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by ghost** [vvoovv/blender-geo#82]
I just downloaded the file and followed the instruction here but when I pressed import button, it gives me errors and doesn't run appropriately.
![22092861_10155494303820590_1787016122_o](https://user-images.githubusercontent.com/10768526/30913335-16d5f7ba-a34d-11e7-85f3-2db237051cef.png)

**Comment by vvoovv** [comment]
Hello!

Just try to close Blender, open it again and run the addon

You probably had an old version before. The reason for the problem is probably that both the old and the new versions of the addon were in memory simultaneously.

Please inform if it solved the problem.
