### ISSUE TITLE
OSM import not on import menu dropdown

### ISSUE THREAD

**Issue by Jontechie** [vvoovv/blender-geo#83]
Hi,
purchased your add on and it  was running fine on 2.78 but since moving to 2.79 the entry point to your addon (import OSM menu) no longer shows. The addon is in the list of add ons and is checked but no appearance on the import menu. Have uninstalled the add,on re installed, trying both the root user path as install location and the alternate bender folder path but although both options show up on installed addons the situation remains the same... any ideas?

...Jon

One further thing I'm running Blender 2.79 Branch (fracture Modifier Build)

**Comment by vvoovv** [comment]
Could you please provide a screen shot to illustrate your problem (i.e. missing import OSM menu)?

**Comment by Jontechie** [comment]
Here you go,  First Screenshot Import menu has no OpenStreetMap option
Second screenshot.. Addons menu shows OpenstreetMap add on checked.
![blender_osm](https://user-images.githubusercontent.com/32717370/31463019-8424fc06-aec6-11e7-8b4d-335c3a6e51fb.jpg)
![blender_addons](https://user-images.githubusercontent.com/32717370/31463026-8cc12100-aec6-11e7-9f6a-c316c98eed78.jpg)

**Comment by vvoovv** [comment]
You probably haven't used the addon for quite long time :)
The addon GUI is located on the _osm_ tab_ (just below the tab Retopology on your screenshot).

Please refer to the [documentation](https://github.com/vvoovv/blender-osm/wiki/Documentation#installation) how to use the addon.

**Comment by Jontechie** [comment]
Doh!, tab was tiny :O, so import options now all done through the settings tab, instead of the import menu...

thanks,

jon

**Comment by vvoovv** [comment]
Thank you for buying the blender-osm addon!
