### ISSUE TITLE
No import..nor in Blender 2.77 neither in 2.79

### ISSUE THREAD

**Issue by os512** [vvoovv/blender-geo#84]
Hello,

am just trying to import a .xml Map via osm-import in Blender, but the .xml doesn't show up.
The Addon is installed and a mark is checked in the Addon-list in both Blender versions.  I also restarted both Blender versions a couple times - with no result.

Any ideas, how to get OSM-loader to import an OpenStreetMap file?

**Comment by vvoovv** [comment]
Please attach a screenshot describing your problem.

**Comment by vvoovv** [comment]
I haven't received any feedback from you. So I'll try to guess the cause of your problem.

Probably you looked for the addon GUI in the wrong place.

The addon GUI is located on the "osm" tab of the left side panel (also known as Tool shelf and toggled with the T key) of the Blender 3D View as shown on the [image](https://github.com/vvoovv/blender-osm/wiki/Documentation#openstreetmap-import-from-the-server) (the letter "h" on the image).

Please refer to the documentation how to install and use the addon: https://github.com/vvoovv/blender-osm/wiki/Documentation#installation

**Comment by austinthecreator** [comment]
I'm experiencing a similar problem, any idea how to fix it? ![23600842_1351643281613340_1362796271_o](https://user-images.githubusercontent.com/33669683/32802386-bdcdc91e-c934-11e7-9dc4-7161c831adf2.png)

**Comment by vvoovv** [comment]
@austinthecreator 

I created a separate issue for your problem: https://github.com/vvoovv/blender-osm/issues/85
Please post there.

Also, could you please contact me via the e-mail prokitektura+support@gmail.com, since I don't want to expose any detail from your computer publicly.

**Comment by vvoovv** [comment]
no feedback
