### ISSUE TITLE
use blender-osm api in python

### ISSUE THREAD

**Issue by cloudwaysX** [vvoovv/blender-geo#88]
I try to run a python script that will automatically download data and do several processing.  Is there a python API I can use for that?

**Comment by vvoovv** [comment]
Hello and thank you for buying the blender-osm addon!

Your task can be accomplished very easily
1) Set addon parameters
2) Call bpy.ops.blender_osm.import_data('INVOKE_DEFAULT')

To get a parameter name and how to access it, hover over the parameter in the addon GUI to get the parameter popup hint.

Let me know if it solves your problem.
