### ISSUE TITLE
Unable to terrain normal's is inverted when extruded

### ISSUE THREAD

**Issue by sokraticcreations** [vvoovv/blender-geo#91]
This might not be an issue with blender-osm but im looking for any advice on how i can extrude the terrain so that i have a thicker base to work with. Currently when i do this  and bring my model into meshmixer for final prep for my printer the terrain's normals are inverted. Any assistance would be appreciated!

**Comment by vvoovv** [comment]
- Switch to the EDIT mode
- Select everything by pressing _A_
- Press _CTRL N_

Also you could try _blender revert normals_ in Google :) The answer will be in the first link.

**Comment by sokraticcreations** [comment]
Yes trust me I did not want to post here but I have tried that exact search
as well as the ctrl n to revert the normals. I could post my .blend here if
you have a moment to take a look. Thanks for the reply I appreciate the
help.

**Comment by vvoovv** [comment]
Please send the file to prokitektura@gmail.com

**Comment by vvoovv** [comment]
solved via e-mail
