### ISSUE TITLE
WinError Connection error

### ISSUE THREAD

**Issue by IvanMax33** [vvoovv/blender-geo#97]
![winerror](https://user-images.githubusercontent.com/39074706/39735551-becbb9be-5284-11e8-964f-c9ac0c0a3100.jpg)
How to fix?
Ver.2.3.3
Terrain works fine
Works from file fine
Thank you!

**Comment by vvoovv** [comment]
That's a consequence of Telegram blocking in Russia.
Could you use a proxy or VPN on your computer?

**Comment by vvoovv** [comment]
I've just impement selection of an alternative OSM data server instead of the default one.

Download the new version via the link in your purchase confirmation e-mail.

Set an alternative OSM data server in the addon preferences.

**Comment by IvanMax33** [comment]
Spasibo!

2018-05-10 23:28 GMT+03:00 Vladimir Elistratov <notifications@github.com>:
